version: '3'
services:
  fswepp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: result/latest
    volumes:
      - /workdir:/workdir
      - /workdir/fswepp-docker/var/www:/var/www
      - /workdir/fswepp-docker/etc/perl/MoscowFSL:/etc/perl/MoscowFSL
      - /workdir/fswepp-baer-db/baer-db:/var/www/BAERTOOLS/baer-db
      - /workdir/fswepp-library/:/var/www/engr/library

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  caddy_data: {}

