version: '3'
services:
  fswepp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: result/latest
    volumes:
      - /workdir/fswepp-docker/var/www:/var/www
    networks:
      - fswepp_network

  caddy:
    image: caddy:2-alpine
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - fswepp_network
    command: caddy reverse-proxy --from forest.eecs.wsu.edu --to fswepp:80
    restart: unless-stopped

networks:
  fswepp_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:

