<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Pseudotsuga menziesii series</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Central Idaho - Soil; Productivity/Management and Soil concerns for Pseudotsuga menziesii (PSME) series" />
		<meta name="keywords" content="Forest Habitat Types of Central Idaho Productivity Management concerns Pseudotsuga menziesii series PSME Douglas-fir soil soils" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../../../GeoPath/habitat/index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF CENTRAL IDAHO</a> &gt; <span class="ital">PSEUDOTSUGA MENZIESII</span> (PSME) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Central Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Steele, Robert; Pfister, Robert D.; Ryker, Russell A.; Kittams, Jay A. 1981. Forest habitat types of central Idaho. Gen. Tech. Rep. INT-114. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 138 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_03.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<strong>4</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">Next &gt;&gt;</a>]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">PSEUDOTSUGA MENZIESII</span> (PSME) SERIES</h3>
			<p><strong>Soil</strong>&#8212;Soil parent materials vary widely in the <span class="ital">Pseudotsuga</span> series and range from granitic and volcanic materials to limestone (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). In general, <span class="ital">Pseudotsuga</span> h.t.'s show little affinity for a particular soil condition although such relationships often occur locally. Exceptions to the above are noted within the appropriate h.t. description.</p>
			<p><strong>Productivity/Management</strong>&#8212;Productivity and response to management vary widely in this series as noted in the h.t. descriptions. Over much of the series <span class="ital">Calamagrostis rubescens</span> proliferates after fire or logging and develops extensive sod. This condition requires careful site preparation for successful regeneration of conifers. On certain soils, Stewart and Beebe (1974) found chemical treatment more effective than mechanical removal of <span class="ital">C. rubescens</span> for survival of <span class="ital">Pinus ponderosa</span> seedlings; however, thorough scarification suffices on most sites in central Idaho.</p>
			<p>Dwarf mistletoe (<span class="ital">Arceuthobium</span> spp.) occurs in many stands and varies considerably in severity of infection. Locally, infection may appear correlated with h.t., but no such relationship is evident throughout the distribution of any <span class="ital">Pseudotsuga</span> h.t. Perhaps this is because infection was assessed at one point in time and the potential for infection is not yet evident in all stands of a given h.t. Needlecast (<span class="ital">Rhabdocline pseudotsugae</span>) was notably severe in a few areas but, like mistletoe, shows little overall relationship with h.t.'s when based on a single sample of the area. Insect damage and sporophores of pathogenic fungi were also observed in minor amounts. However, these occurrences vary seasonally and provide little meaning when sampled in different stands throughout the field season.</p>

			<h4><a name="set1a"></a><span class="ital">Pseudotsuga menziesii/Agropyron spicatum</span> h.t. <br />(PSME/AGSP; Douglas-fir/bluebunch wheatgrass)</h4>
			<p><strong>Soil</strong>&#8212;PSME/AGSP is found on soils derived from a variety of parent rock, ranging from basalt to quartzite (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Because much of central Idaho is occupied by the Idaho Batholith, most soils are of granitic origin. Soil pH ranges from 5.4 to 7.1, with a mean of 6.1. On steep slopes, as much as 60 percent of the surface is bare soil or rock. Litter depths seldom exceed 3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;PSME/AGSP has low to very low potential for producing timber (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). Natural regeneration of trees is slow because of extreme droughty conditions and grass competition. These sites produce some forage for livestock but the steep slopes and loose soil may preclude domestic grazing. In some areas, elk, mule deer, and occasionally bighorn sheep find important forage or cover here, especially during the winter. These sites may also provide important spring forage for black bear and, where large <span class="ital">Pinus ponderosa</span> are present, important year-round habitat for wild turkey.</p>

			<h4><a name="set1b"></a><span class="ital">Pseudotsuga menziesii/Festuca Idahoensis</span> h.t. <br />(PSME/FEID; Douglas-fir/Idaho fescue)</h4>
			<p><strong>Soil</strong>&#8212;The soils are derived from a variety of parent materials including quartzite, granitics, and various volcanics (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). They range from silty loam to gravelly sandy loam but are mainly gravelly loams. Soil pH ranges from 5.4 to 6.7 and averages 6.1. Occasionally the amount of surface rock reaches 30 percent but usually it is less than 10 percent. Most sites have less than 5 percent of the area in bare soil. Average litter depth per site is usually less than 4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to very low (<a href="habitat_types_C-ID_app.php">appendix E-2</a>) and tree regeneration is sporadic. Although some natural stands appear well stocked, natural regeneration is a slow process. The FEID phase tends to occur on more gentle, stable slopes, which makes it relatively compatible with livestock use. In some areas, values of livestock forage production may exceed those of timber. In other areas, elk, mule deer, and occasionally bighorn sheep and mountain goats find important forage or cover here, especially during the winter. This h.t. may also provide important spring forage for black bear and, in the PIP0 phase, important year-round habitat for wild turkey.</p>

			<h4><a name="set1c"></a><span class="ital">Pseudotsuga menziesii/Symphoricarpos oreophilus</span> h.t. <br />(PSME/SYOR; Douglas-fir/mountain snowberry)</h4>
			<p><strong>Soil</strong>&#8212;Soils are derived from most major parent materials in the area (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Texturally they range from loam and gravelly silt loam to very gravelly loamy sand. Soil pH ranges from 8.0 to 6.0 and averages 6.8. Coverages of bare rock reach 70 percent on some sites and areas of bare soil attain 20 percent on other sites. Average litter depth on a site seldom exceeds 4.6 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to very low (<a href="habitat_types_C-ID_app.php">appendix E-2</a>) and trees regenerate very sporadically. Success at artificial regeneration is apt to be poor. The shrubs and grasses attract both wild and domestic herbivores and the tree canopies can shelter animals that use adjacent rangeland. These sites often provide important forage and cover for mule deer and blue grouse and, in some areas, are very important to wintering elk.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Arnica cordifolia</span> h.t. <br />(PSME/ARCO; Douglas-fir/heartleaf arnica)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials include limestone, quartzite, andesite, dacite, schist, and Challis basalt (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Soil textures range from sandy loam to silt loam and most are gravelly to very gravelly. The pH ranges from 5.3 to 8.2 and averages 6.8. Coverage of bare rock is usually less than 10 percent but can approach 70 percent. Litter often had a high coverage but its depth seldom averaged more than 7 cm on any one site.</p>
			<p><strong>Productivity/Management</strong>&#8212;These sites support moderately heavy basal areas especially in the ARCO phase, but yield capability is within the low range (<a href="habitat_types_C-ID_app.php">appendix E</a>). Diameter growth increment in both phases appears to taper off rather quickly with age but we have no response data to evaluate effects of thinning on diameter growth. Natural reproduction is apparently sporadic but has not been studied in this h.t. Seral stands provide some forage for livestock but animals attracted to these sites may impede tree reproduction. Older stands offer little forage but provide shelter for animals that feed in nearby grasslands. In some areas these stands also provide important cover for deer and elk.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Juniperus communis</span> h.t. <br />(PSME/JUCO; Douglas-fir/common juniper)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly quartzite, with occasional stands occurring on limestone or granitics (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Soils are usually gravelly or very gravelly loams or silt loams and contain a high proportion of angular cobbles and stones. Soil pH ranges from 6.1 to 8.1 and averages 7.1. Coverage of bare rock can reach 40 percent and areas of bare soil 10 percent. Average litter depth seldom exceeds 4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potential is low to very low (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). When present, <span class="ital">Pinus contorta</span> may be in a marginal environment and not respond well to management. Regeneration of <span class="ital">Pseudotsuga</span> may be sporadic and timber harvests should be guided by the patterns and frequency of regeneration observed in the stand. Most of these sites have little potential for livestock, but may provide important cover for deer and elk.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Carex geyeri</span> h.t. <br />(PSME/CAGE; Douglas-fir/elk sedge)</h4>
			<p><strong>Soil</strong>&#8212;The most common soil parent materials are
granitics (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Other materials include quartzite, latite, andesite, rhyolite, and basalt. Soil textures vary accordingly from silty clay loam to very gravelly loamy sand. The pH ranges from 5.2 to 7.2 and averages 5.9. On most sites coverage of bare rock is less than 10 percent but a few sites have up to 60 percent. Exposed soil is usually less than 10 percent of the area but can reach 30 percent. Average litter depth on a site seldom exceeds 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from low to high depending on the tree species present and the phase (<a href="habitat_types_C-ID_app.php">appendix E</a>). The SYOR phase appears least productive; a moderate site index for <span class="ital">Pinus ponderosa</span> gives the PIPO phase greatest productivity. Natural regeneration of <span class="ital">Pseudotsuga</span> is often sporadic and apparently requires some site protection. Artificial regeneration of <span class="ital">Pseudotsuga</span> assumes considerable risk of success. In the PIPO phase, the pine may regenerate more readily as a seral species than <span class="ital">Pseudotsuga</span>. The root system of the <span class="ital">Carex</span> is several times greater than the leafy portion and presents formidable competition to tree seedlings. Thus site preparation is needed even where spaces among the <span class="ital">Carex</span> might appear adequate for seedling establishment.</p>
			<p>Forage production is generally low, and on steep slopes the gravelly soils are readily exposed by grazing animals. Destruction of the <span class="ital">Carex</span> sod may cause erosion scars that are difficult to revegetate. On some overgrazed sites, <span class="ital">Artemisia tridentata</span> now dominates the undergrowth. Burning or spraying the <span class="ital">Artemisia</span> denies <span class="ital">Carex geyeri</span> seedlings shade and protection from trampling and jeopardizes recovery of the <span class="ital">Carex</span> sod.</p>
			<p>In some areas, the SYOR phase provides important forage and cover for deer, elk, and blue grouse. The widely spaced trees and frequent ridge-line locations of this phase are well suited for birds of prey. Burning in the PIPO phase may increase forage for deer and elk.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Berberis repens</span> h.t. <br />(PSME/BERE; Douglas-fir/Oregon grape)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly granitic, quartz monzonite, andesite, and basalt (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Soil textures range from loam to loamy sand and are sometimes gravelly. The pH ranged from 5.3 to 6.4 and averaged 5.8. Coverage of bare rock seldom exceeds 5 percent but in a few cases is as high as 25 percent. In the SYOR phase exposed boulders may account for 70 percent coverage. Areas of exposed soil are usually less than 10 percent and average litter depth on a site seldom exceeds 7 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>), but tree seedlings may require some protection from wind and sun. Although forage may be scarce, livestock use these sites for rest and shelter when grazing areas are nearby. Mule deer use the BERE phase for rest and shelter and the SYOR phase provides important browse in some areas.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Cercocarpus ledifolius</span> h.t. <br />(PSME/CELE; Douglas-fir/mountain mahogany)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials vary widely and include limestone, shale, sandstone, pumice, quartz monzonite, and quartzite (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Soil textures are mostly loams or sandy loams and are often gravelly. The pH ranged from 5.5 to 7.9 and averaged 6.4. Coverage of bare rock reaches 40 percent on some sites and areas of bare soil can reach 30 percent. Average litter depth per site seldom surpasses 1.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potential is low to very low based on limited data (<a href="habitat_types_C-ID_app.php">appendix E-1</a>), and tree regeneration is very sporadic. Livestock forage is sparse here, which is partly due to shrub density. In some areas this h.t. provides important browse and cover for elk, mule deer, antelope, and wild horses. As a result, it is an important breeding and hunting area for mountain lion. This h.t. also provides important nesting sites for the blue grouse, dusky flycatcher, rock wren, and American kestrel.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Calamagrostis rubescens</span> h.t. <br />(PSME/CARU; Douglas-fir/pinegrass)</h4>
			<p><strong>Soil</strong>&#8212;Granitics, quartzite, quartz monzonite, trachyte, andesite, and basalt are the common soil parent materials (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Most soil textures range from loam to loamy sand and many are gravelly. Soil pH ranged from 5.5 to 7.1 and averaged 6.2. Coverages of bare rock are usually less than 5 percent but may sometimes reach 50 percent. Areas of bare soil rarely exceed 5 percent. Average litter depth on a site is seldom more than 6 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber production is low to moderate in the CARU phase and moderate to high in the PIPO phase (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). When the overstory is reduced, the <span class="ital">Calamagrostis</span> may develop a thick sod. To establish conifers, the sod often requires special treatment, as outlined under the <span class="ital">Pseudotsuga</span> series description. When present, <span class="ital">Pinus ponderosa</span> or <span class="ital">P. contorta</span> can be regenerated in openings that receive full sunlight if the site is adequately prepared and protected from grazing animals. Where <span class="ital">Pseudotsuga</span> is the only conifer adapted to the site, its seedlings often require additional protection from wind and sun.</p>
			<p>If these sites are burned, <span class="ital">Ceanothus velutinus</span> may sprout from seed stored in the soil and form a dominant layer for several decades. The amount of seed stored in the soil varies. Lyon (1971) describes succession on a burned area in this h.t. that contained a large amount of <span class="ital">Ceanothus</span> seed.</p>
			<p>Seral stands that produce <span class="ital">Ceanothus</span>, <span class="ital">Salix</span>, and <span class="ital">Populus tremuloides</span> are very important to deer and elk. In some areas the sites may be important for elk calving. Old-growth stands are important nesting sites for the Steller's jay, western tanager, and pine siskin. Livestock make some use of these sites if on gentle terrain, but forage production tends to be low.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Osmorhiza chilensis</span> h.t. <br />(PSME/OSCH; Douglas-fir/mountain sweet-root)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials include granitics, andesite, rhyolite, and basalt (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Textures are mainly loams or sandy loams; a few are gravelly. Soil pH ranged from 5.5 to 6.6 and averaged 5.8. Areas covered by bare soil or rock are less than 5 percent. Litter depths seldom exceed 5.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pseudotsuga</span> regenerates most easily in the shade of older trees and is often the only conifer adapted to the site. If present, <span class="ital">Populus tremuloides</span> can quickly dominate cleared areas in this h.t.; otherwise, shrubs from adjacent communities will dominate the clearings and suppress conifer seedlings. Pocket gophers are sometimes numerous and may destroy young trees. Livestock often use these sites as resting areas but find little forage here.</p>
			<p>Big game use is normally light but may increase in early sera1 stages. A few sites provide important resting areas for mule deer.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Spiraea betulifolia</span> h.t. <br />(PSME/SPBE; Douglas-fir/white spiraea)</h4>
			<p><strong>Soil</strong>&#8212;Soil characteristics appear to vary between phases (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). In the PIP0 phase, soil parent materials are mostly granitics, basalt, and some andesite. Textures range from loamy sand to clay loam, but most are loams and a few are gravelly. Soil pH ranged from 5.4 to 6.4 and averaged 5.9. Areas of bare rock reach 60 percent and bare soil 30 percent, although most sites have less than 5 percent of either surface. Average litter depth on a site can attain at least 6.5 cm.</p>
			<p>Soil parent materials in the CARU phase are mostly quartzite and some latite. The textures vary from sandy loam to loam and most are gravelly. Soil pH ranged from 6.2 to 6.7 and averaged 6.4. Coverages of bare rock are less than 5 percent and areas of bare soil less than 2 percent. Litter depths seldom exceed 3.5 cm.</p>
			<p>The SPBE phase has the most variable soils. Parent materials include granitics, quartzite, diorite, dacite, quartz monzonite, and andesite. Textures vary from sandy loam to loam and most are gravelly to very gravelly. Coverages of bare rock vary and may reach 40 percent. The pH ranged from 5.7 to 7.7 and averaged 6.6. Areas of bare soil are usually less than 5 percent. Average litter depth seldom exceeds 3.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate in the SPBE phase and moderate to high in the PIPO phase (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). If present, <span class="ital">Pinus ponderosa</span> or <span class="ital">P. contorta</span> are usually best suited for regenerating the stand. Where <span class="ital">Pseudotsuga</span> is the only species suitable for timber, the seedlings may need protection from wind and sun. If a layer of <span class="ital">Calamagrostis</span> or <span class="ital">Carex</span> is present, the site may need careful preparation for adequate stocking, In most areas livestock use the sites only lightly, but big game use them frequently. Some sites provide important forage and cover for elk and mule deer. Deer may also use these areas for fawning. This h.t. provides important nesting sites for the Steller's jay, red-breasted nuthatch, and Cooper's hawk. In the PIP0 phase, wild turkey may roost in the large pines and feed on the seeds.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Symphoricarpos albus</span> h.t. <br />(PSME/SYAL; Douglas-fir/common snowberry)</h4>
			<p><strong>Soil</strong>&#8212;Most of our sample stands occur on granitics, quartz monzonite, or basalt (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Soil textures vary from sandy loam to clay loam and some are gravelly to very gravelly. The pH ranges from 5.5 to 7.0 and averages 6.4. Areas of bare rock or bare soil seldom exceed 5 percent. Average litter depth can reach 8.7 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-1</a>). In the PIPO phase, <span class="ital">Pinus ponderosa</span> is usually the conifer most suitable for restocking the site. It grows best in openings that receive full sunlight. When present, <span class="ital">Calamagrostis rubescens</span> also responds to increased sunlight and can form a dense sod that retards conifer reproduction. In the SYAL phase, <span class="ital">Pseudotsuga</span> is usually the only conifer well adapted to these sites. Here, the existing stand must be managed carefully to protect <span class="ital">Pseudotsuga</span> seedlings from severe wind and sun.</p>
			<p>Livestock usually find low amounts of forage in this h.t.; but may sometimes congregate because of the gentle terrain. In some areas, the seral shrubs provide important browse for elk, whitetail deer, or mule deer. In the PIPO phase, ruffed grouse may use these sites year round and wild turkey may roost in the large pines and feed on pine seeds.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Vaccinium globulare</span> h.t. <br />(PSME/VAGL; Douglas-fir/blue huckleberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;If present, <span class="ital">Pinus ponderosa</span> or <span class="ital">P. contorta</span> should regenerate wherever the tree canopy is removed and a seedbed is available. <span class="ital">Pseudotsuga</span> seedlings may benefit from a light tree canopy, but the undergrowth of shrubs and grass can impede their establishment. In summer and fall, elk and deer may seek food and cover on these sites and the berry crops attract bears, grouse, and humans.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Acer glabrum</span> h.t. <br />(PSME/ACGL; Douglas-fir/mountain maple)</h4>
			<p><strong>Soil</strong>&#8212;Soil characteristics vary between phases (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Soils in the SYOR phase are derived mostly from calcareous sedimentaries and a few from quartzite. The textures are mostly loams or silt-loams and are usually gravelly to very gravelly. Areas of bare rock often reach 15 percent, but bare soil seldom exceeds 5 percent. Average litter depth per site can approach 8 cm.</p>
			<p>Soils in the ACGL phase are derived from quartz monzonite, diorite, granitics, basalt, and occasionally sedimentaries. Textures are mostly loams to sandy loams and a few are gravelly. Soil pH ranges from 5.9 to 6.6 and averages 6.3. Coverage of bare rock can reach 15 percent but is usually less than 5 percent. Areas of bare soil seldom exceed 5 percent. Average litter depth per site can approach 10 cm.
</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to very high in the ACGL phase (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). In openings, <span class="ital">Pinus ponderosa</span>, if present, grows well and regenerates easily; however, a dense layer of shrubs may develop and suppress conifer seedlings for several decades. Artificial regeneration of <span class="ital">Pseudotsuga</span> can be successful with adequate site preparation (Kittams and Ryker 1975). Part of Lyon's (1971) study of succession after fire included this h.t. and probably this phase.</p>
			<p>In the SYOR phase, timber potential is low to moderate (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pseudotsuga</span> is the only suitable timber species for these sites and its regeneration may be slow to establish. Overstory removal will stimulate the growth of shrubs, which may suppress conifer seedlings.</p>
			<p>In both phases, livestock find little forage in mature stands but may seek shelter from sun and insects. In most areas, however, livestock seldom use these sites because adjacent areas provide more gentle slopes and better forage.</p>
			<p>PSME/ACGL sites may be important to wildlife, depending upon location and stage of succession. The seral shrubs provide important forage and cover for elk and mule deer but snow depths usually prevent winter use. The sites may provide important habitat for ruffed grouse most of the year and for blue grouse in summer and fall.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Physocarpus malvaceus</span> h.t. <br />(PSME/PHMA; Douglas-fir/ninebark)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mostly granitics or basalt and occasionally quartzite or quartz monzonite (<a href="habitat_types_C-ID_appD1.php#PSMEcoarse">appendix D</a>). Soil textures vary from silty clay loam to sandy loam and a few are gravelly to very gravelly. Soil pH ranges from 5.5 to 6.9 and averages 6.4. Coverages of bare rock are usually less than 5 percent but can reach 60 percent in some cases. Areas of bare soil are usually less than 5 percent. Average litter depth on a site can reach at least 11 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate in the PSME and moderate to high in the PIPO phase. In much of the PIPO and CARU phases, <span class="ital">Pinus ponderosa</span> is a vigorous seral species and regenerates easily where it receives full sunlight. In the PSME phase, <span class="ital">Pseudotsuga</span> is the only tree adapted to the site and requires careful stand manipulation for successful regeneration. Removing the tree canopy may stimulate shrub development and retard growth of tree seedlings.</p>
			<p>Livestock seldom graze these sites unless severe disturbance has caused invasion of grasses and forbs.</p>
			<p>Big game frequent these areas; amount of use varies with stage of succession and location of site. In some wintering areas, these sites are important for elk, especially if seral shrubs are present and, in a few areas, moose utilize the forage and cover year round. Along the Salmon River, bighorn sheep use these sites for forage, cover, and escape. Whitetail deer, mule deer, and black bear also use the heavy cover. Ruffed grouse and, to a lesser extent, blue grouse may use these sites much of the year. When large <span class="ital">Pinus ponderosa</span> are present, wild turkeys may forage and roost here and flying squirrels are known to use the old, hollow pines. This h.t. is also considered important for the pileated woodpecker, mountain chickadee, red-breasted
nuthatch, and pygmy owl.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Linnaea borealis</span> h.t. <br />(PSME/LIBO; Douglas-fir/twinflower)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity should be moderate in our area. If present, <span class="ital">Pinus contorta</span> or <span class="ital">P. ponderosa</span> should regenerate in openings that receive full sunlight. However, when the tree canopy is removed <span class="ital">Calamagrostis</span> may increase and create a need for special site preparation.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Vaccinium caespitosum</span> h.t. <br />(PSME/VACA; Douglas-fir/dwarf huckleberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity should be moderate. <span class="ital">Pinus ponderosa</span> and <span class="ital">P. contorta</span> can regenerate in openings that receive ample sunlight. If <span class="ital">Calamagrostis rubescens</span> is present in large amounts, the sod may need to be broken for successful tree regeneration.</p>
			
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_C-ID_05.php">On to <span class="ital">Pseudotsuga menziesii</span> (PSME) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_03.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<strong>4</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">Next &gt;&gt;</a>]</p>
			</div>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
