<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Successional Status of Montana Forests: Fire history, Grazing history, Logging history</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Successional Status of Montana Forests: Fire history, Grazing history, Logging history" />
		<meta name="keywords" content="forest vegetation, Montana, habitat, types, plant communities, forest ecology, forest management, fire, grazing, logging" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../../../GeoPath/habitat/index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF MONTANA</a> &gt; SUCCESSIONAL STATUS OF MONTANA FORESTS</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Montana</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Pfister, Robert D., Bernard L. Kovalchik, Stephen F. Arno, and Richard C. Presby. 1977. Forest habitat types of Montana. Gen. Tech. Rep. INT-34. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Forest &amp; Range Experiment Station. 174 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_01.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<strong>2</strong>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set2"></a>SUCCESSIONAL STATUS OF MONTANA FORESTS</h3>
			<h4>Fire History</h4>
			<p>Recognition of the important role played by lightning-caused fires in Montana forests has been growing, especially in the last few decades (Wellner 1970). During our sampling, we observed and recorded evidence of past fires on about 1,000 plots. Such evidence consists of partially-healed fire scars at the base of old trees or stumps, charred material on or in the ground, and presence of new stands or age-classes of seral species.</p>
			<p>Some of the most abundant species in Montana forests are fire-adapted seral trees (Starker 1934; Wellner 1970). Mature <span class="ital">Larix occidendalis</span>, <span class="ital">Pinus ponderosa</span>, and <span class="ital">Pseudotsuga menziesii</span> have thick basal bark which makes them very resistant to fire. <span class="ital">Pinus contorta</span> and <span class="ital">Thuja</span> show moderate resistance to death from ground fire. Most other species (e.g., <span class="ital">Abies</span>, <span class="ital">Tsuga</span>, <span class="ital">Picea</span>) are likely to be killed by most fires, because of thin bark and susceptibility to rot entering fire-caused wounds.</p>
			<p>The vast majority of all sample stands showed evidence of wildfire within the past two centuries, despite deliberate selection of the oldest and least-disturbed stands. The few stands that showed no evidence of fire in the past 200 years were usually at high elevations or on very moist sites.</p>
			<p>In general, the <span class="ital">Pinus flexilis</span>, <span class="ital">Pinus ponderosa</span> and drier <span class="ital">Pseudotsuga</span> habitat types showed evidence of light ground fires at intervals averaging less than 30 years. Moister <span class="ital">Pseudotsuga</span> habitat types and <span class="ital">Abies lasiocarpa</span> habitat types showed much longer fire-free intervals, and the fires often resulted in formation of new stands, or at least in the addition of a new age class in surviving stands.</p>
			<p>Arno (1976) cross-sectioned fire scars on old growth <span class="ital">Pinus ponderosa</span>, <span class="ital">Pseudotsuga menziesii</span>, <span class="ital">Pinus contorta</span>, <span class="ital">Larix occidentalis</span>, and <span class="ital">Pinus albicaulis</span> in several habitat types in three areas of the Bitterroot National Forest. He found that prior to 1900 average fire frequencies had been about 10 years in <span class="ital">Pinus ponderosa/</span> and <span class="ital">Pseudotsuga/</span> bunchgrass habitat types, 16&#8211;19 years in most other <span class="ital">Pseudotsuga</span> habitat types, 27 years in lower subalpine <span class="ital">Abies lasiocarpa</span> habitat types, and 30&#8211;33 years in upper subalpine and timberline habitat types. Many individual trees and stumps in <span class="ital">Pseudotsuga</span> habitat types at various locations in west-central Montana have scars from 10 or more fires in a period of 200 or 250 years; however, few fires occurred in the last 50 years.</p>
			<p>Gabriel (1976) studied the fire history of <span class="ital">Pinus contorta</span>-dominated forests in an area of the Bob Marshall Wilderness, Flathead National Forest. He found evidence that fire had been rather frequent and that it burned at various intensities. Other fire frequency studies have been made by Houston (1973) in northern Yellowstone National Park and by Loope and Gruell (1973) in the Jackson Hole area of northwestern Wyoming. East of the Continental Divide, in the vast forests dominated by <span class="ital">Pinus contorta</span>, we commonly found stands where many of the trees had scars indicating they had survived one to three ground fires. If <span class="ital">Pinus contorta</span> stands survive more than about 100 years, they often become susceptible to attack and mortality from mountain pine beetle (<span class="ital">Dendroctonus ponderosae</span>); the resulting large buildup of dry fuels invites an intense conflagration (Roe and Amman 1970). <span class="ital">Pinus contorta</span> stands showing no evidence of having survived a fire were in most cases even-aged and evidently had become established after an intense forest fire.</p>
			<p>Relative coverages and species composition in the tree layer and undergrowth often change dramatically after an intense fire. West of the Continental Divide, double or triple burns have sometimes removed the conifer seed source. Thus, a shrub-field stage of succession (composed of such species as <span class="ital">Amelanchier alnifolia</span>, <span class="ital">Salix scouleriana</span>, <span class="ital">Acer glabrum</span>, <span class="ital">Ceanothus velutinus</span>, <span class="ital">Prunus</span> spp., and <span class="ital">Physocarpus malvaceus</span>) may dominate the site for half a century or longer.</p>
			<h4>Grazing History</h4>
			<p>In general, domestic grazing has not had a pronounced impact upon the forest vegetation in Montana. In northwestern and west-central portions of the State, however, some of the most open, low-elevation forests (i.e., <span class="ital">Pinus ponderosa</span> series and drier habitat types in the <span class="ital">Pseudotsuga</span> series) and streamside areas have been moderately to heavily grazed by cattle, horses, or sheep. Hillsides too steep for cattle have not been grazed heavily, due to the decline in sheep raising in the past 20&#8211;30 years. Grazing has been extended into moister forest types in some localities, such as the Montana-Idaho Divide west of Superior, where sheep were historically grazed. Also, clearcuts and other heavily logged areas are often used by cattle. Still, a large proportion of the west-side forest has apparently never been grazed by domestic stock.</p>
			<p>East of the Continental Divide, there is a higher proportion of dry, open forest having bunchgrasses and other palatable forage. Also, the forest is broken by extensive mountain grasslands suitable for summer range. Grazing is often extended up the major forested valleys where streamside vegetation and luxuriant meadows are common. Although lower east-side forests are often moderately to heavily grazed, the denser, high-elevation forests receive little use except as bedding areas where they border subalpine grasslands. Sheep grazing of alpine tundra on the Montana side of the
Beartooth Plateau was halted in the 1950s, and plant recovery has been noticeable. Large flocks of sheep continue to graze the Wyoming portion of this alpine area.</p>
			<h4>Logging History</h4>
			<p>About half of the forest land in Montana had not been logged as of 1973. This generalization applies to both sides of the Continental Divide. However, in some historical mining localities such as Butte and Helena, extensive forests were cut between about 1870 and 1920. In the Highland Mountains south of Butte, for example, the forests were logged nearly to the alpine timberline.</p>
			<p>Early settlement west of the Continental Divide brought extensive clearing of forests in the major valleys for farming and ranching. Heavy cutting was also associated with early mining and railroading activities. Commercial lumbering has long been practiced west of the Divide, and it has expanded considerably with the establishment of a diversified forest products industry in the past two decades. A great deal of virgin forest land both east and west of the Divide has been roaded and logged since 1950, but several wilderness and primitive areas have also been established and many of the remaining roadless areas are being studied for possible inclusion in the National Wilderness System.</p>
									
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_MT_03.php">On to <span class="ital">Pinus flexilus</span> Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_01.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<strong>2</strong>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
