<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Forest Habitat Types of Montana: Thuja plicata and Tsuga heterophylla Series</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Montana: Thuja plicata and Tsuga heterophylla Series" />
		<meta name="keywords" content="forest vegetation, Montana, habitat, types, plant communities, forest ecology, forest management, forests, Thuja plicata, Tsuga heterophylla, western redcedar, western hemlock" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../../../GeoPath/habitat/index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF MONTANA</a> &gt; <span class="ital">THUJA PLICATA</span> SERIES AND <span class="ital">TSUGA HETEROPHYLLA</span> SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Montana</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Pfister, Robert D., Bernard L. Kovalchik, Stephen F. Arno, and Richard C. Presby. 1977. Forest habitat types of Montana. Gen. Tech. Rep. INT-34. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Forest &amp; Range Experiment Station. 174 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_07.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<strong>8</strong>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">THUJA PLICATA</span> SERIES AND <span class="ital">TSUGA HETEROPHYLLA</span> SERIES</h3>
			<p><strong>Soil</strong>&#8212;Parent materials within both series are exclusively noncalcareous and nonigneous&#8212;predominantly sedimentary rock and argillite (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Presumably, volcanic ash and loess deposits have also had a major influence on soil development with resultant fertility and moisture-holding characteristics beneficial to <span class="ital">Thuja</span>, <span class="ital">Tsuga</span>, and associated undergrowth. Surface soils are primarily acidic, gravelly loams to silts. Ground surfaces rarely have exposed rock or bare soil; mean litter depth exceeds 5 cm for all habitat types and phases in the series.</p>
			<p><strong>Productivity/Management</strong>&#8212;The <span class="ital">Thuja</span> and <span class="ital">Tsuga</span> series have the highest timber productivity (<a href="habitat_types_MT_app.php#e3">appendix E-3</a>). Maximum production is usually found in stands dominated by seral species. Shade-tolerant conifers are often susceptible to fungal decay (e.g., <span class="ital">Echinodontium tinctorum</span> in <span class="ital">Abies grandis</span> and <span class="ital">Tsuga</span>) that may be accelerated by partial cutting. Maximum productivity will likely be realized by even-aged management of seral species. Natural regeneration occurs readily when an adequate seed source is available and site preparation has been thorough enough to retard development of brushfields.</p>
			<p>Forage potential (primarily palatable shrubs) for deer and elk is very high in early successional stages, but may be almost nonexistent in dense, near-climax stands. In some areas, these series occur at low enough elevations to provide winter range. <span class="ital">Thuja plicata</span> may be utilized heavily on big-game winter range. Forage potential for domestic livestock is very low.</p>
												
			<h4><a name="set1a"></a><span class="ital">Thuja plicata/Clintonia uniflora</span> h.t.<br /> (THPL/CLUN; western redcedar/queencup beadlily)</h4>
			<p><strong>Soil</strong>&#8212;The THPL/CLUN h.t. was commonly found on argillite or noncalcareous sedimentary parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic, gravelly loams to silts. Ground surfaces had little rock or bare soil exposed; and duff depths averaged greater than 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is high to very high (<a href="habitat_types_MT_app.php#e3">appendix E-3</a>). However, it is difficult to find free-growing individuals for determining site index in the dense mature stands on this habitat type. Limited data from the CLUN phase suggest that productivity is uniformly high for <span class="ital">Pseudotsuga</span>, <span class="ital">Abies lasiocarpa</span>, <span class="ital">A. grandis</span>, <span class="ital">Picea</span>, and <span class="ital">Larix</span>. In the MEFE phase, productivity is somewhat lower and <span class="ital">A. grandis</span> is absent. The ARNU phase has the highest productivity, especially for <span class="ital">Pseudotsuga</span> and <span class="ital">Abies grandis</span>. Although potential productivity is high, realization of it may require intensive management&#8212;selecting the best species, controlling the stocking, and minimizing disease and insect losses.</p>
			<p>Basal areas are high in stands throughout this habitat type, natural fire frequency is low, although fires that do occur are often intense. Fires early in this century destroyed essentially all <span class="ital">Thuja</span> in some narrow canyon habitats observed west of Superior, Montana, and <span class="ital">Thuja</span> has not become reestablished in the new stands. Grazing of <span class="ital">Thuja</span> by cattle and big game appears to retard natural reinvasion.</p>
			<p>Forage production for elk and deer is generally high during early successional stages. Some lower elevation sites provide winter range, with resultant heavy browsing of <span class="ital">Thuja</span>. Forage potential for domestic livestock is low in natural stands.</p>
			<p>Isolated, ancient <span class="ital">Thuja</span> groves have special appeal for recreation and for botanical studies.</p>
			<p>Construction and maintenance of campgrounds, roads, and trails may be difficult and may damage sites in the ARNU phase, which has high water tables for at least part of the growing season.</p>
			
			<h4><a name="set1b"></a><span class="ital">Thuja plicata/Oplapanax horridum</span> h.t.<br /> (THPL/OPHO; western redcedar/devil's club)</h4>
			<p><strong>Soil</strong>&#8212;Soils data were very limited for this habitat type since most of the sample stands were obtained from other studies. In the two stands we sampled, surface soils were acidic, nongravelly loams (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Ground surfaces had no bare soil or rock exposed. R. and J. Daubenmire (1968) indicated that pH was within the range of the <span class="ital">Tsuga/Pachistima</span> h.t. (TSHE/CLUN h.t. equivalent for Montana).</p>
			<p><strong>Productivity/Management</strong>&#8212;Limited site-index data and ecological comparison with the ABLA/OPHO h.t. suggest that productivity potential would be high. However, intensive timber management is usually not practiced in this habitat type for several reasons. The habitat type covers a very small area, and existing stands are frequently ancient groves with high recreational, esthetic, and botanical value. Vegetation manipulation would require special constraints in typical streamside locations. High water tables during most of the season and the possibility of compaction preclude use of heavy equipment. Road construction and intensive site development would be expensive, and could cause irreparable damage.</p>
			<p>Forage production for deer and elk is low to moderate in typical old-growth stands. Some stands may be valuable for winter range. Forage potential for domestic livestock is very low.</p>
			
			<h4><a name="set1c"></a><span class="ital">Tsuga heterophylla/Clintonia uniflora</span> h.t.<br /> (TSHE/CLUN; western hemlock/queencup beadlily)</h4>
			<p><strong>Soil</strong>&#8212;The TSHE/CLUN h.t. occurred almost exclusively on noncalcareous sedimentary and metamorphic parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic gravelly loams to silts. Ground surfaces had virtually no rock or bare soil exposed; duff depth ranged from 4 to 7 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is high to very high, although it was difficult to find free-growing, vigorous trees of seral species in the old-growth stands sampled. Site-indexes for <span class="ital">Larix</span> and <span class="ital">Picea</span> are some of the highest attained for these species (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Because of moderate terrain, accessibility, and high productivity, TSHE/CLUN sites are excellent candidates for intensive timber management. Realizing this high productivity potential will require selecting the best species, controlling stocking, and minimizing disease and insect losses. Obtaining natural regeneration on burned or scarified clearcuts of moderate size is usually no problem, except when brushfields temporarily dominate early succession. Planting and direct seeding have a high probability of success; these measures are sometimes necessary to control species composition or to compensate for lack of a natural seed source.</p>
			<p>Forage production for elk and deer is very high during early successional stages, and almost nonexistent, except for <span class="ital">Thuja</span> saplings, in dense, near-climax stands. Lower elevation sites often provide winter range for big game, with resultant heavy browsing of <span class="ital">Thuja</span>. Forage potential for domestic livestock is very low.</p>
			<p>Isolated ancient groves of <span class="ital">Tsuga</span> and <span class="ital">Thuja</span> have high recreational and botanical value.</p>
			<p>Intensive development may be difficult and may damage the site in the <span class="ital">Aralia</span> phase, which has a high water table for at least part of the growing season.</p>															
															
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_MT_09.php">On to <span class="ital">Abies lasiocarpa</span> Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_07.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<strong>8</strong>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
