<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Forest Habitat Types of Montana: Abies lasiocarpa Series</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Montana: Thuja plicata and Tsuga heterophylla Series" />
		<meta name="keywords" content="forest vegetation, Montana, habitat, types, plant communities, forest ecology, forest management, forests, Thuja plicata, Tsuga heterophylla, western redcedar, western hemlock" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF MONTANA</a> &gt; <span class="ital">ABIES LASIOCARPA</span> SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Montana</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Pfister, Robert D., Bernard L. Kovalchik, Stephen F. Arno, and Richard C. Presby. 1977. Forest habitat types of Montana. Gen. Tech. Rep. INT-34. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Forest &amp; Range Experiment Station. 174 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_08.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<strong>9</strong>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">ABIES LASIOCARPA</span> SERIES</h3>
			<p><strong>Soil</strong>&#8212;Soils in the <span class="ital">Abies lasiocarpa</span> series are derived from a variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Relationships of habitat types to parent materials are not evident except that the ABLA/CLPS h.t. is generally restricted to calcareous substrates. Surface soils are usually acidic to very acidic, and range from gravelly sandy loams to silts. Ground surfaces have little rock or bare soil exposed, except in the upper subalpine and timberline habitat types. Duff depth varies; although litter production is relatively low, natural decomposition is slow and reduction of duff by natural fire occurs infrequently.</p>

			<h4><a name="set1a"></a>LOWER SUBALPINE HABITAT TYPES</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from low to very high (<a href="habitat_types_MT_app.php#e1">appendix E</a>). With relatively high precipitation and snowfall (<a href="habitat_types_MT_app.php#d2">appendix D-2</a>) the lower subalpine sites are also important for water production. Mule deer, elk, and bear use these habitat types for summer range. Domestic stock use is rare west of the Divide, except locally in valley bottom sites. East of the Divide, some of the more moist plateaus and areas of gentle terrain provide moderate grazing opportunities, especially in early successional stages.</p>
												
			<h5><a name="set1a1"></a><span class="ital">Abies lasiocarpa/Oplopanax horridum</span> h.t.<br /> (ABLA/OPHO; subalpine fir/devil's club)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were very acidic, nongravelly loams. Ground surfaces were rock free and no bare mineral soil. was exposed. Duff depths were among the greatest recorded in any habitat type (7 to 10 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Productivity potential for timber is moderate to high (<a href="habitat_types_MT_app.php#e1">appendix E</a>), but sites are generally not suitable for intensive timber production. As in the THPL/OPHO h.t., this habitat type occupies very small areas, often has high recreational and esthetic values, and has high water tables that preclude use of heavy equipment. Road construction, trails, and site development problems can be minimized by avoiding these sites. Domestic grazing potential is very low and little deer or elk use was observed.</p>
			
			<h5><a name="set1a2"></a><span class="ital">Abies lasiocarpa/Clintonia uniflora</span> h.t.<br /> (ABLA/CLUN; subalpine fir/queencup beadlily)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/CLUN h.t. were derived from a variety of noncalcareous sedimentary and metamorphic parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were moderately gravelly throughout, with the lowest gravel contents in the ARNU phase and the highest in the XETE phase. Reactions varied from acidic to very acidic. Ground surfaces had virtually no rock or bare soil exposure and duff accumulation varied from moderate to deep. The VACA phase had the least duff (mean = 3.7 cm), while the MEFE and ARNU phases averaged 6.2 and 7.1 cm, respectively.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity potential ranges from moderate to very high in western Montana (<a href="habitat_types_MT_app.php#e3">appendix E-3</a>). Productivity is highest in the ARNU phase and lowest in the VACA and XETE phases. In the few stands slightly east of the Continental Divide in Glacier National Park and the Lewis and Clark National Forest, productivity is low to moderate (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). Five important seral species (<span class="ital">Pseudotsuga</span>, <span class="ital">Larix occidentalis</span>, <span class="ital">Pinus contorta</span>, <span class="ital">Picea</span>, and <span class="ital">Pinus monticola</span>) provide flexibility for intensive timber management and opportunities for developing mixed species stands. Preferred species vary by phase; silvicultural prescriptions must be tempered by on-site evaluation of existing stands. Except for sites in the VACA phase where it occurs naturally, <span class="ital">Pinus ponderosa</span> is near its cold limits and grows poorly in this habitat type. Partial cutting of mature stands will increase dominance of <span class="ital">Abies lasiocarpa</span>. Even-aged management offers greater promise for production of seral species.</p>
			<p>The VACA phase, with flat ground and well-drained soils, can tolerate heavy equipment, recreational use, and site development. The ARNU phase also has gentle topography, but soft ground and high water tables during part of the growing season limit certain activities and developments. The XETE and MEFE phases (and part of the CLUN phase) are typically on steeper ground at somewhat higher elevations, but are still relatively accessible with conventional logging techniques.</p>
			<p>Site preparation needs will probably be greatest in the XETE and MEFE phases, but for different reasons. The XETE phase is the droughtiest, and site preparation may be needed for prompt seedling establishment. The MEFE phase has ample moisture, but brushfield development could be a problem, although in some areas <span class="ital">Menziesia ferruginea</span> apparently does not reinvade rapidly following disturbance. Additional observations and data are needed to define early successional development in all phases.</p>
			<p>All phases can produce large quantities of browse for elk and deer in early successional stages. However, because of snow depths only a few of the lowest elevation sites (generally VACA and ARNU phases) provide opportunity for winter range.</p>
			<p>Watershed management values in this habitat type are high&#8212;as they are throughout most of the <span class="ital">Abies lasiocarpa</span> series&#8212;because of high precipitation and snowpack accumulation.</p>
			
			<h5><a name="set1a3"></a><span class="ital">Abies lasiocarpa/Galium triflorum</span> h.t.<br /> (ABLA/GATR; subalpine fir/sweetscented bedstraw)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/GATR h.t. were derived from almost all available parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were generally acidic nongravelly loams to silts. Ground surfaces had virtually no bare soil or rock exposed, and duff depth averaged 5.9 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from moderate to high west of the Continental Divide, and is moderate eastward (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Moderate to heavy use (including browsing and bedding) by deer and elk is apparent in most stands. Moose activity is also common especially on valley-bottom sites. In many areas this habitat type provides the best big-game cover available. Browse production is moderate to good, especially in the earlier successional stages. These sites are often used by cattle, primarily for resting or bedding after feeding on nearby meadows or grasslands. This type has high water yield potential, and management activities must be constrained to protect streams.</p>
			
			<h5><a name="set1a4"></a><span class="ital">Abies lasiocarpa/Vaccinium caespitosum</span> h.t.<br /> (ABLA/VACA; subalpine fir/dwarf huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly and nongravelly sandy loams to silts with acidic to very acidic reactions (mean pH 5.0). Ground surfaces had virtually no bare soil or rock exposed; duff depth averaged 4.8 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>), and <span class="ital">Pinus contorta</span> appears to be the only species well suited for management. <span class="ital">Pinus contorta</span> has mostly nonserotinous cones in this habitat type, and natural seedling establishment seems to occur periodically even without disturbance. Gentle terrain and stable soil conditions are favorable for timber management. Some mechanical scarification is desirable to prevent a mat of <span class="ital">Calamagrostis rubescens</span> from retarding reproduction.</p>
			<p>Intensive recreational sites, such as campgrounds and picnic areas, are often located in this habitat type. Observations made in campgrounds indicate that <span class="ital">Vaccinium caespitosum</span> usually increases its coverage under moderate disturbance, while its associate <span class="ital">V. scoparium</span> dies out. However, heavy foot traffic, not directed or regulated by paths and barriers, will soon destroy most of the <span class="ital">V. caespitosum</span> also.</p>
			<p>Light to moderate use by moose, elk, and deer is evident. Cattle use also occurs in some areas, although forage potentials for grazing are generally low.</p>
			
			<h5><a name="set1a5"></a><span class="ital">Abies lasiocarpa/Calamagrostis canadensis</span> h.t.<br /> (ABLA/CACA; subalpine fir/bluejoint)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/CACA h.t. were derived from a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Moist surface soils were acidic to very acidic sandy loams to silts. Most were nongravelly. Ground surfaces had little bare soil or rock exposed. Duff accumulations were extremely variable, ranging from almost none (in stream bottom sites subject to flooding) to depths of 10 to 15 cm in seepage or depression areas.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate (<a href="habitat_types_MT_app.php#e1">appendix E</a>). The CACA phase appears to have lower productivity than the other phases. <span class="ital">Picea</span> (attaining maximum heights of 90 to 120 feet in most stands) and <span class="ital">Pinus contorta</span> offer greatest potential for timber management. However, choice of cutting methods is largely restricted to clearcutting because of severe windthrow hazards associated with partial cutting on high-water-table sites. In narrow stringers along watercourses, light selection cutting (removing less than 30 percent of the basal area) can sometimes be done with little damage to the site or stand. Heavy equipment should not be used in the spring and early summer when water tables are highest.</p>
			<p>Moderate summer use by deer and often by elk was evident in most sample stands in the CACA and VACA phases. Relatively heavy use by moose was noted in each of the GATR phase stands sampled. Domestic grazing values may be relatively high in early successional stages. However, cattle may churn the wet soils by trampling and severely limit conifer seedling establishment. Sites are poorly suited for roads, trails, or other developments. Protection of water resources is a major consideration in any management activity in this habitat type.</p>
			
			<h5><a name="set1a6"></a><span class="ital">Abies lasiocarpa/Linnaea borealis</span> h.t.<br /> (ABLA/LIBO; subalpine fir/twinflower)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). These were noncalcareous except for several stands in the LIBO phase. Surface soils in the LIBO phase were gravelly loams to silts with neutral to acidic reaction. Surface soils in the VASC phase were similar except for finer textures and greater acidity. Surface soils in the XETE phase were gravelly to very gravelly sandy loams to silts with acidic reactions. Ground surfaces generally had very little bare soil or rock exposed and moderate duff depths.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from low to high (<a href="habitat_types_MT_app.php#e1">appendix E</a>). The LIBO and XETE phases appear to have the highest productivity; the VASC phase the lowest. Since ABLA/LIBO sites are generally located on well-drained uplands, they provide good opportunities for timber management. Our observations suggest that <span class="ital">Pseudotsuga</span> may often be frost-damaged when planted in the VASC phase. Value for domestic grazing is low. Light or sometimes moderate spring to fall use by deer and elk was evident in the sample stands; browse is limited, but stands provide good cover for big game. Water yield is moderately high.</p>
			
			<h5><a name="set1a7"></a><span class="ital">Abies lasiocarpa/Menziesia ferrugina</span> h.t.<br /> (ABLA/MEFE; subalpine fir/menziesia)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/MEFE h.t. were derived from a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly (28 percent) loams to silts with very acidic to acidic reactions (mean pH 4.9). Ground surfaces had almost no bare soil or rock exposed; duff depth averaged 4.7 cm. </p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_MT_app.php#e1">appendix E</a>) with several commercial species well adapted to these sites. However, intensive management for timber production presents some major problems. Partial cutting leads to an increase in the shade-tolerant <span class="ital">Abies lasiocarpa</span> or to a lack of regeneration under the dense <span class="ital">Menziesia ferruginea</span> and <span class="ital">Alnus sinuata</span> undergrowth. Clearcutting is recommmended to establish vigorous second-growth stands of seral species. Site preparation is essential and can be accomplished by dozer scarification on gentler slopes. However, on steep slopes prescribed burning is the only feasible method. Unfortunately, fuels on these slopes remain moist, leaving only a brief period in certain years when successful burning can be accomplished. The silvicultural recommendations of Roe and DeJarnette (1965) and Boyd and Deitschman (1969) are probably applicable to this habitat type as well as TSME/MEFE.</p>
			<p>Watershed value is high; maintaining or improving water yields by regulating flows should be considered in any management actions. Elk often make extensive use of this habitat type for both cover and forage during the summer and fall. There is no potential for domestic grazing. Recreational use is severely limited by dense undergrowth and steep slopes.</p>
			
			<h5><a name="set1a8"></a><span class="ital">Tsuga mertensiana/Menziesia ferrugina</span> h.t.<br /> (TSME/MEFE; mountain hemlock/menziesia)</h4>
			<p><strong>Soil</strong>&#8212;Soils appear similar to those of the ABLA/MEFE h.t. (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>).</p>
			<p><strong>Productivity/Management</strong>&#8212;This is similar to that for ABLA/MEFE except that seral conifers are often only minor components of natural stands.</p>
			
			<h5><a name="set1a9"></a><span class="ital">Abies lasiocarpa/Xerophyllum tenax</span> h.t.<br /> (ABLA/XETE; subalpine fir/beargrass)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/XETE h.t. were derived from a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly sandy loams to silts. Reactions were primarily acidic in the VAGL phase (mean pH 5.1) and very acidic in the VASC phase (mean pH 4.6). Ground surfaces had little bare soil and rock exposed; duff depth averaged about 3.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from low to high (<a href="habitat_types_MT_app.php#e1">appendix E</a>); highest values are generally in the VAGL phase. The VAGL phase offers opportunities for mixed species management, but prompt establishment of regeneration may require both site preparation and shade. <span class="ital">Pseudotsuga</span> and <span class="ital">Pinus contorta</span> appear to offer the greatest potential for timber management. In the VASC phase, timber management is generally limited to <span class="ital">Pinus contorta</span>. However, regeneration may be easier to obtain on these cooler aspects, and the gentler terrain is better suited for intensive timber management.</p>
			<p>Browse production for deer and elk is moderate in the VAGL phase and low in the VASC phase. Evidence of light to moderate summer and fall use by deer and elk is present in most stands. Occasional use by moose is evident in the VASC phase.</p>
			<p>Domestic grazing potential is generally low. Watershed management should recognize the moderately high precipitation coupled with high evapotranspiration and runoff rates on southerly exposures. Snowpack in this habitat type (especially in the VAGL phase) may melt periodically during winter and disappear in the spring several weeks earlier than in adjacent types.</p>
			
			<h5><a name="set1a10"></a><span class="ital">Tsuga mertensiana/Xerophyllum tenax</span> h.t.<br /> (TSME/XETE; mountain hemlock/beargrass)</h4>
			<p><strong>Soil</strong>&#8212;Soils were similar to those described for the ABLA/XETE h.t., VAGL phase (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>).</p>
			<p><strong>Productivity/Management</strong>&#8212;This is similar to that described for the ABLA/XETE h.t., VAGL phase.</p>
			
			<h5><a name="set1a11"></a><span class="ital">Abies lasiocarpa/Vaccinium globulare</span> h.t.<br /> (ABLA/VAGL; subalpine fir/blue huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/VAGL h.t. were derived from a wide variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic gravelly loams to silty clay loams. Ground surfaces had little bare mineral soil or rock exposed; duff was moderately deep (average 5.3 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). <span class="ital">Pinus contorta</span> should be easier to regenerate than other species. Sample stands showed light to moderate use by deer and elk with occasional use by moose and bears. Domestic grazing use is quite limited, but watershed values are relatively high. Most of the dense stands of <span class="ital">Vaccinium globulare</span> east of the Continental Divide are limited to this habitat type, so management to enhance berry production may be an important consideration. However, silvicultural prescriptions to increase amounts of <span class="ital">Vaccinium globulare</span> and berry production are not known at this time, and it would be unwise to extrapolate from other habitat types or from areas where different species of <span class="ital">Vaccinium</span> have been studied. Responses of <span class="ital">Vaccinium globulare</span> to various types of vegetative manipulation need to be studied.</p>
			
			<h5><a name="set1a11"></a><span class="ital">Abies lasiocarpa/Vaccinium scoparium</span> h.t.<br /> (ABLA/VASC; subalpine fir/grouse whortleberry)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/VASC h.t. were derived from a wide variety of parent materials with some differences by phase as shown in <a href="habitat_types_MT_app.php#d1">appendix D-1</a>. Surface soils in the VASC phase were gravelly sandy loams to silts; those in the CARU and THOC phases had less gravel and were finer in texture. Soils in all phases were acidic to very acidic. Ground surfaces had small amounts of rock and very little bare mineral soil exposed. Duff was moderate in the VASC phase (average 3.5 cm) to moderately deep in the THOC phase (average 5.6 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate (<a href="habitat_types_MT_app.php#e1">appendix E</a>), with highest productivities in the CARU and THOC phases. Extensive areas of gentle terrain are suitable for timber management. Existing stands of <span class="ital">Pinus contorta</span> could be managed for small sawtimber, pulpwood, posts, and poles. This species should do best under even-aged management systems. <span class="ital">Pseudotsuga</span> is generally available for timber production in the CARU phase; but regeneration may require scarification because of grass sod. In the THOC phase, <span class="ital">Picea</span> is also available; stands with overstories of <span class="ital">Pinus contorta</span> and vigorous understories dominated by <span class="ital">Picea</span> offer opportunities for partial cutting. According to Roe and Amman (1970), the risk of <span class="ital">Pinus contorta</span> loss to mountain pine beetle epidemics is less in this habitat type than in lower elevation habitat types, and smaller trees are less susceptible than large ones.</p>
			<p>Forage potential for big game or domestic stock is extremely low in forest stands. Clearcuts may produce 800 to 1,000 pounds of forage per acre per year, but palatability ratings are only fair for the native early-successional plants (Basile and Jensen 1971).</p>
			<p>Water yield is relatively high, and management constraints may be needed to protect water resources.</p>
			
			<h5><a name="set1a12"></a><span class="ital">Abies lasiocarpa/Alnus sinuata</span> h.t.<br /> (ABLA/ALSI; subalpine fir/Sitka alder)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were loams to silts with very acidic to acidic reactions. Gravel content averaged 18 percent. Ground surfaces generally had no bare soil or rock exposed; duff depth averaged 6.0 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate (<a href="habitat_types_MT_app.php#e1">appendix E</a>); <span class="ital">Pinus contorta</span> and <span class="ital">Picea</span> are prominent seral components. Big-game use appears to be light, stands may be important for cover. Water yield should be relatively high. The presence of <span class="ital">Alnus sinuata</span> suggests that water tables may be high during part of the year; this would create problems for certain management activities. Conifers should reestablish readily following major overstory removal or wildfire; however, tree growth may sometimes be retarded initially by the development of an <span class="ital">Alnus</span> dominated brushfield.</p>
			
			<h5><a name="set1a13"></a><span class="ital">Abies lasiocarpa/Calamagrostis rubescens</span> h.t.<br /> (ABLA/CARU; subalpine fir/pinegrass)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were primarily on sedimentary parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic sandy loams to silts with average gravel content of 21 percent. Ground surfaces had little or no bare soil or rock exposed. Duff averaged 4.3 cm deep.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from low to high (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). <span class="ital">Pseudotsuga</span> and <span class="ital">Pinus contorta</span> are major components of seral stands. Some mechanical scarification may be necessary to obtain conifer regeneration following harvest cuttings. However, many stands have advance regeneration of <span class="ital">Picea</span>, <span class="ital">Abies</span>, and even <span class="ital">Pseudotsuga</span> that could be managed following careful removal of the overstory. Light to moderate deer and elk use is evident in most stands. Cattle also make light use of stands on gentle topography. The potential for domestic forage production may be fairly good in early successional stages of this type&#8212;better than in other habitat types in the <span class="ital">Abies lasiocarpa</span> series. However, we do not know of any studies on forage production or grazing potential in this habitat type.</p>
			
			<h5><a name="set1a14"></a><span class="ital">Abies lasiocarpa/Clematis pseudoalpina</span> h.t.<br /> (ABLA/CLPS; subalpine fir/virgin's bower)</h4>
			<p><strong>Soil</strong>&#8212;All of our stands in the ABLA/CLPS h.t. were on calcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were silts to silty clay loams, ranging from slightly acidic to slightly basic. Gravel content was variable. Ground surfaces had little exposed rock or bare soil; duff depth averaged 4.2 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Forage values for both big game and domestic livestock appear to be low, although stands are often used as bedding areas by deer and elk. Domestic stock also bed and graze in this habitat type occasionally.</p>
			<p>Timber productivity is low (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). Site indexes for all species and maximum stand heights are consistently low (appendix <a href="habitat_types_MT_app.php#e1">E-1</a> and <a href="habitat_types_MT_app.php#e2">E-2</a>). The steep, exposed slopes with shallow, fine-textured soils warrant special precautions to prevent erosion.</p>
			
			<h5><a name="set1a15"></a><span class="ital">Abies lasiocarpa/Arnica cordifolia</span> h.t.<br /> (ABLA/ARCO; subalpine fir/heartleaf arnica)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/ARCO h.t. were derived from a broad variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic, mostly nongravelly loams to silty clay loams. Ground surfaces had little bare soil and rock exposed; duff depth averaged 3.9 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). Old-growth individuals of <span class="ital">Pseudotsuga</span> may attain maximum diameters of 3 feet and heights of 90 to 95 feet. Sod-forming grasses are usually scarce and tree regeneration after logging is not retarded by a flush of undergrowth vegetation in most cases. Watershed values are relatively high. Forest stands received light use by deer, elk, and cattle, but forage production for big game and domestic livestock is very low.</p>
			
			<h5><a name="set1a16"></a><span class="ital">Abies lasiocarpa/Carex geyeri</span> h.t.<br /> (ABLA/CAGE; subalpine fir/elk sedge)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were primarily nongravelly loams to silts with reactions ranging from very acidic to slightly basic (on limestone). Ground surfaces had little rock or bare soil exposed; duff depth averaged greater than 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). Choice of species is limited and varies by phase; regeneration may be difficult to obtain because of the cold, dry conditions and perhaps the competition from <span class="ital">Carex geyeri</span> and associated species. Moderate summer use by deer and elk was evident in sample stands. Cattle use appeared to be limited to bedding in stands adjacent to meadows. Maintaining vegetative cover to prevent erosion may be especially important on these sites.</p>

			
			<h4><a name="set2a"></a>UPPER SUBALPINE HABITAT TYPES</h4>
			<p><strong>Productivity/Management</strong>&#8212;The upper subalpine forest is highly productive for water yield and constitutes a sizable proportion of the land in Wilderness and back-country recreation areas. It is also important as summer range for mule deer, elk, bears, and other big game species. Domestic forage production is low in these stands. Timber productivity is generally low (<a href="habitat_types_MT_app.php#e1">appendix E</a>) and management is frequently hampered by problems in road construction, harvesting, regeneration, and site protection.</p>
			
			<h5><a name="set2a1"></a><span class="ital">Abies lasiocarpa/Ribes montigenum</span> h.t.<br /> (ABLA/RIMO; subalpine fir/mountain gooseberry)</h4>
			<p><strong>Soil</strong>&#8212;Soils were derived from a variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were very acidic nongravelly silts. Ground surfaces had little rock or bare soil exposed, and had deep duff (average 7.5 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is apparently low, based on limited data (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). Forage production is very low, but deer, elk, and domestic livestock evidently use sites adjacent to mountain parks for resting and bedding.</p>
			
			<h5><a name="set2a2"></a><span class="ital">Abies lasiocarpa-Pinus albicaulis/Vaccinium scoparium</span> h.t.<br /> (ABLA-PIAL/VASC; subalpine fir-whitebark pine/grouse whortleberry)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA-PIAL/VASC h.t. were derived from a wide variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were mainly gravelly loams to silts with acidic to very acidic reactions. Ground surfaces had moderate amounts of bare soil and rock exposed; duff depths averaged 4.4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Regenerating drier sites and those at higher elevations within the type will probably be difficult. Succession on disturbed sites will be slow and vegetation will be dominated by the same species found in old-growth stands. Managers should recognize the relatively high water yields and the importance of minimizing site disturbance because of slow vegetational recovery.</p>
			<p>This type and adjacent meadows provide much of the summer range for elk, moose, mule deer, grizzly bears, and black bears in central and southern Montana.</p>
			
			<h5><a name="set2a3"></a><span class="ital">Abies lasiocarpa/Luzula hitchcockii</span> h.t.<br /> (ABLA/LUHI; subalpine fir/wood-rush)</h4>
			<p><strong>Soil</strong>&#8212;Soils in the ABLA/LUHI h.t. were derived from a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were very acidic, gravelly loams to silts. Ground surfaces had little rock or bare soil exposed; duff depths averaged about 4.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is generally low, although a few moist sites in the MEFE phase show moderate productivity (<a href="habitat_types_MT_app.php#e3">appendix E-3</a>). Stands of large <span class="ital">Picea</span> sometimes develop in basins and on sheltered slopes. Because the more productive sites are often associated with wet soils, logging road construction may present problems. Clearcutting may make regeneration of <span class="ital">Picea</span> difficult in these severe environments (Pfister 1972b), and create excessive ground water. Partial cuttings are likely to incur heavy blowdown losses, as in high-elevation <span class="ital">Picea</span> stands in Colorado (Alexander 1973). The generally low productivity and problems associated with management for timber production suggest minimal development on these sites, at least until successful methods are developed and proven.</p>
			<p>Light summer use by mule deer, elk, and bear was observed. Domestic stock use and potential use is very low. This habitat type is a major source for summer streamflow in much of western Montana. Watershed protection and enhancement, as well as maintenance of esthetic values for &#8220;high-county&#8221; recreational pursuits are of primary management importance.</p>
			
			<h5><a name="set2a4"></a><span class="ital">Tsuga mertensiana/Luzula hitchcockii</span> h.t.<br /> (TSME/LUHI; mountain hemlock/wood-rush)</h4>
			<p><strong>Soil</strong>&#8212;Soils appear similar to those described for the ABLA/LUHI h.t. (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>).</p>
			<p><strong>Productivity/Management</strong>&#8212;This is similar to the ABLA/LUHI h.t., based on limited data.</p>
							
							
			<h4><a name="set3a"></a>TIMBERLINE HABITAT TYPES</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timberline habitats have high water yields and provide summer range for various species of big game and other wildlife. Because of their high esthetic value, they are also of considerable interest to outdoor recreationists. Forb and grass growth may be luxuriant in certain timberline areas, particularly those east of the Continental Divide on better soils, notably those derived from limestone. Grazing pressure in these types must be carefully dispersed and otherwise controlled, however, because loss of vegetative cover makes them vulnerable to severe erosion in many cases. Vegetative recovery following disturbance is very slow. Heavy grazing by sheep has caused long-term range deterioration in several timberline and alpine areas in the Northern Rockies, although timberline meadows in Montana generally appear to be in better shape than those in the other Rocky Mountain States.</p>
			<p>Similarly, the vegetation can support little concentrated use by sightseers or campers. Roads, ski facilities, and other developments are usually damaging to timberline ecosystems unless designed, constructed, and maintained with utmost care. The scenic beauty of these environments is easily degraded also. Vegetative healing of scarred areas may require several decades, and in some cases the degradation may be permanent (Habeck 1972; Willard and Marr 1971; Klock 1973).</p>
			<p>Tree growth and regeneration are extremely slow in these habitat types, which can clearly be considered as &#8220;noncommercial&#8221; forest land (<a href="habitat_types_MT_app.php#e1">appendix E</a>).</p>
			
			<h5><a name="set3a1"></a><span class="ital">Pinus albicaulis-Abies lasiocarpa</span> h.t.s<br /> (PIAL-ABLA; whitebark pine-subalpine fir)</h4>
			<p><strong>Soil</strong>&#8212;Soils in our sample stands were derived primarily from sandstone and argillite parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic to very acidic, gravelly loams to silts. Ground surfaces averaged 13 percent rock and 6 percent bare soil exposed; duff depth averaged only 2.8 cm.</p>
			
			<h5><a name="set3a2"></a><span class="ital">Larix lyallii-Abies lasiocarpa</span> h.t.<br /> (LALY-ABLA; alpine larch-subalpine fir)</h4>
			<p><strong>Soil</strong>&#8212;Soils were derived primarily from granite and quartzite parent materials, but occasionally from noncalcareous shale and argillite (Arno 1970). Surface soils were very gravelly loams usually ranging from 3.9 t o 5.7 in pH. Ground surfaces had large amounts of rock but relatively little mineral soil exposed.</p>
			
			<h5><a name="set3a3"></a><span class="ital">Pinus albicaulis</span> h.t.s<br /> (PIAL; whitebark pine)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly silt loams and silts ranging from slightly basic (on calcareous substrates) to slightly acidic. Ground surfaces had little rock or bare soil exposed; duff depths averaged only 2.7 cm.</p>
																											
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_MT_10.php">On to <span class="ital">Pinus contorta</span> Series and other vegetation types&gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_08.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<strong>9</strong>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
