<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Forest Habitat Types of Montana: Pinus ponderosa Series</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Montana: Pinus ponderosa series" />
		<meta name="keywords" content="forest vegetation, Montana, habitat, types, plant communities, forest ecology, forest management, forests, Pinus ponderosa, ponderosa pine" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF MONTANA</a> &gt; <span class="ital">PINUS PONDEROSA</span> SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Montana</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Pfister, Robert D., Bernard L. Kovalchik, Stephen F. Arno, and Richard C. Presby. 1977. Forest habitat types of Montana. Gen. Tech. Rep. INT-34. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Forest &amp; Range Experiment Station. 174 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_03.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<strong>4</strong>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">PINUS PONDEROSA</span> SERIES</h3>
			<p><strong>Soil</strong>&#8212;Soils are variable throughout this series. The surface horizons are gravelly in all types except the <span class="ital">Berberis repens</span> phase of the PIPO/SYAL h.t. Less surface rock and bare soil are exposed in the shrubby group of habitat types, but this may be attributable to heavier duff accumulation and more undergrowth rather than inherent site characteristics.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from very low to moderate within the series (<a href="habitat_types_MT_app.php#e1">appendix E</a>). The grassy habitat types (including PIPO/PUTR) support open forests with stockability limitations and slow growth rates. The bunchgrass-dominated undergrowth has above-average forage potential for livestock or big-game winter range, depending on location within a particular landscape.</p>
			<p>The shrubby habitat types support closed-canopy forests with a higher productivity potential (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Forage production for domestic livestock is lower under the closed canopies, although browse species may provide good forage for big game.</p>
			<p>Wellner and Ryker (1973) suggest that a full range of silvicultural systems are available for timber harvesting and regeneration in this series. Under any system, natural regeneration will be slow because good seed crops are infrequent and soil moisture is often inadequate for seedling establishment. Mechanical site preparation will aid establishment by reducing competition for moisture.</p>
			<p>Foiles and Curtis (1973), in applying cutting methods to R. and J. Daubenmires' (1968) <span class="ital">Pinus ponderosa</span> habitat types, emphasize clearcutting and mechanical site preparation where dwarf mistletoe is present or where timber production is the primary goal. We advocate caution in clearcutting in this series in Montana for several reasons:</p>
			<ol>
				<li>Dwarf mistletoe is rarely found on <span class="ital">Pinus ponderosa</span> in Montana.</li>
				<li>Many natural stands, especially in the grassy group, are unevenaged.</li>
				<li>Timber production often will not be the primary goal because other multiple-use values are often higher.</li>
			</ol>
			<p>Based on these considerations, we suggest selection or shelterwood systems coupled with a long natural regeneration period as a general guideline for this series. In practice, stand prescriptions should be based on individual stand conditions, local experience, and management objectives. For instance, even-aged stands in the PIPO/SYAL and PIPO/PRVI h.t.s may be suited to seed-tree or clearcut systems.</p>
												
			<h4><a name="set1a"></a><span class="ital">Pinus ponderosa/Andropogon</span> spp. h.t.<br /> (PIPO/AND; ponderosa pine/bluestem)</h4>
			<p><strong>Management</strong>&#8212;Management implications are similar to those for the PIPO/AGSP h.t.</p>
			
			<h4><a name="set1b"></a><span class="ital">Pinus ponderosa/Agropyron spicatum</span> h.t.<br /> (PIPO/AGSP; ponderosa pine/bluebunch wheatgrass)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of sedimentary parent materials, the majority of which were calcareous (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly loams to gravelly silts and ranged from acidic to slightly basic, depending on the parent material. Ground surfaces had moderate bare soil (7 percent) and little rock exposed (3 percent); duff depth averaged less than 4 cm. Most of the soils had an A1 horizon.</p>
			<p><strong>Productivity/Management</strong>&#8212;Although forage production is low, winter use by mule deer was evident on most sites. Occasional evidence of elk use was also observed.</p>
			<p>This habitat type may have moderate potential for livestock forage production where slopes are not too steep.</p>
			
			<h4><a name="set1c"></a><span class="ital">Pinus ponderosa/Festuca idahoensis</span> h.t.<br /> (PIPO/FEID; ponderosa pine/Idaho fescue)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly loams to gravelly silts. Most of the soils were acidic, although a few that developed from calcareous parent materials were slightly basic. Ground surfaces had little bare soil and moderate amounts of exposed rock; duff depth averaged 4 cm. Most of the soils have darkened A1 surface horizons, reflecting the forb and grass influence on soil development.</p>
			<p><strong>Productivity/Management</strong>&#8212;On gentle terrain PIPO/FEID is one of the better forest habitat types for production of forage for domestic stock. Forage production is considerably greater than in the PIPO/AGSP h.t., especially in the <span class="ital">Festuca scabrella</span> phase. Mule deer apparently use these sites as both winter and summer range. Elk winter use appears greater than in the PIPO/AGSP h.t., perhaps due to better cover and forage. Forage allocation between big game and domestic stock should be a major management consideration in many areas of this habitat type.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pinus ponderosa/Purshia tridentata</span> h.t.<br /> (PIPO/PUTR; ponderosa pine/bitterbrush)</h4>
			<p><strong>Soil</strong>&#8212;About half of the sample stands were on calcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly, but not more so than other h.t.s in this series. Reactions were acidic to slightly basic, depending on parent material. Ground surfaces had moderate (averages of 4 and 5 percent) exposed rock. The AGSP phase had considerable bare soil (17 percent) and less than 1 cm of duff, whereas the FEID phase had 6 percent bare soil with duff depth averaging 2.4 cm. All of the soils had darkened A1 surface horizons.</p>
			<p><strong>Productivity/Management</strong>&#8212;Forage production for domestic stock, deer, and elk is substantial. Deer and elk winter use is heavy because of mild temperatures, lack of snow cover, and the presence of <span class="ital">Purshia tridentata</span>, one of the more desirable big-game browse species. <span class="ital">Purshia tridentata</span> is killed by ground fire but apparently reinvades quickly following surface fires (R. and J. Daubenmire 1968).</p>
			<p> Timber productivity is very low, because of slow growth and stockability limitations (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Silvicultural considerations are similar to those described for the PIPO/AGSP h.t.</p>
			
			<h4><a name="set1e"></a><span class="ital">Pinus ponderosa/Symphoricarpos albus</span> h.t.<br /> (PIPO/SYAL; ponderosa pine/snowberry)</h4>
			<p><strong><span class="ital">Symphoricarpos albus</span> (SYAL) phase/Soil</strong>&#8212;This is the most widespread phase. Bunchgrasses are often codominant with <span class="ital">Symphoricarpos</span>; such stands either are seral, or are transitional to the grassy <span class="ital">Pinus ponderosa</span> habitat types.</p>
			<p>Parent materials in this phase were variable with only one stand found on calcareous parent material (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were slightly acidic and gravelly with a full range of textures from loamy sands to silty clay loams. Ground surfaces were rock-free with little bare mineral soil exposed in natural stands; duff depth averaged 4.5 cm. Although most soils had darkened A1 horizons, a few displayed surface A2 or B horizons.</p>
			<p>Soil moisture depletion during the growing season has been documented for this phase in two different studies (Daubenmire 1968a, McMinn 1952). Soil dries to the wilting point in the surface horizons during late June to July. By mid- to late August the wilting point depth reaches at least 20 inches.</p>
			<p><strong><span class="ital">Berberis repens</span> (BERE) phase/Soil</strong>&#8212;This minor phase was found only in central Montana in the vicinity of Lewistown and Roundup where it occupies gentle slopes and benches more moist than those occupied by the SYAL phase. <span class="ital">Berberis repens</span> is common in the luxuriant undergrowth, and bunchgrasses are poorly represented. <span class="ital">Juniperus communis</span> and <span class="ital">Spiraea betulifolia</span> are common in the shrub layer. <span class="ital">Schizachne purpurascens</span> is often present, indicating some similarity to the PIPO/PRVI h.t.</p>
			<p>Parent materials in this phase were exclusively limestone (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Soils were virtually gravel-free in the surface 20 cm and ranged from slightly acidic to slightly basic. Textures ranged from silt loam to silty clay loam. Ground surfaces were rock-free and no bare soil was exposed in natural stands. Average duff accumulation was greater than 5 cm. All soils had well-developed A1 surface horizons.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low, although it is one of the more productive habitat types in the <span class="ital">Pinus ponderosa</span> series (<a href="habitat_types_MT_app.php#e1">appendix E</a>). In western Montana, site index for <span class="ital">Pinus ponderosa</span> is similar to that for the grassy habitat types, but basal areas in PIPO/SYAL are substantially greater, indicating higher stockability and volume potentials. Eastward, both site indexes and basal areas are generally higher than for the grassy habitat types in this series. PIPO/SYAL stands should regenerate faster than the grassy habitat types, if site preparation is adequate. However, clearcuts may be difficult to regenerate due to droughtiness and competition from seral bunchgrasses.</p>
			<p>Forage production is somewhat variable. Bunchgrasses are well represented in the <span class="ital">Symphoricarpos albus</span> phase, indicating a good potential for domestic livestock. This potential declines in later successional stages. Both phases have a fair complement of palatable big-game browse species.</p>
			
			<h4><a name="set1f"></a><span class="ital">Pinus ponderosa/Prunus virginiana</span> h.t.<br /> (PIPO/PRVI; ponderosa pine/chokecherry)</h4>
			<p><strong>Soil</strong>&#8212;This habitat type was found only on noncalcareous sandstone, siltstone, and shale parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic to slightly acidic gravelly silt loams with well-developed A1 horizons. Ground surfaces were virtually rock-free and no mineral soil was exposed in natural stands. Duff depths averaged 5.8 cm in the PRVI phase and 3.5 cm in the <span class="ital">Shepherdia canadensis</span> (SHCA) phase.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Average site index and maximum stand heights are higher than other eastside <span class="ital">Pinus ponderosa</span> habitat types.</p>
			<p>A rich assortment of palatable shrubs and forbs makes this a preferred wildlife habitat type. Mule deer browse heavily on <span class="ital">Prunus virginiana</span>, <span class="ital">Amelanchier alnifolia</span>, and other shrubs, often severely restricting development of the shrubs.</p>
			<p>Cattle make little use of this habitat type, preferring adjacent open forests with bunchgrass undergrowth.</p>
															
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_MT_05.php">On to <span class="ital">Pseudotsuga menziesii</span> Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_03.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<strong>4</strong>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_05.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
