<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Forest Habitat Types of Montana: Pseudotsuga menziesii Series</title>
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Montana: Pseudotsuga menziesii series" />
		<meta name="keywords" content="forest vegetation, Montana, habitat, types, plant communities, forest ecology, forest management, forests, Pseudotsuga menziesii, ponderosa pine" />
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF MONTANA</a> &gt; <span class="ital">PSEUDOTSUGA MENZIESII</span> SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Montana</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Pfister, Robert D., Bernard L. Kovalchik, Stephen F. Arno, and Richard C. Presby. 1977. Forest habitat types of Montana. Gen. Tech. Rep. INT-34. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Forest &amp; Range Experiment Station. 174 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_04.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<strong>5</strong>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">PSEUDOTSUGA MENZIESII</span> SERIES</h3>
			<p><strong>Soil</strong>&#8212;Soils are variable throughout the series. In general, habitat types were not strongly related to specific parent materials, although many were found only on noncalcareous substrates. Surface soils are consistently gravelly and acidic, except on calcareous substrates. Surface rock and bare soil are conspicuous in the <span class="ital">Pseudotsuga</span>/bunchgrass h.t.s and average duff depth is less than 3 cm. Average duff depth in the other <span class="ital">Pseudotsuga</span> habitat types is from 3 to 6 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges primarily from low to moderate in this series (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Production of forage for domestic stock and big game varies considerably between habitat types. Lower elevations and southerly exposures are often important for deer and elk winter range.</p>
												
			<h4><a name="set1a"></a><span class="ital">Pseudotsuga menziesii/Agropyron spicatum</span> h.t.<br /> (PSME/AGSP; Douglas-fir/bluebunch wheatgrass)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of calcareous and noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly (42 percent), acidic to slightly basic (on limestone), and ranged in texture from loamy sand to silt. Ground surfaces averaged 11 percent rock, 13 percent bare soil, and only 2.5 cm duff depth. All of the soils had an A1 surface horizon.</p>
			<p><strong>Productivity/Management</strong>&#8212;Forage production for livestock is moderate, but steep slopes limit grazing. Mule deer and elk use was quite evident, apparently as part of their winter range. Browse production is low, but warm exposures encourage frequent use.</p>
			<p>Timber productivity is low to very low, as indicated by both low site indexes and stockability limitations (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Clearcutting in this type will generally result in conversion to grassland with very slow reinvasion of trees. Light selection or sanitation-salvage cutting will permit timber harvest and protect the site. Natural regeneration may take 20 to 40 years, but this should be acceptable under a selection system of management. Intensive cultural work is difficult to justify with such low productivity potential.</p>
			
			<h4><a name="set1b"></a><span class="ital">Pseudotsuga menziesii/Festuca idahoensis</span> h.t.<br /> (PSME/FEID; Douglas-fir/Idaho fescue)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of calcareous and noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic, averaged 31 percent gravel content, and ranged in texture from sandy loam to silt. Ground surfaces averaged 9 percent rock, 9 percent bare soil, and 2.4 cm duff depth. Almost all of the soils had an A1 horizon.</p>
			<p><strong>Productivity/Management</strong>&#8212;Forage potential for livestock is moderate in cleared or open stands. Slopes are often gentle enough to allow domestic livestock grazing. Mule deer and elk use was quite evident, apparently for winter cover and forage.</p>
			<p>Timber productivity is low, as reflected by low site-index values and apparent stockability limitations (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Dense stands on north or east aspects often become stagnated. <span class="ital">Pseudotsuga</span> is the only commercial tree species in this habitat type. Timber management considerations are similar to those described for the PSME/AGSP h.t., except that small clearcuts may be appropriate for stagnated stands on north slopes.</p>
			
			<h4><a name="set1c"></a><span class="ital">Pseudotsuga menziesii/Festuca scabrella</span> h.t.<br /> (PSME/FESC; Douglas-fir/rough fescue)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of calcareous and noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic, averaged 37 percent gravel content and ranged in texture from loam to silt. Ground surfaces averaged 5 percent rock, 7 percent bare soil, and 2.5 cm duff depth. Many of the soils had an A1 horizon.</p>
			<p><strong>Productivity/Management</strong>&#8212;On gentle terrain, the PSME/FESC h.t. is one of the better forest habitat types for production of forage for domestic stock. Canopy coverage of bunchgrasses is much greater than for other <span class="ital">Pseudotsuga</span> habitat types. Mule deer and elk use was quite evident, apparently as winter range.</p>
			<p>Timber productivity is low to very low, due to both low site index values and stockability limitations (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Timber management considerations are similar to those described for the PSME/AGSP h.t.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Vaccinium caespitosum</span> h.t.<br /> (PSME/VACA; Douglas-fir/dwarf huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic, gravelly (26 percent) sandy loams to loams. Very little rock and bare soil were exposed; duff depth averaged 4.3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;West of the Continental Divide this habitat type affords good growth for a mixture of commercially valuable tree species; growth of <span class="ital">Pinus ponderosa</span> is excellent. Productivity ranges from moderate to high in western Montana (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Eastward, the habitat type is less productive, <span class="ital">Pinus contorta</span> is the dominant seral species, and <span class="ital">Pinus ponderosa</span> and <span class="ital">Larix occidentalis</span> are absent.</p>
			<p>Either even-aged management or selective removal of <span class="ital">Pseudotsuga</span> will favor perpetuation of seral tree species in this habitat type. Overstory removal will lead to increasing dominance by <span class="ital">Pseudotsuga</span>. The sod formed by <span class="ital">Calamagrostis rubescens</span> and its associates may need breaking for successful regeneration of conifers. Wide latitude can be taken in managing these productive and accessible sites.</p>
			<p>Domestic stock use was observed only locally. The forage potential for livestock is low in natural stands. However, deer, elk, and occasionally moose use them heavily in winter, if snow depths are not too great.</p>
			<p>This habitat type is frequently used for recreation sites, including campgrounds and summer home developments.</p>
			
			<h4><a name="set1e"></a><span class="ital">Pseudotsuga menziesii/Physocarpus malvaceus</span> h.t.<br /> (PSME/PHMA; Douglas-fir/ninebark)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of noncalcareous parent materials west of the Continental Divide; near and east of the Continental Divide stands were also found on limestone (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic (slightly basic on limestone), gravelly (average 42 percent), and ranged in texture from sandy loam to silt. Little exposed rock was evident in the PHMA phase with about 5 percent in the CARU phase. No bare soil was exposed in either phase and duff depth averaged about 4 cm in both.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high in western Montana, but only low to moderate eastward (<a href="habitat_types_MT_app.php#e1">appendix E</a>). The highest productivities are found in western Montana in the PHMA phase. East of the Continental Divide, silvicultural prescriptions consider only <span class="ital">Pseudotsuga</span> since <span class="ital">Pinus ponderosa</span> and <span class="ital">P. contorta</span> are rarely present. West of the Divide, <span class="ital">P. ponderosa</span>, <span class="ital">P. contorta</span>, and <span class="ital">Larix occidentalis</span> may be perpetuated where they occur naturally through even-aged management. Partial cutting favors <span class="ital">Pseudotsuga</span>, but timber production may be severely reduced in dwarf-mistletoe (<span class="ital">Arceuthobium</span>) infected stands.</p>
			<p>Livestock usually graze only small areas of gentle topography in this type. Heavy grazing can establish a <span class="ital">Poa</span> disclimax similar to that described by R. and J. Daubenmire (1968).</p>
			<p>Big game use of PSME/PHMA h.t. is variable, ranging from transitory or bedding activity to heavy winter use by elk and deer. Intensity of use may depend on snowpack depth, successional stage, and the availability of favored browse species. The <span class="ital">Calamagrostis rubescens</span> phase, which occurs on warmer slopes, may have the greatest importance as winter range.</p>
			
			<h4><a name="set1f"></a><span class="ital">Pseudotsuga menziesii/Vaccinium globulare</span> h.t.<br /> (PSME/VAGL; Douglas-fir/blue huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were very gravelly sandy loams to silts in the XETE phase; gravelly silty clay loams in the ARUV phase, and gravelly loams to silts in the VAGL phase. Soils were acidic in all phases. Ground surfaces had little rock or bare soil exposed; duff depths averaged about 3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Silvicultural prescriptions and choice of species will vary depending on the phase. This habitat type receives little use by domestic stock. Deer and elk use is light to moderate.</p>
			<p>This is an important habitat type for production of <span class="ital">Vaccinium globulare</span>, whose berries are utilized by bears, grouse, other wildlife, and humans, and whose shoots are browsed by big game. Miller (1977) studied the response of <span class="ital">Vaccinium globulare</span> to prescribed fires in spring and fall on a site in the <span class="ital">Arctostaphylos</span> phase in west-central Montana. Her findings should be useful for predicting response of <span class="ital">Vaccinium globulare</span> to management activities.</p>
			<p>This PSME/VAGL h.t. includes a combination of stands formerly classified as <span class="ital">Pseudotsuga/Vaccinium globulare</span> h.t. and <span class="ital">Pseudotsuga/Xerophyllum tenax</span> h.t. (<a href="habitat_types_MT_fig57.php">fig. 57, page 137</a>) in our preliminary classifications. In final analysis it seemed most realistic to treat these situations as three phases of one habitat type.</p>

			<h4><a name="set1g"></a><span class="ital">Pseudotsuga menziesii/Linnaea borealis</span> h.t.<br /> (PSME/LIBO; Douglas-fir/twinflower)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of primarily noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic, gravelly sandy loams to silty clay loams. Little rock or bare soil were exposed. Duff depths averaged 4.6 cm in the SYAL phase, 6.1 cm in the CARU phase, and 3.5 cm in the VAGL phase.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate in western Montana, and low to moderate eastward (<a href="habitat_types_MT_app.php#e1">appendix E</a>). The highest productivities were in the CARU phase. The prevalence of <span class="ital">Calamagrostis rubescens</span> in all phases should be considered in site preparation plans. However, competition for moisture should be less severe than in the PSME/CARU and PSME/SYAL h.t.s. Light to moderate use by deer and often by elk was evident in most sample stands.</p>
															
			<h4><a name="set1h"></a><span class="ital">Pseudotsuga menziesii/Symphoricarpos albus</span> h.t.<br /> (PSME/SYAL; Douglas-fir/snowberry)</h4>
			<p><strong>Soil</strong>&#8212;The PSME/SYAL h.t. was sampled on a variety of calcareous and noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly (33 percent) sandy loams to silts with acidic reactions (slightly basic on some of the calcareous parent materials). Little surface rock was evident in the CARU and SYAL phases, although an average of 7 percent was noted in the AGSP phase. Only small amounts of bare soil were exposed; duff depth averages 2.6 cm in the AGSP phase, 3.6 cm in the CARU phase, and 4.1 cm in the SYAL phase.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity of this type ranges from low to high in western Montana and from low to moderate eastward (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Basal area stocking is good in the CARU and SYAL phases, but the AGSP phase may have stockability limitations and also has the lowest site index values. Regeneration may be difficult in the droughty AGSP phase. The prevalence of rhizomatous graminoids in the CARU phase should be considered in site preparation plans.</p>
			<p>Moderate use by deer and occasionally by elk and moose was evident in most stands in the CARU and SYAL phases.</p>
															
			<h4><a name="set1i"></a><span class="ital">Pseudotsuga menziesii/Calamagrostis rubescens</span> h.t.<br /> (PSME/CARU; Douglas-fir/pinegrass)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of primarily noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic, ranging in texture from gravelly sandy loams to gravelly silts. Surface rock exposure averaged 5 to 6 percent in the AGSP and ARUV phases and 2 to 3 percent in the CARU and PIP0 phases. Bare soil exposure was minimal and duff depth averaged about 4 cm in all phases.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate in the PSME/CARU h.t. (<a href="habitat_types_MT_app.php#e1">appendix E</a>). The ARUV phase averaged highest in productivity; the CARU phase was lowest. Clearcutting and shelterwood systems will favor seral species, while partial cutting will lead to eventual dominance by <span class="ital">Pseudotsuga</span> in most cases. Extensive scarification may be needed to reduce grass competition for successful regeneration.</p>
			<p>Although forage production is low, cattle and horse use is evident on many gentle slopes. Moderate winter use by deer and elk is apparent in the AGSP and ARUV phases. The PIP0 and CARU phases show light to moderate use, evidently in spring and fall.</p>
															
			<h4><a name="set1j"></a><span class="ital">Pseudotsuga menziesii/Carex geyeri</span> h.t.<br /> (PSME/CAGE; Douglas-fir/elk sedge)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on calcareous and noncalcareous parent materials of sedimentary and metamorphic origin (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic to slightly basic, gravelly (42 percent) sandy loams to silts. Little surface rock or bare soil were exposed; duff depth averaged 4.7 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Management implications are similar to those for the PSME/CARU h.t., CARU phase, although timber productivity is somewhat less (<a href="habitat_types_MT_app.php#e4">appendix E-4</a>). Regeneration may also be more difficult on these drier sites and overstory species manipulations are essentially restricted to <span class="ital">Pseudotsuga</span>. Evidence from sample plots suggests that this habitat type receives moderate use by mule deer.</p>
															
			<h4><a name="set1k"></a><span class="ital">Pseudotsuga menziesii/Spiraea betulifolia</span> h.t.<br /> (PSME/SPBE; Douglas-fir/white spiraea)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on calcareous and noncalcareous sedimentary and metamorphic parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic to slightly basic gravelly (40 percent) sandy loams to silts. A moderate amount of surface rock (5 percent) was evident, but little bare soil was exposed. Duff depth averaged 2.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity of the PSME/SPBE h.t. is moderate in western Montana but low eastward (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Most sample stands had evidence of moderate use by mule deer.</p>
															
			<h4><a name="set1l"></a><span class="ital">Pseudotsuga menziesii/Arctostaphylos uva-ursi</span> h.t.<br /> (PSME/ARUV; Douglas-fir/kinnikinnick)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on calcareous and noncalcareous sedimentary and metamorphic parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic to slightly basic gravelly (36 percent) loams to silt loams. Little rock and moderate (5 percent) bare soil were exposed; average duff depth was 6.0 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low (<a href="habitat_types_MT_app.php#e1">appendix E</a>). High soil-surface temperatures coupled with low soil moisture may hamper regeneration of logged stands. Stands might be managed for <span class="ital">Pinus ponderosa</span> using partial cuttings. <span class="ital">Pseudotsuga</span> appears to be a poor choice for timber-production on these sites based on site index comparison (<a href="habitat_types_MT_app.php#e1">appendix E-1</a>).</p>
			<p>Sites are relatively warm and free of snow through much of the winter, and several important big-game forage species are found in this habitat type. Sample stands showed evidence of moderate to heavy use by mule deer.</p>
															
			<h4><a name="set1m"></a><span class="ital">Pseudotsuga menziesii/Juniperus communis</span> h.t.<br /> (PSME/JUCO; Douglas-fir/common juniper)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of sedimentary and igneous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were acidic to slighltly basic, gravelly (27 percent), sandy loams to silts. Little surface rock or bare soil were exposed; duff depth averaged 4.2 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to moderate (<a href="habitat_types_MT_app.php#e1">appendix E</a>). Overstories are strongly even-aged; however, sites appear droughty and regeneration might be difficult to obtain following clearcutting. <span class="ital">Pinus contorta</span> should be the major species for timber management on granitic substrates, while <span class="ital">Pseudotsuga</span> should be the primary species on calcareous substrates. PSME/JUCO sample stands had been used heavily by mule deer and occasionally by elk. <span class="ital">Juniperus communis</span> and <span class="ital">J. horizontalis</span> may be important browse species.</p>
															
			<h4><a name="set1n"></a><span class="ital">Pseudotsuga menziesii/Arnica cordifolia</span> h.t.<br /> (PSME/ARCO; Douglas-fir/heartleaf arnica)</h4>
			<p><strong>Soil</strong>&#8212;Our stands were on a variety of primarily noncalcareous parent materials (<a href="habitat_types_MT_app.php#d1">appendix D-1</a>). Surface soils were gravelly (30 percent) sandy loams to silts with reactions ranging from acidic to slightly basic (on limestone). A moderate amount of surface rock (4 percent) was exposed with no bare soil evident; duff depth averaged 4.3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low (<a href="habitat_types_MT_app.php#e1">appendix E</a>). The PSME/ARCO h.t. frequently occurs adjacent to montane grasslands, suggesting that severe cutting or burning might result in converting the stand to prairie for a long period. Group selection cutting would probably duplicate the natural regeneration patterns observed in sample stands.</p>
			<p>Young seral stands should provide considerable forage for cattle and big game. Mature stands have a poor representation of forage species but are often used for bedding and cover by both mule deer and domestic stock.</p>
															
			<h4><a name="set1o"></a><span class="ital">Pseudotsuga menziesii/Symphoricarpos oreophilus</span> h.t.<br /> (PSME/SYOR; Douglas-fir/mountain snowberry)</h4>
			<p><strong>Soil</strong>&#8212;Soils observed were shallow, coarse-textured, rocky, and excessively well drained. Parent material was not calcareous.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity and management implications are probably similar to those expressed for PSME/AGSP h.t. as it occurs in southwestern Montana where <span class="ital">Pinus ponderosa</span> is absent.</p>
															
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_MT_06.php">On to <span class="ital">Picea</span> Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_MT_04.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_MT_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_MT_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_MT_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_MT_04.php">4</a>&nbsp;&nbsp;<strong>5</strong>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_MT_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_MT_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_MT_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_MT_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_MT_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_MT_12.php">12</a>&nbsp;&nbsp;<a href="habitat_types_MT_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_MT_06.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
