<?phphttps:https:https:https:https:
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Grazing Influences on Selected Soil Attributes in a Sierra Nevada Riparian Meadow</title>
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Impacts of Trampling Soils in Southeast Utah Ecosystems - Jayne Belnap, 1997" />
		<meta name="keywords" content="soil quality impact impacts trampling soils southeast utah ecosystems ecosystem Jayne Belnap" />
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
<!-- BEGIN PUBLICATION -->
	<div id="pub">
		<div id="psubnav"><p><a href="../../index.php">SOLO HOME</a> &gt; <a href="../research_pubs.php">RESEARCH PUBLICATIONS</a></p>
		</div>
	<h1>Grazing Influences on Selected Soil Attributes in a Sierra Nevada Riparian Meadow</h1>
	<p class="authors">Robert R. Blank<sup>1</sup><br />
	    	Tony Svejcar<sup>2</sup></p>
	<p class="notes"><sup>1</sup>USDA Agricultural Research Service, Exotic and Invasive Weed Research Unit, 920 Valley Road, Reno, NV, 89512; e-mail: blank@scs.unr.edu</p>
	<p class="notes"><sup>2</sup>USDA Agricultural Research Service, Eastern Oregon Agricultural Research Center, HC 71, 4.5, Hwy 205, Burns, OR 97720</p>

	<h2>ABSTRACT</h2>
	<p>We studied the effects of livestock grazing on soil attributes in a riparian meadow of the northern Sierra Nevada. Treatments were livestock exclusion and grazing. Tension lysimeters were placed in the treatments by position (stream edge, midfloodplain, and forest edge), and by soil horizon (A, 2C, and Cg). Lysimeter water was collected twice monthly in April, May, and June during 1990&#8211;93, and anions and cations were quantified. In addition, KCl-extractable nitrate and ammonium, bicarbonate-extractable ortho-P, and root length density were quantified on soil samples in the treatments by position and depth in July 1991 and Sept. 1993. Treatment significantly interacted with landscape position for ammonium (A horizon lysimeters), for sulfate, potassium, calcium, and sodium (2C horizon lysimeters), and for magnesium and calcium (Cg horizon lysimeters). The grazed forest edge position had significantly greater bicarbonate-extractable ortho-P than the excluded treatment in July of 1991. Potassium-chloride extractable nitrate was significantly greater in the grazed treatment at 0&#8211;25 cm, than in the corresponding excluded treatment in Sept. of 1993. Treatment effects were largely constrained to the forest edge position. Root length density was not affected by grazing. Grazing-induced changes in soil attributes may be linked to landscape redistribution of plant material and elements from salt blocks via livestock feces and urine.</p>
	<dl class="glossary">
		<dt>KEY TERMS: </dt>
		<dd>ammonium, calcium, potassium, sulfate, potassium, root length density</dd>
	</dl>
	<h2>INTRODUCTION</h2>
	<p>Although relatively small in areal extent, riparian areas in the western United States constitute a large proportion of an ecosystem's biotic diversity, water storage, and primary productivity (Warner and Hendrix, 1984). The impact of grazing livestock on riparian ecosysrems has caused considerable concern. Research addressing these concerns has been multifaceted but is centered on grazing-induced vegetational changes, decline in soil health, loss of biotic diversity, loss of fisheries habitat, reduced stream water quality, and changes in stream hydrology (Kauffman and Krueger, 1984).</p>
	<p>We are unaware of any studies that have examined the influence of livestock grazing on the chemistry of the soil-solution. Moreover, few studies have addressed the influence of livestock grazing on areal distribution of soil chemical properties in such spatially diverse habitats as riparian areas. We believe such a study is warranted given the linkage of changes known to occur in soil physical properties and vegetational characteristics as a consequence of livestock grazing with processes such as nutrient mineralization rates, soil redox status, and the kinetics of denitrification. Our purpose was to measure the influence of grazing in a montane meadow on selected soil attributes, emphasizing the chemistry of the soil-solution, and taking into account floodplain position, year, month, and soil depth.</p>
	<h2>MATERIALS AND METHODS</h2>
	<h3>Site Characteristics</h3>
	<p>The study area is along the upper reach of Big Grizzly Creek (120&#176; 37 W 39&#176; 59 N). Big Grizzly Creek is about 1 m in width and the associated montane meadow ranges from about 150 to 500 m in width. The surrounding uplands are forested by lodgepole pine (<em class="ital">Pinus contorta</em> ssp. <em class="ital">murrayana</em> [Grev. & Balf.] Critchf.), white fir (<em class="ital">Abies concolor</em> [Gordon & Glend.] Lindley), and Jeffrey pine (<em class="ital">Pinus jeffreyi</em> Grev. & Balf.). Meadow vegetation consists of Kentucky bluegrass (<em class="ital">Poa pratensis</em> L.), baltic rush (<em class="ital">Juncus balticus</em> wild.), Nebraska sedge (<em class="ital">Carex nebrascensis</em> Dewey) and tufted-hairgrass (<em class="ital">Deschampsia caespitosa</em> [L.] Beauv.). Nebraska sedge dominates very poorly drained areas along the stream, other graminoids increase in poorly drained mid-floodplain positions, and forbs increase in the better drained floodplain-upland interface. Site elevation is 1,800 m. Long-term average precipitation is 89 cm per year (s.d. = 34). During the study period of 1990&#8211;1993, precipitation was considerably less than average 3 of the 4 years. The soil temperature regime is frigid based on thermistor data collected in 1993&#8211;1994. The high organic soils are silt loam to silty clay in texture and classified as Typic Humaquepts (Blank et al., 1995).</p>
	<h3>Treatments</h3>
	<p>Prior to our experiment, the grazing system was season long (June, July, and August) with up to 80 percent forage utilization. Treatments (2 replicates) were livestock exclusion (25 by 100 m) and moderate grazing (42.5 by 100 m). Moderately grazed treatments were designed to leave about 1,000 kg/ha of vegetation which was accomplished by short-term (7 to 14 d) of high stocking density (Huber et al., 1995). All paddocks included portions of Big Grizzly Creek. Depending on the particular year's vegetation phenology, the grazing treatments were applied from mid-June to August. Treatments were initiated in 1989.</p>
	<h3>Lysimeter Installation and Sampling</h3>
	<p>Lysimeters were constructed using 7.6 cm diameter, 0.63 cm thick porous ceramic plates with 10 &#181;m pore diameter. Duplicate lysimeters were placed in excluded and grazed paddocks at three landscape positions: forest edge, mid-floodplain, and stream edge. The stream edge lysimeters were placed approximately 1 m from the stream channel on a small bench. The mid-floodplain lysimeters were placed about 20 m north of the stream channel. The forest edge lysimeters were placed about 40 m north of the stream channel and about 10 m south of the forest boundary. Lysimeters were placed: (1) 10 cm below the soil surface in the A horizon, (2) within a 2C, tephra-rich horizon, which lays directly atop a paleosol 3Btgb or 2Btb argillic horizon at approximately 60 cm (forest edge and mid-floodplain positions only), and (3) in the gleyed Cg horizon zone (approximately 120 cm deep in forest edge and mid-floodplain position, but only 60 cm deep in the stream edge position). Lysimeters were installed in August 1989. Lysimeter water was extracted using a hand vacuum pump, with the first few mL discarded. Lysimeters were sampled when conditions allowed in 1990, 1991, 1992, and 1993. In most years, the soil was too dry to sample beyond June. For this reason we will report on lysimeter chemistry for the months of April, May, and June, the months when most plant growth occurred during the study period.</p>
	<h3>Other Measured Attributes</h3>
	<p>In July 1991, soils were sampled with a bucket auger (two replicates) by landscape position, depth, and treatment. Landscape positions were stream edge (5 m farther from the stream than where the lysimeters were placed), mid-floodplain, and forest edge. Depths were 0&#8211;20, 20&#8211;40, and 40&#8211;60 cm. Soil samples were again collected in September 1993 near the previous landscape positions, by depth (0&#8211;25 and 25&#8211;50 cm), and by treatment (grazed and excluded). Samples were air-dried in a glasshouse and lightly crushed to pass a 2-mm sieve, homogenized, and stored in paper cartons until analyzed. For root length density, uniform volume samples (three replicates) were taken from excluded and grazed paddocks by position and depth as above. Roots were separated from the soil using a commercial root washer (Gillison's Fabrication, Benzonina, MI) and the total root length was measured with a commercial root length scanner (Hawker de Havilland Victoria Limited, Melbourne, Australia) with corrections made for dead roots.</p>
	<h3>Laboratory</h3>
	<p>Lysimeter samples were taken to the laboratory and kept refrigerated between analyses; all analyses were completed in less than 3 days. Anions and cations were quantified by ion chromatography (Dionex Corp., 1986, 1988) and ortho-P by molybdenum blue chemistry (EPA, 1979). For soil analyses we used: (1) bicarbonate extraction for ortho-P with molybdenum blue chemistry (Olsen and Sommers, 1982) and (2) 0.5 M KCl extraction (Keeney and Nelson, 1982) for nitrate (ion chromatography quantification) and ammonium (membrane diffusion colorimetric procedure).</p>
	<h3>Statistical Analyses</h3>
	<p>A variety of unbalanced factors for the lysimeter part of the experiment necessitated performing multiple analyses. For the middle lysimeters, a four-way repeated measures ANOVA design was used with the following factors: treatment (grazed and excluded), position (mid-floodplain, and forest edge), year (1990, 1991, 1992, 1993), and month (April, May and June) with repeated measure on year and month. Further analyses of different nutrient concentrations for the shallow and deep lysimeters and combining all years, for the factors of treatment (grazed and ungrazed), landscape position (stream edge, mid-floodplain, and forest edge), and month (April, May, and June) were conducted using a three-way repeated measure analysis of variance design with repeated measures on month. Duncan's New Multiple Range Test was used as the multiple comparison test for either an interaction or main effect when significant (P &le; 0.05) ANOVA F-test results were obtained. For the soil attributes measured separately, a three-way completely randomized ANOVA (treatment, position, and depth) was used. For a significant F-test, Fisher&#39;s protected LSD was used to separate means. Figures were prepared using only the highest order significant interactions which included treatment.</p>
	<h2>RESULTS</h2>
	<h3>Lysimeter Data</h3>
	<p>Of all the solutes quantified, ammonium was the only solute with a significant (P &#8804; 0.05) treatment effect for lysimeters placed in A horizons. Concentration of ammonium from excluded forest edge lysimeters was significantly greater than that extracted from the grazed forest edge lysimeters (<a href="#fig1">Fig. 1</a>, A). Sulfate, potassium, calcium, and sodium, extracted from lysimeters placed within 2C horizons (forest edge and mid-floodplain positions), all had significant treatment &#215; landscape position interactions (<a href="#fig1">Figure 1</a>, B&#8211;E). Grazed mid-floodplain sites had significantly greater sulfate than corresponding livestock excluded values. For the forest edge lysimeter sites, the excluded treatment had significantly more potassium and significantly less calcium and sodium than corresponding values for the grazed treatment. For lysimeters placed in Cg horizons, there was a significant treatment &#215; position interaction for magnesium and calcium (<a href="#fig1">Figure 1</a>, F and G). At the forest edge position, the grazed treatment had significantly more magnesium and calcium than the excluded treatment.</p>
	<h3>Lysimeter Data</h3>
	<p>Of all the solutes quantified, ammonium was the only solute with a significant (P &#8804; 0.05) treatment effect for lysimeters placed in A horizons. Concentration of ammonium from excluded forest edge lysimeters was significantly greater than that extracted from the grazed forest edge lysimeters (<a href="#fig1">Fig. 1</a>, A). Sulfate, potassium, calcium, and sodium, extracted from lysimeters placed within 2C horizons (forest edge and mid-floodplain positions), all had significant treatment &#215; landscape position interactions (<a href="#fig1">Figure 1</a>, B&#8211;E). Grazed mid-floodplain sites had significantly greater sulfate than corresponding livestock excluded values. For the forest edge lysimeter sites, the excluded treatment had significantly more potassium and significantly less calcium and sodium than corresponding values for the grazed treatment. For lysimeters placed in Cg horizons, there was a significant treatment &#215; position interaction for magnesium and calcium (<a href="#fig1">Figure 1</a>, F and G). At the forest edge position, the grazed treatment had significantly more magnesium and calcium than the excluded treatment.</p>

	<p class="figure">
		<em class="bld"><a name="fig1"></a>Figure 1</em>&#8212;<strong>Measured Attributes That Showed Statistically Significant (p &#8804; 0.05) Treatment (Grazed, Ungrazed) Differences.</strong> All units are mg kg<sup>&#8722;1</sup>. Lysimeter data (panels A&#8211;G) are pooled over year and month. Panel H is pooled over depth and panel I is pooled over location. Error bars are &#177; one standard error. <a href="graphics/blank2000_fig1_lg.gif">[view larger image - 88K]</a> <a href="graphics/blank2000_fig1_txt.html">[Text description of this figure]</a>
		<br />
		<br />
		 <a href="graphics/blank2000_fig1_lg.gif"><img src="graphics/blank2000_fig1.gif" alt="Nine bar graphs comparing differences in  amounts of various soil nutrients for the different treatments." width="500" height="682" border="0" /></a>
	</p>

	<h3>Other Soil Attributes</h3>
	<p>In July of 1991, for the forest edge position, the grazed treatment had significantly greater bicarbonate-extractable ortho-P than the excluded treatment (<a href="#fig1">Figure 1</a>, H). In addition, KC1-extractable nitrate and ammonium were very low, averaging 2.0 mg kg<sup>&#8722;1</sup> for nitrate and 4.0 mg kg<sup>&#8722;1</sup> for ammonium with no significant treatment differences. In Sept. of 1993, there were no treatment effects for bicarbonate-extractable ortho-P; however, KCl-extractable nitrate was significantly greater in the grazed treatment at 0&#8211;25 cm, compared to the excluded treatment (<a href="#fig1">Figure 1</a>, I).</p>
	<h2>DISCUSSION</h2>
	<p>There were significant differences in the soil-solution chemistry between the livestock exclusion and livestock grazed treatments. In most cases, treatment-induced changes significantly interacted with landscape position. Most treatment differences occurred in the forest edge position; there were no significant treatment influences in the stream edge position. Given that the entire study area was grazed before the experiment began, it is impossible to deduce if the treatment influences are dominantly a result of continued grazing in the grazed paddocks or from reduced grazing in the excluded paddocks. If continued livestock grazing is responsible for the differences, four aspects should be considered: (1) landscape redistribution of elements via livestock urine and feces, (2) elevated metal contents in urine and feces due to uptake from salt blocks (3) enhanced plant nutrient uptake in response to continual growth following livestock grazing, and (4) alteration of the soil microbial community encouraged by cattle due to cattle feces and urine.</p>
	<p>The research of Huber et al. (1995), contemporaneous with our study in 1992 and 1993, indicates that the majority of livestock grazing time was spent in mid-meadow and stream edge positions because of higher forage production and a greater proportion of highly palatable Carex nebrascensis. However, the forest edge position, especially in 1993, received a greater proportion of loafing use (Huber et al., 1995). Although fecal or urine output was not quantified by landscape position, the higher loafing time spent in the forest edge position suggests that there may be a transfer of chemical elements from stream edge and mid-floodplain positions to the forest edge. Redistribution of plant nutrients to the forest edge position via grazing may partially explain elevated calcium and sodium in the middle lysimeters and higher magnesium and calcium in the deep lysimeters. Higher content of bicarbonate extractable ortho-P in the grazed forest edge positions in 1991 may be similarly explained. Cattle had access in the paddocks to trace mineral salts placed along the forest edge with composition by weight (%) of the following: NaCl 97&#8211;99; Zn 0.85; Mn 0.22; Fe 0.21; Mg 0.10; Cu 0.30; 10.01; Co 0.006 (Huber et al., 1995). The high content of sodium in the salt blocks may be responsible for higher content of sodium in the middle lysimeters of the grazed forest edge position. Removal of vegetation by grazing livestock can, under particular circumstances, stimulate vegetative growth greater than that of ungrazed controls (McNaughton, 1983). If this overcompensation is applicable to our montane meadow, one would expect that elevated plant uptake of particular mineral elements in the livestock grazed treatments would lower the lysimeter content of these elements. Hearne and Howard-Williams (1988) showed that a high grazing intensity for a short period could stimulate uptake of nitrate by riparian vegetation. The far lower ammonium and potassium content in the forest edge grazed lysimeter water as compared to the excluded treatment is potential evidence for this effect. Activity of nitrogen and sulfur cleaving soil enzymes can increase due to enhanced microbial production caused by cattle feces and urine (Haynes and Williams, 1999). Greater sulfate content in the middle lysimeters of the grazed mid-floodplain position and greater KCl-extractable nitrate in the 0&#8211;25 cm of the grazed treatment may be partially explained in this manner.</p>
	<p>One must also consider that the exclusion of grazing, on the once completely grazed meadow, may be the controlling factor in the treatment differences found. A major mechanism of change once livestock are excluded is the accumulation of plant litter (Popolizio et al., 1994). Increased amounts of vegetation and litter forestall rising soil temperatures, thereby, delaying plant phenology and lowering early season mineralization rates (Sharrow and Wright, 1977; Kaufhan et al., 1983). This grazing exclusion factor may better explain treatment differences found for lysimeter values of sulfate and ammonium and KC1-extractable nitrate then the previous mechanisms explored.</p>
	<p>The observed treatment differences may occur via mechanisms which are highly complex and little studied in riparian ecosystems. Soil meso- and macro-faunal activity greatly influence the rate of litter decomposition and nutrient cycling (Coleman and Crossley, 1995). Treatment differences in the numbers and species composition of such organisms may differentially influence nutrient mineralization rates. For some plant species and communities, grazing can reduce root weight and root exploration (Klepper, 1991). If livestock grazing causes root systems to explore less soil or not extend to as great a depth, reduced plant nutrient uptake and/or reduced vertical transfer of elements, as compared to ungrazed systems, could result. In the period of our study, however, there were no significant grazing effects on root length density (<a href="#fig2">Figure 2</a>). Our results support the conclusions of Manning et al. (1989), that native meadows in this region can have very high root length densities. The dominant species in the two more mesic communities sampled by Manning et. al. were the same species that dominate the stream edge and mid-meadow locations in this study.</p>

	<p class="figure">
		<em class="bld"><a name="fig2"></a>Figure 2</em>&#8212;<strong>Root Length Density (cm cm<sup>&#8722;3</sup>) by Treatment, Depth, and Floodplain Position.</strong> Error bars are &#177; one standard error. <a href="graphics/blank2000_fig2_lg.gif">[view larger image - 16K]</a> <a href="graphics/blank2000_fig2_txt.html">[Text description of this figure]</a>
		<br />
		<br />
		 <a href="graphics/blank2000_fig2_lg.gif"><img src="graphics/blank2000_fig2.gif" alt="Bar graph comparing differences in root length density for the different treatments." width="500" height="241" border="0" /></a>
	</p>

	<h2>REFERENCES</h2>
	<div id="biblio">
	<p><strong>Blank, R. R., T. Svejcar, and G. Riegel.</strong> 1995. Soil Genesis and Morphology of a Montane Meadow in the Northern Sierra-Nevada Range. Soil Science <strong>160</strong>: 136&#8211;152.</p>
	<p><strong>Coleman, D. C. and D. A. Crossley. Jr.</strong>, 1995. Fundamentals of Soil Ecology. Academic Press. San Diego, California, 205 pp.</p>
	<p><strong>Dionex Corp.</strong>, 1986. Installation Instructions and Troubleshooting Guide for the HPIC-CS3 Column. Document No. 032654. Sunnyvale, Califomia, 12 pp.</p>
	<p><strong>Dionex Corp.</strong>, 1988. Installation Instructions and Troubleshooting Guide for the IONPAC AS4A Analytical Column. Document No. 034035. Sunnyvale, California, 39 pp.</p>
	<p><strong>EPA</strong>, 1979. Methods for Chemical Analysis of Water and Wastes, Method 365.1. U.S. Environmental Protection Agency, Washington, D.C.</p>
	<p><strong>Haynes, R. J. and P. H. Williams</strong>, 1999. Influence of Stock Camping Behaviour on the Soil Microbiological and Biochemical Properties of Grazed Pastoral Soils. Biology and Fertility of Soils <strong>28</strong>: 253&#8211;258.</p>
	<p><strong>Hearne, J. W. and C. Howard-Williams</strong>, 1988. Modelling Nitrate Removal by Riparian Vegetation in a Spring Fed Stream: The Influence of Land-use Practices. Ecological Modelling <strong>42</strong>: 179&#8211;198.</p>
	<p><strong>Huber, S. A., M. B. Judkins, L. Krysl, T. J. Svejcar, B. W. Hess, and D. W. Holcombe</strong>, 1995. Cattle Grazing a Riparian Mountain Meadow: Effects of Low and Moderate Stocking Density on Nutrition, Behavior, Diet Selection, and Plant Growth Response. Journal of Animal Science <strong>73</strong>: 3752&#8211;3765.</p>
	<p><strong>Kauffman, J. B., W. C. Krueger, and M. Vavra</strong>, 1983. Effects of Late Season Cattle Grazing on Riparian Plant Communities. Journal of Range Management <strong>36</strong>: 430&#8211;434.</p>
	<p><strong>Kauffman, J. B. and W. C. Krueger</strong>, 1984. Livestock Impacts on Riparian Ecosystems and Stream-edge Management Implications &#8211; a Review. Journal of Range Management <strong>37</strong>: 430&#8211;437.</p>
	<p><strong>Keeney, D. R. and D. W. Nelson</strong>, 1982. Nitrogen &#8211; Inorganic Fohns. In: Methods of Soil Analysis, Part 2 Chemical and Microbiological Properties, A. L. Page, (editor). American Society of Agronomy, Inc., Madison, Wisconsin, pp. 643&#8211;698.</p>
	<p><strong>Klepper, B.</strong>, 1991. Root-shoot Relationships. In: Plant Roots, The Hidden Half, Y. Waisel, A. Eshel, and U. Kafkafi (editors). Marcel Dekker, Inc., New York, New York, pp. 265&#8211;286.</p>
	<p><strong>Manning, M. E., S. R. Swanson, T. Svejcar, and J. Trent</strong>, 1989. Rooting Characteristics of Four Intermountain Meadow Community Types. Journal of Range Management <strong>42</strong>: 309&#8211;312.</p>
	<p><strong>McNaughton, S. J.</strong>, 1983. Compensatory Plant Growth as a Response to Herbivory. Oikos <strong>40</strong>: 329&#8211;336.</p>
	<p><strong>Olsen, S. R. and L. E. Sommers</strong>, 1982. Phosphorus. In: Methods of Soil Analysis Part 2 Chemical and Microbiological Properties,
A. L. Page (editor). American Society of Agronomy, Inc., Madison, Wisconsin, pp. 403&#8211;430.</p>
	<p><strong>Popolizio, C. A., H. Goetz, and P. L. Chapman</strong>, 1994. Short-term Response of Riparian Vegetation to 4 Grazing Treatments. Journal of Range Management <strong>47</strong>: 48&#8211;53.</p>
	<p><strong>Sharrow, S. H. and H. A. Wright</strong>, 1977. Effects of Fire, Ash and Litter on Soil Nitrate, Temperature, Moisture and Tobosa Grass Production in the Rolling Plains. Journal of Range Management <strong>30</strong>: 266&#8211;270.</p>
	<p><strong>Warner, R. E. and K. M. Hendrix</strong> (editors), 1984. California Riparian Systems: Ecology, Conservation, and Productive Management. University of California Press, Berkeley, California, 1035 pp.</p>
	
	</div>
<!-- END BIBLIO -->

</div>
<!-- END PUBLICATION -->
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
