#! /fsapps/fssys/bin/perl

  @par = <*.par>;
  foreach $par (@par) {
    open PAR, "<" . $par;
    $station = <PAR>;
    $latlong =  <PAR>;
    $lat = substr($latlong,6,8)+ 0;
    if ($lat < 34.50) {
#       print "southern ",$lat," ",$par," ",$station;
       $cmd = "cp $par ../cas/";
       print $cmd,"\n";      
       `$cmd`;
    }
    elsif ($lat < 36.50) {
#       print "central ",$lat," ",$par," ",$station;
       $cmd = "cp $par ../cac/";
       print $cmd,"\n";
       `$cmd`;      
    }
    else {
#       print "northern ",$lat," ",$par," ",$station;
       $cmd = "cp $par ../can/";
       print $cmd,"\n";
       `$cmd`;      
    }
  }
  close PAR;

