<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>SoLo: Soil Productivity Documents</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="SoLo: Soil Productivity Documents" />
		<meta name="keywords" content="soil productivity documents papers publications proceedings SOLO SoLo forest service region I" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../index.php">SOLO HOME</a> &gt; <a href="index.php">PRODUCTIVITY</a> &gt; DOCUMENTS</h5>
			<h1 class="topheading">DOCUMENTS</h1>
			<ul class="navlist">
				<li><a href="#nfsdocs">NFS Documents</a></li>
				<li><a href="#researchpubs">Research Publications</a>
					<ul>
						<li><a href="#researchpubs-FShandbooks">FS Research Handbooks and Manuals</a></li>
						<li><a href="#researchpubs-GTRs">Symposium Proceedings/General Technical Reports (GTRs)</a></li>
						<li><a href="#researchpubs-papers">Research Papers and Notes</a></li>
						<li><a href="#researchpubs-related">Related Publications</a></li>
					</ul>
				</li>
				<li><a href="#gradtheses">Graduate Theses</a></li>
			</ul>
			<p class="dateupdated">[Last update: 09/09/2011]</p>

			<h2 class="section">NATIONAL FOREST SYSTEM (NFS) DOCUMENTS<a name="nfsdocs">&nbsp;</a></h2>

		  	<h3 class="firstsection">Region 1 Forest Service Handbooks</h3>
		  	<p><strong>NOTE:</strong> You will need Adobe Acrobat Reader (<a href="https://www.adobe.com/">free download</a>) to view PDF files.</p>
		  	<ul class="researchpapers">
      			<li><a href="../../documents/reference_docs/r1_nat_forests/clearwater/CleNF_Land_Sys_Inv_1983.pdf">Clearwater <abbr title="National Forest">NF</abbr> Land System Inventory - 1983</a> (PDF - 21.4 MB)</li>
      			<li><a href="../../documents/reference_docs/r1_nat_forests/lolo/LoNF_Land_Sys_Inv_1988.pdf">Lolo <abbr title="National Forest">NF</abbr> Land System Inventory - 1988</a> (PDF - 54.8 MB)</li>
				<li><a href="../../documents/reference_docs/r1_nat_forests/gallatin/GalNF_SoilSurvey_1996.pdf">Soil Survey of Gallatin National Forest, Montana</a> (PDF - 34.6 MB; maps not included). 1996. Authors: Carl E. Davis and Henry F. Shovic. USDA Forest Service and Natural Resources Conservation Service in cooperation with the Montana Agricultural Experiment Station.</li>
				<li><a href="../../documents/reference_docs/r1_nat_forests/kootenai/KooNF_SoilSurvey_1995.pdf">Soil Survey of Kootenai National Forest Area, Montana and Idaho</a> (PDF - 12.8 MB; maps not included). 1995. Authors: Louis J. Kuennen and Marci L. Nielsen-Gerhardt. USDA Forest Service and Natural Resources Conservation Service in cooperation with the Montana Agricultural Experiment Station.</li>
      		</ul>
      
  			<h3 class="subsection">Administrative studies</h3>
      		<ul class="researchpapers">
      			<li><a href="../../documents/monitoring/reports_data/outofarea/ModocNF_TimberFert_1985.pdf">Modoc <abbr title="National Forest">NF</abbr> Timber Stand Fertilization Analysis Inventory - 1985</a> (out of area) (PDF - 896 KB)</li>
      		</ul>

			<h2 class="section">RESEARCH PUBLICATIONS<a name="researchpubs">&nbsp;</a></h2>

			
			<h3 class="firstsection"><abbr title="Forest Service">FS</abbr> Research Handbooks and Manuals<a name="researchpubs-FShandbooks"></a></h3>
			<ul class="researchpapers">
				<li><strong>2010 Soil Management Manual</strong> (part of FSM 2500 &ndash; Watershed and Air Management)   <br />
				<span class="dateupdated">[Documents added to SoLo on 12/06/2010]</span>
					<ul>
						<li><a href="../../documents/MISC/soil_mgmt_manual_2010/wo_2500_zero_code.pdf">Chapter 2500 - Zero Code</a></li>
						<li><a href="../../documents/MISC/soil_mgmt_manual_2010/wo_2509.18-2010-1_transmittal.pdf">FSH 2509.18 - Soil Management Handbook</a></li>
						<li><a href="../../documents/MISC/soil_mgmt_manual_2010/wo_2550.pdf">Chapter 2550 - Soil Managment Manual</a></li>
					</ul>
				</li>
      			<li>Moll, Jeffry E. A Guide to Road Closure and Obliteration in the Forest Service. (PDF available at <a href="https://www.fs.fed.us/eng/php/library_card.php?p_num=9677%201205">USDA Forest Service Engineering Publications</a>). 1996.</li>
			</ul>

			<h3 class="subsection">Symposium Proceedings/General Technical Reports (GTRs)<a name="researchpubs-GTRs"></a></h3>
			<h4>Intermountain Research Station (Later renamed Rocky Mountain Research Station)</h4>
			<ul class="researchpapers">
      			<li><strong>GTR-INT-374 &#8211;</strong> Harvey, Alan E., Martin F. Jurgensen, Michael J. Larsen and Joyce A. Schlieter. <a href="../../documents/GTRs/INT_374/Harvey_INT-374_1986.pdf">Distribution of Active Ectomycorrhizal Short Roots in Forest Soils of the Inland Northwest: Effects of Site and Disturbance (GTR-INT-374)</a> (PDF - 620 KB). 1986.</li>
      			<li><strong>GTR-INT-341 &#8211;</strong> Hardy, Colin C. and Steven F. Arno. eds. The Use of Fire in Forest Restoration. (A General Session at the Annual Meeting of the Society for Ecological Restoration, Seattle, WA, September 14&#8211;16, 1995.) [table of contents and selected papers available at <a href="https://www.fs.fed.us/rm/pubs/int_gtr341/">https://www.fs.fed.us/rm/pubs/int_gtr341/</a>]. 1996.</li>
				<li><strong>GTR-INT-280 &#8211;</strong> <a href="../../InfoPath/productivity/bibliography/GTR_INT-280.php"><strong>Proceedings&#8212;Management and Productivity of Western-Montane Forest Soils</strong></a>, April 10&#8211;12, 1990, Boise, ID, USDA Forest Service General Technical Report INT-280, August 1991.
  					<ul class="researchpapers">
  						<li>Amaranthus, M. P. <a href="../../documents/GTRs/INT_280/Amaranthus_INT-280.php">Factors Affecting Ectomycorrhizae and Forest Regeneration Following Disturbance in the Pacific Northwest</a> (HTML)</li>
						<li>Binkley, D. <a href="../../documents/GTRs/INT_280/Binkley_INT-280.php">Connecting Soils with Forest Productivity</a> (HTML)</li>
						<li>Bosworth, B.; Studer D. <a href="../../documents/GTRs/INT_280/Bosworth_INT-280.php">Comparisons of Tree Height Growth on Broadcast-Burned, Bulldozer-Piled, and Nonprepared Sites 15 to 25 Years After Clearcut Logging</a> (HTML)</li>
						<li>DeBano, L. F. <a href="../../documents/GTRs/INT_280/DeBano_INT-280.php">The Effect of Fire on Soil Properties</a> (HTML)</li>
						<li>Edmonds, R. L. <a href="../../documents/GTRs/INT_280/Edmonds_INT-280.php">Organic Matter Decomposition in Western United States Forests</a> (HTML)</li>
						<li>Everett, R.; Zabowski, D.; McColley, P. <a href="../../documents/GTRs/INT_280/Everett_INT-280.php">Vegetative Restoration of Western-Montane Forest Soils</a> (HTML)</li>
						<li>Geist, J. M. ; Cochran, P. H. <a href="../../documents/GTRs/INT_280/GeistCochran_INT-280.php">Influences of Volcanic Ash and Pumice Deposition on Productivity of Western Interior Forest Soils</a> (HTML)</li>
						<li>Geist, J. M.; Meurisse, R. T.; Max, T. A. <a href="../../documents/GTRs/INT_280/GeistMeurisse_INT-280.php">Monitoring Forest Soil Properties to Maintain Productivity</a> (HTML)</li>
						<li>Graham, R. T.; Minore, D.; Harvey, A. E.; Jurgensen, M. F.;. Page-Dumroese, D. S. <a href="../../documents/GTRs/INT_280/Graham_INT-280.php">Soil Management as an Integral Part of Silvicultural Systems</a> (HTML)</li>
						<li>Harvey, A. E.; Page-Dumroese, D. S.; Graham, R. T.; Jurgensen, M. F. <a href="../../documents/GTRs/INT_280/Harvey_INT-280.php">Ectomycorrhizal Activity and Conifer Growth Interactions in Western-Montane Forest Soils</a> (HTML)</li>
						<li>Hironaka, M.; Fosberg, M. A.; Neiman, K. E. Jr. <a href="../../documents/GTRs/INT_280/Hironaka_INT-280.php">The Relationship Between Soils and Vegetation</a> (HTML)</li>
						<li>Hungerford, R. D.; Harrington, M. G.; Frandsen, W. H.; Ryan, K. C.; Niehoff, G. J. <a href="../../documents/GTRs/INT_280/Hungerford_INT-280.php">Influence of Fire on Factors that Affect Site Productivity</a> (HTML)</li>
						<li>Jensen, M. E. <a href="../../documents/GTRs/INT_280/Jensen_MontaneProc_1990.pdf">Ecological Classification and Cumulative Soil Effects</a> (PDF - 449 KB) <br /><span class="dateupdated">[Document added to SoLo on 07/15/2005]</span></li>
						<li>Jurgensen, M. F.; Tonn, J. R.; Graham, R. T.; Harvey, A. E.; Geier-Hayes, K. <a href="../../documents/GTRs/INT_280/Jurgensen_INT-280.php">Nitrogen Fixation in Forest Soils of the Inland Northwest</a> (HTML)</li>
						<li>Megahan, W. F. <a href="../../documents/GTRs/INT_280/Megahan_INT-280.php">Erosion and Site Productivity in Western-Montane Forest Ecosystems</a> (HTML)</li>
						<li>Meurisse, R. T.; Robbie, W. A.; Niehoff, G. J.; Ford, G. <a href="../../documents/GTRs/INT_280/Meurisse_INT-280.php">Dominant Soil Formation Processes and Properties in Western-Montane Forest Types and Landscapes&#8212;Some Implications for Productivity and Management</a> (HTML)</li>
						<li>Molina, R.; Amaranthus, M. <a href="../../documents/GTRs/INT_280/Molina_INT-280.php">Rhizosphere Biology: Ecological Linkages Between Soil Processes, Plant Growth, and Community Dynamics</a> (HTML)</li>
						<li>Page-Dumroese, D.; Harvey, A.; Jurgensen, M.; Graham, R. <a href="../../documents/GTRs/INT_280/PageDumroese_INT-280.php">Organic Matter Function in the Western-Montane Forest Soil System</a> (HTML)</li>
						<li>Page-Dumroese, D.; Graham, R. T.; Harvey, A. E. <a href="../../documents/GTRs/INT_280/PageDumroesePoster_INT-280.php">Soil Organic Matter Effects on Douglas-Fir Growth in Northern Idaho Soils</a> (HTML)</li>
						<li>Powers, R. F. <a href="../../documents/GTRs/INT_280/Powers_INT-280.php">Are We Maintaining the Productivity of Forest Lands? Establishing Guidelines Through a Network of Long-Term Studies</a> (HTML)</li>
						<li>Sommer, M.; Adams, D.; Mahler, R. <a href="../../documents/GTRs/INT_280/SommerPoster_INT-280.php">Soil Properties as a Factor in Regeneration Failures in the Grand Fir Mosaic&#8212;Preliminary Results</a> (HTML)</li>
						<li>Stark, N. M.; Zuuring, H. <a href="../../documents/GTRs/INT_280/Stark_INT-280.php">Minimizing the Adverse Impacts of Timber Harvest in the Northern Rocky Mountains</a> (HTML)</li>
						<li>Steele, R.; Pfister, R. D. <a href="../../documents/GTRs/INT_280/Steele_INT-280.php">Western-Montane Plant Communities and Forest Ecosystem Perspectives</a> (HTML)</li>
						<li>Verbyla, D. L. <a href="../../documents/GTRs/INT_280/Verbyla_INT-280.php">Validation of Soil-Site Models</a> (HTML)</li>
					</ul> 
				</li>
      			<li><strong>GTR-INT-264 &#8211;</strong> Burroughs, Edward R. Jr. and John G. King. <a href="../../documents/GTRs/INT_264/INT-264_ReducSoilEro_1989.pdf">Reduction of Soil Erosion on Forest Roads</a> (PDF - 1.9 MB). 1989.</li>
  				<li><strong>GTR-INT-110 &#8211;</strong> <a href="../../documents/GTRs/INT_90/INT-90_Harvest_1979.pdf">Environmental Consequences of Timber Harvesting in Rocky Mountain Coniferous Forests: Symposium Proceedings</a> (PDF - 19.7 MB), Sept. 11&#8211;13, 1979, Missoula, MT, USDA Forest Service General Technical Report INT-90, September 1980.</li>
  				<li><strong>GTR-INT-90 &#8211;</strong> <a href="../../documents/GTRs/INT_110/INT-110_HarvRes_1979.pdf">Harvesting and Utilization Opportunities for Forest Residues in the Northern Rocky Mountains: Symposium Proceedings</a> (PDF - 10.3 MB), Sept. 11&#8211;13, 1979, Missoula, MT, USDA Forest Service General Technical Report INT-110, September 1980.</li>
      				<li><strong>GTR-INT-65 &#8211;</strong> Harvey, Alan E., Martin F. Jurgensen and Michael J. Larsen. <a href="../../documents/GTRs/INT_65/Harvey1979_GTR-INT-65.pdf">Role of Forest Fuels in the Biology and Management of soil</a> (PDF - 4.4 MB). 1979.</li>
      			<li><strong>GTR-INT-28 &#8211;</strong> Harvey, Alan E., Martin F. Jurgensen and Michael J. Larsen. <a href="../../documents/GTRs/INT_28/INT-28_FiberUtil_1976.pdf">Intensive Fiber Utilization and Prescribed Fire: Effects on the Microbial Ecology of Forests</a> (PDF - 3.1 MB). 1976.</li>
			</ul>				
			<h4>Pacific Northwest Research Station</h4>
			<ul class="researchpapers">
      			<li><strong>GTR-PNW-840 &#8211;</strong> Reynolds, Keith M., Paul F. Hessburg, Richard E. Miller, and Robert T. Meurisse. <a href="https://www.treesearch.fs.fed.us/pubs/38190">Evaluating Soil Risks Associated With Severe Wildfire and Ground-Based Logging</a>. 2011. <br /><span class="dateupdated">[Link to document added 09/09/2011]</span></li>
      				<li><strong>GTR-PNW-811 &#8211;</strong> Miller, Richard E., James D. McIver, Steven W. Howes and William B Gaeuman. <a href="https://www.treesearch.fs.fed.us/pubs/35150">Assessment of Soil Disturbance in Forests of the Interior Columbia River Basin: A Critique</a>. 2010. <br /><span class="dateupdated">[Link to document added 07/30/2010]</span></li>
				<li><strong>GTR-PNW-802 &#8211; </strong>Pye J.M., H.M. Rauscher, Y. Sands, D.C. Lee, and J. S. Beatty, Technical Eds. <a href="https://www.treesearch.fs.fed.us/pubs/36650">Advances in Threat Assessment and Their Application to Forest and Rangeland Management, Volume 1</a>. September 2010. <br /><span class="dateupdated">[Link added to SoLo on 05/04/2011]</span></li>
      			<li><strong>GTR-PNW-759 &#8211;</strong> Erickson, Heather E.; White, Rachel. <a href="https://www.treesearch.fs.fed.us/pubs/29927">Soils under fire: soils research and the Joint Fire Science Program</a>. 2008.</li>
      			<li><strong>GTR-PNW-362 &#8211;</strong> Cooper, Stephen V., Peter Lesica and Deborah Page-Dumroese. <a href="https://treesearch.fs.fed.us/pubs/35499">Plant Community Classification for Alpine Vegetation on the Beaverhead National Forest, Montana</a>. 1997. <br /><span class="dateupdated">[Link to document added 07/30/2010]</span></li>
      			<li><strong>GTR-PNW-323 &#8211;</strong> Harvey, Alan E., Michael Geist, Gerald McDonald, Martin F. Jurgensen, Patrick H. Cochran, Darlene Zabowski and Robert T. Meurisse. <a href="https://www.treesearch.fs.fed.us/pubs/6286">Biotic and Abiotic Processes in Eastside Ecosystems: The Effects of Management on Soil Properties, Processes, and Productivity (GTR-PNW-323)</a>. 1994.</li>
			</ul>				
			<h4>Rocky Mountain Research Station (formerly called Intermountain Research Station)</h4>
			<ul class="researchpapers">
      			<li><strong>RMRS-GTR-215 &#8211;</strong> Rawinski, John J. and Deborah S. Page-Dumroese. <a href="https://www.treesearch.fs.fed.us/pubs/30957">Soil compaction monitoring of the Pool Timber Sale, Rio Grande National Forest, Colorado 16 years after logging</a>. 2008. <br /><span class="dateupdated">[link to document added 02/20/2009]</span></li>
      			<li><strong>RMRS-P-44 &#8211;</strong> Page-Dumroese, Deborah; Miller, Richard; Mital, Jim; McDaniel, Paul; Miller, Dan, tech. eds. <strong>Volcanic-Ash-Derived Forest Soils of the Inland Northwest: Properties and Implications for Management and Restoration</strong>.  [entire proceedings available at <a href="https://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-44.pdf">https://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-44.pdf (PDF - 6.7 MB)</a>; individual papers can be downloaded separately at <a href="https://www.fs.fed.us/rm/pubs/rmrs_p044.html">https://www.fs.fed.us/rm/pubs/rmrs_p044.html</a>]. 2007. (Conference was held November 9&#8211;10, 2005 in Coeur d'Alene, Idaho.)</li>
      			<li><strong>GTR-RMRS-42 &#8211;</strong> Neary, Daniel G.; Ryan, Kevin C.; DeBano, Leonard F., eds. <a href="https://www.fs.fed.us/rm/pubs/rmrs_gtr042_4.pdf">Wildland Fire in Ecosystems: Effects of Fire on Soil and Water</a>. 2005 (revised 2008).</li>
			</ul>				
			<h4>Miscellaneous GTRs and Proceedings</h4>
			<ul class="researchpapers">
  				<li><strong>WO-WSA-2 &#8211;</strong> <a href="../../documents/MISC/WO-WSA-2/WO-WSA-2_ProcSoilQualSt_1992.pdf">Proceedings of the Soil Quality Standards Symposium</a> (PDF - 4 MB), Oct. 23, 1990, San Antonio, TX, USDA Forest Service Watershed and Air Management, WO-WSA-2, Washington D.C., February 1992.</li>
			</ul>				

			<h3 class="subsection">Research Papers and Notes<a name="researchpubs-papers"></a></h3>
			<ul class="researchpapers">
      			<li>Adams, P. W.; H. A. Froehlich. <a href="../../documents/RPs/Adams_Froehlich_1984.pdf">Compaction of Forest Soils</a> (PDF - 1.3 MB). 1984.</li>
      			<li>Amaranthus, Michael P. and David E. Steinfeld. <a href="../../documents/RPs/Amaranthus_PNW-RP-504_1997.pdf">Soil compaction after yarding of small-diameter Douglas-fir with a small tractor in southwest Oregon</a> (PDF - 707 KB). 1997.</li>
      			<li>Amaranthus, Michael P., Debbie Page-Dumroese, Al Harvey, Efren Cazares and Larry F. Bednar. <a href="https://forest.moscowfsl.wsu.edu/smp/docs/docs/Amaran_PNW-RP-494_1996.html">Soil compaction and organic matter affect conifer seedling nonmycorrhizal and ectomycorrhizal root tip abundance and diversity</a> (HTML). 1996.</li>
      			<li>Andrus, C. W.; H. A. Froehlich. <a href="../../documents/RPs/Andrus_Froehlich_1983.pdf">An Evaluation of Four Implements Used to Till Compacted Forest Soils in the Pacific Northwest</a> (PDF - 1.2 MB). 1983.</li>
				<li>Angima S.D. and T. A. Terry. 2011. <a href="https://hdl.handle.net/1957/20678">Best Management Practices for Maintaining Soil Productivity in the Douglas-fir Region</strong>. Oregon State University Extension Service. 44 p.<br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
              	<li>Arno, S. F. Forest fire history in the Northern Rockies. 1980. <a href="https://www.safnet.org/periodicals/jof/">Journal of Forestry</a> 78(8): 460&#8211;465.</li>
      			<li>Arno, Stephen F. <a href="../../documents/RPs/Arno_RP-INT-187_1976.pdf">The historical role of fire on the Bitterroot National Forest</a> (PDF - 2.34 MB). 1976. (<strong>RP-INT-187</strong>)</li>
      			<li>Azuma, David L. and Glenn A. Christensen. <a href="https://www.fs.fed.us/pnw/pubs/pnw_rp560.pdf">Southwest Oregon Biscuit Fire: An analysis of forest resources and fire severity</a>. 2004. USDA Forest Service, Pacific Northwest Research Station, PNW-RP-560.<br /><span class="dateupdated">[Document linked to SoLo on 02/13/2009]</span></li>
      			<li>B. C. Ministry of Forests. <a href="https://faculty.forestry.ubc.ca/bendickson/FOPRLibrary/Library/M%20o%20F%20Guidebooks%20&%20Pubications/Soil%20&%20Windthrow/Hazard%20Assess%20Keys.pdf">Hazard Assessment Keys for Evaluating Site Sensitivity to Soil Degrading Processes Guidebook, 2nd Edition, Ver. 2.1</a>. 1999. Province of British Columbia, Canada. <br /><span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Barkley, Yvonne C. <a href="https://www.cnr.uidaho.edu/extforest/AftertheBurnFINAL.pdf">After the burn: Assessing and managing your forestland after a wildfire</a>. 2006. Published by University of Idaho Extension for the University of Idaho Forest, Wildlife and Range Experiment Station, Moscow, Idaho. <br /><span class="dateupdated">[link to document added 02/20/2009]</span></li>
     			<li>Belnap, J. <a href="../../documents/RPs/belnap_se-UT_1998.php">Impacts of Trampling Soils in Southeast Utah Ecosystems</a> (HTML). 1998?</li>
      			<li>Benson, Robert E. <a href="../../documents/RNs/Benson_RN-INT-294_1980.pdf">Damage from logging and prescribed burning in partially cut Douglas-fir stands</a> (PDF - 846 KB). 1980. (<strong>RN-INT-294</strong>)</li>
              	<li>Bissett, J. and D. Parkinson. Long-term effects of fire on the composition and activity of the soil microflora of a subalpine, coniferous forest. 1980. <a href="https://www.ingentaconnect.com/content/nrc/cjb">Canadian Journal of Botany</a> 58: 1704&#8211;1721.</li>
				<li>Blank, R. T.; T. Svejcar. <a href="../../documents/RPs/blank_2000.php">Grazing Influences on Selected Soil Attributes in a Sierra Nevada Riparian Meadow</a> (HTML). Proceedings, AWRA's 2000 summer specialty conference: riparian ecology and management in multi-land use watersheds: August 28&#8211;31, 2000, Portland, Oregon. Middleburg, VA: American Water Resources Association, c2000. Technical publication series; no. TPS 00-2: p. 269&#8211;273.</li>
      			<li>Bock, Michael D. and Ken C. J. Van Rees. <a href="https://www.ingentaconnect.com/content/nrc/cjfr/2002/00000032/00000008/art00008;jsessionid=1fzeu39o1wz82.alexandra">Mechanical site preparation impacts on soil properties and vegetation communites in the Northwest Territories</a>. 2002. Can. J. For. Res. 32: 1381&#8211;1392. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
           		<li>Brantley, Susan L. <a href="https://www.sciencemag.org/cgi/search?volume=321&firstpage=1454&journal_search_volume_go.x=17&journal_search_volume_go.y=5&journal_search_volume_go=go&andorexactfulltext=and&andorexacttitleabs=and">Understanding soil time</a>. 2008. Science. 321: 1454&#8211;1455<br /><span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Busse, Matt D.; Samual E. Beattie; Robert F. Powers; Felipe G. Sanchez and Allan E. Tiarks. <a href="https://www.treesearch.fs.fed.us/pubs/22169">Microbial community responses in forest mineral soil to compaction, organic matter removal, and vegetation control</a>. Can. J. For. Res. 2006. 36(3): 577&#8211;588.</li>
      			<li>Carter, Mason C.; Thomas J. Dean; Ziyin Wang and Ray A. Newbold. <a href="https://www.treesearch.fs.fed.us/pubs/25274">Impacts of harvesting and postharvest treatments on soil bulk density, soil strength, and early growth of Pinus taeda in the Gulf Coastal Plain: a Long-Term Soil Productivity affiliated study</a>. Can. J. For. Res. 2006. 36(3): 601&#8211;614.</li>
      			<li>Carter, Mason C. and C. Darwin Foster. <a href="https://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4BFPF4K-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=1c3cf225e65f0669cdfce09d1ed976db">Prescribed burning and productivity in southern pine forests: a review</a>. 2004. For. Ecol. Mgmt. 191: 93&#8211;109. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Cline, Richard G. and Gaylon S. Campbell. <a href="https://www.esajournals.org/doi/abs/10.2307/1934826">Seasonal and diurnal water relations of selected forest species</a>. 1976. Ecology 57(2): 367&#8211;373. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Cline, Richard G.; Jerry Ragus; Gary D. Hogan; Doug G. Maynard; Neil W. Foster; Thomas A. Terry; Ronald L. Heninger; Robert G. Campbell and Mason C. Carter. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?cjfr_x05-266_36_ns_nf_cjfr">Policies and practices to sustain soil productivity: perspectives from the public and private sectors</a>. Can. J. For. Res. 2006. 36(3): 615&#8211;625.</li>
				<li>Coleman, Mark; Page-Dumroese, Deborah; Archuleta, Jim; Badger, Phil; Chung, Woodum; Venn, Tyron; Loeffler, Dan; Jones, Greg; McElligott, Kristin. 2010. <a href="https://www.treesearch.fs.fed.us/pubs/37322">Can portable pyrolysis units make biomass utilization affordable while using bio-char to enhance soil productivity and sequester carbon?</a>. In: Jain, Theresa B.; Graham, Russell T.; Sandquist, Jonathan. Integrated management of carbon sequestration and biomass utilization opportunities in a changing climate: Proceedings of the 2009 National Silviculture Workshop; 2009 June 15&#8211;18; Boise, ID. Proceedings RMRS-P-61. Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. p. 159&#8211;168. <br />
					<span class="dateupdated">[link added 05/03/2011]</span></li>
              	<li>Conlin, T. S. S. and R. van den Driessche. <a href="https://www.for.gov.bc.ca/hfd/pubs/docs/Frr/Frr264.pdf">Soil Compaction Studies.</a> 1996. Canadian Forest Service and B.C. Ministry of Forests<br /><span class="dateupdated">[link to document added 02/13/2009]</span></li>
               	<li>Cromer, R. N. and R. G. Vines. 1966. Soil temperatures under a burning windrow. Aust. For. Res. 2: 29&#8211;34.</li>
      			<li>Curran, Michael, P.; Douglas G. Maynard; Ronald L. Heninger; Thomas A. Terry; Steven W. Howes; Douglas M. Stone; Thomas Niemann; Richard E. Miller and Robert F. Powers. <a href="https://www.treesearch.fs.fed.us/pubs/25522">An adaptive management process for forest soil conservation</a>. 2005. For. Chron. 81(5): 717&#8211;722. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Daddow, R. L. and G. E. Warrington. <a href="../../documents/RPs/daddow_warrington_root_limiting_bulk_density.pdf">Growth-limiting Soil Bulk Densities as Influenced by Soil Texture</a> (PDF - 104 KB). 1983. Watershed Systems Development Group Report: WSDG-TN-00005.</li>
              	<li>Davis, K. P. and K. A. Klehm. <a href="https://www.ingentaconnect.com/content/saf/jof/1939/00000037/00000005/art00014">Controlled burning in the Western White Pine type.</a> 1939.</li>
      			<li>Davis, S. <a href="../../documents/RPs/Davis_1983.pdf">Effectiveness of a Winged Subsoiler in Ameliorating a Compacted Clayey Forest Soil</a> (PDF - 316 KB). 1983.</li>
				<li>DeByle, N. V. 1976. <a href="../../documents/RPs/DeByle_USGovtPub_1976.pdf">Fire, logging, and debris disposal effects on soil and water in northern coniferous forests</a>. (PDF - 729 KB) International Union of Forest Research Organizations, Div. 1, Proceedings XVI IUFRO World Congr. Oslo, Norway. U.S. Government Printing Office. p. 201&#8211;212.</li>
      			<li>DeLuca, T. H. and K. L. Zouhar. <a href="https://www.ingentaconnect.com/content/els/03781127/2000/00000138/00000001/art00401;jsessionid=7hbdg473119ch.alice?format=print">Effects of selection harvest and prescribed fire on the soil nitrogen status of ponderosa pine forests</a>. 2000. For. Ecol. Mgmt. 138: 263&#8211;271. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
				<li>Dumroese, R. Kasten; Heiskanen, Juha; Englund, Karl; Tervahauta, Arja  2011. <a href="https://www.treesearch.fs.fed.us/pubs/37521">Pelleted biochar: chemical and physical properties show potential use as a substrate in container nurseries</a>. Biomass &amp; Bioenergy. 35: 2018&#8211;2027. <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
				<li>Dumroese, R. Kasten; Page-Dumroese, Deborah S.; Brown, Robert E.  2011. <a href="https://www.treesearch.fs.fed.us/pubs/37877">Allometry, nitrogen status, and carbon stable isotope composition of Pinus ponderosa seedlings in two growing media with contrasting nursery irrigation regimes</a>. Canadian Journal of Forest Research. 40: 1091&#8211;1101. <br />
					<span class="dateupdated">[link added 05/23/2011]</span></li>
             	<li>Entry, J. A.; N. M. Stark and H. Loewenstein. <a href="https://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?calyLang=eng&journal=cjfr&volume=16&year=0&issue=5&msno=x86-186">Effect of timber harvesting on microbial biomass fluxes in a northern Rocky Mountain forest soil.</a> 1986.</li>
      			<li>Fahnestock George R. <a href="../../documents/RPs/Fahnestock_RP-INT-70_1962.pdf">Logging slash flammability after five years</a> (PDF - 2.58 MB). 1962. (<strong>RP-INT-70</strong>)</li>
           		<li>Feller, M. C. <a href="https://miva.crownpub.bc.ca/Merchant2/merchant.mvc?Screen=PROD&Product_Code=013-833&Category_Code=CP-02-01-40-25">The Ecological Effects of Slashburning with particular reference to British Columbia: A Literature Review.</a> 1982.</li>
      			<li>Fleming, R. L.; T. A. Black and N. R. Eldridge. <a href="https://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4915VW5-5&_user=10&_coverDate=10%2F31%2F1994&_alid=836033404&_rdoc=1&_fmt=high&_orig=search&_cdi=5042&_sort=d&_docanchor=&view=c&_ct=1&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=7413e05b413a64c9d9ef8aa106028071">Effects of site preparation on root zone soil water regimes in high-elevation forest clearcuts</a>. 1994. For. Ecol. Mgmt. 68: 173&#8211;188. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Fleming, Robert L.; Michael F. Laporte; Gary D. Hogan and Paul W. Hazlett. Effects of harvesting and soil disturbance on soil CO2 efflux from a jack pine forest. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_f?cjfr_x05-258_36_ns_nf_cjfr3-06">Can. J. For. Res.</a> (abstract and full text available). 2006. 36(3): 589&#8211;600.</li>
      			<li>Fleming, Robert L.; Robert F. Powers; Neil W. Foster; J. Marty Kranabetter; D. Andrew Scott; Felix Ponder, Jr.; Shannon Berch; William K. Chapman; Richard D. Kabzems; Kim H. Ludovici; David M. Morris; Deborah S. Page-Dumroese; Paul T. Sanborn; Felipe G. Sanchez; Douglas M. Stone and Allan E. Tiarks. <a href="https://www.treesearch.fs.fed.us/pubs/22170">Effects of organic matter removal, soil compaction, and vegetation control on 5-year seedling performance: a regional comparison of Long-Term Soil Productivity sites</a>. Can. J. For. Res. 2006. 36(3): 529&#8211;550.</li>
      			<li>Ford, G. L.; C. L. Maynard; J. A. Nesser; D. Page-Dumroese. <a href="../../documents/RPs/Ford_etal_LTA_1996.pdf">Landtype Associations of the Northern Region, A First Approximation</a> (PDF - 2.6 MB). 1996. (This document was expanded in 1997 and functions as the <a href="https://forest.moscowfsl.wsu.edu/smp/solo/GeoPath/lta/index.php">Landtype Associations section</a> of this SoLo web site.)</li>
             	<li>Frandsen, W. H. and K. C. Ryan. <a href="https://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=16&year=&issue=&msno=x86-043&calyLang=eng">Soil moisture reduces belowground heat flux and soil temperatures under a burning fuel pile.</a> 1986.</li>
      			<li>Froehlich, H. A.; D. H. McNabb. <a href="../../documents/RPs/Froehlich_McNabb_1983.pdf">Minimizing Soil Compaction in Pacific Northwest Forests</a> (PDF - 2.7 MB). 1983.</li>
      			<li>Froehlich, H. A.; D. W. R. Miles. <a href="../../documents/RPs/Froehlich_Miles_1984.pdf">Winged subsoiler tills compacted forest soils</a> (PDF - 436 KB). 1984.</li>
      			<li>Geist, M. J.; H. A. Froehlich. <a href="../../documents/RPs/Geist_Froehlich.pdf">Principles and Processes of Subsoiling in Forest Ecosystems</a> (PDF - 456 KB).</li>
      			<li>Gent, J. A.; H. L. Allen; Robert G. Campbell and C. G. Wells. <a href="https://www.ingentaconnect.com/content/saf/sjaf/1986/00000010/00000003/art00004">Magnitude, duration, and economic analysis of Loblolly Pine growth response following bedding and phosphorus fertilization</a>. 1986. South. J. Appl. For. 10(3): 124&#8211;128. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
                <li>Gore, J. A. and W. A. Patterson III. <a href="https://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?calyLang=eng&journal=cjfr&volume=16&year=0&issue=2&msno=x86-057">Mass of downed wood in northern hardwood forests in New Hampshire: potential effects of forest management.</a> 1986.</li>
     			<li>Greacen, E. L.; R. Sands. <a href="../../documents/RPs/Greacen_Sands_1980.pdf">Compaction of Forest Soils: A Review</a> (PDF - 2.7 MB).</li>
      			<li>Gundale, Michael J.; Thomas H. DeLuca; Carl E. Fiedler; Philip W. Ramsey; Michael G. Harrington and James E. Gannon. <a href="https://www.fs.fed.us/ffs/docs/Gundale_etal_2005.pdf">Restoration treatments in a Montana ponderosa pine forest: Effects on soil physical, chemical and biological properties</a>. 2005. For. Ecol. Mgmt. 213: 25&#8211;38.<br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
				<li>Han, H.-S.; D. S. Page-Dumroese; S.-K. Han and J. Tirocke. <a href="https://www.lib.unb.ca/Texts/JFE/index.html">Effects of slash, machine passes, and soil moisture on penetration resistance in a cut-to-length harvesting</a>. International Journal of Forest Engineering. 2006. 17(2): 11&#8211;24.</li>
				<li>Han, S.-K.; H.-S. Han; D. S. Page-Dumroese; and L. R. Johnson. <a href="https://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=39&year=2009&issue=5&msno=x09-027&calyLang=eng">Soil compaction associated with cut-to-length and whole-tree harvesting of a coniferous forest</a>. 2009. Can. J. For. Res. 39: 976&#8211;989. <br /><span class="dateupdated">[link to publication added 05/19/2009]</span></li>
      			<li>Hardesty, Linda, Christopher E. Gebauer and John Buckhouse. <a href="../../documents/RPs/Hardesty_Grazing_1996.pdf">Forest Soil Characteristics After Twenty-Six Years of Cattle and Big Game Grazing in Northeastern Oregon</a> (PDF - 518 KB). 1996. (Part of the Northern Region Soils Workshop, May 20&#8211;22, 1997.)</li>
               	<li>Harvey, A. E.; M. F. Jurgensen and R. T. Graham. <a href="https://cru84.cahe.wsu.edu/cgi-bin/pubs/MISC0231.html">Fire-soil interactions governing site productivity in the northern Rocky Mountains.</a> 1999.</li>
				<li>Harvey, Alan E., Michael J. Larsen and Martin F. Jurgensen. Partial cut harvesting and ectomycorrhizae: early effects in Douglas-fir-larch forests of western Montana. 1980b. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_desc_e?cjfr">Canadian Journal of Forest Research</a>. 10(3): 436&#8211;440.</li>
      			<li>Hatten, J. A.; D. Zabowski; A. Ogden and W. T. <a href="https://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4S02JX3-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=321f7263572a92c1edc0fe4d60dc1ab4">Soil organic matter in a ponderosa pine forest with varying seasons and intervals of prescribed burn</a>. 2008. For. Ecol. Mgmt. 255: 2555&#8211;2565. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Heninger, Ronald; William Scott; Alex Dobkowski; Richard Miller; Harry Anderson and Steve Duke. <a href="https://www.ingentaconnect.com/content/nrc/cjfr/2002/00000032/00000002/art00006">Soil disturbance and 10-year growth response of coast Douglas-fir on nontilled and tilled skid trails in the Oregon Cascades</a>. 2002. Can. J. For. Res. 32: 233&#8211;246. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Heninger, R.; W. Scott; R. Miller; H. Anderson. <a href="../../documents/RPs/Heninger_etal_1983.pdf">Case Study: Growth of Douglas-fir on Cultivated and Non-Cultivated Skid Trails in Coastal Washington and Western Oregon</a> (PDF - 112 KB). 1983.</li>
      			<li>Hermann, Richard K. <a href="https://www.ingentaconnect.com/content/saf/jof/1964/00000062/00000002/art00006">Paper mulch for reforestation in southwestern Oregon</a>. 1964. Journ. of For. 62(2): 98&#8211;101. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
               	<li>Hesterberg, G. A. and M. F. Jurgensen. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?tfc_tfc48092-2_48_ns_nf_tfc">The relation of forest fertilization to disease incidence.</a> 1972.</li>
              	<li>Humphreys, F. R. and Marcia J. Lambert. 1965. Soil temperature profiles under slash and log fires of various intensities. Australian For. Res. 1?: 23&#8211;29.</li>
				<li>Johnson L.R., D. Page-Dumroese, and H.-S. Han. 2007. <strong>Effects of Machine Traffic on the Physical Properties of Ash-Cap Soils</strong> (available at <a href="https://www.treesearch.fs.fed.us/pubs/26213">https://www.treesearch.fs.fed.us/pubs/26213</a>. In: Page-Dumroese, Deborah; Miller, Richard; Mital, Jim; McDaniel, Paul; Miller, Dan, tech. eds. 2007. Volcanic-Ash-Derived Forest Soils of the Inland Northwest: Properties and Implications for Management and Restoration. 9&#8211;10 November 2005; Coeur d&#8217;Alene, ID. Proceedings RMRS-P-44; Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. p. 69&#8211;82 <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
				<li>Jurgensen, M. F.; A. E. Harvey; M. J. Larsen. <a href="../../documents/RPs/Jurgensen1981_RP-INT-275.pdf">Effects of Prescribed Fire on Soil Nitrogen Levels in a Cutover Douglas-fir/Western Larch Forest (PDF - 3.7 MB)</a>. 1981. Research Paper INT-275.</li>
				<li>Jurgensen, M. F.; A. E. Harvey; R. T. Graham; D. S. Page-Dumroese; J. R. Tonn; M. J. Larsen; T. B. Jain. <a href="../../documents/RPs/Jurgensen_etal_97.php">Impacts of Timber Harvesting on Soil Organic Matter, Nitrogen, Productivity, and Health of Inland Northwest Forests</a> 1997. (HTML).</li>
				<li>Jurgensen, M. F.; M. J. Larsen; A. E. Harvey. <a href="../../documents/RPs/Jurgensen_etal_SocAmFor_1978.pdf">Effects of timber harvesting on soil biology (PDF - 483 KB)</a>. 1978. Presented at the Society of American Foresters National Convention, 1977. <br /><span class="dateupdated">[publication added 02/27/2009]</span></li>
      			<li>Kavanagh, Kathleen; George Stankey and Jim Boyle. <a href="https://www.ingentaconnect.com/content/klu/nefo/1999/00000018/00000001/00195701;jsessionid=7aoqtab0ea3ka.alice?format=print">The integration of planted and natural forests in a regional landscape</a>. 1999. New Forests 18: 97&#8211;109. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
		      	<li>Klock, G. O. and C. C. Grier. 1981. Effects of Fire on the Long-term Maintenance of Forest Productivity.  In: Gessel, S.P.; Kenady, R.M.; Atkinson, W.A., eds. Proceedings, Forest fertilization conference; 1979 September 25-27; Union, WA. Institute of Forest Resources Cont. 40. Seattle, WA: <a href="https://www.washington.edu/">University of Washington</a>, College of Forest Resources: 247&#8211;250.</li>                    
      			<li>Kruse, William H. <a href="../../documents/RNs/Kruse_RN-RM-226_1972.pdf">Effects of wildfire on elk and deer use of a Ponderosa Pine forest</a> (PDF - 680 KB). 1972. (<strong>RN-INT-226</strong>)</li>
				<li>Kuennen, Louis; Garry Edson and Timothy V. Tolle. <a href="../../documents/RPs/Kuennen_etal_1979.pdf">Soil compaction due to timber harvest activities (PDF - 187 KB)</a>. 1979. Published in the USDA Forest Service Northern Region, Soil Air and Water Notes, May 1979 (79-3). <br /><span class="dateupdated">[publication added 02/27/2009]</span></li>
      			<li>Luce, Charles H. <a href="https://www.fs.fed.us/rm/boise/publications/watershed/rmrs_1997_lucec001.pdf">Effectiveness of road ripping in restoring infiltration capacity of forest roads</a>. 1997. Restoration ecology 5(3): 265&#8211;270. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
		      	<li>Martin, Robert E. 1988. Interaction among fire, arthropods, and diseases in a healthy forest. In: Healthy Forests, Healthy World: Proceedings of the 1988 Society of American Foresters National Convention, Rochester, N.Y., Oct. 16&#8211;19, 1988. <a href="https://www.safnet.org/">Society of American Foresters</a>, Bethesda, MD. 87&#8211;91.</li>  
		      	<li>Martin, Robert E. 1981. Prescribed Burning Techniques to Maintain or Improve Soil Productivity. In: Reforestation of Skeletal Soils, Proceedings of a Workshop, November 17&#8211;19, 1981, Medford, Oregon. S.D. Hobbs and O.T. Helgerson, eds. Forest Research Laboratory, <a href="https://oregonstate.edu/">Oregon State University</a>, Corvallis, OR. pp 66&#8211;70.</li>  
				<li>McDaniel, P. A.; K. E. Houston; M. A. Fosberg; A. L. Falen. <a href="../../documents/RPs/McDaniel_etal_1994.php">Soil-Plant Community Relationships in the Selkirk Mountains of Northern Idaho</a> (HTML). Published in Northwest Science, Vol. 68, No. 1, 1994.</li>
      			<li>McNabb, D. H.; H. A. Froehlich. <a href="../../documents/RPs/McNabb_Froehlich_1983.pdf">Conceptual Model for Predicting  Forest Productivity Losses from Soil Compaction</a> (PDF - 568 KB). 1983.</li>
      			<li>McRae, D. J.; L. C. Duchesne; B. Freedman; T. J. Lynham and S. Woodley. <a href="https://www.ingentaconnect.com/content/nrc/er/2001/00000009/00000004/art00001;jsessionid=5p4bc61334i0s.alice?format=print">Comparisons between wildfire and forest harvesting and their implications in forest management</a>. 2001. Environ. Rev. 9: 223&#8211;260. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Meurisse, R. T. <a href="../../documents/RPs/Meurisse_1996.pdf">Soil Quality and Health-some Applications to Forest Ecosystems</a> (PDF - 1.3 MB).</li>
      			<li>Meurisse, R. T. <a href="../../documents/RPs/Meurisse_1995.pdf">Soil: The Foundation of the Ecosystem; Effects of Management Activities on Forest Soils: Can We Manage Better?</a> (PDF - 512 KB).</li>
      			<li>Miller, Dick and Harry Anderson. <a href="https://www.fs.fed.us/pnw/olympia/silv/publications/no468_r-miller-soilcompaction_cce.pdf">Soil compaction: Concerns, claims, and evidence</a>. 2002. Washington State University Cooperative Extension. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Miller, R. E.; W. Scott; J. W. Hazard. <a href="../../documents/RPs/Miller_etal_1996.pdf">Soil compaction and conifer growth after tractor yarding at three coastal Washington locations</a> (PDF - 1.4 MB).</li>
      			<li>Moghaddas, Emily E. Y. and Scott L. Stephens. <a href="https://www.cnr.berkeley.edu/stephens-lab/Publications/Moghaddas%20Stephens%20Soil%20Mech%20FFS%20FEM%204-08.pdf">Mechanized fuel treatment effects on soil compaction in Sierra Nevada mixed-conifer stands</a>. 2008. For. Ecol. Mgmt. 255: 3098&#8211;3106. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Monleon, Vicente J. and Kermit Cromack, Jr. <a href="https://www.ingentaconnect.com/content/els/03781127/1996/00000081/00000001/art03658;jsessionid=8njgb9t6llsc0.alexandra?format=print">Long-term effects of prescribed underburning on litter decomposition and nutrient release in ponderosa pine stands in central Oregon</a>. 1996. For. Ecol. Mgmt. 81: 143&#8211;152. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Monleon, Vicente J.; Kermit Cromack, Jr. and Johanna D. Landsberg. <a href="https://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=27&year=&issue=&msno=x96-184&calyLang=eng">Short- and long-term effects of prescribed underburning on nitrogen availability in ponderosa pine stands in central Oregon</a>. 1997. Can. J. For. Res. 27: 369&#8211;378. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
				<li>National Council for Air and Stream Improvement, Inc. (NCASI). 2004. Effects of Heavy Equipment on Physical Properties of Soils and on Long-Term Productivity: A Review of Literature and Current Research.  Technical Bulletin No. 0887.  Research Triangle Park, NC: National Council for Air and Stream Improvement, Inc. (PDF located at the National Council for Air and Stream Improvement's web site: <a href="https://www.ncasi.org/publications/Detail.aspx?id=2649" title="Effects of Heavy Equipment on Physical Properties of Soils and on Long-Term Productivity: A Review of Literature and Current Research">https://www.ncasi.org/publications/Detail.aspx?id=2649</a>)</li>
      			<li>Norberg, G.; A. Jaderlund; O. Zackrisson; T. Nordfjell; D. A. Wardle; M.-C. Nilsson and A. Dolling. <a href="https://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=27&year=&issue=&msno=x97-183&calyLang=eng">Vegetation control by steam treatment in boreal forests: a comparison with burning and soil scarification</a>. 1997. Can. J. For. Res. 27: 2026&#8211;2033. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
				<li>Norum, Rodney A. 1976. <a href="../../documents/RPs/Norum_USGovtPub_1976.pdf">Fire Intensity-Fuel Reduction Relationships Associated With Understory Burning in Larch/Douglas-Fir Stands</a>. (PDF - 456 KB) In: Tall Timbers fire ecology conference No. 14; symposium proceedings; 1974 October 8&#8211;10; Missoula, MT. Tallahassee, FL: Tall Timbers Research Station. U.S. Government Printing Office. p. 559&#8211;572.</li>
      			<li>Norum, Rodney A. <a href="../../documents/RNs/Norum_RN-INT-229_1977.pdf">Preliminary guidelines for prescribed burning under standing timber in western larch/Douglas-fir forests</a> (PDF - 977 KB). 1977. (<strong>RN-INT-229</strong>)</li>
      			<li>Neal, J. L.; Wright, E. and W. B. Bollen. Burning Douglas-fir slash: Physical, chemical, and microbial effects in the soil. 1965. <a href="https://oregonstate.edu/">Oregon State University</a>.</li>
      			<li>Ouden, Jan den and Danielle Vogels. <a href="https://cat.inist.fr/?aModele=afficheN&cpsidt=2203920">Mechanical resistance by an ectorganic soil layer on root development of seedling Pinus sylvestris</a>. 1997. Plant and Soil 197: 209&#8211;217. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Page-Dumroese, Deborah. S. Is Woody Residue Part of Your Plan for Sustainable Forestry? <a href="https://www.oswa.org/NWW-Summer2010.pdf">Northwest Woodlands, Summer 2010.</a> (article also available at <a href="https://www.treesearch.fs.fed.us/pubs/35753">https://www.treesearch.fs.fed.us/pubs/35753</a>)  <br /><span class="dateupdated">[Document added to SoLo on 07/30/2010]</span></li>
      			<li>Page-Dumroese, D. S. <a href="../../documents/RPs/Page-Dumroese_1993.pdf">Susceptibility of Volcanic Ash-Influenced Soil in Northern Idaho to Mechanical Compaction</a> (PDF - 632 KB). 1993.</li>
      			<li>Page-Dumroese, Deborah S.; R. Kasten Dumroese; Martin F. Jurgensen; Ann Abbott; Jennifer J. Hensiek. <a href="https://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4TCGM3W-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=c98522d91191a4c2a13ce28ba1ed82f5">Effect of nursery storage and site preparation techniques on field performance of high-elevation Pinus contorta seedlings</a>. 2008. For. Ecol. Mgmt. 256: 2065&#8211;2072. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Page-Dumroese, D. S. and M. F. Jurgensen. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?cjfr_x06-125_36_ns_nf">Soil carbon and nitrogen pools in mid- to late- successional forest stands of the northwestern United States: potential impact of fire</a>. Can. J. For. Res. 2006.</li>
      			<li>Page-Dumroese, Deborah S.; Jurgensen, Martin; Terry, Thomas  2010. <a href="https://www.treesearch.fs.fed.us/pubs/34428">Maintaining soil productivity during forest or biomass-to-energy thinning harvests in the western United States</a>. Western Journal of Applied Forestry. 25(1): 5&#8211;11. <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
      			<li>Page-Dumroese, D. S.; A. E. Harvey; M. F. Jurgensen and M. P. Amaranthus. Impacts of soil compaction and tree stump removal on soil properties and outplanted seedlings in northern Idaho, USA. Can. J. Soil Sci. (abstract available at <a href="https://pubs.nrc-cnrc.gc.ca/aic-journals/feb98ab.html">https://pubs.nrc-cnrc.gc.ca/aic-journals/feb98ab.html</a>). 1998.</li>
      			<li>Page-Dumroese, Deborah S., Alan E. Harvey, Martin F. Jurgensen and Michael J. Larsen. Ponderosa Pine Seedling Response to Planting-site Soil Fumigation and Fungicide Application. 1996. <a href="https://www.vetmed.wsu.edu/org_NWS/Journal.htm">Northwest Science</a>. 70(2): 139&#8211;146.</li>
      			<li>Page-Dumroese, D. S.; M. F. Jurgensen and T. Terry. <a href="https://www.ingentaconnect.com/content/saf/wjaf/2010/00000025/00000001/art00002" title="Paper available at IngentaConnect">Maintaining soil productivity during forest or biomas-to-energy thinning harvests in the western United States</a>. Western Journal of Applied Forestry. 2010. 25(1): 5&#8211;11. <br /><span class="dateupdated">[link to publication added 03/09/2010]</span></li>
      			<li>Page-Dumroese, Deborah S.; Martin F. Jurgensen; Allan E. Tiarks; Felix Ponder, Jr.; Felipe G. Sanchez; Robert L. Fleming, J.; Marty Kranabetter, Robert F. Powers; Douglas M. Stone; John D. Elioff and D. Andrew Scott. <a href="https://www.treesearch.fs.fed.us/pubs/22171">Soil physical property changes at the North American Long-Term Soil Productivity study sites: 1 and 5 years after compaction</a>. Can. J. For. Res. 2006. 36(3): 551&#8211;564.</li>
      			<li>Page-Dumroese, Deborah S.; H. Loewenstein, R. T. Graham and A. E. Harvey. <a href="https://soil.scijournals.org/cgi/content/abstract/54/1/229">Soil source, seed source, and organic-matter content effects on Douglas-fir seedling growth</a>. 1990. Soil Science Society of America Journal 54(1): 229&#8211;233. <br /><span class="dateupdated">[publication added 02/20/2009]</span></li>
      			<li>Powers, Robert F. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?cjfr_x05-279_36_ns_nf_cjfr3-06">Long-Term Soil Productivity: genesis of the concept and principles behind the program</a>. Can. J. For. Res. 2006. 36(3): 519&#8211;528.</li>
      			<li><a href="../../documents/MISC/rangeland_health_tables.pdf">Rangeland Health Criteria Tables</a> (PDF - 76 KB) - applies to eastern Montana forests that contain open rangeland</li>
               	<li>Roberts, W. B. 1965. Soil temperatures under a pile of burning logs. Aust. For. Res. 1?: 21&#8211;25.</li>
               	<li>Russell, K. W.; W. G. Thies; D. L. Campbell, R. I. Gara and W. R. Littke. <a href="https://www.cfr.washington.edu/news_pubs/Pubs/index.htm">Effects of slash burning on forest damage from animals, insects, disease and adverse environment.</a> 1989.</li>
      			<li>Sanchez, Felipe G.; D. Andrew Scott and Kim H. Ludovici. <a href="https://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4JMM5P8-1&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=6caf94e1b1b8dc389396dd34e83e1009">Negligible effects of severe organic matter removal and soil compaction on loblolly pine growth over 100 years</a>. 2006. For. Ecol. Mgmt. 227: 145&#8211;154.<br />
      			<span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Sanchez, Felipe G.; Allan E. Tiarks; J. Marty Kranabetter; Deborah S. Page-Dumroese; Robert F. Powers; Paul T. Sanborn and William K. Chapman. Effects of organic matter removal and soil compaction on fifth-year mineral soil carbon and nitrogen contents for sites across the United States and Canada. Can. J. For. Res. (abstract and full text available at <a href="https://www.treesearch.fs.fed.us/pubs/22654">https://www.treesearch.fs.fed.us/pubs/22654</a>). 2006. 36(3): 565&#8211;576.</li>
      			<li>Schadt, Christopher W.; Andrew P. Martin; David A. Lipson and Steven K. Schmidt. <a href="https://www.sciencemag.org/cgi/content/abstract/sci;301/5638/1359?maxtoshow=&HITS=10&hits=10&RESULTFORMAT=&andorexacttitleabs=and&andorexactfulltext=and&searchid=1&FIRSTINDEX=0&volume=301&firstpage=1359&resourcetype=HWCIT">Seasonal dynamics of previously unknown fungal lineages in tundra soils</a>. 2003. Science 301: 1359&#8211;1361. <br />
      			  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      			<li>Schoennagel, Tania; Thomas T. Veblen and William H. Romme. The interaction of fire, fuels, and climate across Rocky Mountain forests. 2004. <a href="https://www.aibs.org/bioscience/">BioScience</a> 54(7): 661&#8211;676. <br />
      			  <span class="dateupdated">[link to journal added 02/13/2009]</span></li>
      			<li>Sharrow, S. <a href="../../documents/RPs/sharrow_comp-graz_2003.php">Soil Compaction During Forest Grazing</a> (HTML). 2003.</li>
      			<li>Shearer, Raymond C. <a href="../../documents/RPs/Shearer_RP-INT-167_1975.pdf">Seedbed characteristics in western larch forests after prescribed burning</a> (PDF - 1.25 MB). 1975. (<strong>RP-INT-167</strong>)</li>
      			<li>Steele, Robert W. <a href="../../documents/RNs/Steele_RN-INT-293_1980.pdf">Postharvest residue burning under alternative silvicultural practices</a> (PDF - 346 KB). 1980. (<strong>RN-INT-293</strong>)</li>
            	<li>Tarrant, R. F. <a href="https://www.ingentaconnect.com/content/saf/fs/1956/00000002/00000001/art00006">Effect of slash burning on some physical soil properties.</a> 1956.</li>
				<li>Thies, Walter G. 1990. Effects of prescribed fire on diseases of conifers. In: Natural and Prescribed Fire in Pacific Northwest Forests. John D. Walstad, Steven R. Radosevich and David V. Sandberg, edit. <a href="https://oregonstate.edu/dept/press//">Oregon State University Press</a>, Corvallis, OR p. 117&#8211;121</li>
              	<li>Thomson, A. J. <a href="https://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?calyLang=eng&journal=cjfr&volume=16&year=0&issue=2&msno=x86-048">Trend surface analysis of spatial patterns of tree size, microsite effects, and competitive stress.</a> 1986.</li>
      			<li>Wennstrom, Ulfstand; Urban Bergsten and Jan-Erik Nilsson. <a href="https://cat.inist.fr/?aModele=afficheN&cpsidt=1359889">Mechanized microsite preparation and direct seedling of Pinus sylvestris in boreal forests - a way to create desired spacing at low cost</a>. 1999. New Forests 18: 179&#8211;198. <br />
      			<span class="dateupdated">[link to document added 02/13/2009]</span></li>
           		<li>Widden, P. and D. Parkinson. The effects of a forest fire on soil microfungi. 1974. <a href="https://www.elsevier.com/wps/find/journaldescription.cws_home/332/description#description">Soil Biology and Biochemistry</a> 7: 125&#8211;138.</li>
      			<li>Wilson, S. D. and H. R. Kleb. 1996. The influence of prairie and forest vegetation on soil moisture and available nitrogen. <a href="https://www.nd.edu/~ammidnat/index.htm">The American Midland Naturalist</a>. 136: 222&#8211;231.</li>
      			<li>Wright, E. and R. F. Tarrant. 1958. <a href="https://treesearch.fs.fed.us/pubs/25808">Occurrence of mycorrhizae after logging and slash burning in the Douglas-fir forest type</a>.</li>
      			<li>Zlatnik, E. J.;  T. H. DeLuca; K. S. Milner and D. F. Potts. 1999. <a href="https://saf.publisher.ingentaconnect.com/content/saf/wjaf/1999/00000014/00000001/art00009">Site Productivity and Soil Conditions on Terraced Ponderosa Pine Sites in Western Montana</a>. Western Journal of Applied Forestry. 14(1): 35&#8211;40.</li>
				</ul>
			<h3 class="subsection">Other Related Publications<a name="researchpubs-related"></a></h3>
				<ul class="researchpapers">
      				<li>Fire Effects Information System (FEIS) located at <a href="https://www.fs.fed.us/database/feis/">https://www.fs.fed.us/database/feis/</a>. (FEIS summarizes and synthesizes research about living organisms in the United States&#8212;their biology, ecology, and relationship to fire.)</li>
		      		<li>Hungry Horse News articles - September 20, 1974, Columbia Falls, Montana: <a href="../../documents/MISC/HungryHorseNews_1974-09-20_01.pdf">Forest Research Study Centers on Desert Mountain (page 1 - 866 KB)</a>, <a href="../../documents/MISC/HungryHorseNews_1974-09-20_02.pdf">Forest Research Study Centers on Desert Mountain (page 2 - 1.86 MB)</a> and <a href="../../documents/MISC/HungryHorseNews_1974-09-20_03.pdf">Skyline Logging on Desert Mountain  (page 3 - 2.78 MB)</a>. (articles posted with permission of the <a href="https://www.hungryhorsenews.com/">Hungry Horse News</a>, Columbia Falls, MT) <br />
					<li>The Sunday Missoulian article - <a href="../../documents/MISC/documents/MISC/TheSundayMissoulian_1975-09-14.pdf">Yes Folks, That Was a Forest Fire</a>. September 14, 1975. <br /><span class="dateupdated">[publication added 05/19/2009]</span></li>
				</ul>

				<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
    	
				<h2 class="section">GRADUATE THESES<a name="gradtheses">&nbsp;</a></h2>
				<ul class="researchpapers">
					<li>Collins, Harold P.<a href="../../documents/GTs/Thesis_Collins_HaroldP.pdf">&#8220;Effects of Mechanical Site Preparation on Selected Physical Properties of Four Volcanic Ash Influenced Forest Soils in Northern Idaho.&#8221; (PDF file - 2.8 MB)</a> Unpublished masters thesis, University of Idaho, 1983.</li>
					<li>Han, Sang-Kyun. <a href="../../documents/GTs/Thesis_Sang-Kyun_Han.doc">&#8220;Impacts on Soils from Cut-To-Length and Whole Tree Harvesting.&#8221; (Microsoft Word Document - 1.6 MB)</a> Diss. University of Idaho, 2006.</li>
					<li>McElligott, Kristin M. <a href="../../documents/GTs/McElligott-Kristin_Thesis.pdf">&#8220;Biochar Amendments to Forest Soils: Effects on Soil Properties and Tree Growth.&#8221; (PDF file - 545 KB)</a> Unpublished masters thesis, University of Idaho, 2011.<br /><span class="dateupdated">[document added 05/23/2011]</span></li>
				</ul>
				<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
		
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>