#!/usr/bin/perl
#!C:\Perl\bin\perl.exe T-w
#use strict;
use CGI ':standard';

##########################################
# code name: whrm                        #
##########################################            

$debug=0;
$hdebug=0;

$version = '2005.02.02';

print "Content-type: text/html\n\n";
my @names;
my @values;

######
  if ($hdebug) {
    foreach my $name (param () ) {
      my @values= param ($name);
      print "<p><b>Key:</b>$name <b>
      Value(s) :</b>@values";
     }
  }

########################################
## HTML output of all the input        #
########################################

$tax_group=param('tax_group');
	$tax_group = 'Forest Carnivores' if ($tax_group eq '');
$taxgroup=lc($tax_group);
$taxgroup=~s/ //g;

$species=param('species');
	$species = 'Wolverine / Gulo gulo' if ($species eq '');
$action=param('Model');
	$action = 'Display Habitat Associations' if ($action eq '');
###$location=param('location');
###$habitattype=param('habitat_type');
###$spatialscale=param('spatial_scale'); 
###$treatment=param('treatment'); 

###if($treatment==0){$ptreatment="Thin and Pile";}
###elsif($treatment==1){$ptreatment="Thin and Broadcast Burn(moderate burn conditions)";}
###elsif($treatment==2){$ptreatment="Thin and Broadcast Burn(severe burn conditions)";}
###elsif($treatment==3){$ptreatment="No Thin and Broadcast Burn(moderate burn conditions)";}
###else{$ptreatment="No Thin and Wildfire ";}

###$area=param('area'); 
###$temposcale=param('tempo_scale');

if($debug)
{
print"<p>tax_group is $tax_group";
print"<p>taxgroup is $taxgroup";
print"<p>species is $species";
print"<p>action is $action";
###print"<p>location is $location";
###print"<p>habitattype is $habitattype";
###print"<p>spatialscale is $spatialscale";
###print"<p>treatment is $treatment";
###print"<p>area is $area";
###print"<p>temposcale is $temposcale";
}

######################################
## Habitat Features Vector   
##################################

@habitatfeatures=('Bare Mineral Soil Exposure','Duff Cover', 'Grass Cover','Forb/Herbaceous Cover','Shrub Cover (size classes not specified)',
'Shrub Cover 0-18" height','Shrub Cover 18+" height','Litter Cover', 'Down Wood (size classes not specified)','Down Wood 0-3" ',
'Down Wood 4-6" ','Down Wood 7-12"', 'Down Wood >12"', 'Snags (size classes not specified)','Snags 0-4.9" dbh','Snags 5-9" dbh', 
'Snags 10-19" dbh', 'Snags 20-29" dbh', 'Snags 30+" dbh', 'Crown Base Height','Tree Canopy Cover', 
'Trees (all species, size classes not specified)','Trees (all species) 0-4.9" dbh', 'Trees (all species) 5-9" dbh',  
'Trees (all species) 10-19" dbh',  'Trees (all species) 20-29" dbh',  'Trees (all species) 30+" dbh',  
'PP Trees (size classes not specified)','PP Trees 0-4.9" dbh', 'PP Trees 5-9" dbh',  'PP Trees 10-19" dbh',  'PP Trees 20-29" dbh',  
'PP Trees 30+" dbh',  'DF Trees (size classes not specified)','DF Trees 0-4.9" dbh', 'DF Trees 5-9" dbh',  'DF Trees 10-19" dbh',  
'DF Trees 20-29" dbh',  'DF Trees 30+" dbh',  'LP Trees (size classes not specified)','LP Trees 0-4.9" dbh', 'LP Trees 5-9" dbh',  
'LP Trees 10-19" dbh',  'LP Trees 20-29" dbh',  'LP Trees 30+" dbh',  'Aspen Trees (size classes not specified)','Aspen Trees 0-4.9" dbh', 
'Aspen Trees 5-9" dbh',  'Aspen Trees 10-19" dbh',  'Aspen Trees 20+" dbh',  'Other Trees (size classes not specified)',
'Other Trees 0-4.9" dbh', 'Other Trees 5-9" dbh',  'Other Trees 10-19" dbh',  'Other Trees 20-29" dbh',  'Other Trees 30+" dbh'
);

##############################
# extraction of the file name
###############################
@name1=split/\//,lc($species);
@name2=split/ /,$name1[0];
$filename=join("",@name2);
$filename=~s/'//g;
$filename=~s/-//g;

if($debug){print"<p>filename is: $filename";}

###################################
##writing files with information
################################

#$workingpath = "c:\\Inetpub\\Scripts\\fuels\\whrm\\";
#open (work_file, ">".$workingpath ."working.txt")|| Error('open','file');
#print work_file "#this files is generated by wildlifem.pl
#taxgroup\n$taxgroup
#species\n$species
#filename\n$filename
#";
#close (work_file);
#########################################
## uploading all information about the species
############################

$spefilename = $filename .".txt";
$spepath = "c:\\Inetpub\\Scripts\\fuels\\whrm\\species\\".$taxgroup."\\";
$spepath = "species/".$taxgroup."/";	# 2005.02.01 DEH
($comname,$sciname) = split '/', $species;

if($debug)
{
print "<p>spefilename is $spefilename";
print "<p>spepath is $spepath";
}

##################starting extraction of habitat features
if($action=~/Display/)
{
#####start if for rank 
####read rank

open (rank_file, $spepath .$spefilename)|| die("Error: files unopened!\n");
while(<rank_file>)
{if($_=~/Rank/)
	{$rank=<rank_file>}
}
close (rank_file);

if($debug)
{
print "<p>the rank in the file is: $rank\n";
}

###########rank equal 1

if ($rank==1) {

   head_html();

  print <<"endrank1";
       <h3>        <b>Habitat Associations for<br>         $comname (<i>$sciname</i>)</b> </h3>
      <br>
      <b>
       <font color=red>Sorry!</font>
       Available data are insufficient to run the model on your selected species at this time.
       You may try selecting a different species with similar life history characteristics.
       To view general life history information for your selected species,
       please use the "View Background Information" button.
      </b>
      <br>
      <center>
       <!-- form method="post" name="wildlifem4" action="http://localhost/Scripts/fuels/whrm/whrm2.pl" -->
       <form method="post" name="wildlifem4" action="/cgi-bin/fuels/whrm/whrm2.pl">
        <input type="hidden" value="$taxgroup" name="taxgroup">
        <input type="hidden" value="$species" name="species">
        <input type="hidden" value="$filename" name="filename">
        <input type="submit" value="View Background Information"  NAME="literature">
       </form>
       <br><br>
       <hr>
endrank1

tail_html('rank 1');

  }
  else {

open (spe_file, $spepath .$spefilename)|| Error('open','file');;
while(<spe_file>)
{
	if($_=~/Literature/){close (spe_file);}
	if($_=~/Nestsite/)
	{$_=<spe_file>;
	@row=split(/:/,$_);
	$nestrow=(@row);
		for($i=0; $i<=(@row-1);$i++)
		{($nestfeacode[$i],$nestdir[$i])=split(/,/,$row[$i],2);
		 if($debug){print"<p>nestcode is $nestfeacode[$i] and nestdir is $nestdir[$i] ";}}
	}
###	if($_=~/Mates/)
###	{$_=<spe_file>;
###	@row=split(/:/,$_);
###	$matesrow=(@row);
###		for($i=0; $i<=(@row-1);$i++)
###		{($matesfeacode[$i],$matesdir[$i])=split(/,/,$row[$i],2);
###		 if($debug){print"<p>matescode is $matesfeacode[$i] and nestdir is $matesdir[$i] ";}}
###	}
	if($_=~/Foraging Habitat/)
	{$_=<spe_file>;
	@row=split(/:/,$_);
	$fhabirow=(@row);
		for($i=0; $i<=(@row-1);$i++)
		{($fhabifeacode[$i],$fhabidir[$i])=split(/,/,$row[$i],2);
		 if($debug){print"<p>fhabicode is $fhabifeacode[$i] and fhabidir is $fhabidir[$i] ";}}
	}
	if($_=~/Forage\/Prey Availability/)
	{$_=<spe_file>;
	@row=split(/:/,$_);
	$preavarow=(@row);
		for($i=0; $i<=(@row-1);$i++)
		{($preavafeacode[$i],$preavadir[$i])=split(/,/,$row[$i],2);
		 if($debug){print"<p>preavacode is $preavafeacode[$i] and preavadir is $preavadir[$i] ";}}
	}
###	if($_=~/Density of Predator/)
###	{$_=<spe_file>;
###	@row=split(/:/,$_);
###	$deprerow=(@row);
###		for($i=0; $i<=(@row-1);$i++)
###		{($deprefeacode[$i],$depredir[$i])=split(/,/,$row[$i],2);
###		 if($debug){print"<p>deprecode is $deprefeacode[$i] and depredir is $depredir[$i] ";}}
###	}
	if($_=~/Predator Avoidance/)
	{$_=<spe_file>;
	@row=split(/:/,$_);
	$avoprerow=(@row);
		for($i=0; $i<=(@row-1);$i++)
		{($avoprefeacode[$i],$avopredir[$i])=split(/,/,$row[$i],2);
		 if($debug){print"<p>avoprecode is $avoprefeacode[$i] and avopredir is $avopredir[$i] ";}}
	}
	if($_=~/Refugia\/Shelter/)
	{$_=<spe_file>;
	@row=split(/:/,$_);
	$refsherow=(@row);
		for($i=0; $i<=(@row-1);$i++)
		{($refshefeacode[$i],$refshedir[$i])=split(/,/,$row[$i],2);
		 if($debug){print"<p>refshecode is $refshefeacode[$i] and refshedir is $refshedir[$i] ";}}
	}
###	if($_=~/Environmental Stress/)
###	{$_=<spe_file>;
###	@row=split(/:/,$_);
###	$envstrrow=(@row);
###		for($i=0; $i<=(@row-1);$i++)
###		{($envstrfeacode[$i],$envstrdir[$i])=split(/,/,$row[$i],2);
###		 if($debug){print"<p>envstrcode is $envstrfeacode[$i] and envstrdir is $envstrdir[$i] ";}}
###	}

}

close (spe_file);
if($debug)
{
print "<p>nestrow is :$nestrow";
###print "<p>matesrow is :$matesrow";
print "<p>fhabirow is :$fhabirow";
print "<p>preavarow is :$preavarow";
###print "<p>deprerow is :$deprerow";
print "<p>avoprerow is :$avoprerow";
print "<p>refsherow is :$refsherow";
###print "<p>envstrrow is :$envstrrow";
}
$rr1=$nestrow;
$rr2=$fhabirow+$preavarow;
$rr3=$avoprerow;
$rr4=$refsherow;

########################
##html blocks to repeat
####
$block[0]= "  <td>$habitatfeatures[$nestfeacode[0]]</td>
<td align=center><INPUT type=radio VALUE='-2' NAME='a'></td>
<td align=center><INPUT type=radio VALUE='-1' NAME='a'></td>
<td align=center><INPUT type=radio VALUE='0'  NAME='a' checked></td>
<td align=center><INPUT type=radio VALUE='1'  NAME='a'></td>
<td align=center><INPUT type=radio VALUE='2'  NAME='a'></td>
</tr>
";
$block[1]="
<tr>
<td>$habitatfeatures[$nestfeacode[1]]</td>
<td align=center><INPUT type=radio VALUE='-2' NAME=a></td>
<td align=center><INPUT type=radio VALUE='-1' NAME=a></td>
<td align=center><INPUT type=radio VALUE='0'  NAME=a checked></td>
<td align=center><INPUT type=radio VALUE='1'  NAME=a></td>
<td align=center><INPUT type=radio VALUE='2'  NAME=a></td>
</tr>
";
####end of blocks to repeat
#####

  head_html();

#print<<"end";
#<html>
# <head>
#  <title>Wildlife Habitat Response Model Output</title>
#   <script language="javascript">
#<!-- hide from old browsers...
#
# function popuphistory() {
#    url = '';
#    height=500;
#    width=660;
#    popupwindow = window.open(url,'popupwindow','toolbar=no,location=no,status=no,directories=no,menubar=no,scrollbars=yes,resizable=yes,width='+width+',height='+height);
#    popupwindow.document.writeln('<html>')
#    popupwindow.document.writeln(' <head>')
#    popupwindow.document.writeln('  <title>Wildlife Habitat Response Model Input version history</title>')
#    popupwindow.document.writeln(' </head>')
#    popupwindow.document.writeln(' <body bgcolor=white>')
#    popupwindow.document.writeln('  <font face="tahoma, arial, helvetica, sans serif">')
#    popupwindow.document.writeln('  <center>')
#    popupwindow.document.writeln('   <h3>Wildlife Habitat Response Model Input Version History</h3>')
#    popupwindow.document.writeln('   <p>')
#    popupwindow.document.writeln('   <table border=0 cellpadding=10>')
#    popupwindow.document.writeln('    <tr>')
#    popupwindow.document.writeln('     <th bgcolor=lightblue>Version</th>')
#    popupwindow.document.writeln('     <th bgcolor=lightblue>Comments</th>')
#    popupwindow.document.writeln('    </tr>')
#    popupwindow.document.writeln('    <tr>')
#    popupwindow.document.writeln('     <th valign=top bgcolor=lightblue>2004.09.24</th>')
#    popupwindow.document.writeln('     <td>Beta release for Boise presentation</td>')
#    popupwindow.document.writeln('    </tr>')
#    popupwindow.document.writeln('   </table>')
#    popupwindow.document.writeln('   <p>')
#    popupwindow.document.writeln('  </font>')
#    popupwindow.document.writeln('  </center>')
#    popupwindow.document.writeln(' </body>')
#    popupwindow.document.writeln('</html>')
#    popupwindow.document.close()
#    popupwindow.focus()
#  }
#
#
#// end of hiding -->
#  </script>
# </head>
# <body>
#  <font face="tahoma, arial, helvetica, sans serif">
#   <table align="center" width="100%" border="0">
#    <tr>
#     <td>
#      <img src="/fuels/whrm/images/borealtoad4_Pilliod.jpg" alt="Wildlife Habitat Response Model" align="left">
#     </td>
#     <td align="center"><hr>
#      <h2>Wildlife Habitat Response Matrix</h2>
#      <img src="/fswepp/images/underc.gif" border=0 width=532 height=34>
#      <hr>
#     </td>
#     <td>
#      <img src="/fuels/whrm/images/grayjay2_Pilliod.jpg" alt="Wildlife Habitat Response Model" align="right">
#     </td>
#    </tr>
#   </table>
#   <br>
#   <center>
#    <br><br>
#    Select the change in each habitat element based on expected results of the planned fuel treatment.<br>If a habitat element is repeated in more than one life history requirement category, <br>please make sure the selection is the same for each category.</p>
#    <br>
#    <!--<form method="post" name="wildlifem2" action="http://localhost/Scripts/fuels/whrm/whrm2.pl">-->
#    <form method="post" name="wildlifem2" action="/cgi-bin/fuels/whrm/whrm2.pl">
#     <table align="center" border="2">
#      <caption>
#       <font size="4">
#        <b>Habitat Associations for<br>
#         $comname (<i>$sciname</i>)
#        </b>
#       </font>
#      </caption>
#      <tr>
#       <th BGCOLOR="#006009">
#        <font color="#99ff00">Taxonomic group:</font>
#       </th>
#       <td>$tax_group</td>
#      </tr>
#      <tr>
#       <th BGCOLOR="#006009">
#	<font color="#99ff00">Species:</font>
#       </th>
#       <td>$species</td>
#      </tr>
#     </table>
#     <br>

   print "
       <h3><b>Habitat Associations for<br>$comname (<i>$sciname</i>)</b> </h3>
";
	if ($rank==2)	{
	print "
     <br>
     <b>
      <font color=red>Warning:</font>
      There are limited data available for this species at this time.
      If you proceed, please interpret output conservatively.
      You may also want to try selecting a different species with similar life history characteristics.
     </b>
     <br>
";
   }		# if ($rank==2)

##################
##form 2    ######
#####begining of form two
   print <<"fin";
     <table align="center" border="2" ID="Table1">
      <caption>
       <b>
        <font size="4"></font>
       </b>
      </caption>
      <tr>
       <th colspan="2" rowspan="2" bgcolor="#006009">
        <font color="#99ff00">Life History Requirements</font>
       </th>
       <th rowspan="2" bgcolor="#006009">
        <font color="#99ff00">Key Wildlife Habitat Elements</font>
       </th>
       <th colspan="7" bgcolor="#006009">
        <font color="#99ff00">Change in Habitat Elements</font>
       </th>
      </tr>
      <tr>
       <th bgcolor="#006009"><font color="#99ff00" size="2">Greater than<br>70% Decrease</font></th>
       <th bgcolor="#006009"><font color="#99ff00" size="2">41-70%<br>Decrease</font></th>
       <th bgcolor="#006009"><font color="#99ff00" size="2">11-40%<br>Decrease</font></th>
       <th bgcolor="#006009"><font color="#99ff00" size="2">No Change<br>(+/-10%)</font></th>
       <th bgcolor="#006009"><font color="#99ff00" size="2">11-40%<br>Increase</font></th>
       <th bgcolor="#006009"><font color="#99ff00" size="2">41-70%<br>Increase</font></th>
       <th bgcolor="#006009"><font color="#99ff00" size="2">Greater than<br>70% Increase</font></th>
      </tr>
      <tr>
       <th rowspan=$rr1 BGCOLOR="#006009"><font color="#99ff00">Reproduction</Font></th>
       <th rowspan=$nestrow BGCOLOR="#006009"><font color="#99ff00">Nest Sites,<br>Birthing Areas,<br>Breeding Sites</font></th>
fin
   for ($i=0; $i<=$nestrow-1;$i++) {
    if ($i==0) {
      if ($nestfeacode[$i]==-99) {
        print "       <td colspan=8 align=center>No Information Is Available</td>
      </tr>
";
      }
      else {
        print "       <td>$habitatfeatures[$nestfeacode[0]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='nestfea0'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='nestfea0'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='nestfea0'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='nestfea0' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='nestfea0'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='nestfea0'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='nestfea0'></td>
      </tr>
";
      }		# else of if ($nestfeacode[$i]==-99)
    }    	# if ($i==0)
    else {      # if ($i==0)
      print "      <tr>
       <td>$habitatfeatures[$nestfeacode[$i]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='nestfea$i'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='nestfea$i'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='nestfea$i'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='nestfea$i' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='nestfea$i'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='nestfea$i'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='nestfea$i'></td>
      </tr>
";
    }		# else of if ($i==0)
  }		# if ($i==0)

###print "<tr>
###	<th rowspan=$matesrow BGCOLOR=\"#006009\">
###	<Font color=\"#99ff00\">Mates</Font></th>";

###for($i=0; $i<=$matesrow-1;$i++)
###{
###	if($i==0){print "<td>$habitatfeatures[$matesfeacode[0]]</td>
###			<td align=center><INPUT type=radio  VALUE=-2 NAME=\"matesfea0\"></td>
###			<td align=center><INPUT type=radio  VALUE=-1 NAME=matesfea0></td>
###			<td align=center><INPUT type=radio VALUE=0 NAME=matesfea0 checked></td>
###			<td align=center><INPUT type=radio  VALUE=1 NAME=matesfea0></td>
###			<td align=center><INPUT type=radio  VALUE=2 NAME=matesfea0></td>
###			</tr>";}
###	else{print "<tr>
###		<td>$habitatfeatures[$matesfeacode[$i]]</td>
###		<td align=center><INPUT type=radio  VALUE=-2 NAME=\"matesfea$i\"></td>
###		<td align=center><INPUT type=radio  VALUE=-1 NAME=\"matesfea$i\"></td>
###		<td align=center><INPUT type=radio VALUE=0 NAME=\"matesfea$i\" checked></td>
###		<td align=center><INPUT type=radio  VALUE=1 NAME=\"matesfea$i\"></td>
###		<td align=center><INPUT type=radio  VALUE=2 NAME=\"matesfea$i\"></td>
###		</tr>";}
###}

print "      <tr>
       <th rowspan='$rr2' BGCOLOR='#006009'><font color='#99ff00'>Food Resources</font></th>
       <th rowspan='$fhabirow' BGCOLOR='#006009'><font color='#99ff00'>Foraging Habitat</font></th>
";
  for ($i=0;$i<=$fhabirow-1;$i++) {
    if ($i==0) {
      if ($fhabifeacode[$i]==-99) {
        print "       <td colspan=8 align=center>No Information Is Available</td>
      </tr>
";
      }		# if ($fhabifeacode[$i]==-99)
      else {
        print "       <td>$habitatfeatures[$fhabifeacode[0]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='fhabifea0'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='fhabifea0'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='fhabifea0'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='fhabifea0' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='fhabifea0'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='fhabifea0'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='fhabifea0'></td>
      </tr>
";
      }         # if ($fhabifeacode[$i]==-99)
    }		# if ($i==0)
    else { 
      print "      <tr>
       <td>$habitatfeatures[$fhabifeacode[$i]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='fhabifea$i'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='fhabifea$i'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='fhabifea$i'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='fhabifea$i' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='fhabifea$i'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='fhabifea$i'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='fhabifea$i'></td>
      </tr>
";
    }		# else of if ($i==0)
  }		# for ($i=0;$i<=$fhabirow-1;$i++)
  print "      <tr>
       <th rowspan='$preavarow' BGCOLOR='#006009'><font color='#99ff00'>Forage,<br>Prey Habitat</font></th>
";

  for ($i=0;$i<=$preavarow-1;$i++) {
    if ($i==0) {
      if ($preavafeacode[$i]==-99) {
        print "       <td colspan=8 align=center>No Information Is Available</td>
      </tr>
";
      }		# if ($preavafeacode[$i]==-99)
      else {
        print "       <td>$habitatfeatures[$preavafeacode[0]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='preavafea0'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='preavafea0'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='preavafea0'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='preavafea0' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='preavafea0'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='preavafea0'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='preavafea0'></td>
      </tr>
";
      }		# else of if ($preavafeacode[$i]==-99)
    }	# if ($i==0)
    else {
      print "      <tr>
       <td>$habitatfeatures[$preavafeacode[$i]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='preavafea$i'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='preavafea$i'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='preavafea$i'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='preavafea$i' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='preavafea$i'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='preavafea$i'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='preavafea$i'></td>
      </tr>
";
    }	# else of if ($i==0)
  }	# for ($i=0;$i<=$preavarow-1;$i++)
  print "
      <tr>
       <th rowspan='$rr3' BGCOLOR='#006009'><font color='#99ff00'>Predators</font></th>
       <th rowspan='$avoprerow' BGCOLOR='#006009'><font color='#99ff00'>Predator Avoidance,<br>Shelter from Predators</font></th>
";

###for($i=0; $i<=$deprerow-1;$i++)
###{
###	if($i==0){print "<td>$habitatfeatures[$deprefeacode[0]]</td>
###			<td align=center><INPUT type=radio  VALUE=-2 NAME=\"deprefea0\"></td>
###			<td align=center><INPUT type=radio  VALUE=-1 NAME=deprefea0></td>
###			<td align=center><INPUT type=radio VALUE=0 NAME=deprefea0 checked></td>
###			<td align=center><INPUT type=radio  VALUE=1 NAME=deprefea0></td>
###			<td align=center><INPUT type=radio  VALUE=2 NAME=deprefea0></td>
###			</tr>";}
###	else{print "<tr>
###		<td>$habitatfeatures[$deprefeacode[$i]]</td>
###		<td align=center><INPUT type=radio  VALUE=-2 NAME=\"deprefea$i\"></td>
###		<td align=center><INPUT type=radio  VALUE=-1 NAME=\"deprefea$i\"></td>
###		<td align=center><INPUT type=radio VALUE=0 NAME=\"deprefea$i\" checked></td>
###		<td align=center><INPUT type=radio  VALUE=1 NAME=\"deprefea$i\"></td>
###		<td align=center><INPUT type=radio  VALUE=2 NAME=\"deprefea$i\"></td>
###		</tr>";}
###}
###print "<tr>
###	<th rowspan=$avoprerow BGCOLOR=\"#006009\">
###	<Font color=\"#99ff00\">Predator Avoidance</Font></th>";

  for ($i=0;$i<=$avoprerow-1;$i++) {
    if ($i==0) {
      if ($avoprefeacode[$i]==-99) {
        print "       <td colspan=8 align=center>No Information Is Available</td>
      </tr>
";
      	}	# if ($avoprefeacode[$i]==-99)
        else {
          print "       <td>$habitatfeatures[$avoprefeacode[0]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='avoprefea0'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='avoprefea0'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='avoprefea0'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='avoprefea0' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='avoprefea0'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='avoprefea0'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='avoprefea0'></td>
      </tr>
";
    }	# else of if ($avoprefeacode[$i]==-99)
  }	# if ($i==0)
  else {
    print "      <tr>
       <td>$habitatfeatures[$avoprefeacode[$i]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='avoprefea$i'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='avoprefea$i'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='avoprefea$i'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='avoprefea$i' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='avoprefea$i'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='avoprefea$i'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='avoprefea$i'></td>
      </tr>
";
    }	# else of if ($i==0)
  }	# for ()
  print "      <tr>
       <th rowspan='$rr4' BGCOLOR='#006009'><font color='#99ff00'>Hazards</font></th>
       <th rowspan='$refsherow' BGCOLOR='#006009'><font color='#99ff00'>Shelter from <br>Environmental Extremes</font></th>
";
  for ($i=0;$i<=$refsherow-1;$i++) {
    if ($i==0) {
      if ($refshefeacode[$i]==-99) {
        print "       <td colspan=8 align=center>No Information Is Available</td>
      </tr>
";
      }		# if ($refshefeacode[$i]==-99)
      else {
        print "       <td>$habitatfeatures[$refshefeacode[0]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='refshefea0'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='refshefea0'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='refshefea0'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='refshefea0' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='refshefea0'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='refshefea0'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='refshefea0'></td>
      </tr>
";
    }	# else of if ($refshefeacode[$i]==-99)
  }	# if ($i==0)
  else {
    print "      <tr>
       <td>$habitatfeatures[$refshefeacode[$i]]</td>
       <td align=center><INPUT type=radio VALUE='-3' NAME='refshefea$i'></td>
       <td align=center><INPUT type=radio VALUE='-2' NAME='refshefea$i'></td>
       <td align=center><INPUT type=radio VALUE='-1' NAME='refshefea$i'></td>
       <td align=center><INPUT type=radio VALUE='0' NAME='refshefea$i' checked></td>
       <td align=center><INPUT type=radio VALUE='1' NAME='refshefea$i'></td>
       <td align=center><INPUT type=radio VALUE='2' NAME='refshefea$i'></td>
       <td align=center><INPUT type=radio VALUE='3' NAME='refshefea$i'></td>
      </tr>
";
    }	# else of if ($i==0)
  }	# for ()

###print "<tr>
###	<th rowspan=$envstrrow BGCOLOR=\"#006009\">
###	<Font color=\"#99ff00\">Predator Avoidance</Font></th>";

###for($i=0; $i<=$envstrrow-1;$i++)
###{
###	if($i==0){print "<td>$habitatfeatures[$envstrfeacode[0]]</td>
###			<td align=center><INPUT type=radio  VALUE=-2 NAME=\"envstrfea0\"></td>
###			<td align=center><INPUT type=radio  VALUE=-1 NAME=envstrfea0></td>
###			<td align=center><INPUT type=radio VALUE=0 NAME=envstrfea0 checked></td>
###			<td align=center><INPUT type=radio  VALUE=1 NAME=envstrfea0></td>
###			<td align=center><INPUT type=radio  VALUE=2 NAME=envstrfea0></td>
###			</tr>";}
###	else{print "<tr>
###		<td>$habitatfeatures[$envstrfeacode[$i]]</td>
###		<td align=center><INPUT type=radio  VALUE=-2 NAME=\"envstrfea$i\"></td>
###		<td align=center><INPUT type=radio  VALUE=-1 NAME=\"envstrfea$i\"></td>
###		<td align=center><INPUT type=radio VALUE=0 NAME=\"envstrfea$i\" checked></td>
###		<td align=center><INPUT type=radio  VALUE=1 NAME=\"envstrfea$i\"></td>
###		<td align=center><INPUT type=radio  VALUE=2 NAME=\"envstrfea$i\"></td>
###		</tr>";}
###}

print <<"end1";
      </table>
      <br>
      <br>You may return to this page to examine a different fuel treatment alternative by using the back arrow or starting over.</p>
      <br>
      <form method="post" name="wildlifem4" action="/cgi-bin/fuels/whrm/whrm2.pl">
       <input type="hidden" value="$taxgroup" name="taxgroup">
       <input type="hidden" value="$tax_group" name="tax_group">
       <input type="hidden" value="$species" name="species">
       <input type="hidden" value="$filename" name="filename">
       <input type="submit" value="Run Wildlife Habitat Response Model"  NAME="matrix">
      </form>
     </center>
end1

  tail_html('rank >1');

#		<P>
#   <hr>
#    <table border=0>
#     <tr>
#      <td valign="top" bgcolor="lightgoldenrodyellow">
#       <font face="tahoma, arial, helvetica, sans serif" size=1>
#        The Wild Response Model: <b>WH</b><b>RM</b>
#       </font>
#      </td>
#      <td valign="top">
#       <a href="http://forest.moscowfsl.wsu.edu/fswepp/comments.html"><img src="/fswepp/images/epaemail.gif" align="right" border=0></a>
#      </td>
#     </tr>
#     <tr>
#      <td valign="top">
#       <font face="tahoma, arial, helvetica, sans serif" size=1>
#        Wildlife Habitat Response Model input interface v.
#        <a href="javascript:popuphistory()">$version</a>
#        (for review only) by
#        David Hall &amp; Elena Velasquez<br>
#	  Model Developed by: David Pilliod<br>
#        Team leader Elaine Kennedy Sutherland, USDA Forest Service, Rocky Mountain Research Station
#       </font>
#     </table>
#   </form>
# </body>
#</html>

### end of begining of form 2
    }			####end else for ranks
  }		####end if Display
  else {
    open (LITFILE, $spepath .$spefilename)|| die("Error: files unopened!\n");
      while (<LITFILE>) {
        if ($_=~/Literature/)	{@litreview=<LITFILE>;}
      }

    close (LITFILE);
    $test=int((@litreview-1)/2);
    if ($debug) {
      $sizelit=(@litreview);
      print "<p>literature $sizelit";
      print "<p>test is $test";
    }

#print<<"fin1";
#<html>
# <head>
#  <title>Wildlife Habitat Response Model Literature Review</title>
# </head>
# <body>
#  <font face="tahoma, arial, helvetica, sans serif">
#   <center>
#    <font size=5><b>Wildlife Habitat Response Model</b></font>
#     <br>
#     <img src="/fswepp/images/underc.gif" border=0 width=532 height=34>
#      <table align="center" border="2">
#       <caption>
#        <font size="4">
#         <b>
#          Species Information for<br>
#          $comname (<i>$sciname</i>)
#         </b>
#        </font>
#       </caption>
#fin1
   head_html();

   print "        <h3><b>Species Information for<br>$comname (<i>$sciname</i>)</b></h3>
      <table align='center' border='2'>
";

   for ($i=0;$i<=11;$i++) {
print "      <tr>
      <th colspan='2' bgcolor='#006009'><font size=3 color='#99ff00'>$litreview[(2*$i)]</font></th>
      <td>$litreview[(2*$i+1)]</td>
    </tr>
";
  }
  print "
       </table>
       <br>
       <font size=5><b>$litreview[24]</b></font>
       <br><br>
      </center>
";

  for ($i=25;$i<=(@litreview-1);$i++) {
    print"$litreview[$i]<br>";
  }

  tail_html('Literature');

}

sub head_html {

  print<<"end11";
<html>
 <head>
  <title>Wildlife Habitat Response Model Output</title>
   <script language="javascript">
    <!-- hide from old browsers...

 function popuphistory() {
    url = '';
    height=500;
    width=660;
    popupwindow = window.open(url,'popupwindow','toolbar=no,location=no,status=no,directories=no,menubar=no,scrollbars=yes,resizable=yes,width='+width+',height='+height);
    popupwindow.document.writeln('<html>')
    popupwindow.document.writeln(' <head>')
    popupwindow.document.writeln('  <title>Wildlife Habitat Response Model Input version history</title>')
    popupwindow.document.writeln(' </head>')
    popupwindow.document.writeln(' <body bgcolor=white>')
    popupwindow.document.writeln('  <font face="tahoma, arial, helvetica, sans serif">')
    popupwindow.document.writeln('  <center>')
    popupwindow.document.writeln('   <h3>Wildlife Response Model Input Version History</h3>')
    popupwindow.document.writeln('   <p>')
    popupwindow.document.writeln('   <table border=0 cellpadding=10>')
    popupwindow.document.writeln('    <tr>')
    popupwindow.document.writeln('     <th bgcolor=lightblue>Version</th>')
    popupwindow.document.writeln('     <th bgcolor=lightblue>Comments</th>')
    popupwindow.document.writeln('    </tr>')
    popupwindow.document.writeln('    <tr>')
    popupwindow.document.writeln('     <th valign=top bgcolor=lightblue>2004.09.24</th>')
    popupwindow.document.writeln('     <td>Beta release for Boise presentation</td>')
    popupwindow.document.writeln('    </tr>')
    popupwindow.document.writeln('   </table>')
    popupwindow.document.writeln('   <p>')
    popupwindow.document.writeln('  </font>')
    popupwindow.document.writeln('  </center>')
    popupwindow.document.writeln(' </body>')
    popupwindow.document.writeln('</html>')
    popupwindow.document.close()
    popupwindow.focus()
  }


   // end of hiding -->
  </script>
 </head>
 <body>
  <font face="tahoma, arial, helvetica, sans serif">
   <table align="center" width="100%" border="0">
    <tr>
     <!--<td><img src="http://localhost/fuels/whrm/images/borealtoad4_Pilliod.jpg" alt="Wildlife Habitat Response Model" align="left"></td>-->
     <td><img src="/fuels/whrm/images/borealtoad4_Pilliod.jpg"  alt="Wildlife Habitat Response Model" align="left"></td>
     <td align="center">
      <font face="tahoma, arial, helvetica, sans serif">
       <hr>
       <h2>Wildlife Habitat Response Model</h2>
       <hr>
      </font>
     </td>
     <!--<td><img src="http:/fuels/whrm/images/grayjay2_Pilliod.jpg" alt="Wildlife Habitat Response Model" align="right">-->
     <td>
      <img src="/fuels/whrm/images/grayjay2_Pilliod.jpg"  alt="Wildlife Habitat Response Model" align="right">
     </td>
    </tr>
   </table>
   <br>
   <center>
    <!-- form method="post" name="wildlifem2" action="http://localhost/Scripts/fuels/whrm/wildlifem2.pl"-->
    <!-- form method="post" name="wildlifem2" action="/cgi-bin/fuels/whrm/whrm2.pl" -->

end11

#     <table align="center" border="2">
#      <caption>
#       <font size="4">
#        <b>Habitat Associations for<br>
#         $comname (<i>$sciname</i>)
#        </b>
#       </font>
#      </caption>
#      <tr>
#       <th BGCOLOR="#006009">
#        <font color="#99ff00">Taxonomic group:</font>
#       </th>
#       <td>$tax_group</td>
#      </tr>
#      <tr>
#       <th BGCOLOR="#006009">
#        <font color="#99ff00">Species:</font>
#       </th>
#       <td >$species</td>
#      </tr>
#     </table>
#     <br>

}

sub tail_html {

print '
     <table border=0 width=100%>
      <tr>
       <td valign="top" bgcolor="lightgoldenrodyellow">
       <font face="tahoma, arial, helvetica, sans serif" size=1>
        The Wildlife Habitat Response Model (<b>WHRM</b>)  version
        <a href="javascript:popuphistory()">',$version,'</a> [',$_,'] (for review only)<br>
        Interface developed by David Hall &amp; Elena Velasquez<br>
        Model developed by David Pilliod<br>
        Team leader Elaine Kennedy Sutherland, USDA Forest Service, Rocky Mountain Research Station<br>
        forest.moscowfsl.wsu.edu/fuels/
       </font>
      </td>
      <td valign="top">
       <a href="http://forest.moscowfsl.wsu.edu/fswepp/comments.html"><img src="/fswepp/images/epaemail.gif" align="right" border=0></a>
      </td>
     </tr>
    </table>
   </center>
  </font>
 </body>
</html>
';
}
