<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Pinus ponderosa series</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Central Idaho - Soil; Productivity/Management and Soil concerns for Pinus ponderosa (PIPO) series" />
		<meta name="keywords" content="Forest Habitat Types of Central Idaho Productivity Management concerns Pinus ponderosa series PIPO soil soils" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF CENTRAL IDAHO</a> &gt; <span class="ital">PINUS PONDEROSA</span> (PIPO) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Central Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Steele, Robert; Pfister, Robert D.; Ryker, Russell A.; Kittams, Jay A. 1981. Forest habitat types of central Idaho. Gen. Tech. Rep. INT-114. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 138 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_02.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<strong>3</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">Next &gt;&gt;</a>]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">PINUS PONDEROSA</span> (PIPO) SERIES</h3>
			<p><strong>Soil</strong>&#8212;Most soils in the <span class="ital">Pinus ponderosa</span> series are derived from granitics, basalt, or andesite. Habitat types in this series show little overall relationship to parent material (<a href="habitat_types_C-ID_appD1.php#PIPOcoarse">appendix D</a>) although local distribution patterns may be evident. Soils derived from granitics and andesite are mostly sandy loams to loamy sands, some of which are also gravelly. Those from basalt range from silty clay-loam to loam. Soil pH ranges from 5.0 to 6.8, with most samples between 5.5 and 6.5. No correlation between pH and h.t. was evident.</p>
			<p><strong>Productivity/Management</strong>&#8212;The <span class="ital">Pinus ponderosa</span> series reflects some of the least productive timberland in the area. Because no other conifer is successful here, the existing trees must be managed prudently to maintain a tree cover. Tree regeneration is sometimes sporadic and may coincide with periodic burning or years of higher moisture. Forage value for grazing often outweighs other values of these sites. Most undergrowth consists of dry-site shrubs and grasses which grow well beneath open canopies of pine. These plants can produce considerable forage most years, but recovery from overuse often requires several years or even decades.</p>
			<p>Trees in most stands of this series appeared free of disease. Dwarf mistletoe (<span class="ital">Arceuthobium</span> spp.) was observed in 15 percent of the stands. It was about equally distributed in all h.t.'s except where <span class="ital">Stipa</span> dominated the undergrowth and probably it would be found there too if more stands were sampled. The sporadic but widespread occurrence of mistletoe in central Idaho contrasts markedly with findings of other studies. In northern Idaho and eastern Washington, R. and J. Daubenmire (1968) noted widespread infection that was restricted to sites where dry-site grasses or <span class="ital">Purshia</span> dominated the undergrowth. In Montana, it was not found at all (Pfister and others 1977).</p>
			<p>Very little insect damage to pine was observed in this series. However, in 1972, populations of pine butterfly (<span class="ital">Neophasia menapia</span>) were exceptionally large along the lower South Fork of the Salmon River where several <span class="ital">Pinus ponderosa</span> h.t.'s are common.</p>

			<h4><a name="set1a"></a><span class="ital">Pinus ponderosa/Stipa occidentalis</span> h.t. <br />(PIPO/STOC; ponderosa pine/western needlegrass)</h4>
			<p><strong>Soil</strong>&#8212;The soils appear to be old alluvial deposits and are mainly sandy loams (<a href="habitat_types_C-ID_appD1.php#PIPOcoarse">appendix D</a>). Soil pH ranged from 5.3 to 6.2 and averaged 5.7. Exposed surface rock varies from 0.5 to 15 percent and bare soil ranges from 0 to 30 percent. Litter depths are less than 3.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is apparently very low to low and of poor quality. The trees regenerate sporadically and form open stands with limited stocking. Forage production is low, but the gentle terrain attracts livestock. Use by wildlife is generally light.</p>

			<h4><a name="set1b"></a><span class="ital">Pinus ponderosa/Agropyron spicatum</span> h.t. <br />(PIPO/AGSP; ponderosa pine/bluebunch wheatgrass)</h4>
			<p><strong>Soil</strong>&#8212;Soils range from loam to clay loam on basalt and andesite, and from sandy loam to loamy sand on granitics (<a href="habitat_types_C-ID_appD1.php#PIPOcoarse">appendix D</a>). Soil pH varies from 5.2 to 6.8 and averages 6.0. The soils on granitics are slightly more acidic, but this is not always the case. Areas of exposed rock or soil are often high, up to 75 percent. Litter is shallow, usually less than 2.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low to very low because of low site index (<a href="habitat_types_C-ID_app.php">appendix E-1</a>) and apparent stockability limitations (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). Natural regeneration requires a long time to produce adequate stocking. Artificial regeneration would be expensive because the probability of survival is very low.</p>
			<p>These sites can produce good forage for livestock, but unregulated grazing can easily reduce forage production and create considerable erosion. On ranges used by both livestock and big game, forage production may need to be allocated, depending on objectives. Big game forage production is low; but the big game winter demand may be relatively high. In some areas, the dried grasses provide important winter forage for elk and bighorn sheep. The large, spreading trees may provide winter cover for mule deer and important roosts for wild turkey.</p>

			<h4><a name="set1c"></a><span class="ital">Pinus ponderosa/Festuca idahoensis</span> h.t. <br />(PIPO/FEID; ponderosa pine/Idaho fescue)</h4>
			<p><strong>Soil</strong>&#8212;Soils are mainly of granitic or basaltic origin (<a href="habitat_types_C-ID_appD1.php#PIPOcoarse">appendix D</a>). Textures range from loam to clay loam on basalts and from loam to gravelly loamy sand on granitics. Soil pH varies from 5.5 to 6.7 and averages 6.1. in contrast to PIPO/AGSP, surface rock varies from 0 to only 20 percent, and bare soil ranges from 0.5 to 20 percent. Litter depths vary from 0.3 to 7.5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is low (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). Management considerations are similar to PIPO/AGSP; however, forage production should be greater due to a more moderate environment and greater number of plant species. Wildlife and livestock considerations are similar to those of PIPO/AGSP.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pinus ponderosa/Purshia tridentata</span> h.t. <br />(PIPO/PUTR; ponderosa pine/bitterbrush)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly andesite,
rhyolite, and granitics (<a href="habitat_types_C-ID_appD1.php#PIPOcoarse">appendix D</a>). A few sites occur on basalts. Soil textures vary from gravelly loamy sand to clay loam but are mostly sandy loam to loamy sand. Soil pH ranges from 5.0 to 6.4, with both extremes from granitic soils. Coverages of both surface rock and bare soil range from 0 to 30 percent. The large areas of bare soil have resulted either from livestock, or earth movement on steep slopes. Average litter depth seldom exceeds 4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity ranges from low to very low (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). Some forage is available for livestock but grazing abuse can easily deplete production potential. In some areas, elk and mule deer use this h.t. heavily for winter forage and cover and, in spring, black bear feed heavily on the perennial grasses and forbs. The large spreading trees may also provide roosts for wild turkey.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pinus ponderosa/Symphoricarpos oreophilus</span> h.t. <br />(PIPO/SYOR; ponderosa pine/mountain snowberry)</h4>
			<p><strong>Soil</strong>&#8212;These dry sites often have shallow rocky soils but are cooler than most <span class="ital">Pinus ponderosa</span> h.t.'s. Basalts and granitics are the common parent materials. In the three samples taken (<a href="habitat_types_C-ID_appD1.php#PIPOcoarse">appendix D</a>), soil texture varied from loam to clay loam and pH ranged from 6.1 to 6.2. Litter depth is usually less than 3.5 cm. The sites have only small amounts of exposed rock (2 percent or less) and less than 10 percent bare soil.</p>
			<p><strong>Productivity/Management</strong>&#8212;Trees regenerate sporadically and the stocking is very limited. Timber productivity of existing trees apparently is low. Forage production for livestock is limited by the shrub layer while the upper slope position of this h.t. seldom attracts much use. In some areas, wintering elk feed heavily on these sites and mule deer find important food and cover here. In spring, this h.t. may be important for mule deer fawning and rearing and for black bear that feed on perennial grasses and forbs. Blue grouse will also nest and raise their young here. Fall berry crops may be important to blue grouse and black bear.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pinus ponderosa/Symphoricarpos albus</span> h.t. <br />(PIPO/PUTR; ponderosa pine/common snowberry)</h4>
			<p><strong>Soil</strong>&#8212;These sites normally have well-drained, sandy loam to clay loam soils (<a href="habitat_types_C-ID_appD1.php#PIPOcoarse">appendix D</a>). Most parent materials are basalt or granitic. Soil pH varies between 5.6 and 6.4 and averages 5.9. Unless disturbed, these sites have only trace amounts of bare soil or rock and litter depths often reach 4 to 6 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;This h.t. produces more timber than most other sites where <span class="ital">Pinus ponderosa</span> is climax (<a href="habitat_types_C-ID_app.php">appendix E-2</a>) and trees seem to regenerate more readily. Amounts of livestock forage will vary with grass species and coverage. Big game forage is limited by the few palatable shrub species present, but deer and elk make light to moderate use of these sites.</p>
			
			<h4><a name="set1d"></a><span class="ital">Pinus ponderosa/Physocarpus malvaceus</span> h.t. <br />(PIPO/PHMA; ponderosa pine/ninebark)</h4>
			<p><strong>Soil</strong>&#8212;Soils vary from silty loam to loamy sand and are derived from basalt or granitic material. Of the three samples taken, soil pH ranged from 5.6 to 6.3. Only 0 to 2 percent bare soil was found; exposed rock was absent. Litter depths ranged from 3 to 8 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber production should be similar to that of the PIPO/SYAL h.t. Utility for livestock and wildlife should be similar to that of the PSME/PHMA h.t.</p>
			
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_C-ID_04.php">On to <span class="ital">Pseudotsuga menziesii</span> (PSME) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_02.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<strong>3</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">Next &gt;&gt;</a>]</p>
			</div>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
