<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Abies grandis series</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Central Idaho - Soil; Productivity/Management and Soil concerns for Abies grandis (ABGR) series" />
		<meta name="keywords" content="Forest Habitat Types of Central Idaho Productivity Management concerns Abies grandis series ABGR grand fir soil soils" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF CENTRAL IDAHO</a> &gt; <span class="ital">Abies grandis</span> (ABGR) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Central Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Steele, Robert; Pfister, Robert D.; Ryker, Russell A.; Kittams, Jay A. 1981. Forest habitat types of central Idaho. Gen. Tech. Rep. INT-114. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 138 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_05.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<strong>6</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">Next &gt;&gt;</a>]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">ABIES GRANDIS</span> (ABGR) SERIES</h3>
			<p><strong>Soil</strong>&#8212;Soils vary from clay loams to sandy loams and are mostly loams (<a href="habitat_types_C-ID_appD1.php#ABGRcoarse">appendix D</a>). The parent materials are mostly granitic or basalt. Soil pH varies from 5.0 to 6.9. In general, soil conditions appear similar throughout the <span class="ital">Abies grandis</span> series, although soil-habitat type relationships may occur locally. </p>
			<p><strong>Productivity/Management</strong>&#8212;This series provides the most productive timberlands and greatest silvicultural diversity in central Idaho. <span class="ital">Pinus ponderosa</span> and <span class="ital">Pseudotsuga</span> grow exceptionally well here and <span class="ital">Picea</span>, <span class="ital">Pinus contorta</span>, and even <span class="ital">Larix occidentalis</span> will grow on certain h.t.'s. On some of the drier sites in this series, growth rates of the <span class="ital">Abies</span> may equal or even surpass that of the seral species. Relative acreages of this series are quite small in our area, increasing further the timber value of these sites.</p>
			<p>Frederick and Partridge (1977) studied the occurrence of decay in <span class="ital">Abies grandis</span> and its relationship to certain undergrowth species. They found a low incidence of decay on the drier sites that support high coverages of <span class="ital">Calamagrostis rubescens</span> and <span class="ital">Symphoricarpos albus</span>. Much of this condition would occur in the ABGR/SPBE and ABGR/CARU h.t.'s. We also noted remarkably few sporophores of <span class="ital">Echinodontium tinctorium</span> in these two h.t.'s.</p>
			<p>In 1972, insect damage to the needles and new growth of <span class="ital">Abies</span>, <span class="ital">Picea</span>, and <span class="ital">Pseudotsuga</span> were noted throughout this series. Most of this damage was presumedly caused by western spruce budworm (<span class="ital">Choristoneura fumiferana</span>) and appeared concentrated geographically rather than by h.t. Infestation apparently increased northward and became notably severe around McCall, Idaho.</p>

			<h4><a name="set1a"></a><span class="ital">Abies grandis/Calamagrostis rubescens</span> h.t. <br />(ABGR/CARU; grand fir/pinegrass)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials include basalt, granitics, and mixtures of granitics and rhyolite (<a href="habitat_types_C-ID_appD1.php#ABGRcoarse">appendix D</a>). The textures vary from clay loam to sandy loam. Soil pH ranges from 5.7 to 6.3 and averages 6.1. Areas of bare rock or bare soil seldom exceed 2 percent. Litter depths on a site can average at least 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pseudotsuga</span>, <span class="ital">Pinus ponderosa</span>, and, on some sites, <span class="ital">P. contorta</span> all grow well here. However, the <span class="ital">Calamagrostis</span> sod may need scarification or other treatment to obtain prompt regeneration. <span class="ital">Abies grandis</span> seldom contains much heartrot in this h.t. and may be at least as productive as the seral trees.</p>			
			<p>Livestock frequent these sites due to the gentle terrain but find only moderate amounts of forage here. In some areas these sites may provide important forage and cover for deer and elk.</p>

			<h4><a name="set1b"></a><span class="ital">Abies grandis/Spiraea betulifolia</span> h.t. <br />(ABGR/SPBE; grand fir/white spiraea)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mostly basalt and occasionally granitics (<a href="habitat_types_C-ID_appD1.php#ABGRcoarse">appendix D</a>). Textures vary from clay loam to sandy loam. The pH ranges from 5.5 to 6.4 and averages 6.0. Areas of bare rock and soil are less than 1 percent on most sites. Average litter depths per site can reach at least 6 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is high to very high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pinus ponderosa</span> and <span class="ital">Pseudotsuga</span> should regenerate well in small clearings. <span class="ital">Abies grandis</span> can regenerate in partial shade and, in some areas, can grow at least as fast as the pine when given adequate sunlight. If a <span class="ital">Calamagrostis</span> sod is present, site preparation will be needed to achieve adequate stocking.</p>
			<p>Livestock use the gentle terrain of these sites but find little forage beneath the trees. Some of these sites may provide important food and cover for deer, elk, and black bear and important nesting areas for ruffed grouse.</p>

			<h4><a name="set1c"></a><span class="ital">Abies grandis/Vaccinium globulare</span> h.t. <br />(ABGR/VAGL; grand fir/blue huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are either basalt or granitics (<a href="habitat_types_C-ID_appD1.php#ABGRcoarse">appendix D</a>). Textures vary from loam to sandy loam and are mostly loam. The pH ranges from 5.2 to 6.8 but averages 5.9. Areas of bare rock and soil are negligible. Average litter depths on a site can reach at least 7 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is generally high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Picea</span> and <span class="ital">Pseudotsuga</span> have the highest site indexes (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). If present, <span class="ital">Pinus contorta</span> should regenerate well in small clearings. Areas with partial shade will favor <span class="ital">Pseudotsuga</span>, <span class="ital">Picea</span>, and <span class="ital">Abies</span>.</p>
			<p>Seral stands may provide important forage and cover for elk and occasionally whitetail deer. The berry crops of <span class="ital">Vaccinium</span> are important for black bear, ruffed grouse, and to a lesser extent, blue grouse.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies grandis/Xerophyllum tenax</span> h.t. <br />(ABGR/XETE; grand fir/beargrass)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Only limited data on timber productivity are available, but yield capability is probably moderate to high. On most sites <span class="ital">Pinus contorta</span> should regenerate well in clearings. Openings with partial shade will favor <span class="ital">Pseudotsuga</span> and <span class="ital">Abies</span>.</p>
			<p>Early successional stages offer limited forage for deer and elk, and the sites are seldom accessible for winter use. The <span class="ital">Vaccinium</span> berries are sought by black bear, grouse, and humans.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies grandis/Acer glabrum</span> h.t. <br />(ABGR/ACGL; grand fir/mountain maple)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly basalt, granitics, and occasionally quartz diorite (<a href="habitat_types_C-ID_appD1.php#ABGRcoarse">appendix D</a>). Textures range from clay loam to sandy loam and a few are gravelly. The pH ranges from 5.6 to 6.7 and averages 6.1. Areas of bare rock or bare soil seldom exceed 5 percent. Litter depths can average 10 cm on a site.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivities are generally high to very high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). Both <span class="ital">Pseudotsuga</span> and <span class="ital">Pinus ponderosa</span> should regenerate well wherever they escape competition of the shrubs and tree canopy. Complete removal of overstories may allow suppressed shrubs to develop a tall, dense layer that will persist for several decades.</p>
			<p>Livestock find little forage in old-growth stands but may use early successional stages.</p>
			<p>ABGR/ACGL provides important forage and cover for elk, mule deer, and, in some areas, whitetail deer. Seral conditions, especially, produce an abundance of browse and the berry crops of a few species are important to black bear. When a tree canopy is present, these sites become important habitat for ruffed grouse.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies grandis/Linnaea borealis</span> h.t. <br />(ABGR/LIBO; grand fir/twinflower)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly basalt, andesite, and granitics (<a href="habitat_types_C-ID_appD1.php#ABGRcoarse">appendix D</a>). Textures are usually loamy and sometimes gravelly. The pH ranges from 5.4 to 6.9 and averages 6.0. Areas of bare soil and bare rock are usually negligible. Litter depths can reach 9 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity data is scarce, but yield capabilities appear to range from moderate to very high. The VAGL phase apparently is less productive than the LIBO phase. <span class="ital">Pinus ponderosa</span> should regenerate well wherever openings eliminate competition from larger trees. Smaller openings will favor <span class="ital">Pseudotsuga</span> and <span class="ital">Abies grandis</span> (and <span class="ital">Picea</span> in the VAGL phase).</p>
			<p>The gentle terrain may attract livestock to these sites, but timbered stands seldom provide much forage.</p>
			<p>Early successional stages may produce good browse for deer and elk, but the sites are seldom accessible in winter. Older stands may be important nesting sites for ruffed grouse. In the VAGL phase, the <span class="ital">Vaccinium</span> fruits are important to black bear, grouse, and humans.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies grandis/Vaccinium caespitosum</span> h.t. <br />(ABGR/VACA; grand fir/dwarf huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;The soils are depositional, largely of granitic origin, and are mostly clay loams to sandy loams. A few are gravelly. The pH ranges from 5.0 to 5.6. Areas of bare rock and bare soil are negligible. Litter depths on a site can average at least 3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pinus contorta</span> should regenerate in any clearing that receives ample sunlight. Although <span class="ital">Picea</span> and <span class="ital">Pseudotsuga</span> may establish naturally beneath the pine, plantings may be damaged by untimely frosts.</p>
			<p>The gentle terrain may attract livestock, but the animals find only moderate forage here. Elk and whitetail deer use the cover on these sites, but find much of their browse on adjacent h.t.'s.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies grandis/Coptis occidentalis</span> h.t. <br />(ABGR/COOC; grand fir/western goldthread)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity should be nearly as high as that of the ABGR/CLUN h.t. and silvicultural treatments should be similar. When <span class="ital">Pinus ponderosa</span> or <span class="ital">P. contorta</span> are naturally present plantations of the appropriate pine have been very successful.</p>
			<p>Livestock, deer, and elk use these sites only lightly.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies grandis/Clintonia uniflora</span> h.t. <br />(ABGR/CLUN; grand fir/queencup beadlily)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are usually basalt or granitics (<a href="habitat_types_C-ID_appD1.php#ABGRcoarse">appendix D</a>). Textures range from loam to sandy loam. Soil pH varies from 5.5 to 6.3 and averages 5.9. Areas of bare soil and bare rock are normally less than 1 percent. Average litter depth on a site can reach at least 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is usually high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>), with a wide choice of silvicultural options. If present, <span class="ital">Pinus ponderosa</span>, <span class="ital">P. contorta</span>, and <span class="ital">Larix occidentalis</span> should regenerate best in openings that eliminate competition from older trees. Smaller openings with partial shade will favor <span class="ital">Pseudotsuga</span>, <span class="ital">Picea</span>, and <span class="ital">Abies grandis</span>. Both artificial and natural regeneration should prove successful on properly prepared sites. Young <span class="ital">Pinus ponderosa</span> grow rapidly but sampling only the near-climax conditions precluded a meaningful site index for this species. Daubenmire (1961) found that <span class="ital">P. ponderosa</span> grew most rapidly on these sites for the first 50&#8211;60 years. After age 60, the pine showed higher productivity on PSME/PHMA and PIPO/PHMA h.t.'s.</p>
			<p>Livestock find very little forage on timbered sites. Early succession following major disturbances may produce some forage.</p>
			<p>These sites can provide important browse and cover for elk and whitetail deer. Early seral stages often produce high-quality browse, but snow depths may prevent winter use. ABGR/CLUN provides good ruffed grouse habitat and, when <span class="ital">Vaccinium globulare</span> is present, food for black bear.</p>
						
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_C-ID_07.php">On to <span class="ital">Abies lasiocarpa</span> (ABLA) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_05.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<strong>6</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">Next &gt;&gt;</a>]</p>
			</div>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
