<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Successional Status of Central Idaho Forests</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Central Idaho - Successional Status" />
		<meta name="keywords" content="alpine habitats, vegetation classification, key to classification, parent materials, soil variables, central Idaho, habitat types, successional status, fire history, grazing history, logging history" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF CENTRAL IDAHO</a> &gt; SUCCESSIONAL STATUS OF CENTRAL IDAHO FORESTS</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Central Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Lesica, Peter; Page-Dumroese, Deborah. Rev. 1997. Plant Community Classification for Alpine Vegetation on the Beaverhead National Forest, Montana. Gen. Tech. Rep. INT-362. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 61 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="index.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<strong>1</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a>SUCCESSIONAL STATUS OF CENTRAL IDAHO FORESTS</h3>
			<h4><a name="set1a"></a>Fire History</h4>
			<p>As Wellner (1970) noted, fire has burned over most all forest land in the Northern Rocky Mountains at one time or another. There appears, however, to be a trend for fires to occur more often in some areas than others. Over a 5-year period, the Northern Region experienced about three times as many fires from lightning as the Intermountain Region (Barrows 1951). About 89 percent of these fires in the Northern Region occurred west of the Continental Divide. No correlation was found between number of natural fires and critical burning conditions. Instead, a broad lightning zone was recognized across the Clearwater and Nezperce Forests and eastward. This zone, which lies across the northern edge of the central Idaho study area, had more lightning-caused fires than anywhere else in Idaho or Montana.</p>
			<p>Western portions of central Idaho also reveal a higher frequency of stand replacing fires than eastern portions. It was notably more difficult to find near-climax stands of closed forest in western and central portions of the area than in the east. The mesic conditions to the west apparently produce more fuels, which may allow greater spread of individual fires. However, frequency of lightning storms may also differ in the two areas enough to be a major factor.</p>
			<p>Wellner (1970) suggests that fire has been a natural part of Northern Rocky Mountain ecosystems. Numerous plants including <span class="ital">Pinus monticola</span>, <span class="ital">P. contorta</span>, <span class="ital">Larix occidentalis</span>, and <span class="ital">Ceanothus sanguineus</span> have adapted so well to the effects of repeated burning that much of their present distribution is strongly related to past fires. <span class="ital">Pinus monticola</span>, <span class="ital">Larix occidentalis</span>, and <span class="ital">Ceanothus sanguineus</span> occur widely in northern Idaho, but become increasingly restricted southward due to unfavorable climate. However, the abundance of seral <span class="ital">Pinus contorta</span>, <span class="ital">Ceanothus velutinus</span>, and <span class="ital">Pinus ponderosa</span> is often strongly related to fire history in central Idaho.</p>
			<p>Though fire frequency may be less in central Idaho than farther north, stand-replacing fires still occur here. In some cases, conflagrations result from dead foliage of trees killed by insect epidemics (Wellner 1970; Hockaday 1968, unpubl. ref.). In other cases, large fires result from unusually dry weather conditions.</p>
			<p>Man has caused many of the fires in the Northern Rocky Mountains. Before the white man came, aborigines burned the vegetation for various reasons (DeVoto 1953). Later, prospectors started fires to expose mineral outcrops (Space 1964; unpubl. ref.) and settlers set fires to improve the range (Smith undated, unpubl. ref.). Many of these fires crept into the forest and burned unchecked until extinguished by fall rains. In recent years, some of the most catastrophic fires in central Idaho have been man-caused. According to Barrows (1961), the Intermountain Region had more man-caused fires than the Northern Region during the same period.</p>
			<p>Recent studies indicate that low-intensity ground fires were frequent in some parts of the Northern Rocky Mountains prior to the advent of suppression activities in the early 1900's. On the Bitterroot National Forest in western Montana, mean fire-free intervals ranged from 6 to 41 years in different habitat types (Arno 1976). Fire scars were also evident in many central Idaho sample stands, especially at lower elevations. Thus, the composition of many existing stands may reflect the partial influence of one or more ground fires during the life of the stand. The prevalence of <span class="ital">Pinus ponderosa</span> on many sites within the <span class="ital">Pseudotsuga menziesii</span> habitat types may reflect these historic fires.</p>
			<h4><a name="set1b"></a>Grazing History</h4>
			<p>Early grazing by cattle and later by sheep have caused considerable destruction to range and soil resources in central Idaho. The most severe depletion was, and apparently still is, on private and public lands. Here free, unregulated use resulted in forage depletion of more than 50 percent and some areas were estimated at over 75 percent depletion (McArdle and others 1936). Most of the range depleted by cattle was nonforest or open forests at lower elevations.</p>
			<p>Range depletion by sheep occurred from lower elevations to the ridges and mountain meadows at upper elevations. Perhaps the most severely abused areas were in the foothills of the Weiser River drainage where one early account (Hockaday 1968, unpubl. ref.) notes soil losses up to 1 foot and a great increase in surface rock. Here several mud-rock and debris floods were attributed to severe overgrazing by sheep. The railhead at Ketchum became the largest shipping point for sheep in the United States (Goodwin and Hussey undated, unpubl. ref.). Sheep trailed into Ketchum from all over central Idaho and elsewhere and so badly overcrowded the Sawtooth Valley that it became almost impossible to graze there. Ten to 20 bands of sheep (up to 3,000 per band) could be commonly seen on the hills above Ketchum awaiting shipping. As a result, the Big Wood River drainage and Sawtooth Valley were severely overgrazed.</p>
			<p>By 1903, Idaho had 2.6 million sheep (Stewart 1936), a large percentage of which grazed in central Idaho at least part of the year. Because there were no grazing allotments, sheep men would race herds to choice range in the high country each spring and were then forced to graze one drainage all summer because all other range was occupied (Hockaday 1968, unpubl. ref.; Goodwin and Hussey undated, unpubl. ref.).</p>
			<p>On the granitic soils in central Idaho, <span class="ital">Carex geyeri</span> once formed a dominant ground cover on many sites. In hopes of producing a more palatable forage, sheepherders would destroy the <span class="ital">Carex</span> swards by trailing their flocks over them (Mont Lewis, USDA Forest Service, retired, personal communication). Other times, just the number of animals in the area destroyed the <span class="ital">Carex</span>. The results did not always produce more forage and many sites were left exposed to erosion. The <span class="ital">Carex</span> has only partially recovered but <span class="ital">Artemisia</span> now partly protects many areas. Artificial revegetation on granitic soils has seen only limited success and rates of natural recovery here are extremely slow.</p>
			<p>Today, small bands of sheep still graze the upper ridges and meadows. Cattle graze the densely forested land where they find excellent forage near streams, in natural openings, and in openings created by logging. The widespread grazing abuse of the early 1900's has ended and much of the range is recovering at various rates. Localized damage still may occur where animals congregate. New clearcuts seem especially attractive to livestock; trampling of conifer seedlings and disturbance of soils often outweighs the value of consumed forage.</p>
			<h4><a name="set1c"></a>Logging History</h4>
			<p>Since arrival of early pioneers, considerable timber has been cut in central Idaho forests. In mineralized areas, prospectors used many logs for construction and fuel and sometimes the land near mining towns was cleared of trees. Early farmers and ranchers often cleared the most fertile forest lands to raise crops and depended on the nearby stands of timber for building materials and fuel. Lumbermen first concentrated on more accessible areas but soon gained access to more remote stands of valuable timber. Access to uncut stands is sought continually so that eventually only very remote areas or those designated for preservation will remain in their natural state. With aerial logging techniques now removing timber once considered impractical to harvest, even small stands of uncut forest may eventually disappear.</p>
			<p>Much of the land in central Idaho recovers slowly from logging disturbance, especially in the southern and eastern portions. The clearcut and burn technique of timber management successful farther north has often failed as a tree regeneration method in these areas. Grazing pressure, droughty soils, and low fertility often contribute to the difficulty of reforestation on these sites.</p>
									
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_C-ID_02.php">On to <span class="ital">Pinus flexilis</span> (PIFL) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="index.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<strong>1</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
