<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Abies lasiocarpa series</title>
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Central Idaho - Soil; Productivity/Management and Soil concerns for Abies lasiocarpa (ABLA) series" />
		<meta name="keywords" content="Forest Habitat Types of Central Idaho Productivity Management concerns Abies lasiocarpa series ABLA subalpine fir soil soils" />
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF CENTRAL IDAHO</a> &gt; <span class="ital">Abies lasiocarpa</span> (ABLA) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Central Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Steele, Robert; Pfister, Robert D.; Ryker, Russell A.; Kittams, Jay A. 1981. Forest habitat types of central Idaho. Gen. Tech. Rep. INT-114. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 138 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_06.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<strong>7</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">ABIES LASIOCARPA</span> (ABLA) SERIES</h3>
			<p><strong>Soil</strong>&#8212;Most soils in this series ranged from gravelly loam to sandy loam. Habitat types showed little overall correlation with soil parent materials that varied from granitics and volcanics to sedimentaries. A few exceptions are noted under the appropriate h.t.</p>
			<p><strong>Productivity/Management</strong>&#8212;Lower-elevation sites within the <span class="ital">Abies lasiocarpa</span> series have the highest timber potentials. Here <span class="ital">Pseudotsuga</span> is often the most productive species, but regeneration is sometimes difficult to obtain. <span class="ital">Pinus contorta</span> responds better to silvicultural treatments and is fairly productive throughout much of this series. <span class="ital">Picea</span> grows well on many sites but is susceptible to windthrow in partially cut stands, especially on those sites with high water tables. These sites with excess moisture almost always require special consideration during timber harvest and stand regeneration.</p>
			<p>Upper-elevation sites within this series have low timber potential and are best suited for recreation, wildlife, and snowpack management.</p>

			<h4><a name="set1a"></a><span class="ital">Abies lasiocarpa/Caltha biflora</span> h.t. <br />(ABLA/CABI; subalpine fir/marsh marigold)</h4>
			<p><strong>Soil</strong>&#8212;Substrates in this h.t. often consist of a thick layer (20 + cm) of organic material overlying loamy to sandy loam soils (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Soil parent materials are primarily granitic. Soil pH ranges from 4.9 to 6.2 and averages 5.2. Areas of bare soil and bare rock are negligible.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Picea engelmannii</span> grows well here, but regeneration often is limited to the raised microsites within the stands. If the large trees are removed, water tables are likely to rise and seriously impede tree regeneration. Most disturbances can degrade these sites to a bog-like condition. Livestock and machinery can easily churn the wet substrate and destroy considerable undergrowth. Acreages of this h.t. are usually small locally but require recognition when considering access and use of adjacent h.t.'s. Hazards to soil and water resources may result from almost any manipulation of these sites.</p>
			<p>This h.t. is very important to elk in summer and fall. The many lush forbs and proximity to water create important feeding areas, and the wet depressions provide excellent elk wallows. Mule deer also find important forage here in summer and fall. Black bear, too, forage and wallow on these sites and Franklin's grouse seek food and cover here.</p>

			<h4><a name="set1b"></a><span class="ital">Abies lasiocarpa/Calamagrostis canadensis</span> h.t. <br />(ABLA/CACA; subalpine fir/bluejoint)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly granitic but also include quartzite, quartz monzonite, and trachyte (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). The textures are mostly loams but range from loam to loamy sand. A few are gravelly. Soil pH ranges from 4.6 to 6.4 and averages 5.1. Areas of bare soil or rock are negligible on most sites. Average litter depths on a site can reach 13 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity varies from low to high, depending on the phase involved (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). The LICA phase has the highest potential. <span class="ital">Pinus contorta</span> may be the easiest conifer to regenerate but in the LICA and CACA phases, <span class="ital">Picea</span> should yield more timber. These sites can be prepared for planting in late summer after they have dried enough to support machinery. Plantings of <span class="ital">Picea</span> in contour trenches have been successful where grating was restricted. Picea may also regenerate naturally with adequate site preparation but longer periods of grazing protection are needed. In all phases of this h.t., partial cutting leaves the remaining large trees especially prone to windthrow. Overstory removal permits water tables to rise and allows the <span class="ital">Calamagrostis</span> and <span class="ital">Carex</span> species to increase and outcompete conifer seedlings.</p>
			<p>Livestock may find considerable forage here, and the adjacent streams attract many animals. But until late summer, the animals can easily churn the wet soil and destroy the plant cover as well as conifer seedlings. Depending on location, these sites may provide important food and cover for moose, elk, deer, black bear,and Franklin's grouse. The elk and bear can make wallows in the wet spots and seral stages can produce willows and abundant sedges. The LICA phase, especially, produces many lush forbs and whitetail deer are frequently found here.</p>

			<h4><a name="set1c"></a><span class="ital">Abies lasiocarpa/Streptopus amplexifolius</span> h.t. <br />(ABLA/STAM; subalpine fir/twisted stalk)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly granitics and basalt but also include quartzite, quartz monzonite, and rhyolite (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). The textures range from loam to sandy loam and are mostly loam. A few are gravelly. Soil pH ranges from 4.7 to 6.1 and averages 5.4. Areas of bare soil or bare rock are usually less than 1 percent. Litter depths can reach at least 9 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potential is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Picea</span> is the most productive species, but high water tables hamper timber management.</p>
			<p>Forage is often abundant in seral stands and the nearby streams also attract livestock. However, the animals can easily churn the wet soil with their hooves and destroy the plant cover and tree seedlings.</p>
			<p>In certain areas this h.t. may provide important forage and cover for elk and the wet spots make good wallows. The food and cover on these sites may also be important to moose, mule deer, black bear, and Franklin's grouse.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies lasiocarpa/Clintonia uniflora</span> h.t. <br />(ABLA/CLUN; subalpine fir/queencup beadlily)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly granitics and the textures are loam to fine sandy loam (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). The pH ranges from 5.3 to 5.8 and averages 5.5. Areas of bare rock and bare soil are negligible. Litter depths on a site can average at least 7 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Limited data suggest that timber potential is high. <span class="ital">Pinus contorta</span> and <span class="ital">Larix occidentalis</span> often regenerate easily and grow vigorously in clearings that receive adequate sunlight. <span class="ital">Pseudotsuga</span> and <span class="ital">Picea</span> may also regenerate easily and grow well here.</p>		
			<p>Normally, livestock find little food on the timbered sites but are attracted to openings, which produce lush forage. Here the animals may trample or bruise seedlings and can retard timber production for many years.</p>
			<p>Seral shrubs can produce considerable summer forage for elk and whitetail deer. These sites may also be important to ruffed grouse and the <span class="ital">Vaccinium</span> berries are important food for black bear.</p>
			
			<h4><a name="set1e"></a><span class="ital">Abies lasiocarpa/Coptis occidentalis</span> h.t. <br />(ABLA/COOC; subalpine fir/western goldthread)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity should be nearly as high as that of the ABLA/CLUN h.t. and silvicultural treatments should be similar. However, our limited data suggest that wildlife values may be less than in ABLA/CLUN. <span class="ital">Amelanchier</span>, <span class="ital">Ribes lacustre</span>, <span class="ital">Rubus parviflorus</span>, and <span class="ital">Sorbus</span> are notably absent in this h.t., whereas they all occur frequently in ABLA/CLUN.</p>
			
			<h4><a name="set1f"></a><span class="ital">Abies lasiocarpa/Menziesia ferruginea</span> h.t. <br />(ABLA/MEFE; subalpine fir/menziesia)</h4>
			<p><strong>Soil</strong>&#8212;The soils are derived mainly from granitics and vary from loam to loamy sand. The pH ranges from 5.1 to 6.2 and averages 5.4 in the MEFE phase. The LUHI phase should average somewhat less. Areas of bare soil or rock are usually negligible, but boulders and rock outcrops may be present. Litter depths can average at least 9 cm on a site.</p>
			<p><strong>Productivity/Management</strong>&#8212;Limited data suggest that timber potentials are moderate to high in the MEFE phase and somewhat lower in the LUHI phase. <span class="ital">Picea</span> appears productive and though it regenerates easily in openings that receive partial shade, the most vigorous growth is attained in clearcut areas (Roe and DeJarnette 1965). Overstory shade eventually favors <span class="ital">Abies lasiocarpa</span>. Exposing mineral soil and prescribed burning produce better regeneration than the undisturbed forest floor, scarification being the more effective treatment (Roe and DeJarnette 1965). When the overstory is removed, densities of <span class="ital">Menziesia</span>, <span class="ital">Vaccinium</span>, and other shrubs can increase and retard regeneration of conifers. Where mineral soil is exposed in openings, <span class="ital">Alnus sinuata</span> can easily invade and remain dominant for many years; however, the nitrogen-fixing capabilities of <span class="ital">Alnus</span> may be useful on some sites.</p>
			<p>Domestic livestock seldom find much forage here, but in the summer and fall, big game, especially elk, benefit considerably from the dense cover and browse. In certain areas, moose, mule deer, black bear and Franklin's grouse also seek food and cover on these sites. In winter, old-growth stands are important habitat for marten (Koehler and Hornocker 1977).</p>
			
			<h4><a name="set1g"></a><span class="ital">Abies lasiocarpa/Acer glabrum</span> h.t. <br />(ABLA/ACGL; subalpine fir/mountain maple)</h4>
			<p><strong>Soil</strong>&#8212;Parent materials are mainly granitic but also include quartz monzonite and rhyolite (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures are mostly loam to fine sandy loam and are occasionally gravelly. The pH ranges from 5.4 to 6.2 and averages 5.8. Areas of bare soil or bare rock are usually less than 5 percent. Average litter depths can reach at least 6 cm on a site. Soils are deep and fertile. Much of this h.t. occupies cryoplanated lands where soil moisture occurs near the surface (John Arnold, USDA Forest Service, retired; personal communication). This moisture apparently transports plant nutrients through the root zone and increases effective fertility in spite of low-nutrient parent materials.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is moderate to high (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pseudotsuga</span> is the most productive species and should regenerate well on carefully prepared sites that benefit from partial shade. Complete overstory removal by fire or logging can produce a tall shrub field that persists for decades and retards conifer seedlings.</p>
			<p>Livestock find little forage here, but sheep can feed on the numerous forbs and lower limbs of the tall shrubs. In some brushfields defoliation and trampling by sheep may improve conditions for tree establishment after the sheep are removed.</p>
			<p>The seral shrubs in this h.t. have high forage value to elk and mule deer but snow depths usually prevent winter use. The shrubs may also provide food and cover for black bear and blue grouse.</p>
			
			<h4><a name="set1h"></a><span class="ital">Abies lasiocarpa/Vaccinium caespitosum</span> h.t. <br />(ABLA/VACA; subalpine fir/dwarf huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;The soils, though often alluvial, are mainly of granitic origin (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures vary from silt loam to loamy sand and are frequently gravelly. Soil pH ranges from 5.1 to 5.7 and averages 5.3. Areas of bare soil or rock are normally less than 1 percent. Average litter depth on a site seldom exceeds 4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are low to moderate (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pinus contorta</span> is apparently the only species suitable for timber on these sites. It has mostly nonserotinous cones and the seedlings appear to establish quite readily. The gentle terrain makes these sites amenable to intensive silviculture, but no data are available to assure a satisfactory response to silvicultural treatment.</p>
			<p>Although the terrain is suitable for grazing, livestock find only light to moderate forage in the form of <span class="ital">Calamagrostis rubescens</span> and <span class="ital">Carex geyeri</span>.</p>
			<p>Because ABLA/VACA often borders moist meadows, elk and mule deer use these sites for cover in summer and fall. These sites may also be important habitat for Franklin's grouse.</p>
			<p>In some areas, this h.t. has been developed for campgrounds. Both <span class="ital">Vaccinium caespitosum</span> and <span class="ital">Calamagrostis rubescens</span> can withstand light foot traffic, but heavy, uncontrolled use can destroy plant cover and expose soil. The gentle terrain provides easy access and is well suited for campground development; however, knowledgeable campers may prefer areas that receive less frost and fewer mosquitoes, which thrive in adjacent wet sites.</p>
			
			<h4><a name="set1i"></a><span class="ital">Abies lasiocarpa/Linnaea borealis</span> h.t. <br />(ABLA/LIBO; subalpine fir/twinflower)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly granitic and occasionally andesite (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures are clay loams to fine sandy loams. Soil pH ranges from 5.1 to 6.4 and averages 5.5. Areas of bare soil and rock are negligible although exposed boulders may be present. Average litter depth on a site can reach at least 6 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Limited data suggest that timber potential is moderate, with the VASC phase having the lowest productivity. <span class="ital">Pinus contorta</span> is the most productive conifer in the VASC phase and regenerates readily wherever there is ample sunlight. In the LIB0 phase <span class="ital">Pseudotsuga</span> and <span class="ital">Picea</span> should regenerate well in partially shaded openings.</p>
			<p>Livestock may be attracted by the gentle terrain of these sites but find mainly <span class="ital">Calamagrostis rubescens</span> as forage. The animals cause little damage here except for the trampling of conifer seedlings.</p>
			<p>ABLA/LIBO can provide escape cover for deer and elk, and the <span class="ital">Vaccinium</span> fruits may be important feed for grouse and black bear.</p>
			
			<h4><a name="set1j"></a><span class="ital">Abies lasiocarpa/Alnus sinuata</span> h.t. <br />(ABLA/ALSI; subalpine fir/Sitka alder)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Limited data suggest that timber productivity should be moderate, with <span class="ital">Pinus contorta</span> as the major species. The pine can regenerate easily in clearings that receive full sunlight, but <span class="ital">Alnus sinuata</span> will also invade the clearings wherever bare soil occurs and may retard the seedlings. The alder suggests that soils are wet at least part of the year, which may create problems for access and timber harvest. Use by both livestock and big game appears to be light.</p>
			
			<h4><a name="set1k"></a><span class="ital">Abies lasiocarpa/Xerophyllum tenax</span> h.t. <br />(ABLA/XETE; subalpine fir/beargrass)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mostly granitic but include some quartzite, andesite, and schist (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures are mainly loam to sandy loam and are often gravelly, especially in the VASC phase. The pH ranges from 4.5 to 5.9 and averages 5.0. Areas of bare rock are usually less than 5 percent, but occasionally exposed boulders amount to 30-percent coverage. Most sites have less than 5 percent bare soil. Average litter depth on a site can reach 6 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potential appears low in the LUHI phase and is generally moderate in the VASC and VAGL phases (<a href="habitat_types_C-ID_app.php">appendix E</a>). <span class="ital">Pinus contorta</span> is usually the most productive species and regenerate well in clearings that receive full sunlight. Occasionally <span class="ital">Picea</span> or <span class="ital">Pseudotsuga</span> are suitable timber species in the VAGL phase.</p>
			<p>Livestock find little forage in this h.t. but may congregate in clearings and reduce survival of tree seedlings. In summer and fall, these sites can provide forage and cover for deer and elk. The <span class="ital">Vaccinium</span> fruits are usually important to black bear, blue grouse, and Franklin's grouse.</p>
			<p>Many of the sites accumulate a considerable snowpack each year and are often visited by recreationists during the summer.</p>
			
			<h4><a name="set1l"></a><span class="ital">Abies lasiocarpa/Vaccinium globulare</span> h.t. <br />(ABLA/VAGL; subalpine fir/blue huckleberry)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mostly granitics but also include quartz monzonite, rhyolite, and metasediments (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures are mostly loams or sandy loams and are often gravelly. The pH ranges from 5.0 to 6.2 and averages 5.5. Areas of bare soil or bare rock are usually less than 3 percent. Average litter depth on a site can reach at least 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are moderate in the VAGL phase (<a href="habitat_types_C-ID_app.php">appendix E-2</a>) and appear to be somewhat lower in the VASC phase. <span class="ital">Picea</span> and <span class="ital">Pseudotsuga</span> are the best suited timber species for the VAGL phase and should regenerate in small clearings that receive partial shade. <span class="ital">Pinus contorta</span> is best suited for the VASC phase and regenerates well in clearings that receive full sunlight. When the tree canopy is reduced, <span class="ital">Vaccinium globulare</span> may increase and compete with conifer seedlings, especially toward the moist extreme of this h.t.</p>
			<p>Livestock find very little forage in this h.t. and seldom spend much time here.</p>
			<p>These sites can provide cover and some forage for elk and mule deer in summer and fall. The berry crops of <span class="ital">Vaccinium</span> are used by black bear, grouse, and humans.</p>
			
			<h4><a name="set1m"></a><span class="ital">Abies lasiocarpa/Spiraea betulifolia</span> h.t. <br />(ABLA/SPBE; subalpine fir/white spiraea)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly granitic or quartz monzonite (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures range from loam to loamy sand and are often gravelly. Soil pH varies from 5.3 to 6.2 and averages 5.7. Areas of bare soil are usually negligible, but bare rock may reach 20 percent. Average litter depths on a site may reach 4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potential is low to moderate (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pseudotsuga</span> usually grows best on these sites and should regenerate in small clearings that receive partial shade. If present, <span class="ital">Pinus contorta</span> will regenerate in unshaded clearings, but its productivity may be less than <span class="ital">Pseudotsuga</span>.</p>
			<p>Livestock find little forage on these sites except when <span class="ital">Carex geyeri</span> or <span class="ital">Calamagrostis rubescens</span> are present.</p>
			<p>Mule deer and occasionally elk find cover and some forage here in summer and fall. Seral stands can produce some shrubs with high forage value to big game. In spring and summer, ABLA/SPBE is considered important habitat for red squirrel, flying squirrel, red-backed vole, and marten. It is also considered as nesting habitat for pine siskin, dark-eyed junco, mountain chickadee, and red-breasted nuthatch.</p>
			
			<h4><a name="set1n"></a><span class="ital">Abies lasiocarpa/Luzula hitchcockii</span> h.t. <br />(ABLA/LUHI; subalpine fir/woodrush)</h4>
			<p><strong>Soil</strong>&#8212;The soils are derived mainly from granitics and sometimes andesite (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). They vary from loam to fine sandy loam and a few are gravelly. In the LUHI phase, soil pH ranges from 4.3 to 5.0 and averages 4.6. In the VASC phase it ranges from 4.9 to 5.2 and averages 5.0. In both phases, coverage of bare rock is usually less than 5 percent, but exposed boulders may reach 50 percent. Areas of bare soil are mostly less than 10 percent. Average litter depths can reach at least 3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Limited data suggest timber potentials are low and it may be difficult to achieve tree regeneration after logging. Heavy snowpacks often deform the smaller trees and regeneration of <span class="ital">Abies lasiocarpa</span> may be largely vegetative.</p>
			<p>Livestock find little forage here; but in the past, domestic sheep trailed across these sites and destroyed the <span class="ital">Luzula</span> sod. In some areas, the bared soil was then eroded by melting snowpacks.</p>
			<p>In summer and fall, ABLA/LUHI provides cover and forage for elk, mule deer, mountain goat, and in some areas bighorn sheep. In fall and winter, these sites are important to blue grouse, which feed on the leaves and buds of <span class="ital">Abies lasiocarpa</span>.</p>
			<p>The depth and persistence of snow in this h.t. indicates that water is a key resource for management consideration.</p>
			
			<h4><a name="set1o"></a><span class="ital">Abies lasiocarpa/Vaccinium scoparium</span> h.t. <br />(ABLA/VASC; subalpine fir/grouse whortleberry)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials vary considerably and usually reflect overall geology of the area. They include granitics, quartzite, quartz monzonite, diorite, trachyte, latite, andesite, and basalt (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Soil textures are loam to sandy loam and are often gravelly. The pH ranges from 4.7 to 5.7 and averages 5.1. Coverage of bare rock is usually less than 5 percent but can reach 15 percent. Areas of bare soil are less than 5 percent. Average litter depths can reach at least 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are moderate in the VASC phase (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). (Limited data suggest low productivity in the PIAL phase and low-to-moderate productivity in the CARU phase.) <span class="ital">Pinus contorta</span> is the most suitable timber species and will regenerate in unshaded clearings. Attempts to regenerate other species assume considerable risk. In the CARU phase, coverages of <span class="ital">Calamagrostis rubescens</span> and <span class="ital">Carex geyeri</span> may impede tree regeneration unless there is thorough site preparation. However, soil scarification may increase hazards to frost heaving.</p>
			<p>Livestock find little forage here due to short growing seasons, limited numbers of forage species, and shade of the tree canopy.</p>
			<p>In fall, ABLA/VASC can provide escape cover for elk and mule deer and the <span class="ital">Vaccinium</span> fruits are important food for both blue and Franklin's grouse. It is considered important habitat for snowshoe hare, flying squirrel, red squirrel, red-backed vole, porcupine, marten, and lynx. It also provides important nesting habitat for the red crossbill, dark-eyed junco, mountain chickadee, and red-breasted nuthatch.</p>
			<p>Annual snowpacks may produce high quantities of water in certain watersheds and recreational summer use may also be quite high.</p>
			
			<h4><a name="set1p"></a><span class="ital">Abies lasiocarpa/Calamagrostis rubescens</span> h.t. <br />(ABLA/CARU; subalpine fir/pinegrass)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mostly granitic but also include quartz monzonite, trachyte, and basalt (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). The textures vary from loam to loamy sand and may be gravelly to very gravelly. Soil pH ranges from 4.9 to 6.1 and averages 5.4. Areas of bare soil or bare rock are usually less than 5 percent. Average litter depth on a site can reach 3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are low to moderate (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). If present, <span class="ital">Pinus contorta</span> is the most dependable species for timber management and should regenerate in clearings that have ample sunlight. Attempts to establish other conifers are risky and should be guided by patterns and frequency of regeneration in the stand. If the overstory is removed, the <span class="ital">Calamagrostis</span> and <span class="ital">Carex</span> may increase rapidly and retard seedling establishment.</p>
			<p>Normally livestock use these sites only lightly but are attracted to recent clearings where the forbs and graminoids have renewed vigor. Here the animals may congregate and trample tree seedlings.</p>
			<p>Elk and mule deer use these sites for cover in summer and fall and the elk will also feed on the graminoids present. Seral stands may produce some shrubs and forbs with light forage value to deer and elk. These sites are also considered important for red-breasted nuthatch and, in some areas, great gray owl.</p>
			
			<h4><a name="set1q"></a><span class="ital">Abies lasiocarpa/Carex geyeri</span> h.t. <br />(ABLA/CAGE; subalpine fir/elk sedge)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are largely granitic but also include quartzite, monzonite, dacite, trachyte, rhyolite, andesite, and basalt (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). The textures are loam to loamy sand and are almost always gravelly to very gravelly. The pH ranges from 4.6 to 6.4 and averages 5.5. Bare rock usually has less than 5 percent coverage but may reach 20 percent. Areas of bare soil are often 5&#8211;10 percent and may reach 40 percent from past grazing abuse. Average litter depth on a site seldom exceeds 4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are low to moderate (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). <span class="ital">Pinus contorta</span>, when present, is the only practical tree for regeneration but its site index is relatively low. <span class="ital">Pseudotsuga</span>, if present, usually grows slowly and reproduces sporadically. In the ARTR phase, <span class="ital">Pinus albicaulis</span> is more prevalent than <span class="ital">P. contorta</span>, but its production is low and its regeneration is marginal.</p>
			<p>Livestock find little forage here except for <span class="ital">Carex geyeri</span>. In some areas, disturbing the <span class="ital">Carex</span> sod permits invasion of forbs and grasses but quite often such disturbance provides little forage and increases erosion hazards. Generally these soils are easily eroded and difficult to revegetate.</p>
			<p>In general, elk and mule deer use these sites for cover in summer and fall and the elk may feed on the <span class="ital">Carex</span>. These sites may also be important for both blue and Franklin's grouse. In certain areas the ARTR phase provides habitat for mountain goats and bighorn sheep and the elk reportedly use these sites for calving. Because the ARTR phase often occurs on ridges, it provides important perching and foraging habitat for blue grouse and birds of prey.</p>
			
			<h4><a name="set1r"></a><span class="ital">Abies lasiocarpa/Juniperus communis</span> h.t. <br />(ABLA/JUCO; subalpine fir/common juniper)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mostly quartzite but also include trachyte and dacite (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures vary from loam to sandy loam and are usually gravelly to very gravelly. The pH ranges from 5.6 to 7.9 and averages 6.0. Coverage of bare rock is often 10&#8211;15 percent and may reach 60 percent. Areas of bare soil are usually negligible but occasionally reach 15 percent. Average litter depth on a site seldom exceeds 4 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are low (<a href="habitat_types_C-ID_app.php">appendix E-2</a>) and management alternatives are limited. If present, <span class="ital">Pinus contorta</span> may establish in clearings that receive adequate sunlight but its production is usually low. When <span class="ital">P. contorta</span> is absent, timber harvests of other species should be guided by patterns and frequency of natural regeneration.</p>
			<p>Livestock find little forage here and seldom use this h.t. except when it occurs on benches or dry stream terraces.</p>
			<p>ABLA/JUCO can provide cover for elk and mule deer that feed on other sites nearby. Seral stands may produce <span class="ital">Shepherdia canadensis</span>, which is occasionally browsed in some areas.</p>
			
			<h4><a name="set1s"></a><span class="ital">Abies lasiocarpa/Ribes montegenum</span> h.t. <br />(ABLA/RIMO; subalpine fir/mountain gooseberry)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials include quartzite, sandstone, and limestone (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures vary from loam to sandy loam and are usually gravelly. Areas of bare soil or rock may reach 15 to 20 percent. Average litter depth on a site may reach 5 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Limited data suggest that timber productivity is low to very low (<a href="habitat_types_C-ID_app.php">appendix E-1</a>), and regeneration may be sporadic. Large clearings in the stand may subject tree seedlings to damage from frost heaving and extreme sunlight. Recovery from any disturbance is apt to be very slow.</p>	
			<p>Both big game and livestock may seek shelter on these sites but find very little forage. Snowpacks persist late into the growing season and, in some areas, may be the most valuable resource present.</p>
			
			<h4><a name="set1t"></a><span class="ital">Abies lasiocarpa/Arnica cordifolia</span> h.t. <br />(ABLA/ARCO; subalpine fir/heartleaf arnica)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mainly quartzite but include dacite, trachyte, latite, and quartz monzonite (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures are loam to sandy loam and most are gravelly to very gravelly. The pH ranges from 4.7 to 6.3 and averages 5.5. Areas of bare rock or bare soil vary considerably among stands and may reach 20 percent. Average litter depth on a site can reach 3 cm.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are low to moderate (<a href="habitat_types_C-ID_app.php">appendix E-2</a>). Even though these may be the most productive sites in the area, management alternatives are limited. If present, <span class="ital">Pinus contorta</span> should regenerate in clearings that receive ample sunlight. When <span class="ital">P. contorta</span> is absent, timber harvest should be guided by the natural patterns and frequency of regeneration in the stand.</p>
			<p>Livestock seldom find much forage here but may use these sites for shelter.</p>
			<p>ABLA/ARCO provides little forage for big game, but elk and mule deer that feed in adjacent areas will use these sites for thermal and hiding cover.</p>
						
			<h4><a name="set1u"></a><span class="ital">Pinus albicaulis-Abies lasiocarpa</span> h.t. <br />(PIAL-ABLA; whitebark pine-subalpine fir)</h4>
			<p><strong>Soil</strong>&#8212;Soil parent materials are mostly granitic but include quartzite, quartz monzonite, and trachyte (<a href="habitat_types_C-ID_appD1.php#ABLAcoarse">appendix D-1</a>). Textures vary from loam to loamy sand and are usually gravelly to very gravelly. The pH ranges from 4.3 to 5.6 and averages 4.9. Areas of bare rock and bare soil can be quite high, 60 and 80 percent, respectively, but past grazing has aggravated this condition and it is now difficult to characterize natural condition of the ground surface. Litter depths on a site can average up to 4 cm beneath the tree canopy.</p>
			<p><strong>Productivity/Management</strong>&#8212;The PIAL-ABLA h.t.'s apparently have low to very low timber potential (<a href="habitat_types_C-ID_app.php">appendix E-1</a>) but may have high watershed value. Forage production may sustain light grazing, but in many areas grazing abuse has decimated the forage and exposed the soil. The vegetation recovers very slowly and, in some areas, soil loss may prevent complete restoration. The open slopes with light undergrowth afford easy travel and the surrounding scenery has considerable esthetic appeal. Hence recreationists seek these areas for hiking and camping but, if concentrated, these activities can easily disrupt soils and vegetation. In some areas, these sites provide important food and cover for mountain goats and bighorn sheep. The sheep also use these sites for lambing and rearing. Elk and mule deer find food and cover here and the elk will feed in the swards of <span class="ital">Festuca idahoensis</span> found in some areas. PIAL-ABLA h.t.'s may also be important wintering areas for blue grouse.</p>
						
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_C-ID_08.php">On to <span class="ital">Pinus albicaulis</span> (PIAL) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_C-ID_06.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_06.php">6</a>&nbsp;&nbsp;<strong>7</strong>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_C-ID_08.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
