<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>SoLo Documents: Research Publications</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="SoLo Documents: Research Publications" />
		<meta name="keywords" content="SoLo Documents research publications soil monitoring productivity" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<!-- <div id="fixedwidth"> -->
			<h5 class="subnav"><a href="http://forest.moscowfsl.wsu.edu/smp/solo/index.php">SOLO HOME</a> &gt; DOCUMENTS: RESEARCH PUBLICATIONS</h5>
				<h1 class="topheading">RESEARCH PUBLICATIONS</h1>
			<ul class="navlist">
				<li><a href="#biochar">Biomass, Bioenergy, and Biochar Production and Application</a></li>
				<li><a href="#monitoring">Monitoring</a></li>
				<li><a href="#productivity">Productivity</a></li>
			</ul>
			<p class="dateupdated">[Last update: 03/04/2013] </p>
			<h2 class="section">BIOMASS, BIOENERGY, AND BIOCHAR PRODUCTION AND APPLICATION<a name="biochar">&nbsp;</a></h2>
		  		<h3 class="firstsection">Research Papers</h3>
		  		<p><strong>NOTE:</strong> You will need Adobe Acrobat Reader (<a href="http://www.adobe.com/">free download</a>) to view PDF files.</p>
			<ul class="researchpapers">
				<li>Angima S.D. and T. A. Terry. 2011. <a href="http://hdl.handle.net/1957/20678">Best Management Practices for Maintaining Soil Productivity in the Douglas-fir Region</a>. Oregon State University Extension Service. 44 p.<br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
				<li>Coleman, Mark; Page-Dumroese, Deborah; Archuleta, Jim; Badger, Phil; Chung, Woodum; Venn, Tyron; Loeffler, Dan; Jones, Greg; McElligott, Kristin. 2010. <strong>Can portable pyrolysis units make biomass utilization affordable while using bio-char to enhance soil productivity and sequester carbon?</strong> (available at <a href="http://www.treesearch.fs.fed.us/pubs/37322">http://www.treesearch.fs.fed.us/pubs/37322</a>. In: Jain, Theresa B.; Graham, Russell T.; Sandquist, Jonathan. Integrated management of carbon sequestration and biomass utilization opportunities in a changing climate: Proceedings of the 2009 National Silviculture Workshop; 2009 June 15&#8211;18; Boise, ID. Proceedings RMRS-P-61. Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. p. 159&#8211;168. <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
				<li>Dumroese, R. Kasten; Heiskanen, Juha; Englund, Karl; Tervahauta, Arja 2011. <a href="http://www.treesearch.fs.fed.us/pubs/37521">Pelleted biochar: chemical and physical properties show potential use as a substrate in container nurseries</a>. Biomass &amp; Bioenergy. 35: 2018&#8211;2027. <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
				<li>Johnson L.R., D. Page-Dumroese, and H.-S. Han. 2007. <a href="http://www.treesearch.fs.fed.us/pubs/26213">Effects of Machine Traffic on the Physical Properties of Ash-Cap Soils</a>. In: Page-Dumroese, Deborah; Miller, Richard; Mital, Jim; McDaniel, Paul; Miller, Dan, tech. eds. 2007. Volcanic-Ash-Derived Forest Soils of the Inland Northwest: Properties and Implications for Management and Restoration. 9&#8211;10 November 2005; Coeur d&#8217;?Alene, ID. Proceedings RMRS-P-44; Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. p. 69&#8211;82. <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
				<li>Kimsey, Mark Jr., Deborah Page-Dumroese and Mark Coleman. 2011. <a href="http://dx.doi.org/10.3390/f2030797">Assessing Bioenergy Harvest Risks: Geospatially Explicit Tools for Maintaining Soil Productivity in Western US Forests</a>. Forests. 2: 797&#8211;813. doi:10.3390/f2030797 <br />
					<span class="dateupdated">[link added 09/21/2011]</span></li>
				<li>McElligott, Kristin, Deborah Page-Dumroese and Mark Coleman. 2011. <a href="http://treesearch.fs.fed.us/pubs/39454" title="Link to article at TreeSearch">Bioenergy Production Systems and Biochar Application in Forests: Potential for Renewable Energy, Soil Enhancement, and Carbon Sequestration</a>. USDA Forest Service, Rocky Mountain Research Station, Research Note. October 2011. RMRS-RN-46. <br />
					<span class="dateupdated">[link added 10/24/2011]</span></li>
      			<li>Page-Dumroese, Deborah. S. Is Woody Residue Part of Your Plan for Sustainable Forestry? <a href="http://www.oswa.org/NWW-Summer2010.pdf">Northwest Woodlands, Summer 2010.</a> (article also available at <a href="http://www.treesearch.fs.fed.us/pubs/35753">http://www.treesearch.fs.fed.us/pubs/35753</a>)  <br /><span class="dateupdated">[Document added to SoLo on 07/30/2010]</span></li>
      			<li>Page-Dumroese, Deborah S.; Jurgensen, Martin; Terry, Thomas. 2010. <a href="http://www.treesearch.fs.fed.us/pubs/34428">Maintaining soil productivity during forest or biomass-to-energy thinning harvests in the western United States</a>. Western Journal of Applied Forestry. 25(1): 5&#8211;11. <br />
				<span class="dateupdated">[link added 05/04/2011]</span></li>
				<li>Pye J.M., H.M. Rauscher, Y. Sands, D.C. Lee, and J. S. Beatty, Technical Eds. <a href="http://www.treesearch.fs.fed.us/pubs/36650">Advances in Threat Assessment and Their Application to Forest and Rangeland Management, Volume 1</a>. <strong>GTR-PNW-802</strong>. September 2010. <br /><span class="dateupdated">[link added to SoLo on 05/04/2011]</span></li>
			</ul>


		<h2 class="section">MONITORING<a name="monitoring">&nbsp;</a></h2>
		  		<h3 class="firstsection">Symposium Proceedings/General Technical Reports (GTRs)</h3>
		  		<p><strong>NOTE:</strong> You will need Adobe Acrobat Reader (<a href="http://www.adobe.com/">free download</a>) to view PDF files.</p>
                <h4>Washington Office</h4>
                <ul class="researchpapers">
				<li><strong>2010 Soil Management Manual</strong> (part of FSM 2500 &ndash; Watershed and Air Management)   <br />
				<span class="dateupdated">[Document added to SoLo on 12/06/2010]</span>
					<ul>
						<li><a href="../documents/MISC/soil_mgmt_manual_2010/wo_2500_zero_code.pdf">Chapter 2500 - Zero Code</a></li>
						<li><a href="../documents/MISC/soil_mgmt_manual_2010/wo_2509.18-2010-1_transmittal.pdf">FSH 2509.18 - Soil Management Handbook</a></li>
						<li><a href="../documents/MISC/soil_mgmt_manual_2010/wo_2550.pdf">Chapter 2550 - Soil Managment Manual</a></li>
					</ul>
				</li>
                    <li><strong>GTR-WO-82 &#8211;</strong> Page-Dumroese, Deborah S.; Ann M. Abbott and Thomas M. Rice. September 2009. <br /><strong>Forest Soil Disturbance Monitoring Protocol, Volumes I and II</strong>. USDA Forest Service, Washington Office.</span>
                      <ul>
                            <li><a href="../documents/GTRs/WO_82/SoilMonProtocol_GTR-WO-82a.pdf">Forest Soil Disturbance Monitoring Protocol, <br />Volume I: Rapid Assessment <br />General Technical Report GTR-WO-82a</a> <br />(PDF - 211 KB) <span class="dateupdated">[Document posted on 08/26/2009]</span></li>
                            <li><a href="../documents/GTRs/WO_82/SoilMonProtocol_GTR-WO-82b.pdf">Forest Soil Disturbance Monitoring Protocol, <br />Volume II: Supplementary Methods, Statistics, and Data Collection <br />General Technical Report GTR-WO-82b</a> <br />(PDF - 1.8 MB) <span class="dateupdated">[Document posted on 08/26/2009]</span></li>
                        <li><a href="../documents/GTRs/RMRS_301/Spanish_Version_Monitoring_Protocols_RMRS-GTR-301.pdf">Forest Soil Disturbance Monitoring Protocol, <br />SPANISH version</a> <br />
                       	(PDF - 13.57 MB) <span class="dateupdated">[Document posted on 03/04/2013]</span></li>
                        </ul>
                    </li>
                    <li><strong>GTR-WO-68 &#8211;</strong> Winthers, E.; Fallon, D.; Haglund, J.; DeMeo, T.; Nowacki, G.; Tart, D.; Ferwerda, M.; Robertson, G.; Gallegos, A.; Rorick, A.; Cleland, D. T.; Robbie, W. 2005. <a href="http://www.fs.fed.us/biology/resources/pubs/soils/gtr_wo-68.pdf">Terrestrial Ecological Unit Inventory technical guide: Landscape and Land Unit Scales</a>. USDA Forest Service, Washington Office, Ecosystem Management Coordination Staff. <br /><span class="dateupdated">[Document added to SoLo on 03/03/2009]</span></li>
                </ul>
                <h4>Intermountain Research Station (Later renamed Rocky Mountain Research Station)</h4>
                <ul class="researchpapers">
                    <li><strong>GTR-INT-326 &#8211;</strong> Page-Dumroese, D.; Harvey, A.; Jurgensen, M. <a href="GTRs/INT_326/NW-US_natl-forest_soil_sampling_guide_GTR-RMRS-326.pdf">A Guide to Soil Sampling and Analysis on the National Forests of the Inland Northwest United States (PDF - 6.92 MB)</a>. United States Department of Agriculture, Forest Service, Intermountain Research Station - General Technical Report, INT-GTR-326, October 1995.</li>		
                  <li><strong>(Document in GTR-INT-280) &#8211;</strong> Geist, J. M., R. T. Meurisse, T. A. Max. 1991. <a href="GTRs/INT_280/GeistMeurisse_INT-280.php">Monitoring Forest Soil Properties to Maintain Productivity. (HTML)</a> In:&nbsp; Harvey, Alan E.; Neuenschwander, Leon F., compilers. Proceedings - management and productivity of western-montane forest soils; 1990 April 10&#8211;12; Boise, ID. Gen. Tech. Rep. INT-280. Ogden UT: U. S. Department of Agriculture, Forest Service, Intermountain Research Station. pp 90&#8211;94.</li>
                </ul>
                <h4>Rocky Mountain Research Station (Previously named Intermountain Research Station)</h4>
                <ul class="researchpapers">
                    <li><strong>(Document in RMRS-P-41) &#8211;</strong> Page-Dumroese, D.; Jurgensen, M.; Abbott, A.; Rice, T.; Tirocke, J.; Farley, S.; DeHart, S. Monitoring Changes in Soil Quality from Post-fire Logging in the Inland Northwest (PDF available at <a href="http://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-41_605-614.pdf">http://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-41_605-614.pdf</a>). In:&nbsp; Andrews, Patricia L.; Butler, Bret W., comps. 2006. Fuels Management. How to Measure Success: Conference Proceedings. 28-30 March 2006; Portland, OR. Proceedings RMRS-P-41. Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. pp 605&#8211;614.</li>
                </ul>
                <h4>San Dimas Technology and Development Center</h4>
                <ul class="researchpapers">
                    <li>Napper, Carolyn; Deborah S. Page-Dumroese; and Steve Howes. <a href="http://www.fs.fed.us/t-d/php/library_card.php?p_num=0819%201815P">Soil-Disturbance Field Guide 0819 1815P.</a> 2009. San Dimas, CA: U.S. Department of Agriculture, Forest Service, San Dimas Technology and Development Center. 112 p.<br /> <span class="dateupdated">[Link to document posted on 01/06/2010]</span> <br />
                    <strong>Related materials: </strong>
                    <ul>
                    	<li><a href="monitoring/forms/Point_Form_Paper_100331.xls">Download the point form from the Soil Disturbance Field Guide</a> (Excel file) <br />
               	  	  <span class="dateupdated">[brochure added 03/09/2010; last update 04/20/2010]</span></li>
            			<li><a href="monitoring/forms/Transect_Form.xls">Abbreviated Soil Monitoring Form</a> (Excel file) - This form is for 10 soil monitoring points. Can be used during a quick walk-through of the activity area.<br />
           			  <span class="dateupdated">[Link posted on 04/01/2010; last update 04/20/2010]</span></li>
           		  	  <li><a href="monitoring/forest-soil-disturbance-monitoring-protocol-toolkit/FSDMP_Toolkit_Brochure.pdf">Forest Soil-Disturbance Monitoring Protocol Toolkit Brochure</a> <br />(PDF - 4.2 MB) <br />
           		  	  <span class="dateupdated">[form added 03/09/2010]</span></li>
                      </ul>
                   </li> 
                </ul>
				<h3 class="subsection">Research Papers</h3>
					<ul class="researchpapers">
      					<li>Arnold, Julie and Chelsea Wrenn. <a href="http://forest.moscowfsl.wsu.edu/smp/solo/documents/RPs/Arnold_Wrenn_2008.pdf">Assessment of Soil Disturbance Following Silvicultural Operations Using the Draft Visual Indicators Protocol: A Region 8 Trial on the Santee Experimental Forest</a>. 2008. USDA Forest Service, Center for Forested Wetlands Research, Southern Research Station, Cordesville, SC (unpublished as of 01/06/2009). <br /><span class="dateupdated">[link to document added 02/20/2009]</span></li>
      					<li>Aust, W. Michael; James A. Burger; Emily A. Carter; David P. Preston and Steven C. Patterson. <a href="http://www.treesearch.fs.fed.us/pubs/1427">Visually determined soil disturbance classes used as indices of forest harvesting disturbance</a>. 1998. South. J. Appl. For. 22(4): 245&#8211;250. <br />
      					<span class="dateupdated">[link to document added 02/13/2009]</span></li>
      					<li>B. C. Ministry of Forests. <a href="http://www.for.gov.bc.ca/tasb/legsregs/fpc/fpcguide/SOILSURV/Soil-toc.htm">Soil Conservation Surveys Guidebook, 2nd Edition</a>. 2001. Province of British Columbia, Canada. <br />
      					<span class="dateupdated">[link to document added 02/13/2009]</span></li>
      					<li>Barkley, Yvonne C. <a href="http://www.cnr.uidaho.edu/extforest/AftertheBurnFINAL.pdf">After the burn: Assessing and managing your forestland after a wildfire</a>. 2006. Published by University of Idaho Extension for the University of Idaho Forest, Wildlife and Range Experiment Station, Moscow, Idaho. <br /><span class="dateupdated">[link to document added 02/20/2009]</span></li>
    		  			<li>Breckenridge, R. P., W. G. Kepner, and D. A. Mouat. 1995. <a href="RPs/breckenridge_1994.php">A Process for Selecting Indicators for Monitoring Conditions of Rangeland Health. (HTML)</a> Environmental Monitoring and Assessment. 36: 45&#8211;60.</li>
           		  		<li>Bulmer, Chuck; Shannon M. Berch; Mike Curran; Bill Chapman; Marty Kranabetter; Stephane Dubé; Graeme Hope; Paul Courtin and Richard Kabzems. <a href="http://www.forrex.org/publications/jem/ISS48/vol9_no2_art6.pdf">Monitoring the effects of forest practices on soil productivity and hydrologic function</a>. 2008. BC Journal of Ecosystems and Management 9(2):48&#8211;59. <br /><span class="dateupdated">[link to document added 02/20/2009]</span></li>
      					<li>Burger, James A. and Daniel L. Kelting. <a href="http://cat.inist.fr/?aModele=afficheN&cpsidt=1901911">Using soil quality indicators to assess forest stand management</a>. 1999. For. Ecol. Mgmt. 122: 155&#8211;166. <br />
      					<span class="dateupdated">[link to document added 02/13/2009]</span></li>
      					<li>Canadian Forest Service and B.C. Ministry of Forests. Forest Soil Temperature Manual (FRDA report 130)</a> (available at <a href="http://www.for.gov.bc.ca/hfd/pubs/Docs/Frr/Frr130.htm">http://www.for.gov.bc.ca/hfd/pubs/Docs/Frr/Frr130.htm</a>). 1990.</li>
      					<li>Curran, Mike; Doug Maynard; Ron Heninger; Tom Terry; Steve Howes; Doug Stone; Tom Niemann and Richard E. Miller. <a href="http://www.treesearch.fs.fed.us/pubs/30436">Elements and rationale for a common approach to assess and report soil disturbance</a>. 2007. For. Chron. 83(6): 1&#8211;15. <br />
      					  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      					<li>Curran, Michael P.; Richard E. Miller; Steven W. Howes; Douglas G. Maynard; Thomas A. Terry; Ronald L. Heniger; Thomas Niemann; Ken van Rees; Robert F. Powers and Stephen H. Schoenholtz. <a href="http://www.treesearch.fs.fed.us/pubs/27161">Progress towards more uniform assessment and reporting of soil disturbance for operations, research, and sustainability protocols</a>. 2005. For. Ecol. Mgmt. 220: 17&#8211;30. <br />
      					  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      					<li>Ford, G. L.; C. L. Maynard; J. A. Nesser; D. Page-Dumroese. <a href="RPs/Ford_etal_LTA_1996.pdf">Landtype Associations of the Northern Region, A First Approximation (PDF - 2.6 MB)</a>. 1996. (This document was expanded in 1997 and functions as the <a href="http://forest.moscowfsl.wsu.edu/smp/solo/GeoPath/lta/index.php">Landtype Associations section</a> of this SoLo web site.)</li>
			    		<li>Geist, J. M., R. T. Meurisse, T. A. Max. 1991. <a href="GTRs/INT_280/GeistMeurisse_INT-280.php">Monitoring Forest Soil Properties to Maintain Productivity. (HTML; Document in GTR-INT-280)</a> In:&nbsp; Harvey, Alan E.; Neuenschwander, Leon F., compilers. Proceedings - management and productivity of western-montane forest soils; 1990 April 10&#8211;12; Boise, ID. Gen. Tech. Rep. INT-280. Ogden UT: U. S. Department of Agriculture, Forest Service, Intermountain Research Station. pp 90&#8211;94.</li>
      					<li>Halvorson, Jonathan J., Jeffrey L. Smith, and R. I. Papendick. 1997. <a href="RPs/HalvorsonSmithPapendick.php">Issues of scale for evaluating soil quality. (HTML)</a> Journal of Soil and Water Conservation, Jan.&#8211;Feb. 1997. pp 26&#8211;30.</li>
  						<li>Herrick, J. E.; Whitford, W. G.; de Soyza, A. G.; Van Zee, J. W.; Havstad, K. M.; Seybold, C. A.; Walton, M. <em>Field soil aggregate stability kit for soil quality and rangeland health evaluations (HTML)</em>. 2001. (published in CATENA 44: 27&#8211;35 by <a href="http://www.elsevier.com/">Elsevier</a>; available for purchase at <a href="http://www.sciencedirect.com/">Science Direct</a>)</li>		
    			  		<li>Howes, Steve; John Hazard, and J. Michael Geist. 1983. <a href="RPs/HowesHazardGeist1983.pdf">Guidelines for sampling some physical conditions of surface soils.</a> (PDF - 3.2 MB) U.S. Forest Service publication R6-RWM-146-1983. Pacific Northwest Region. Portland, OR. July 1983. 34 pp.</li>
    		  			<li>National Research Council &#8211; Board on Agriculture. Rangeland Health: New Methods to Classify, Inventory, and Monitor Rangelands. (<a href="http://books.nap.edu/books/0309048796/html/97.html#pagetop">http://books.nap.edu/books/0309048796/html/97.html#pagetop</a>) Washington, DC: National Academy Press, 1994.</li>
  						<li>Page-Dumroese, D.; Harvey, A.; Jurgensen, M. <a href="GTRs/INT_326/GTR326.php">A Guide to Soil Sampling and Analysis on the National Forests of the Inland Northwest United States (HTML)</a>. United States Department of Agriculture, Forest Service, Intermountain Research Station - General Technical Report, INT-GTR-326, October 1995.</li>		
  						<li>Page-Dumroese, D. S., A. E. Harvey, M. F. Jurgensen and M. P. Amaranthus. Comparison methods for determining bulk densities of rocky forest soils. 1999. (abstract is available at <a href="http://soil.scijournals.org/cgi/content/abstract/63/2/379">Soil Science Society of America Journal</a>) </li>		
      					<li><a href="MISC/rangeland_health_tables.pdf">Rangeland Health Criteria Tables (PDF - 76 KB)</a> - applies to eastern Montana forests that contain open rangeland</li>
						<li>Reeves, Derrick, Deborah Page-Dumroese and Mark Coleman. <a href="RPs/Reeves_Page-Dumroese_Coleman_rmrs_rp089.pdf">&#8220;Detrimental Soil Disturbance Associated with Timber Harvest Systems on National Forests in the Northern Region.&#8221; (PDF file - 1.89 MB)</a> RMRS-RP-89, June 2011. <br /><span class="dateupdated">[document added 07/06/2011]</span></li>
      					<li>Wilson, S. D. and H. R. Kleb. 1996. The influence of prairie and forest vegetation on soil moisture and available nitrogen. The American Midland Naturalist. 136: 222&#8211;231.</li>
					</ul>	
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
  			<h2 class="section">PRODUCTIVITY<a name="productivity">&nbsp;</a></h2>
				<h3 class="firstsection"><abbr title="Forest Service">FS</abbr> Research Handbooks and Manuals</h3>
				<ul class="researchpapers">
      		<li>Moll, Jeffry E. A Guide to Road Closure and Obliteration in the Forest Service. (PDF available at <a href="http://www.fs.fed.us/eng/php/library_card.php?p_num=9677%201205">USDA Forest Service Engineering Publications</a>). 1996.</li>
				</ul>
				<h3 class="subsection">Symposium Proceedings/General Technical Reports (GTRs)</h3>
				<h4>Intermountain Research Station (Later renamed Rocky Mountain Research Station)</h4>
				<ul class="researchpapers">
      				<li><strong>GTR-INT-374 &#8211;</strong> Harvey, Alan E., Martin F. Jurgensen, Michael J. Larsen and Joyce A. Schlieter. <a href="GTRs/INT_374/Harvey_INT-374_1986.pdf">Distribution of Active Ectomycorrhizal Short Roots in Forest Soils of the Inland Northwest: Effects of Site and Disturbance</a> (PDF - 620 KB). 1986.</li>
      				<li><strong>GTR-INT-341 &#8211;</strong> Hardy, Colin C. and Steven F. Arno. eds. The Use of Fire in Forest Restoration. (A General Session at the Annual Meeting of the Society for Ecological Restoration, Seattle, WA, September 14&#8211;16, 1995.) [table of contents and selected papers available at <a href="http://www.fs.fed.us/rm/pubs/int_gtr341/">http://www.fs.fed.us/rm/pubs/int_gtr341/</a>]. 1996.</li>
					<li><strong>GTR-INT-280 &#8211;</strong> <a href="../InfoPath/productivity/bibliography/GTR_INT-280.php"><strong>Proceedings&#8212;Management and Productivity of Western-Montane Forest Soils</strong></a>, April 10&#8211;12, 1990, Boise, ID, USDA Forest Service General Technical Report INT-280, August 1991.
  					<ul class="researchpapers">
  					<li><a name="gtrint280a"></a>Amaranthus, M. P. <a href="GTRs/INT_280/Amaranthus_INT-280.php">Factors Affecting Ectomycorrhizae and Forest Regeneration Following Disturbance in the Pacific Northwest (HTML)</a></li>
						<li>Binkley, D. <a href="GTRs/INT_280/Binkley_INT-280.php">Connecting Soils with Forest Productivity (HTML)</a></li>
						<li>Bosworth, B.; Studer D. <a href="GTRs/INT_280/Bosworth_INT-280.php">Comparisons of Tree Height Growth on Broadcast-Burned, Bulldozer-Piled, and Nonprepared Sites 15 to 25 Years After Clearcut Logging (HTML)</a></li>
						<li>DeBano, L. F. <a href="GTRs/INT_280/DeBano_INT-280.php">The Effect of Fire on Soil Properties (HTML)</a></li>
						<li>Edmonds, R. L. <a href="GTRs/INT_280/Edmonds_INT-280.php">Organic Matter Decomposition in Western United States Forests (HTML)</a></li>
						<li>Everett, R.; Zabowski, D.; McColley, P. <a href="GTRs/INT_280/Everett_INT-280.php">Vegetative Restoration of Western-Montane Forest Soils (HTML)</a></li>
						<li>Geist, J. M. ; Cochran, P. H. <a href="GTRs/INT_280/GeistCochran_INT-280.php">Influences of Volcanic Ash and Pumice Deposition on Productivity of Western Interior Forest Soils (HTML)</a></li>
						<li>Geist, J. M.; Meurisse, R. T.; Max, T. A. <a href="GTRs/INT_280/GeistMeurisse_INT-280.php">Monitoring Forest Soil Properties to Maintain Productivity (HTML)</a></li>
						<li>Graham, R. T.; Minore, D.; Harvey, A. E.; Jurgensen, M. F.;. Page-Dumroese, D. S. <a href="GTRs/INT_280/Graham_INT-280.php">Soil Management as an Integral Part of Silvicultural Systems (HTML)</a></li>
						<li>Harvey, A. E.; Page-Dumroese, D. S.; Graham, R. T.; Jurgensen, M. F. <a href="GTRs/INT_280/Harvey_INT-280.php">Ectomycorrhizal Activity and Conifer Growth Interactions in Western-Montane Forest Soils (HTML)</a></li>
						<li>Hironaka, M.; Fosberg, M. A.; Neiman, K. E. Jr. <a href="GTRs/INT_280/Hironaka_INT-280.php">The Relationship Between Soils and Vegetation (HTML)</a></li>
						<li>Hungerford, R. D.; Harrington, M. G.; Frandsen, W. H.; Ryan, K. C.; Niehoff, G. J. <a href="GTRs/INT_280/Hungerford_INT-280.php">Influence of Fire  on Factors that Affect Site Productivity (HTML)</a></li>
						<li>Jensen, M. E. <a href="../documents/GTRs/INT_280/Jensen_MontaneProc_1990.pdf">Ecological Classification and Cumulative Soil Effects</a> (PDF - 449 KB)</li>
						<li>Jurgensen, M. F.; Tonn, J. R.; Graham, R. T.; Harvey, A. E.; Geier-Hayes, K. <a href="GTRs/INT_280/Jurgensen_INT-280.php">Nitrogen Fixation in Forest Soils of the Inland Northwest (HTML)</a></li>
						<li>Megahan, W. F. <a href="GTRs/INT_280/Megahan_INT-280.php">Erosion and Site Productivity in Western-Montane Forest Ecosystems (HTML)</a></li>
						<li>Meurisse, R. T.; Robbie, W. A.; Niehoff, G. J.; Ford, G. <a href="GTRs/INT_280/Meurisse_INT-280.php">Dominant Soil Formation Processes and Properties in Western-Montane Forest Types and Landscapes&#8212;Some Implications for Productivity and Management (HTML)</a></li>
						<li>Molina, R.; Amaranthus, M. <a href="GTRs/INT_280/Molina_INT-280.php">Rhizosphere Biology: Ecological Linkages Between Soil Processes, Plant Growth, and Community Dynamics (HTML)</a></li>
						<li>Page-Dumroese, D.; Harvey, A.; Jurgensen, M.; Graham, R. <a href="GTRs/INT_280/PageDumroese_INT-280.php">Organic Matter Function in the Western-Montane Forest Soil System (HTML)</a></li>
						<li>Page-Dumroese, D.; Graham, R. T.; Harvey, A. E. <a href="GTRs/INT_280/PageDumroesePoster_INT-280.php">Soil Organic Matter Effects on Douglas-Fir Growth in Northern Idaho Soils (HTML)</a></li>
						<li>Powers, R. F. <a href="GTRs/INT_280/Powers_INT-280.php">Are We Maintaining the Productivity of Forest Lands? Establishing Guidelines Through a Network of Long-Term Studies (HTML)</a></li>
						<li>Sommer, M.; Adams, D.; Mahler, R. <a href="GTRs/INT_280/SommerPoster_INT-280.php">Soil Properties as a Factor in Regeneration Failures in the Grand Fir Mosaic&#8212;Preliminary Results (HTML)</a></li>
						<li>Stark, N. M.; Zuuring, H. <a href="GTRs/INT_280/Stark_INT-280.php">Minimizing the Adverse Impacts of Timber Harvest in the Northern Rocky Mountains (HTML)</a></li>
						<li>Steele, R.; Pfister, R. D. <a href="GTRs/INT_280/Steele_INT-280.php">Western-Montane Plant Communities and Forest Ecosystem Perspectives (HTML)</a></li>
						<li>Verbyla, D. L. <a href="GTRs/INT_280/Verbyla_INT-280.php">Validation of Soil-Site Models (HTML)</a></li>
					</ul> 
					</li>
   				  <li><strong>GTR-INT-264 &#8211;</strong> Burroughs, Edward R. Jr. and John G. King. <a href="GTRs/INT_264/INT-264_ReducSoilEro_1989.pdf">Reduction of Soil Erosion on Forest Roads (PDF - 1.9 MB)</a>. 1989. <br /><span class="dateupdated">[Document added to SoLo on 11/27/2006]</span></li>
  					<li><strong>GTR-INT-110 &#8211;</strong> <a href="GTRs/INT_110/INT-110_HarvRes_1979.pdf">Harvesting and Utilization Opportunities for Forest Residues in the Northern Rocky Mountains: Symposium Proceedings (PDF - 10.3 MB)</a>, Sept. 11&#8211;13, 1979, Missoula, MT, USDA Forest Service General Technical Report INT-110, September 1980.</li>
  					<li><strong>GTR-INT-90 &#8211;</strong> <a href="GTRs/INT_90/INT-90_Harvest_1979.pdf">Environmental Consequences of Timber Harvesting in Rocky Mountain Coniferous Forests: Symposium Proceedings (PDF - 19.7 MB)</a>, Sept. 11&#8211;13, 1979, Missoula, MT, USDA Forest Service General Technical Report INT-90, September 1980.</li>
      				<li><strong>GTR-INT-65 &#8211;</strong> Harvey, Alan E., Martin F. Jurgensen and Michael J. Larsen. <a href="GTRs/INT_65/Harvey1979_GTR-INT-65.pdf">Role of Forest Fuels in the Biology and Management of soil</a> (PDF - 4.4 MB). 1979. <br />
   				  <span class="dateupdated">[Document added to SoLo on 03/07/2008]</span></li>
      				<li><strong>GTR-INT-28 &#8211;</strong> Harvey, Alan E., Martin F. Jurgensen and Michael J. Larsen. <a href="GTRs/INT_28/INT-28_FiberUtil_1976.pdf">Intensive Fiber Utilization and Prescribed Fire: Effects on the Microbial Ecology of Forests (PDF - 3.1 MB)</a>. 1976. <br /><span class="dateupdated">[Document added to SoLo on 11/27/2006]</span></li>
				</ul>				
				<h4>Pacific Northwest Research Station</h4>
				<ul class="researchpapers">
      				<li><strong>GTR-PNW-840 &#8211;</strong> Reynolds, Keith M., Paul F. Hessburg, Richard E. Miller, and Robert T. Meurisse. <a href="http://www.treesearch.fs.fed.us/pubs/38190">Evaluating Soil Risks Associated With Severe Wildfire and Ground-Based Logging</a>. 2011. <br /><span class="dateupdated">[Link to document added 09/09/2011]</span></li>
      				<li><strong>GTR-PNW-811 &#8211;</strong> Miller, Richard E., James D. McIver, Steven W. Howes and William B Gaeuman. <a href="http://www.treesearch.fs.fed.us/pubs/35150">Assessment of Soil Disturbance in Forests of the Interior Columbia River Basin: A Critique</a>. 2010. <br /><span class="dateupdated">[Link to document added 07/30/2010]</span></li>
				<li><strong>GTR-PNW-802 &#8211; </strong>Pye J.M., H.M. Rauscher, Y. Sands, D.C. Lee, and J. S. Beatty, Technical Eds. <a href="http://www.treesearch.fs.fed.us/pubs/36650">Advances in Threat Assessment and Their Application to Forest and Rangeland Management, Volume 1</a>. September 2010. <br />
				<span class="dateupdated">[Link added to SoLo on 05/04/2011]</span></li>
      				<li><strong>GTR-PNW-759 &#8211;</strong> Erickson, Heather E.; White, Rachel. <a href="http://www.treesearch.fs.fed.us/pubs/29927">Soils under fire: soils research and the Joint Fire Science Program</a>. 2008.</li>
      				<li><strong>GTR-PNW-362 &#8211;</strong> Cooper, Stephen V., Peter Lesica and Deborah Page-Dumroese. Plant Community Classification for Alpine Vegetation on the Beaverhead National Forest, Montana (available at <a href="http://treesearch.fs.fed.us/pubs/35499">http://treesearch.fs.fed.us/pubs/35499</a>). 1997. <br /><span class="dateupdated">[Link to document added 07/30/2010]</span></li>
      				<li><strong>GTR-PNW-323 &#8211;</strong> Harvey, Alan E., Michael Geist, Gerald McDonald, Martin F. Jurgensen, Patrick H. Cochran, Darlene Zabowski and Robert T. Meurisse. <a href="http://www.treesearch.fs.fed.us/pubs/6286">Biotic and Abiotic Processes in Eastside Ecosystems: The Effects of Management on Soil Properties, Processes, and Productivity</a>. 1994.</li>
				</ul>				
				<h4>Rocky Mountain Research Station (formerly called Intermountain Research Station)</h4>
				<ul class="researchpapers">
      				<li><strong>RMRS-GTR-215 &#8211;</strong> Rawinski, John J. and Deborah S. Page-Dumroese. <a href="http://www.treesearch.fs.fed.us/pubs/30957">Soil compaction monitoring of the Pool Timber Sale, Rio Grande National Forest, Colorado 16 years after logging</a>. 2008. <br /><span class="dateupdated">[link to document added 02/20/2009]</span></li>
      				<li><strong>RMRS-P-44 &#8211;</strong> Page-Dumroese, Deborah; Miller, Richard; Mital, Jim; McDaniel, Paul; Miller, Dan, tech. eds. <strong>Volcanic-Ash-Derived Forest Soils of the Inland Northwest: Properties and Implications for Management and Restoration</strong>.  [entire proceedings available at <a href="http://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-44.pdf">http://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-44.pdf (PDF - 6.7 MB)</a>; individual papers can be downloaded separately at <a href="http://www.fs.fed.us/rm/pubs/rmrs_p044.html">http://www.fs.fed.us/rm/pubs/rmrs_p044.html</a>]. 2007. (Conference was held November 9&#8211;10, 2005 in Coeur d'Alene, Idaho.)</li>
      				<li><strong>GTR-RMRS-42 &#8211;</strong> Neary, Daniel G.; Ryan, Kevin C.; DeBano, Leonard F., eds. <a href="http://www.fs.fed.us/rm/pubs/rmrs_gtr042_4.pdf">Wildland Fire in Ecosystems: Effects of Fire on Soil and Water</a>. 2005 (revised 2008). <br /><span class="dateupdated">[Document added to SoLo on 09/11/2008]</span></li>
				</ul>				
				<h4>Miscellaneous GTRs and Proceedings</h4>
				<ul class="researchpapers">
  					<li><strong>WO-WSA-2 &#8211;</strong> <a href="../documents/MISC/WO-WSA-2/WO-WSA-2_ProcSoilQualSt_1992.pdf">Proceedings of the Soil Quality Standards Symposium (PDF - 4 MB)</a>, Oct. 23, 1990, San Antonio, TX, USDA Forest Service Watershed and Air Management, WO-WSA-2, Washington D.C., February 1992.</li>
				</ul>				
				<h3 class="subsection">Research Papers and Notes</h3>
				<ul class="researchpapers">
      				<li>Adams, P. W.; H. A. Froehlich. <a href="RPs/Adams_Froehlich_1984.pdf">Compaction of Forest Soils (PDF - 1.3 MB)</a>. 1984.</li>
      				<li>Amaranthus, Michael P. and David E. Steinfeld. <a href="RPs/Amaranthus_PNW-RP-504_1997.pdf">Soil compaction after yarding of small-diameter Douglas-fir with a small tractor in southwest Oregon</a> (PDF - 707 KB). 1997. </li>
   				  	<li>Amaranthus, Michael P., Debbie Page-Dumroese, Al Harvey, Efren Cazares and Larry F. Bednar. <a href="http://forest.moscowfsl.wsu.edu/smp/docs/docs/Amaran_PNW-RP-494_1996.html">Soil compaction and organic matter affect conifer seedling nonmycorrhizal and ectomycorrhizal root tip abundance and diversity</a> (HTML). 1996. </li>
   				  	<li>Andrus, C. W.; H. A. Froehlich. <a href="RPs/Andrus_Froehlich_1983.pdf">An Evaluation of Four Implements Used to Till Compacted Forest Soils in the Pacific Northwest (PDF - 1.2 MB)</a>. 1983.</li>
					<li>Angima S.D. and T. A. Terry. 2011. <a href="http://hdl.handle.net/1957/20678">Best Management Practices for Maintaining Soil Productivity in the Douglas-fir Region</strong>. Oregon State University Extension Service. 44 p.<br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
              		<li>Arno, S. F. Forest fire history in the Northern Rockies. 1980. <a href="http://www.safnet.org/periodicals/jof/">Journal of Forestry</a> 78(8): 460&#8211;465.</li>
      				<li>Arno, Stephen F. <a href="RPs/Arno_RP-INT-187_1976.pdf">The historical role of fire on the Bitterroot National Forest</a> (PDF - 2.34 MB). 1976. (<strong>RP-INT-187</strong>)</li>
      				<li>Azuma, David L. and Glenn A. Christensen. <a href="http://www.fs.fed.us/pnw/pubs/pnw_rp560.pdf">Southwest Oregon Biscuit Fire: An analysis of forest resources and fire severity</a>. 2004. USDA Forest Service, Pacific Northwest Research Station, PNW-RP-560.<br /><span class="dateupdated">[Document linked to SoLo on 02/13/2009]</span></li>
      				<li>B. C. Ministry of Forests. <a href="http://faculty.forestry.ubc.ca/bendickson/FOPRLibrary/Library/M%20o%20F%20Guidebooks%20&%20Pubications/Soil%20&%20Windthrow/Hazard%20Assess%20Keys.pdf">Hazard Assessment Keys for Evaluating Site Sensitivity to Soil Degrading Processes Guidebook, 2nd Edition, Ver. 2.1</a>. 1999. Province of British Columbia, Canada. <br />
      				<span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  <li>Belnap, J. <a href="RPs/belnap_se-UT_1998.php">Impacts of Trampling Soils in Southeast Utah Ecosystems (HTML)</a>. 1998?</li>
      				<li>Benson, Robert E. <a href="RNs/Benson_RN-INT-294_1980.pdf">Damage from logging and prescribed burning in partially cut Douglas-fir stands</a> (PDF - 846 KB). 1980. (<strong>RN-INT-294</strong>)</li>
           		  	<li>Bissett, J. and D. Parkinson. Long-term effects of fire on the composition and activity of the soil microflora of a subalpine, coniferous forest. 1980. <a href="http://www.ingentaconnect.com/content/nrc/cjb">Canadian Journal of Botany</a> 58: 1704-1721.</li>
					<li>Blank, R. T.; T. Svejcar. <a href="RPs/blank_2000.php">Grazing Influences on Selected Soil Attributes in a Sierra Nevada Riparian Meadow (HTML)</a>. Proceedings, AWRA's 2000 summer specialty conference: riparian ecology and management in multi-land use watersheds: August 28&#8211;31, 2000, Portland, Oregon. Middleburg, VA: American Water Resources Association, c2000. Technical publication series; no. TPS 00-2: p. 269&#8211;273.</li>
      				<li>Bock, Michael D. and Ken C. J. Van Rees. <a href="http://www.ingentaconnect.com/content/nrc/cjfr/2002/00000032/00000008/art00008;jsessionid=1fzeu39o1wz82.alexandra">Mechanical site preparation impacts on soil properties and vegetation communites in the Northwest Territories</a>. 2002. Can. J. For. Res. 32: 1381&#8211;1392. <br />
      				<span class="dateupdated">[link to document added 02/13/2009]</span></li>
           		  	<li>Brantley, Susan L. <a href="http://www.sciencemag.org/cgi/search?volume=321&firstpage=1454&journal_search_volume_go.x=17&journal_search_volume_go.y=5&journal_search_volume_go=go&andorexactfulltext=and&andorexacttitleabs=and">Understanding soil time</a>. 2008. Science. 321: 1454&#8211;1455<br /><span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Busse, Matt D.; Samual E. Beattie; Robert F. Powers; Felipe G. Sanchez and Allan E. Tiarks. <a href="http://www.treesearch.fs.fed.us/pubs/22169">Microbial community responses in forest mineral soil to compaction, organic matter removal, and vegetation control</a>. Can. J. For. Res. 2006. 36(3): 577&#8211;588.</li>
      				<li>Carter, Mason C.; Thomas J. Dean; Ziyin Wang and Ray A. Newbold. <a href="http://www.treesearch.fs.fed.us/pubs/25274">Impacts of harvesting and postharvest treatments on soil bulk density, soil strength, and early growth of Pinus taeda in the Gulf Coastal Plain: a Long-Term Soil Productivity affiliated study</a>. Can. J. For. Res. 2006. 36(3): 601&#8211;614.</li>
      				<li>Carter, Mason C. and C. Darwin Foster. <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4BFPF4K-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=1c3cf225e65f0669cdfce09d1ed976db">Prescribed burning and productivity in southern pine forests: a review</a>. 2004. For. Ecol. Mgmt. 191: 93&#8211;109. <br />
      				<span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Cline, Richard G. and Gaylon S. Campbell. <a href="http://www.esajournals.org/doi/abs/10.2307/1934826">Seasonal and diurnal water relations of selected forest species</a>. 1976. Ecology 57(2): 367&#8211;373. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  <li>Cline, Richard G.; Jerry Ragus; Gary D. Hogan; Doug G. Maynard; Neil W. Foster; Thomas A. Terry; Ronald L. Heninger; Robert G. Campbell and Mason C. Carter. <a href="http://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?cjfr_x05-266_36_ns_nf_cjfr">Policies and practices to sustain soil productivity: perspectives from the public and private sectors</a>. Can. J. For. Res. 2006. 36(3): 615&#8211;625.</li>
					<li>Coleman, Mark; Page-Dumroese, Deborah; Archuleta, Jim; Badger, Phil; Chung, Woodum; Venn, Tyron; Loeffler, Dan; Jones, Greg; McElligott, Kristin. 2010. <a href="http://www.treesearch.fs.fed.us/pubs/37322">Can portable pyrolysis units make biomass utilization affordable while using bio-char to enhance soil productivity and sequester carbon?</a>. In: Jain, Theresa B.; Graham, Russell T.; Sandquist, Jonathan. Integrated management of carbon sequestration and biomass utilization opportunities in a changing climate: Proceedings of the 2009 National Silviculture Workshop; 2009 June 15&#8211;18; Boise, ID. Proceedings RMRS-P-61. Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. p. 159&#8211;168. <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
              		<li>Conlin, T. S. S. and R. van den Driessche. <a href="http://www.for.gov.bc.ca/hfd/pubs/docs/Frr/Frr264.pdf">Soil Compaction Studies.</a> 1996. Canadian Forest Service and B.C. Ministry of Forests<br /><span class="dateupdated">[link to document added 02/13/2009]</span></li>
                   	<li>Cromer, R. N. and R. G. Vines. 1966. Soil temperatures under a burning windrow. Aust. For. Res. 2: 29&#8211;34.</li>
      				<li>Curran, Michael, P.; Douglas G. Maynard; Ronald L. Heninger; Thomas A. Terry; Steven W. Howes; Douglas M. Stone; Thomas Niemann; Richard E. Miller and Robert F. Powers. <a href="http://www.treesearch.fs.fed.us/pubs/25522">An adaptive management process for forest soil conservation</a>. 2005. For. Chron. 81(5): 717&#8211;722. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  <li>Daddow, R. L. and G. E. Warrington. <a href="RPs/daddow_warrington_root_limiting_bulk_density.pdf">Growth-limiting Soil Bulk Densities as Influenced by Soil Texture</a> (PDF - 104 KB). 1983. Watershed Systems Development Group Report: WSDG-TN-00005.</li>
              		<li>Davis, K. P. and K. A. Klehm. <a href="http://www.ingentaconnect.com/content/saf/jof/1939/00000037/00000005/art00014">Controlled burning in the Western White Pine type.</a> 1939.</li>
      				<li>Davis, S. <a href="RPs/Davis_1983.pdf">Effectiveness of a Winged Subsoiler in Ameliorating a Compacted Clayey Forest Soil (PDF - 316 KB)</a>. 1983.</li>
					<li>DeByle, N. V. 1976. <a href="RPs/DeByle_USGovtPub_1976.pdf">Fire, logging, and debris disposal effects on soil and water in northern coniferous forests (PDF - 729 KB)</a>. International Union of Forest Research Organizations, Div. 1, Proceedings XVI IUFRO World Congr. Oslo, Norway. U.S. Government Printing Office. p. 201&#8211;212.</li>
      				<li>DeLuca, T. H. and K. L. Zouhar. <a href="http://www.ingentaconnect.com/content/els/03781127/2000/00000138/00000001/art00401;jsessionid=7hbdg473119ch.alice?format=print">Effects of selection harvest and prescribed fire on the soil nitrogen status of ponderosa pine forests</a>. 2000. For. Ecol. Mgmt. 138: 263&#8211;271. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
					<li>Dumroese, R. Kasten; Heiskanen, Juha; Englund, Karl; Tervahauta, Arja  2011. <a href="http://www.treesearch.fs.fed.us/pubs/37521">Pelleted biochar: chemical and physical properties show potential use as a substrate in container nurseries</a>. Biomass &amp; Bioenergy. 35: 2018&#8211;2027. <br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
					<li>Dumroese, R. Kasten; Page-Dumroese, Deborah S.; Brown, Robert E.  2011. <a href="http://www.treesearch.fs.fed.us/pubs/37877">Allometry, nitrogen status, and carbon stable isotope composition of Pinus ponderosa seedlings in two growing media with contrasting nursery irrigation regimes</a>. Canadian Journal of Forest Research. 40: 1091&#8211;1101. <br />
					<span class="dateupdated">[link added 05/23/2011]</span></li>
           		  <li>Entry, J. A.; N. M. Stark and H. Loewenstein. <a href="http://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?calyLang=eng&journal=cjfr&volume=16&year=0&issue=5&msno=x86-186">Effect of timber harvesting on microbial biomass fluxes in a northern Rocky Mountain forest soil.</a> 1986.</li>
      				<li>Fahnestock, George R. <a href="RPs/Fahnestock_RP-INT-70_1962.pdf">Logging slash flammability after five years</a> (PDF - 2.58 MB). 1962. (<strong>RP-INT-70</strong>)</li>
           			<li>Feller, M. C. <a href="http://miva.crownpub.bc.ca/Merchant2/merchant.mvc?Screen=PROD&Product_Code=013-833&Category_Code=CP-02-01-40-25">The Ecological Effects of Slashburning with particular reference to British Columbia: A Literature Review</a>. 1982.</li>
      				<li>Fleming, R. L.; T. A. Black and N. R. Eldridge. <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4915VW5-5&_user=10&_coverDate=10%2F31%2F1994&_alid=836033404&_rdoc=1&_fmt=high&_orig=search&_cdi=5042&_sort=d&_docanchor=&view=c&_ct=1&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=7413e05b413a64c9d9ef8aa106028071">Effects of site preparation on root zone soil water regimes in high-elevation forest clearcuts</a>. 1994. For. Ecol. Mgmt. 68: 173&#8211;188. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  <li>Fleming, Robert L.; Michael F. Laporte; Gary D. Hogan and Paul W. Hazlett. <a href="http://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_f?cjfr_x05-258_36_ns_nf_cjfr3-06">Effects of harvesting and soil disturbance on soil CO<sub>2</sub> efflux from a jack pine forest</a>. Can. J. For. Res. 2006. 36(3): 589&#8211;600.</li>
      				<li>Fleming, Robert L.; Robert F. Powers; Neil W. Foster; J. Marty Kranabetter; D. Andrew Scott; Felix Ponder, Jr.; Shannon Berch; William K. Chapman; Richard D. Kabzems; Kim H. Ludovici; David M. Morris; Deborah S. Page-Dumroese; Paul T. Sanborn; Felipe G. Sanchez; Douglas M. Stone and Allan E. Tiarks. <a href="http://www.treesearch.fs.fed.us/pubs/22170">Effects of organic matter removal, soil compaction, and vegetation control on 5-year seedling performance: a regional comparison of Long-Term Soil Productivity sites</a>. Can. J. For. Res. 2006. 36(3): 529&#8211;550.</li>
      				<li>Ford, G. L.; C. L. Maynard; J. A. Nesser; D. Page-Dumroese. <a href="RPs/Ford_etal_LTA_1996.pdf">Landtype Associations of the Northern Region, A First Approximation (PDF - 2.6 MB)</a>. 1996.</li>
             		<li>Frandsen, W. H. and K. C. Ryan. <a href="http://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=16&year=&issue=&msno=x86-043&calyLang=eng">Soil moisture reduces belowground heat flux and soil temperatures under a burning fuel pile.</a> 1986.</li>
      				<li>Froehlich, H. A.; D. H. McNabb. <a href="RPs/Froehlich_McNabb_1983.pdf">Minimizing Soil Compaction in Pacific Northwest Forests (PDF - 2.7 MB)</a>. 1983.</li>
      				<li>Froehlich, H. A.; D. W. R. Miles. <a href="RPs/Froehlich_Miles_1984.pdf">Winged subsoiler tills compacted forest soils (PDF - 436 KB)</a>. 1984.</li>
      				<li>Geist, M. J.; H. A. Froehlich. <a href="RPs/Geist_Froehlich.pdf">Principles and Processes of Subsoiling in Forest Ecosystems (PDF - 456 KB)</a>.</li>
      				<li>Gent, J. A.; H. L. Allen; Robert G. Campbell and C. G. Wells. <a href="http://www.ingentaconnect.com/content/saf/sjaf/1986/00000010/00000003/art00004">Magnitude, duration, and economic analysis of Loblolly Pine growth response following bedding and phosphorus fertilization</a>. 1986. South. J. Appl. For. 10(3): 124&#8211;128. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
               	  <li>Gore, J. A. and W. A. Patterson III. <a href="http://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?calyLang=eng&journal=cjfr&volume=16&year=0&issue=2&msno=x86-057">Mass of downed wood in northern hardwood forests in New Hampshire: potential effects of forest management.</a> 1986.</li>
      				<li>Greacen, E. L.; R. Sands. <a href="RPs/Greacen_Sands_1980.pdf">Compaction of Forest Soils: A Review (PDF - 2.7 MB)</a>.</li>
      				<li>Gundale, Michael J.; Thomas H. DeLuca; Carl E. Fiedler; Philip W. Ramsey; Michael G. Harrington and James E. Gannon. <a href="http://www.fs.fed.us/ffs/docs/Gundale_etal_2005.pdf">Restoration treatments in a Montana ponderosa pine forest: Effects on soil physical, chemical and biological properties</a>. 2005. For. Ecol. Mgmt. 213: 25&#8211;38.<br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
					<li>Han, H.-S.; D. S. Page-Dumroese; S.-K. Han and J. Tirocke. Effects of slash, machine passes, and soil moisture on penetration resistance in a cut-to-length harvesting. <a href="http://www.lib.unb.ca/Texts/JFE/index.html">International Journal of Forest Engineering</a>. 2006. 17(2): 11&#8211;24.</li>
					<li>Han, S.-K.; H.-S. Han; D. S. Page-Dumroese; and L. R. Johnson. <a href="http://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=39&year=2009&issue=5&msno=x09-027&calyLang=eng">Soil compaction associated with cut-to-length and whole-tree harvesting of a coniferous forest</a>. 2009. Can. J. For. Res. 39: 976&#8211;989. <br /><span class="dateupdated">[link to publication added 05/19/2009]</span></li>
      				<li>Hardesty, Linda, Christopher E. Gebauer and John Buckhouse. <a href="RPs/Hardesty_Grazing_1996.pdf">Forest Soil Characteristics After Twenty-Six Years of Cattle and Big Game Grazing in Northeastern Oregon</a> (PDF - 518 KB). 1996. (Part of the Northern Region Soils Workshop, May 20-22, 1997.) <br />
      				</li>
               		<li>Harvey, A. E.; M. F. Jurgensen and R. T. Graham. <a href="http://cru84.cahe.wsu.edu/cgi-bin/pubs/MISC0231.html">Fire-soil interactions governing site productivity in the northern Rocky Mountains.</a> 1999.</li>
					<li>Harvey, Alan E., Michael J. Larsen and Martin F. Jurgensen. <a href="http://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_desc_e?cjfr">Partial cut harvesting and ectomycorrhizae: early effects in Douglas-fir-larch forests of western Montana</a>. 1980b. Canadian Journal of Forest Research. 10(3): 436&#8211;440.</li>
      				<li>Hatten, J. A.; D. Zabowski; A. Ogden and W. T. <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4S02JX3-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=321f7263572a92c1edc0fe4d60dc1ab4">Soil organic matter in a ponderosa pine forest with varying seasons and intervals of prescribed burn</a>. 2008. For. Ecol. Mgmt. 255: 2555&#8211;2565. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  <li>Heninger, Ronald; William Scott; Alex Dobkowski; Richard Miller; Harry Anderson and Steve Duke. <a href="http://www.ingentaconnect.com/content/nrc/cjfr/2002/00000032/00000002/art00006">Soil disturbance and 10-year growth response of coast Douglas-fir on nontilled and tilled skid trails in the Oregon Cascades</a>. 2002. Can. J. For. Res. 32: 233&#8211;246. <br />
   				    <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Heninger, R.; W. Scott; R. Miller; H. Anderson. <a href="RPs/Heninger_etal_1983.pdf">Case Study: Growth of Douglas-fir on Cultivated and Non-Cultivated Skid Trails in Coastal Washington and Western Oregon (PDF - 112 KB)</a>. 1983.</li>
      				<li>Hermann, Richard K. <a href="http://www.ingentaconnect.com/content/saf/jof/1964/00000062/00000002/art00006">Paper mulch for reforestation in southwestern Oregon</a>. 1964. Journ. of For. 62(2): 98&#8211;101. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
           		  <li>Hesterberg, G. A. and M. F. Jurgensen. <a href="http://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?tfc_tfc48092-2_48_ns_nf_tfc">The relation of forest fertilization to disease incidence.</a> 1972.</li>
                   	<li>Humphreys, F. R. and Marcia J. Lambert. 1965. Soil temperature profiles under slash and log fires of various intensities. Australian For. Res. 1?: 23&#8211;29.</li>
					<li>Johnson L.R., D. Page-Dumroese, and H.-S. Han. 2007. <a href="http://www.treesearch.fs.fed.us/pubs/26213">Effects of Machine Traffic on the Physical Properties of Ash-Cap Soils</a>. In: Page-Dumroese, Deborah; Miller, Richard; Mital, Jim; McDaniel, Paul; Miller, Dan, tech. eds. 2007. Volcanic-Ash-Derived Forest Soils of the Inland Northwest: Properties and Implications for Management and Restoration. 9&#8211;10 November 2005; Coeur d?&#8217;Alene, ID. Proceedings RMRS-P-44; Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. p. 69&#8211;82.<br />
					<span class="dateupdated">[link added 05/04/2011]</span></li>
					<li>Jurgensen, M. F.; A. E. Harvey; M. J. Larsen. <a href="RPs/Jurgensen1981_RP-INT-275.pdf">Effects of Prescribed Fire on Soil Nitrogen Levels in a Cutover Douglas-fir/Western Larch Forest (PDF - 3.7 MB)</a>. 1981. Research Paper INT-275.</li>
					<li>Jurgensen, M. F.; A. E. Harvey; R. T. Graham; D. S. Page-Dumroese; J. R. Tonn; M. J. Larsen; T. B. Jain. <a href="RPs/Jurgensen_etal_97.php">Impacts of Timber Harvesting on Soil Organic Matter, Nitrogen, Productivity, and Health of Inland Northwest Forests (HTML)</a>. 1997.</li>
					<li>Jurgensen, M. F.; M. J. Larsen; A. E. Harvey. <a href="RPs/Jurgensen_etal_SocAmFor_1978.pdf">Effects of timber harvesting on soil biology (PDF - 483 KB)</a>. 1978. Presented at the Society of American Foresters National Convention, 1977. <br /><span class="dateupdated">[publication added 02/27/2009]</span></li>
      				<li>Kavanagh, Kathleen; George Stankey and Jim Boyle. <a href="http://www.ingentaconnect.com/content/klu/nefo/1999/00000018/00000001/00195701;jsessionid=7aoqtab0ea3ka.alice?format=print">The integration of planted and natural forests in a regional landscape</a>. 1999. New Forests 18: 97&#8211;109. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
	      		  	<li>Klock, G. O. and C. C. Grier. 1981. Effects of Fire on the Long-term Maintenance of Forest Productivity.  In: Gessel, S.P.; Kenady, R.M.; Atkinson, W.A., eds. Proceedings, Forest fertilization conference; 1979 September 25-27; Union, WA. Institute of Forest Resources Cont. 40. Seattle, WA: <a href="http://www.washington.edu/">University of Washington</a>, College of Forest Resources: 247&#8211;250.</li>  
      				<li>Kruse, William H. <a href="RNs/Kruse_RN-RM-226_1972.pdf">Effects of wildfire on elk and deer use of a Ponderosa Pine forest</a> (PDF - 680 KB). 1972. (<strong>RN-RM-226</strong>)</li>
					<li>Kuennen, Louis; Garry Edson and Timothy V. Tolle. <a href="RPs/Kuennen_etal_1979.pdf">Soil compaction due to timber harvest activities (PDF - 187 KB)</a>. 1979. Published in the USDA Forest Service Northern Region, Soil Air and Water Notes, May 1979 (79-3). <br /><span class="dateupdated">[publication added 02/27/2009]</span></li>
      				<li>Luce, Charles H. <a href="http://www.fs.fed.us/rm/boise/publications/watershed/rmrs_1997_lucec001.pdf">Effectiveness of road ripping in restoring infiltration capacity of forest roads</a>. 1997. Restoration ecology 5(3): 265&#8211;270. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
	      		  	<li>Martin, Robert E. 1988. Interaction among fire, arthropods, and diseases in a healthy forest. In: Healthy Forests, Healthy World: Proceedings of the 1988 Society of American Foresters National Convention, Rochester, N.Y., Oct. 16&#8211;19, 1988. <a href="http://www.safnet.org/">Society of American Foresters</a>, Bethesda, MD. 87&#8211;91.</li>  
		      		<li>Martin, Robert E. 1981. Prescribed Burning Techniques to Maintain or Improve Soil Productivity. In: Reforestation of Skeletal Soils, Proceedings of a Workshop, November 17&#8211;19, 1981, Medford, Oregon. S.D. Hobbs and O.T. Helgerson, eds. Forest Research Laboratory, <a href="http://oregonstate.edu/">Oregon State University</a>, Corvallis, OR. pp 66&#8211;70.</li>  
					<li>McDaniel, P. A.; K. E. Houston; M. A. Fosberg; A. L. Falen. <a href="RPs/McDaniel_etal_1994.php">Soil-Plant Community Relationships in the Selkirk Mountains of Northern Idaho (HTML)</a>. Published in Northwest Science, Vol. 68, No. 1, 1994.</li>
      				<li>McNabb, D. H.; H. A. Froehlich. <a href="RPs/McNabb_Froehlich_1983.pdf">Conceptual Model for Predicting  Forest Productivity Losses from Soil Compaction (PDF - 568 KB)</a>. 1983.</li>
      				<li>McRae, D. J.; L. C. Duchesne; B. Freedman; T. J. Lynham and S. Woodley. <a href="http://www.ingentaconnect.com/content/nrc/er/2001/00000009/00000004/art00001;jsessionid=5p4bc61334i0s.alice?format=print">Comparisons between wildfire and forest harvesting and their implications in forest management</a>. 2001. Environ. Rev. 9: 223&#8211;260. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Meurisse, R. T. <a href="RPs/Meurisse_1996.pdf">Soil Quality and Health-some Applications to Forest Ecosystems (PDF - 1.3 MB)</a>.</li>
      				<li>Meurisse, R. T. <a href="RPs/Meurisse_1995.pdf">Soil: The Foundation of the Ecosystem; Effects of Management Activities on Forest Soils: Can We Manage Better? (PDF - 512 KB)</a>.</li>
      				<li>Miller, Dick and Harry Anderson. <a href="http://www.fs.fed.us/pnw/olympia/silv/publications/no468_r-miller-soilcompaction_cce.pdf">Soil compaction: Concerns, claims, and evidence</a>. 2002. Washington State University Cooperative Extension. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Miller, R. E.; W. Scott; J. W. Hazard. <a href="RPs/Miller_etal_1996.pdf">Soil compaction and conifer growth after tractor yarding at three coastal Washington locations (PDF - 1.4 MB)</a>.</li>
      				<li>Moghaddas, Emily E. Y. and Scott L. Stephens. <a href="http://www.cnr.berkeley.edu/stephens-lab/Publications/Moghaddas%20Stephens%20Soil%20Mech%20FFS%20FEM%204-08.pdf">Mechanized fuel treatment effects on soil compaction in Sierra Nevada mixed-conifer stands</a>. 2008. For. Ecol. Mgmt. 255: 3098&#8211;3106. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Monleon, Vicente J. and Kermit Cromack, Jr. <a href="http://www.ingentaconnect.com/content/els/03781127/1996/00000081/00000001/art03658;jsessionid=8njgb9t6llsc0.alexandra?format=print">Long-term effects of prescribed underburning on litter decomposition and nutrient release in ponderosa pine stands in central Oregon</a>. 1996. For. Ecol. Mgmt. 81: 143&#8211;152. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Monleon, Vicente J.; Kermit Cromack, Jr. and Johanna D. Landsberg. <a href="http://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=27&year=&issue=&msno=x96-184&calyLang=eng">Short- and long-term effects of prescribed underburning on nitrogen availability in ponderosa pine stands in central Oregon</a>. 1997. Can. J. For. Res. 27: 369&#8211;378. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
				  	<li>National Council for Air and Stream Improvement, Inc. (NCASI).  2004.  <a href="http://www.ncasi.org/publications/Detail.aspx?id=2649" title="Effects of Heavy Equipment on Physical Properties of Soils and on Long-Term Productivity: A Review of Literature and Current Research">Effects of Heavy Equipment on Physical Properties of Soils and on Long-Term Productivity: A Review of Literature and Current Research</a>.  Technical Bulletin No. 0887.  Research Triangle Park, NC: National Council for Air and Stream Improvement, Inc.</li>
      				<li>Neal, J. L.; Wright, E. and W. B. Bollen. Burning Douglas-fir slash: Physical, chemical, and microbial effects in the soil. 1965. <a href="http://oregonstate.edu/">Oregon State University</a>.</li>
      				<li>Norberg, G.; A. Jaderlund; O. Zackrisson; T. Nordfjell; D. A. Wardle; M.-C. Nilsson and A. Dolling. <a href="http://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?journal=cjfr&volume=27&year=&issue=&msno=x97-183&calyLang=eng">Vegetation control by steam treatment in boreal forests: a comparison with burning and soil scarification</a>. 1997. Can. J. For. Res. 27: 2026&#8211;2033. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
				  <li>Norum, Rodney A. 1976. <a href="RPs/Norum_USGovtPub_1976.pdf">Fire Intensity-Fuel Reduction Relationships Associated With Understory Burning in Larch/Douglas-Fir Stands (PDF - 456 KB)</a>. In: Tall Timbers fire ecology conference No. 14; symposium proceedings; 1974 October 8&#8211;10; Missoula, MT. Tallahassee, FL: Tall Timbers Research Station. U.S. Government Printing Office. p. 559&#8211;572.</li>
      				<li>Norum, Rodney A. <a href="RNs/Norum_RN-INT-229_1977.pdf">Preliminary guidelines for prescribed burning under standing timber in western larch/Douglas-fir forests</a> (PDF - 977 KB). 1977. (<strong>RN-INT-229</strong>)</li>
      				<li>Ouden, Jan den and Danielle Vogels. <a href="http://cat.inist.fr/?aModele=afficheN&cpsidt=2203920">Mechanical resistance by an ectorganic soil layer on root development of seedling Pinus sylvestris</a>. 1997. Plant and Soil 197: 209&#8211;217. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
      				<li>Page-Dumroese, Deborah. S. Is Woody Residue Part of Your Plan for Sustainable Forestry? <a href="http://www.oswa.org/NWW-Summer2010.pdf">Northwest Woodlands, Summer 2010.</a> (article also available at <a href="http://www.treesearch.fs.fed.us/pubs/35753">http://www.treesearch.fs.fed.us/pubs/35753</a>)  <br /><span class="dateupdated">[Document added to SoLo on 07/30/2010]</span></li>
      				<li>Page-Dumroese, D. S. <a href="../../documents/RPs/Page-Dumroese_1993.pdf">Susceptibility of Volcanic Ash-Influenced Soil in Northern Idaho to Mechanical Compaction</a> (PDF - 632 KB). 1993.</li>
      				<li>Page-Dumroese, Deborah S.; R. Kasten Dumroese; Martin F. Jurgensen; Ann Abbott; Jennifer J. Hensiek. <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4TCGM3W-2&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=c98522d91191a4c2a13ce28ba1ed82f5">Effect of nursery storage and site preparation techniques on field performance of high-elevation Pinus contorta seedlings</a>. 2008. For. Ecol. Mgmt. 256: 2065&#8211;2072. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  <li>Page-Dumroese, D. S.; A. E. Harvey; M. F. Jurgensen and M. P. Amaranthus. Impacts of soil compaction and tree stump removal on soil properties and outplanted seedlings in northern Idaho, USA. Can. J. Soil Sci. (abstract available at <a href="http://pubs.nrc-cnrc.gc.ca/aic-journals/feb98ab.html">http://pubs.nrc-cnrc.gc.ca/aic-journals/feb98ab.html</a>). 1998.</li>
      				<li>Page-Dumroese, Deborah S., Alan E. Harvey, Martin F. Jurgensen and Michael J. Larsen. Ponderosa Pine Seedling Response to Planting-site Soil Fumigation and Fungicide Application. 1996. <a href="http://www.vetmed.wsu.edu/org_NWS/Journal.htm">Northwest Science</a>. 70(2): 139&#8211;146.</li>
      				<li>Page-Dumroese, D. S. and M. F. Jurgensen. <a href="http://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?cjfr_x06-125_36_ns_nf">Soil carbon and nitrogen pools in mid- to late- successional forest stands of the northwestern United States: potential impact of fire</a>. Can. J. For. Res. 2006. 36: 2270&#8211;2284.</li>
      			<li>Page-Dumroese, Deborah S.; Jurgensen, Martin; Terry, Thomas  2010.    <a href="http://www.treesearch.fs.fed.us/pubs/34428">Maintaining soil productivity during forest or biomass-to-energy thinning harvests in the western United States</a>. Western Journal of Applied Forestry. 25(1): 5&#8211;11. <br />
					<span class="dateupdated">[link added 03/09/2010]</span></li>
      				<li>Page-Dumroese, Deborah S.; Martin F. Jurgensen; Allan E. Tiarks; Felix Ponder, Jr.; Felipe G. Sanchez; Robert L. Fleming, J.; Marty Kranabetter, Robert F. Powers; Douglas M. Stone; John D. Elioff and D. Andrew Scott. <a href="http://www.treesearch.fs.fed.us/pubs/22171">Soil physical property changes at the North American Long-Term Soil Productivity study sites: 1 and 5 years after compaction</a>. Can. J. For. Res. 2006. 36(3): 551&#8211;564.</li>
      				<li>Page-Dumroese, Deborah S.; H. Loewenstein, R. T. Graham and A. E. Harvey. <a href="http://soil.scijournals.org/cgi/content/abstract/54/1/229">Soil source, seed source, and organic-matter content effects on Douglas-fir seedling growth</a>. 1990. Soil Science Society of America Journal 54(1): 229&#8211;233. <br /><span class="dateupdated">[publication added 02/20/2009]</span></li>
      				<li>Powers, Robert F. <a href="http://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_e?cjfr_x05-279_36_ns_nf_cjfr3-06">Long-Term Soil Productivity: genesis of the concept and principles behind the program</a>. Can. J. For. Res. 2006. 36(3): 519&#8211;528.</li>
               		<li>Roberts, W. B. 1965. Soil temperatures under a pile of burning logs. Aust. For. Res. 1?: 21&#8211;25.</li>
               		<li>Russell, K. W.; W. G. Thies; D. L. Campbell, R. I. Gara and W. R. Littke. <a href="http://www.cfr.washington.edu/news_pubs/Pubs/index.htm">Effects of slash burning on forest damage from animals, insects, disease and adverse environment.</a> 1989.</li>
      				<li>Sanchez, Felipe G.; D. Andrew Scott and Kim H. Ludovici. <a href="http://www.sciencedirect.com/science?_ob=ArticleURL&_udi=B6T6X-4JMM5P8-1&_user=10&_rdoc=1&_fmt=&_orig=search&_sort=d&view=c&_acct=C000050221&_version=1&_urlVersion=0&_userid=10&md5=6caf94e1b1b8dc389396dd34e83e1009">Negligible effects of severe organic matter removal and soil compaction on loblolly pine growth over 100 years</a>. 2006. For. Ecol. Mgmt. 227: 145&#8211;154.<br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  	<li>Sanchez, Felipe G.; Allan E. Tiarks; J. Marty Kranabetter; Deborah S. Page-Dumroese; Robert F. Powers; Paul T. Sanborn and William K. Chapman. <a href="http://www.treesearch.fs.fed.us/pubs/22654">Effects of organic matter removal and soil compaction on fifth-year mineral soil carbon and nitrogen contents for sites across the United States and Canada</a>. Can. J. For. Res. 2006. 36(3): 565&#8211;576.</li>
      				<li>Schadt, Christopher W.; Andrew P. Martin; David A. Lipson and Steven K. Schmidt. <a href="http://www.sciencemag.org/cgi/content/abstract/sci;301/5638/1359?maxtoshow=&HITS=10&hits=10&RESULTFORMAT=&andorexacttitleabs=and&andorexactfulltext=and&searchid=1&FIRSTINDEX=0&volume=301&firstpage=1359&resourcetype=HWCIT">Seasonal dynamics of previously unknown fungal lineages in tundra soils</a>. 2003. Science 301: 1359&#8211;1361. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
   				  	<li>Schoennagel, Tania; Thomas T. Veblen and William H. Romme. The interaction of fire, fuels, and climate across Rocky Mountain forests. 2004. <a href="http://www.aibs.org/bioscience/">BioScience</a> 54(7): 661&#8211;676. <br /><span class="dateupdated">[link to journal added 02/13/2009]</span></li>
      				<li>Sharrow, S. <a href="RPs/sharrow_comp-graz_2003.php">Soil Compaction During Forest Grazing (HTML)</a>. 2003.</li>
      				<li>Shearer, Raymond C. <a href="RPs/Shearer_RP-INT-167_1975.pdf">Seedbed characteristics in western larch forests after prescribed burning</a> (PDF - 1.25 MB). 1975. (<strong>RP-INT-167</strong>)</li>
      				<li>Steele, Robert W. <a href="RNs/Steele_RN-INT-293_1980.pdf">Postharvest residue burning under alternative silvicultural practices</a> (PDF - 346 KB). 1980. (<strong>RN-INT-293</strong>)</li>
            		<li>Tarrant, R. F. <a href="http://www.ingentaconnect.com/content/saf/fs/1956/00000002/00000001/art00006">Effect of slash burning on some physical soil properties.</a> 1956.</li>
					<li>Thies, Walter G. 1990. Effects of prescribed fire on diseases of conifers. In: Natural and Prescribed Fire in Pacific Northwest Forests. John D. Walstad, Steven R. Radosevich and David V. Sandberg, edit. <a href="http://oregonstate.edu/dept/press//">Oregon State University Press</a>, Corvallis, OR p. 117&#8211;121.</li>
              		<li>Thomson, A. J. <a href="http://rparticle.web-p.cisti.nrc.ca/rparticle/AbstractTemplateServlet?calyLang=eng&journal=cjfr&volume=16&year=0&issue=2&msno=x86-048">Trend surface analysis of spatial patterns of tree size, microsite effects, and competitive stress.</a> 1986.</li>
      				<li>Wennstrom, Ulfstand; Urban Bergsten and Jan-Erik Nilsson. <a href="http://cat.inist.fr/?aModele=afficheN&cpsidt=1359889">Mechanized microsite preparation and direct seedling of Pinus sylvestris in boreal forests - a way to create desired spacing at low cost</a>. 1999. New Forests 18: 179&#8211;198. <br />
      				  <span class="dateupdated">[link to document added 02/13/2009]</span></li>
       			  <li>Widden, P. and D. Parkinson. The effects of a forest fire on soil microfungi. 1974. <a href="http://www.elsevier.com/wps/find/journaldescription.cws_home/332/description#description">Soil Biology and Biochemistry</a> 7: 125&#8211;138.</li>
      				<li>Wilson, S. D. and H. R. Kleb. 1996. The influence of prairie and forest vegetation on soil moisture and available nitrogen. <a href="http://www.nd.edu/~ammidnat/index.htm">The American Midland Naturalist</a>. 136: 222&#8211;231.</li>
      				<li>Wright, E. and R. F. Tarrant. 1958. <a href="http://treesearch.fs.fed.us/pubs/25808">Occurrence of mycorrhizae after logging and slash burning in the Douglas-fir forest type</a>.</li>
      				<li>Zlatnik, E. J.;  T. H. DeLuca; K. S. Milner and D. F. Potts. 1999. <a href="http://saf.publisher.ingentaconnect.com/content/saf/wjaf/1999/00000014/00000001/art00009">Site Productivity and Soil Conditions on Terraced Ponderosa Pine Sites in Western Montana</a>. Western Journal of Applied Forestry. 14(1): 35&#8211;40.</li>
				</ul>
			<h3 class="subsection">Other Related Publications</h3>
				<ul class="researchpapers">
		      		<li>Fire Effects Information System (FEIS) located at <a href="http://www.fs.fed.us/database/feis/">http://www.fs.fed.us/database/feis/</a>. (FEIS summarizes and synthesizes research about living organisms in the United States&#8212;their biology, ecology, and relationship to fire.)</li>
		      		<li>Hungry Horse News articles - September 20, 1974, Columbia Falls, Montana: <a href="MISC/HungryHorseNews_1974-09-20_01.pdf">Forest Research Study Centers on Desert Mountain (page 1 - 866 KB)</a>, <a href="MISC/HungryHorseNews_1974-09-20_02.pdf">Forest Research Study Centers on Desert Mountain (page 2 - 1.86 MB)</a> and <a href="MISC/HungryHorseNews_1974-09-20_03.pdf">Skyline Logging on Desert Mountain  (page 3 - 2.78 MB)</a>. (articles posted with permission of the <a href="http://www.hungryhorsenews.com/">Hungry Horse News</a>, Columbia Falls, MT) <br />
	      		  <span class="dateupdated">[added to SoLo on 10/15/2008]</span></li>
					<li>The Sunday Missoulian article - <a href="MISC/documents/MISC/TheSundayMissoulian_1975-09-14.pdf">Yes Folks, That Was a Forest Fire</a>. September 14, 1975. <br /><span class="dateupdated">[publication added 05/19/2009]</span></li>
			</ul>
				<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
				<!-- </div> -->
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
