<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Activities Monitored: Timber Harvest</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Activities Monitored: Timber Harvest" />
		<meta name="keywords" content="forest timber harvest harvesting" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">MONITORING</a> &gt; <a href="../../activities.php">ACTIVITIES</a> &gt; HARVEST</h5>
			<h2 class="topheading">ACTIVITIES MONITORED: HARVEST</h2>
			<p class="dateupdated">[Last update: 03/15/2007] <br />
			[Most recent addition of documents: 03/15/2007]</p>
			<p>Historically, timber harvest has been one of the largest uses of National Forest land. Depending on the method used, the effects can vary widely. As a result, some management practices can be termed &quot;sustainable&quot; while others cannot.</p>
			<p>Soil organic components are important factors in the health and productivity of Inland Northwest forests. Timber harvesting and extensive site preparation (piling, windrowing, or scalping) reduces the amount of surface organic material (woody residues and forest floor layers) over large areas. Some wildfires and severe prescribed burns can have similar consequences. Such organic matter reductions can have important implications for soil chemical, biological and physical properties.</p>
			<p>A number of studies have linked substantial reduction in mycorrhizae development and tree growth to high levels of soil disturbance, or removal of organic horizons. Timber harvesting also removes a large percentage of coarse woody debris, which has unknown ramifications on soil productivity. Current woody residue guidelines in this region recommend leaving &lt;10 to 125 Mg ha<sup>&#8722;1</sup> on site to replace woody materials lost during harvesting operations. Large amounts of soil nitrogen (&gt;500 kg ha<sup>&#8722;1</sup>) can also be lost from timber harvesting and site preparation, especially when using prescribed fire. The time required to replace this lost nitrogen may range from &lt;10 to &gt;275 years, and depends on the severity of site treatments, presence or absence of nitrogen-fixing plants, and amounts of atmospheric deposition.</p>
			<p>Maintaining adequate amounts of organic matter on some forest sites in the Inland Northwest may temporarily increase the risk of wildfire or favor the activity of certain insects or disease fungi. However, carefully planned prescribed burns and mechanical site preparation can be practiced on most sites with relatively low impacts on soil organic levels, while accomplishing the important forest management objectives of fuel reduction, seedbed preparation, and reducing competing vegetation. Organic matter management will be the most difficult on very dry sites, with their historically low soil organic and nitrogen content, and high fire potential. The maintenance of adequate soil organic matter levels is critical for sustaining forest health and productivity under the variable moisture and temperature conditions of this region. Thus, soil organic components will become more important in the future as ecosystem management systems are developed for western forests. (Abstract from <a href="../../../../documents/RPs/Jurgensen_etal_97.php">Jurgensen, et al. 1997</a>)</p>
			<h3>Related Publications</h3>
			<ul class="researchpapers">
      			<li>Amaranthus, Michael P. and David E. Steinfeld. <a href="../../../../documents/RPs/Amaranthus_PNW-RP-504_1997.pdf">Soil compaction after yarding of small-diameter Douglas-fir with a small tractor in southwest Oregon</a> (PDF - 707 KB). 1997.</li>
      			<li>Amaranthus, Michael P., Debbie Page-Dumroese, Al Harvey, Efren Cazares and Larry F. Bednar. <a href="https://forest.moscowfsl.wsu.edu/smp/docs/docs/Amaran_PNW-RP-494_1996.html">Soil compaction and organic matter affect conifer seedling nonmycorrhizal and ectomycorrhizal root tip abundance and diversity</a> (HTML). 1996.</li>
      			<li>Carter, Mason C.; Thomas J. Dean; Ziyin Wang and Ray A. Newbold. Impacts of harvesting and postharvest treatments on soil bulk density, soil strength, and early growth of Pinus taeda in the Gulf Coastal Plain: a Long-Term Soil Productivity affiliated study. Can. J. For. Res. (abstract and full text available at <a href="https://www.treesearch.fs.fed.us/pubs/25274">https://www.treesearch.fs.fed.us/pubs/25274</a>). 2006. 36(3): 601&#8211;614.</li>
      			<li>Fleming, Robert L.; Michael F. Laporte; Gary D. Hogan and Paul W. Hazlett. Effects of harvesting and soil disturbance on soil CO<sub>2</sub> efflux from a jack pine forest. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_abst_f?cjfr_x05-258_36_ns_nf_cjfr3-06">Can. J. For. Res.</a> (abstract and full text available). 2006. 36(3): 589&#8211;600.</li>
      			<li>Fleming, Robert L.; Robert F. Powers; Neil W. Foster; J. Marty Kranabetter; D. Andrew Scott; Felix Ponder, Jr.; Shannon Berch; William K. Chapman; Richard D. Kabzems; Kim H. Ludovici; David M. Morris; Deborah S. Page-Dumroese; Paul T. Sanborn; Felipe G. Sanchez; Douglas M. Stone and Allan E. Tiarks. Effects of organic matter removal, soil compaction, and vegetation control on 5-year seedling performance: a regional comparison of Long-Term Soil Productivity sites. Can. J. For. Res. (abstract and full text available at <a href="https://www.treesearch.fs.fed.us/pubs/22170">https://www.treesearch.fs.fed.us/pubs/22170</a>). 2006. 36(3): 529&#8211;550.></li>
      			<li>Froehlich, H. A.; D. H. McNabb. <a href="../../../../documents/RPs/Froehlich_McNabb_1983.pdf">Minimizing Soil Compaction in Pacific Northwest Forests (PDF - 2.7 MB)</a>. 1983.</li>
      			<li>Froehlich, H. A.; D. W. R. Miles. <a href="../../../../documents/RPs/Froehlich_Miles_1984.pdf">Winged subsoiler tills compacted forest soils (PDF - 436 KB)</a>. 1984.</li>
      			<li>Geist, M. J.; H. A. Froehlich. <a href="../../../../documents/RPs/Geist_Froehlich.pdf">Principles and Processes of Subsoiling in Forest Ecosystems</a> (PDF - 456 KB).</li>
				<li>Graham, R. T.; Minore, D.; Harvey, A. E.; Jurgensen, M. F.;. Page-Dumroese, D. S. <a href="../../../../documents/GTRs/INT_280/Graham_INT-280.php">Soil Management as an Integral Part of Silvicultural Systems</a> (HTML). In: Proceedings&#8212;Management and Productivity of Western-Montane Forest Soils, April 10&#8211;12, 1990, Boise, ID, USDA Forest Service General Technical Report INT-280, August 1991.</li>
     			<li>Greacen, E. L.; R. Sands. <a href="../../../../documents/RPs/Greacen_Sands_1980.pdf">Compaction of Forest Soils: A Review</a> (PDF - 2.7 MB).</li>
				<li><strong>GTR-INT-110 &#8211;</strong> <a href="../../../../documents/GTRs/INT_90/INT-90_Harvest_1979.pdf">Environmental Consequences of Timber Harvesting in Rocky Mountain Coniferous Forests: Symposium Proceedings</a> (PDF - 19.7 MB), Sept. 11&#8211;13, 1979, Missoula, MT, USDA Forest Service General Technical Report INT-90, September 1980.</li>
  				<li><strong>GTR-INT-90 &#8211;</strong> <a href="../../../../documents/GTRs/INT_110/INT-110_HarvRes_1979.pdf">Harvesting and Utilization Opportunities for Forest Residues in the Northern Rocky Mountains: Symposium Proceedings</a> (PDF - 10.3 MB), Sept. 11&#8211;13, 1979, Missoula, MT, USDA Forest Service General Technical Report INT-110, September 1980.</li>
				<li>Han, Sang-Kyun. <a href="../../../../documents/GTs/Thesis_Sang-Kyun_Han.doc">&#8220;Impacts on Soils from Cut-To-Length and Whole Tree Harvesting.&#8221; (Microsoft Word Document - 1.6 MB)</a> Diss. University of Idaho, 2006.</li>
      			<li>Harvey, Alan E., Martin F. Jurgensen and Michael J. Larsen. <a href="../../../../documents/GTRs/INT_28/INT-28_FiberUtil_1976.pdf">Intensive Fiber Utilization and Prescribed Fire: Effects on the Microbial Ecology of Forests</a> (PDF - 3.1 MB). 1976. (GTR-INT-28)</li>
      			<li>Harvey, Alan E., Michael Geist, Gerald McDonald, Martin F. Jurgensen, Patrick H. Cochran, Darlene Zabowski and Robert T. Meurisse. Biotic and Abiotic Processes in Eastside Ecosystems: The Effects of Management on Soil Properties, Processes, and Productivity (available at <a href="https://www.treesearch.fs.fed.us/pubs/6286">https://www.treesearch.fs.fed.us/pubs/6286</a>). 1994. (GTR-PNW-323)</li>
				<li>Harvey, Alan E., Michael J. Larsen and Martin F. Jurgensen. Partial cut harvesting and ectomycorrhizae: early effects in Douglas-fir-larch forests of western Montana. 1980b. <a href="https://pubs.nrc-cnrc.gc.ca/cgi-bin/rp/rp2_desc_e?cjfr">Canadian Journal of Forest Research</a>. 10(3): 436&#8211;440.</li>
      			<li>Heninger, R.; W. Scott; R. Miller; H. Anderson. <a href="../../../../documents/RPs/Heninger_etal_1983.pdf">Case Study: Growth of Douglas-fir on Cultivated and Non-Cultivated Skid Trails in Coastal Washington and Western Oregon</a> (PDF - 112 KB). 1983.</li>
				<li>Jurgensen, M. F.; A. E. Harvey; R. T. Graham; D. S. Page-Dumroese; J. R. Tonn; M. J. Larsen; T. B. Jain. <a href="../../../../documents/RPs/Jurgensen_etal_97.php">Impacts of Timber Harvesting on Soil Organic Matter, Nitrogen, Productivity, and Health of Inland Northwest Forests</a> (HTML), 1997.</li>
				<li>Jurgensen, M. F.; Tonn, J. R.; Graham, R. T.; Harvey, A. E.; Geier-Hayes, K. <a href="../../../../documents/GTRs/INT_280/Jurgensen_INT-280.php">Nitrogen Fixation in Forest Soils of the Inland Northwest</a> (HTML). In: Proceedings&#8212;Management and Productivity of Western-Montane Forest Soils, April 10&#8211;12, 1990, Boise, ID, USDA Forest Service General Technical Report INT-280, August 1991.</li>
      			<li>McNabb, D. H.; H. A. Froehlich. <a href="../../../../documents/RPs/McNabb_Froehlich_1983.pdf">Conceptual Model for Predicting  Forest Productivity Losses from Soil Compaction</a> (PDF - 568 KB). 1983.</li>
				<li>Megahan, W. F. <a href="../../../../documents/GTRs/INT_280/Megahan_INT-280.php">Erosion and Site Productivity in Western-Montane Forest Ecosystems</a> (HTML). In: Proceedings&#8212;Management and Productivity of Western-Montane Forest Soils, April 10&#8211;12, 1990, Boise, ID, USDA Forest Service General Technical Report INT-280, August 1991.</li>
      			<li>Miller, R. E.; W. Scott; J. W. Hazard. <a href="../../../../documents/RPs/Miller_etal_1996.pdf">Soil compaction and conifer growth after tractor yarding at three coastal Washington locations</a> (PDF - 1.4 MB).</li>
				<li>National Council for Air and Stream Improvement, Inc. (NCASI).  2004.  Effects of Heavy Equipment on Physical Properties of Soils and on Long-Term Productivity: A Review of Literature and Current Research.  Technical Bulletin No. 0887.  Research Triangle Park, NC: National Council for Air and Stream Improvement, Inc. (PDF located at the National Council for Air and Stream Improvement's web site: <a href="https://www.ncasi.org/publications/Detail.aspx?id=2649" title="Effects of Heavy Equipment on Physical Properties of Soils and on Long-Term Productivity: A Review of Literature and Current Research">https://www.ncasi.org/publications/Detail.aspx?id=2649</a>)</li>
      			<li>Page-Dumroese, D. S. <a href="../../../../documents/RPs/Page-Dumroese_1993.pdf">Susceptibility of Volcanic Ash-Influenced Soil in Northern Idaho to Mechanical Compaction</a> (PDF - 632 KB). 1993.</li>
      			<li>Page-Dumroese, D. S.; A. E. Harvey; M. F. Jurgensen and M. P. Amaranthus. Impacts of soil compaction and tree stump removal on soil properties and outplanted seedlings in northern Idaho, USA. Can. J. Soil Sci. (abstract available at <a href="https://pubs.nrc-cnrc.gc.ca/aic-journals/feb98ab.html">https://pubs.nrc-cnrc.gc.ca/aic-journals/feb98ab.html</a>). 1998.</li>
      			<li>Page-Dumroese, Deborah S.; Martin F. Jurgensen; Allan E. Tiarks; Felix Ponder, Jr.; Felipe G. Sanchez; Robert L. Fleming, J.; Marty Kranabetter, Robert F. Powers; Douglas M. Stone; John D. Elioff and D. Andrew Scott. Soil physical property changes at the North American Long-Term Soil Productivity study sites: 1 and 5 years after compaction. Can. J. For. Res. (abstract and full text available at <a href="https://www.treesearch.fs.fed.us/pubs/22171">https://www.treesearch.fs.fed.us/pubs/22171</a>). 2006. 36(3): 551&#8211;564.</li>
		      	<li>Page-Dumroese, D.; Jurgensen, M.; Abbott, A.; Rice, T.; Tirocke, J.; Farley, S.; DeHart, S. Monitoring Changes in Soil Quality from Post-fire Logging in the Inland Northwest (PDF available at <a href="https://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-41_605-614.pdf">https://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-41_605-614.pdf</a>). In:&nbsp; Andrews, Patricia L.; Butler, Bret W., comps. 2006. Fuels Management. How to Measure Success: Conference Proceedings. 28-30 March 2006; Portland, OR. Proceedings RMRS-P-41. Fort Collins, CO: U.S. Department of Agriculture, Forest Service, Rocky Mountain Research Station. pp 605&#8211;614.</li>
      			<li>Page-Dumroese, Deborah; Miller, Richard; Mital, Jim; McDaniel, Paul; Miller, Dan, tech. eds. <strong>Volcanic-Ash-Derived Forest Soils of the Inland Northwest: Properties and Implications for Management and Restoration</strong>.  [entire proceedings available at <a href="https://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-44.pdf">https://forest.moscowfsl.wsu.edu/smp/docs/dumroese/RMRS-P-44.pdf (PDF - 6.7 MB)</a>; individual papers can be downloaded separately at <a href="https://www.fs.fed.us/rm/pubs/rmrs_p044.html">https://www.fs.fed.us/rm/pubs/rmrs_p044.html</a>]. 2007. (Conference was held November 9&#8211;10, 2005 in Coeur d'Alene, Idaho.)</li>
				<li>Stark, N. M.; Zuuring, H. <a href="../../../../documents/GTRs/INT_280/Stark_INT-280.php">Minimizing the Adverse Impacts of Timber Harvest in the Northern Rocky Mountains</a> (HTML). Taken from <strong>GTR-INT-280</strong> � Proceedings�Management and Productivity of Western-Montane Forest Soils, April 10�12, 1990, Boise, ID, USDA Forest Service General Technical Report INT-280, August 1991.</li>
			</ul>

<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
