<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Soil - Vegetation Relationships</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Soil - Vegetation Relationships" />
		<meta name="keywords" content="Soil Vegetation Relationships" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
<!-- BEGIN PUBLICATION -->
	<div id="pub">
		<div id="psubnav"><p><a href="../../../index.php">SOLO HOME</a> &gt; <a href="../../research_papers.php">RESEARCH PUBLICATIONS</a></p>
		</div>
		<h1>THE RELATIONSHIP BETWEEN SOILS AND VEGETATION</h1>
		<p class="authors">
			M. Hironaka<br />
			Maynard A. Fosberg<br />
			Kenneth E. Neiman, Jr.</p>
		<h2>ABSTRACT</h2>
		<p>Numerous studies have failed to show consistent relationship between soils and vegetation. A review of basic concepts of soil and vegetation development indicates that vegetation and soils are mutually associated with each other, both being the product of the same environmental variables. The mutual association is between the whole soil and vegetation, not individual soil properties and vegetation or selected attributes of vegetation. At any scale beyond a very localized application, a universal correlation does not exist between soil properties and vegetation attributes. Even within very restricted geographic bounds, variation between attributes can yield untenable results. Soil bodies, when grouped and classified at the soil series level, should correlate reasonably well with habitat type. Conceptually, each habitat type is associated with a unique set of soil series.</p>
		<h2>INTRODUCTION</h2>
		<p>Numerous studies have attempted to correlate climax vegetation and soils (Daubenmire 1970; Daubenmire and Daubenmire 1968; Jensen and others 1990; Neiman 1988; Sexton 1986; Tisdale and Bramble-Brodahl 1983) and, in general, the results have been disappointing. There have been few successes demonstrating correlation between selected soil properties and vegetation. Using factor analysis and multiple discriminant functions, Bunting (1978) was successful in correlating selected soil properties with major vegetation types in the Guadaloupe Mountains in southwestern Texas. Working in an area where parent materials were similar, Tisdale and Bramble-Brodahl (1983) showed site variables, including soil pedon properties, discriminated between habitat types to a fair degree. Klemmedson (1964), working with seral vegetation in a very localized situation, demonstrated the relationship between site factors and vegetation.</p>
		<p>In general, studies involving soils derived from different parent materials have done poorly (Neiman 1988; Sexton 1986). Attempts to predict tree site index using selected soils and site properties have been inconsistent (Copeland 1958; Monserud 1990).</p>
		<p>The numerous failures suggest that a basic soil/vegetation relationship does not exist orsomething fundamental has been overlooked. The sporadic successes in correlating soilswith vegetation appear to be locally significant, but are not applicable elsewhere. Johnson and Simon (1987) had some success in broad relational correlations; for example, <em class="ital">Festuca idahoensis</em> occurred on loess soils, whereas <em class="ital">Agropyron spicatum</em> did not, <em class="ital">Pseudotsuga menziesii</em> and <em class="ital">Pinus ponderosa</em> occupied soils without Mazama ash, and <em class="ital">Abies grandis</em> and <em class="ital">Abies lasiocarpa</em> were associated with soils without ash. Although supported with data from 775 intensively sampled plots, they were unable to extrapolate their correlations between soils and vegetation outside their area of study. The high number of failures that have been published is surely dwarfed by the number of studies that were not reported. A review of some of the basic concepts appears in order.</p>
		<h2>FUNDAMENTAL SOIL EQUATION</h2>
		<p>Let us start with Jenny's (1941, 1958) widely accepted basic soil formation equation:</font></p>
		<div class="eqnsimple">Soil = f(climate, parent material, relief,
  organisms, time)</div>
		<p>This tells us that if the soil pedons at two different points on the landscape have, in all details, the same kinds and intensities of soil properties, the soils of the two places are the same and they have had the same developmental history. Conceptually, the productivity of the soil at the two places also would be the same, because the physical and chemical properties of the soil at the two places would be the same. And, should the soil pedons be classified according to conventional soil classification standards, they would be classed as members of the same soil series, the basic unit of soil classification.</p>
		<h2>VEGETATION-SOIL DEVELOPMENT</h2>
		<p>A less familiar concept is that each soil body is associated with a specific climax vegetation. This is supported by Major's (1951) deduction and rationale that the same environmental factors responsible for soil formation are also responsible for the vegetation that is produced. The same independent variables involved in the soil equation are included in his equation on plant community:</p>
		<div class="eqnsimple">Vegetation = f(<em class="ital">cl, pm, r, o, t</em>)</div>
		<p>A particular climax vegetation as well as a specific soil would result under a fixed set of independent variables. Vegetation, like soil, is the product of the same group of independent variables. Vegetation and soil mutually influence each other and neither is the result of the other (Jenny 1958; Major 1951).</p>
		<p>The two fundamental equations show that a soil body is associated with a specific plant community, the climax plant community. This is an important point. This means that all points on the landscape with the same soil are associated with the same climax plant community, the same plant association, and the same habitat type. The plant association is the basic classification unit of climax vegetation and the habitat type is the land classification unit that supports or supported a particular plant association (Daubenmire and Daubenmire 1968).</p>
		<p>Different soils are known to support the same climax vegetation (Daubenmire 1979; Daubenmire and Daubenmire 1968; Hironaka and others 1983; Neiman 1988). The fact that the same aggregate of plants can grow and thrive on different soils means the same climax vegetation can be supported on more than one soil. This phenomenon is explained by factor compensation of plants. Plants are able to grow and thrive over a range of conditions, permitting the same plant community to occur on different soils.</p>
		<h2>SOILS AND HABITAT TYPE</h2>
		<p>The relationship between soils and habitat type has not been easy to demonstrate because of fuzziness of how much variation we include in our abstract classification units of soil and vegetation. Conceptually, the units can be defined, but the problem is whether they are sufficiently close to ecological reality. Because of the lack of undisturbed vegetation, we are unable to confirm whether our assumptions about vegetation are correct.</p>
		<p>Assuming we are correct, each soil series is associated with a particular climax community, and in turn with a particular habitat type. Otherwise, Major's (1951) vegetation equation is flawed. Since it is likely that more than one soil series is associated with the same climax community, by definition then, each habitat type is associated with a unique climax vegetation and a unique set of soils. It also tells us that all soils included in a soil series are associated with a single habitat type and no other. Should this not be the case, the soil or the habitat type is misclassified.</p>
		<p>Not only should all soils of a soil series support the same climax community, they should also have the same productivity. It must be kept in mind that soils of different soil series may possess the same productivity. While differences in pedon properties or intensities justify placing soils in different soil series, the differences may not affect productivity because of plant compensation. That is to say, soils of different soil series may possess the same level of productivity.</p>
		<h2>SOILS AND RANGE SITE</h2>
		<p>The concept that soil series and productivity go together in wildland management is the basis of the range site classification (Shiftlet 1973). Here each unit includes soils of several soil series of similar productivity that support or supported the same climax vegetation. For those familiar with habitat type classification, the range site classification would be comparable to the habitat type phase, if the phase were to be based on productivity (Hironaka 1986). If one were to group all range sites capable of supporting the same climax vegetation, the group of range sites would be equivalent to a habitat type (Hironaka 1986). Therefore, range sites represent differences in productivity within a habitat type. Unfortunately, the nomenclature of the range site classification does not identify or allude to the climax vegetation, and grouping of range sites into habitat types cannot be easily done.</p>
		<h2>FOREST SITE PRODUCTIVITY</h2>
		<p>The site index has been a primary means of assessing forest site productivity. In essence, the average height of dominant trees at age 50 or 100 years is used as the site's index of productivity. Site index curves have been developed for various timber species for local and regional interpolation. To estimate site index from soil and site characteristics, attempts have been made to correlate known index values with site and soil parameters to develop prediction equations. Recently, using stem analysis to get direct measure of site index of inland Douglas-fir, Monserud (1984) found that site index for old inland Douglas-fir tended to drop off considerably because the older measured trees occurred on &quot;poorer&quot; and more inaccessible sites. This suggested that the older trees occurred on different and less productive soils. In a follow up study Monserud and others (1990) attempted to correlate site and soil factors with site index by partitioning the habitat type series. They came to the overall conclusion that site index correlations with site and soil
variables were not very reliable.</p>
		<p>Jenny's (1941) contention that no soil property can be universally correlated with property of vegetation and Major's (1951) stress that mathematically there are no universal correlations between vegetation and soil properties as neither is determined by the other have been ignored. In a nutshell, this is the basic reason why seeking of mathematical correlation of soil properties and vegetation has failed in the majority of cases. Only with studies where the independent variables have been sufficiently constrained have meaningful correlations been demonstrated. It would appear that the forest site index would be closely predicted by the soil series. It is something to think
about.</p>
		<h2>SOIL CLASSIFICATION AND FOREST AND RANGELAND MANAGEMENT</h2>
		<p>The practice of classifying and mapping soils at the soil family level of classification does not work very well for intensive land management. This is especially true when it is not used in conjunction with the habitat type classification. The soil family class groups soil series on the basis of broad textural, mineralogical, and soil climate similarities. This level of classification often includes soils of different habitat types and productivity levels, and greatly weakens the reliability and effectiveness of management prescriptions.</p>
		<p>For intensive management of forests and rangelands, a baseline soil map at the soil series level of classification is something to work toward. Used in conjunction with habitat type, community type, and topographic maps (GIS overlays), much could be known about any piece of land before leaving the office. Supported by an information storage/retrieval system based on habitat type, community type, and soil series and soil series phase, much detailed management information could be made available concerning any piece of inventoried landscape. More important, it would provide a means whereby new information relating to land treatment and responses can be inputted and retrieved for later use by the next generation of land managers. The new generation of land managers need not reinvent the wheel as we have repeatedly done in the past.</p>
		<h2>REFERENCES</h2>
		<p class="ref"><strong>Copeland, O. L., Jr.</strong> 1958. Soil-site index studies of western white pine in the northern Rocky Mountain region. Soil Science Society of America Proceedings. <strong>22</strong>: 268-269.</p>
		<p class="ref"><strong>Daubenmire, R.</strong> 1979. Steppe vegetation of Washington. Tech. Bull. 62. Pullman, WA: Washington Agricultural Experiment Station, Washington State University. 131 p.</p>
		<p class="ref"><strong>Daubenmire, R.; Daubenmire, Jean B.</strong> 1968. Forest vegetation of eastern Washington and north Idaho. Tech. Bull. 60. Pullman, WA: Washington Agricultural Experiment Station,
Washington State University. 104 p.</p>
		<p class="ref"><strong>Hironaka, M.</strong> 1986. Habitat type, range site, and community type. In: McArthur, E. D.; Welch, B. L., compilers. Proceedings symposium on the biology of <em class="ital">Artemisia</em> and <em class="ital">Chrysothamnus</em>. Gen. Tech. Rep. INT-200. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station: 15-18.</p>
		<p class="ref"><strong>Hironaka, M.; Fosberg, M. A.; Winward, A. H.</strong> 1983. Sagebrush-grass habitat types of southern Idaho. Bull. 35. Moscow, ID: University of Idaho, Forestry, Wildlife and Range Experiment Station. 44 p.</p>
		<p class="ref"><strong>Jensen, M. E.; Simonson, G. H.; Dosskey, M.</strong> 1990. Correlation between soils and sagebrush-dominated plant communities of northeastern Nevada. Soil Science Society of America Journal. <strong>54</strong>: 902-910.</p>
		<p class="ref"><strong>Jenny, H.</strong> 1941. Factors of soil formation. New York: McGraw-Hill. 281 p.</p>
		<p class="ref"><strong>Jenny, Hans.</strong> 1958. Role of the plant factor in the pedogenic functions. Ecology. <strong>39</strong>: 5-16.</p>
		<p class="ref"><strong>Johnson, C. G.; Simon, S. A.</strong> 1987. Plant associations of the Wallowa-Snake Province, Wallowa-Whitman National Forest. R6-ECOL-TP-255a-86. Portland, OR: U.S. Department of Agriculture, Forest Service, Pacific Northwest Region. 400 p.</p>
		<p class="ref"><strong>Klemmedson, James O.</strong> 1964. Topofunction of soils and vegetation in a range landscape. In: Forage plant physiology and soil-range relationships. American Society of Agronomy Spec. Publ. 5. Madison, WI: American Society of Agronomy: 176-189.</p>
		<p class="ref"><strong>Major, Jack.</strong> 1951. A functional, factorial approach to plant ecology. Ecology. <strong>32</strong>: 392-412.</p>
		<p class="ref"><strong>Monserud, Robert A.</strong> 1984. Height growth and site index curves for inland Douglas-fir based on stem analysis data and forest habitat types. Forest Science. <strong>30</strong>: 943-965.</p>
		<p class="ref"><strong>Monserud, R. A.; Moody, U.; Breuer, D. W.</strong> 1990. A soil-site study for inland Douglas-fir. Canadian Journal of Forest Research. <strong>20</strong>: 686-695.</p>
		<p class="ref"><strong>Neiman, Kenneth E., Jr.</strong> 1988. Soil characteristics as an aid to identifying forest habitat types in northern Idaho. Res. Pap. INT-390. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 16 p.</p>
		<p class="ref"><strong>Sexton, William T.</strong> 1986. Selected forest soil-parent material relationships in the Clearwater and Nez Perce National Forests. Moscow, ID: University of Idaho. 85 p. Dissertation.</p>
		<p class="ref"><strong>Shiftlet, Thomas N.</strong> 1973. Range sites and soils in the United States. In: Hyder, D. N., ed. Arid shrublands. Proceedings 3rd workshop of U.S./Australia Rangelands Panel. Tucson, AZ. Denver, CO: Society for Range Management: 26-33.</p>
		<p class="ref"><strong>Tisdale, E. W.; Bramble-Brodahl, Mary.</strong> 1983. Relationships of site characteristics to vegetation in canyon grasslands of west central Idaho and adjacent areas. Journal of Range Management. <strong>36</strong>: 775-778.</p>
		<p class="notes">Paper presented at the Symposium on Management and Productivity of Western-Montane Forest Soils, Boise, ID, April 10-12, 1990.<br />M. Hironaka is Professor, Department of Range Resources, University of Idaho, Moscow, ID 83843. Maynard A. Fosberg is Professor, Department of Soil Science, University of Idaho. Kenneth E. Neiman, Jr., is Terrestrial Ecologist, Parametrix, Inc., Bellevue, WA 98004.</p>

</div>
<!-- END PUBLICATION -->
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
