<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Abies lasiocarpa (ABLA) Series</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Northern Idaho - Soil and Productivity and Management concerns for Abies lasiocarpa (ABLA) series" />
		<meta name="keywords" content="Forest Habitat Types of Northern Idaho Productivity Management concerns Abies lasiocarpa series ABLA soil Soils" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../../../GeoPath/habitat/index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF NORTHERN IDAHO</a> &gt; <span class="ital">ABIES LASIOCARPA</span> (ABLA) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Northern Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Neiman, Kenneth E.; Roberts, David W. Rev. 1991. Forest habitat types of northern Idaho: a second approximation. Gen. Tech. Rep. INT-236. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 143 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_04.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<strong>5</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">ABIES LASIOCARPA</span> (ABLA) SERIES</h3>
			<p><strong>Productivity/Management</strong>&#8212;Lower subalpine sites have the greatest timber potential followed by the upper subalpine and lastly the noncommercial timberline environments. These upper elevation sites are better suited for management that emphasizes recreation, wildlife, and watershed values. <span class="ital">Pinus contorta, Picea, L. occidentalis,</span> and <span class="ital">P. monticola</span> are productive and can be successfully regenerated in the lower subalpine zone. <span class="ital">Picea</span> is susceptible to windthrow on partial cuts, especially where water tables are high. <span class="ital">Pseudotsuga</span> is moderately to highly productive, and the highest probability of successful silvicultural manipulation occurs on lower subalpine sites. The notable lack of success  with planted <span class="ital">P. ponderosa</span> in the ABLA series corresponds to the observation that it rarely occurs naturally within the series.</p>
			<p>Pertinent studies of silvicultural manipulation and succession include Roe and DeJarnette (1965), Boyd and Deitschman (1969), Basile and Jensen (1971), Alexander (1973), Fiedler (1980,1982), Arno and Simmerman (1982), and McCaughey and Schmidt (1982).</p>

			<h4><a name="set1a"></a><span class="ital">Abies lasiocarpa/Calamagrostis canadensis</span> h.t. <br />(ABLA/STAM; subalpine fir/bluejoint)</h4>
			<p><strong>Soils</strong>&#8212;All soils are developed on granitic parent materials (<a href="habitat_types_N-ID_app.php">appendix D</a>); only one plot contained ash. Most soils are well-drained silt loams with an average rock content of 20 percent in the surface horizon, increasing to 35 percent in subsurface horizons. Only one profile had a restrictive layer, but some test excavations indicate restrictive clay pans may be a feature distinguishing this type, particularly ABLA/CACA-VACA from associated h.t.'s with better drainage (usually ABLA/XETE-VASC). Exposed rock and soil were not noted. Surface soils are strongly to moderately acidic (pH 5.1 to 5.6); acidity decreases slightly with increasing depth (pH 5.4 to 5.9).</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity data are meager, causing us to draw on the results of Steele and others (1981). We concur with their observations that the LICA phase is the most productive and LEGL is the least, and that <span class="ital">Picea</span> has the highest site index values, with <span class="ital">P. contorta</span> the most easily regenerated species. Steele and others (1981) note that partial cutting leaves the remaining trees susceptible to windthrow. As a consequence of rising water tables following overstory removal, <span class="ital">Carex</span> spp. and <span class="ital">C. canadensis</span> increase to compete with tree seedlings.</p>
			<p>Harvesting, site preparation, and grazing of these sites should be postponed until late summer because wet soils are easily churned and compacted. Considerable forage and access to water attract livestock. These sites offer important food and cover for moose, elk, deer, bear, and Franklin&#146;s grouse (Steele and others 1981). Seral stages can support <span class="ital">Salix</span> spp. and abundant <span class="ital">Carex</span> spp.</p>

			<h4><a name="set1b"></a><span class="ital">Abies lasiocarpa/Streptopus amplexifolius</span> h.t. <br />(ABLA/STAM; subalpine fir/twisted stalk)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are dominated by alluvium, especially in the LICA phase, and include granitics, sandstone, quartzite, and mica schist (<a href="habitat_types_N-ID_app.php">appendix D</a>). Restrictive layers, primarily clay pans and compacted glacial till, are found on virtually all the LICA and half of the MEFE sites. Most of the MEFE sites have a deep (13 inches [33 cm] average) ash cap, whereas ash influences were limited in the LICA phase. Though gravel content varies widely, low content (&lt;5 percent) prevails in both the surface and lower horizons on benches, stream terraces, and toe-slope positions; across both phases and all soil depths gravel content averages only 16 percent. The range in surface and subsurface soil textures is narrow, loam to silty clay loam. Effective rooting depths are relatively shallow (average of 14 inches [36 cm]), reflecting the presence of high water tables and saturated soils. Soil reaction (pH) for surface and subsurface horizons is strongly to moderately acidic.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potential varies from moderate, where cold-air drainage is impeded and soils are saturated throughout the year, to very high on sites with better drainage; on these better drained sites <span class="ital">Picea</span> has the highest site index values. Caution should be exercised in timber management; clearcutting will negate the high probability of windthrow associated with partial cutting, but the resulting rise in water tables may produce herb-dominated meadows that reforest very slowly. Light selection cutting may avoid these pitfalls, but heavy equipment use should be delayed until the late summer. Roads, trails, or other site development should be avoided. Cole (1983) showed trails crossing this h.t. to be in much poorer condition than those trail portions located in h.t.&#146;s with higher drainage rates.</p>
			<p>The abundant forage found in the LICA phase and adjacent watercourses attracts livestock; soils on these sites are easily churned, destroying undergrowth and tree seedlings. Elk use of lower elevations within the MEFE phase is moderate to high for cover and forage. Mountain caribou use old-growth stands as part of their winter range because the lower branches are festooned with lichens, an important part of their nutrition (Edwards and others 1960; Edwards and Ritcey 1960).</p>
			
			<h4><a name="set1c"></a><span class="ital">Abies lasiocarpa/Clintonia uniflora</span> h.t. <br />(ABLA/CLUN; subalpine fir/queencup beadlily)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are dominated by granitics, quartzites, and mica schists (<a href="habitat_types_N-ID_app.php">appendix D</a>). Surface soils are generally dominated by an ash cap (andic diagnostic horizon) averaging over 12 inches (30 m) in depth (ranging from 3 to 24 inches [8 to 60 cm] thick). Surface horizon textures are primarily loams to silt loams; subsurface textures are highly variable. Rock content averages 17 percent in the surface horizons and does not increase appreciably with depth. The MEFE phase has slightly deeper rooting depths than the XETE phase, 23 inches (58 cm) (14 to 43 inches [35 to 110 cm]) versus 18 inches (45 cm) (11 to 21 inches [28 to 53 cm]). Restrictive layers are found only in the XETE phase. Surface soil pH ranges from strongly acidic to neutral; acidity decreases slightly with increasing depth.</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are generally high for all seral species, ABLA/CLUN being the most productive sites in terms of site index and basal area of all subalpine h.t.&#146;s. Based on limited site index data, the three phases appear equally productive, though natural understocking commonly occurs on the MEFE phase. <span class="ital">Pseudotsuga</span> and <span class="ital">Larix</span> readily establish here and exhibit high growth rates. Vast acreages, however, support an overstory of only <span class="ital">Pinus contorta</span> (with <span class="ital">A. lasiocarpa</span> and <span class="ital">Picea</span> as understory) because of their fire history coupled with poor <span class="ital">Pseudotsuga</span> and <span class="ital">Larix</span> cone crops. <span class="ital">Picea</span> is the highest site index species on all phases, but regeneration may be considerably delayed and in lesser amounts than <span class="ital">P. contorta</span> or <span class="ital">Pseudotsuga</span>. The diversity of seral species and high productivity of this h.t. permits the greatest range of silvicultural options for subalpine sites. Partial cutting will accelerate <span class="ital">A. lasiocarpa</span>, and to a lesser degree <span class="ital">Picea</span>, dominance.</p>
			<p>Fiedler&#146;s (1980) studies on the ABLA/CLUN h.t. in western Montana have established that the probability of immediate natural stocking following clearcutting is high, 70 to 80 percent, and does not improve significantly over the following 10 years. Probability of stocking is higher with site scarification than with burning for approximately 12 years following treatment. Undergrowth coverages above 10 to 15 percent are correlated with significantly reduced stocking probability; in 12 years at 100 percent undergrowth coverage (no site preparation), only 60 percent stocking is achieved. The MEFE phase usually requires more intensive site preparation because of possible shrubfield development.</p>
			<p>Seral shrubs can produce considerable summer browse for elk and deer; the lower elevation sites within the MEFE phase constitute a portion of moose winter range on the Nez Perce <abbr title="National Forest">NF</abbr>. Along the Canadian border ABLA/CLUN is one of the major h.t.&#146;s, serving as critical winter range for woodland caribou (Edwards and Ritcey 1960; Edwards and others 1960). The lush forage produced in openings and early seral stages attracts livestock.</p>
			<p>Watershed values are high because of heavy snowpack and high precipitation, typical across most of the subalpine zone.</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies lasiocarpa/Menziesia ferruginea</span> h.t. <br />(ABLA/MEFE; subalpine fir/menziesia)</h4>
			<p><strong>Soils</strong>&#8212;Within ABLA/MEFE, four phases are recognized; compared below are two phases for which we possess limited soils information, the most moderate phase, COOC, and the most environmentally stressed phase, LUHI. Parent materials are exclusively granitics and mica schists. Ash layers are present on most sites; depths of those on the COOC phase averaged 15 inches (38 cm) and on the LUHI phase only 7 inches (18 cm). No restrictive layers are found in either phase. Surface soil textures are consistently silt loams in the COOC phase and more variable in the LUHI phase. The two phases show notable differences in gravel content. COOC surface soils are nearly devoid of gravel, and content increased an average of only 5 percent to the subsoil depths. In contrast, LUHI soils are gravelly in the surface portion (30 percent average) and content increases markedly with depth, to an average of 60 percent, LUHI also exhibits higher soil acidity than COOC in both the surface (pH 4.7 versus 5.8) and subsurface (pH 5.3 versus 5.8) horizons.</p>
			<p><strong>Productivity/Management</strong>&#8212;Based on limited data it appears there is a distinction between phases for timber potentials, the COOC phase having the highest site index values. <span class="ital">Picea</span> has the highest site index and is the most important species (basal area) on all phases, although absolute values of site index range upward to high only on the XETE and COOC phases; on the VASC and LUHI phases the 50-year site index for <span class="ital">Picea</span> does not exceed 58 to 60. <span class="ital">Pinus contorta</span> exhibits moderate site index values on the XETE and VASC phases and reduced potential on the more severe LUHI phase.</p>
			<p>Roe and DeJarnette (1965) state that the best <span class="ital">Picea</span> growth is attained on clearcuts, but that ample regeneration is achieved only in partially shaded openings of scarified sites. Fiedler (1982) has shown for ABLA/MEFE (no phase designated) in western Montana: (1) High relative importance of <span class="ital">Picea</span> (followed closely by <span class="ital">A. lasiocarpa</span> and distantly by <span class="ital">P. contorta</span>) extends to the earliest seral stages following clearcutting. (2) Total undergrowth coverage exceeding 50 percent (contributed by increased <span class="ital">Menziesia</span>, <span class="ital">Vaccinium</span> spp., and <span class="ital">Alnus sinuata</span>) is correlated with retardation of natural regeneration by up to 60 percent of possible stocking for at least 12 years. (3) Considerably higher (by 10 to 30 percent) probabilities of natural stocking follow scarification, as opposed to burning (however, slopes too steep for scarification dictate burning during the few times when fuels are dry). (4) ABLA/MEFE displays a high probability for natural stocking, considering 82 percent stocking results 7 to 10 years following cutting, regardless of treatment. (5) The success rate of planted regeneration (the most frequently employed strategy) is relatively high (75 percent), and 35 percent of these planting attempts achieved a super-abundant stocking because natural regeneration was adequate. Silvicultural recommendations of Boyd and Deitschman (1969) may also apply here.</p>
			<p>The harsher environments and lower productivity of the VASC and LUHI phases suggest silvicultural prescriptions should consider minimal site disturbance. The consistently deep snowpack will tend to increase in clearcuts, in some cases promoting a <span class="ital">Luzula</span> sward and/or <span class="ital">Menziesia-</span> and <span class="ital">Alnus-</span>dominated shrubfields that can appreciably retard reforestation. Partial cuttings will expose these high-elevation, fragile sites, risking heavy blowdown in <span class="ital">Picea</span> and promoting dominance by <span class="ital">A. lasiocarpa</span>. Livestock grazing has little potential, but big game, especially elk and moose, use these areas in summer for cover and browse. Along the northern border of the Kaniksu <abbr title="National Forest">NF</abbr>, mature stands of ABLA/MEFE serve as critical winter range for mountain caribou, their principal forage being epidendric lichens encrusting older trees (Edwards and others 1960). Watershed values are high.</p>
			
			<h4><a name="set1e"></a><span class="ital">Abies lasiocarpa/Vaccinium caespitosum</span> h.t. <br />(ABLA/VACA; subalpine fir/dwarf huckleberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Based on data from contiguous areas, timber productivity ranges from low to moderate, with <span class="ital">P. contorta</span> the only species well suited for management (Pfister and others 1977; Steele and others 1981). These populations have predominantly nonserotinous cones, accounting for the high rate of seedling establishment in the absence of disturbance. Gentle terrain and stable soils should favor intensive silviculture. However, the frost pocket microclimate argues otherwise; data assessing response to treatment are wanting.</p>
			<p>Livestock find moderate forage, provided by <span class="ital">C. rubescens</span> and <span class="ital">C. geyeri</span>, and favorable terrain. Proximity to moist meadows suits these sites for summer and fall elk and deer use as cover.</p>
			
			<h4><a name="set1f"></a><span class="ital">Abies lasiocarpa/Xerophyllum tenax</span> h.t. <br />(ABLA/XETE; subalpine fir/beargrass)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials included, in decreasing frequency of occurrence, granitics, gneiss, mica schist, and rhyolite (<a href="habitat_types_N-ID_app.php">appendix D</a>). Only one restrictive layer was found in 30 profiles. The ash cap influence is strong (averaging 14 inches [35 cm] in depth) in all phases but LUHI, where it is conspicuously reduced. Surface horizons in COOC and VAGL phases are exclusively silt loams and loams, whereas for VASC and LUHI the textural range is much greater; soil textures increase in coarseness with increasing depth. Surface soil gravel content averages about 15 percent for COOC, XETE, and VASC with LUHI averaging approximately double this value; subsurface soil gravel content increases with depth and averages about twice that of the surface soil for all phases. Rooting depth averages 16, 20, 21, and 13 inches (41, 50, 53, and 33 cm) for COOC, VAGL, VASC, and LUHI phases, respectively. In accordance with expectations of increasing precipitation and hence increased leaching, the surface soil pH decreases along the gradient COOC (5.9), VAGL (5.8), VASC (5.6), LUHI (5.2); subsoil pH values are slightly higher but approximate the surface soil gradient.</p>
			<p><strong>Productivity/Management</strong>&#8212;Site index data are sketchy but indicate a steady decline by phase from moderate to high in VAGL and COOC, low to moderate in VASC, and low in LUHI. The VAGL and COOC phases offer the most opportunity for mixed species management; in order of decreasing potential they are <span class="ital">P. contorta</span>, <span class="ital">Pseudotsuga</span>, <span class="ital">Picea</span>, and <span class="ital">L. occidentalis</span>.</p>
			<p>Fiedler (1980) has shown that following clearcutting on the VAGL phase in northwestern Montana (1) undergrowth has a dramatic, inverse correlation with tree stocking at tree coverages greater than 25 percent; (2) scarification is preferable to burning in achieving regeneration the first 9 to 10 years following cutting&#8212;the "no treatment" alternative following cutting is least successful; and (3) <span class="ital">A. lasiocarpa</span> seedlings constituted 40 percent of natural regeneration in 12 years, followed distantly by <span class="ital">Pseudotsuga</span> (18 percent) and, in order of decreasing amounts, <span class="ital">P. contorta</span>, <span class="ital">Picea</span>, and <span class="ital">L. occidentalis</span>. <span class="ital">Abies lasiocarpa</span>, though relatively prolific in regeneration, has slow initial growth, with seedlings concentrated in the lower crown class. Planting of these sites in areas with an abundant seed source seems unwarranted. Some of these results can be extrapolated to the VASC phase.</p>
			<p>Timber management for VASC and LUHI phases should concentrate on <span class="ital">P. contorta</span> and <span class="ital">Picea</span>. These are severe sites. The creation of forest openings through patch clearcutting can cause increased snow deposition and retarded reforestation. Partial cutting leaves <span class="ital">Picea</span> susceptible to windthrow, while advance regeneration of <span class="ital">Abies lasiocarpa</span> may be released to dominate the stand.</p>
			<p>Livestock grazing potential is low in all phases. Evidence of light to moderate use by elk and deer is present in the VAGL phase in early and midsummer, with herds moving through all phases by late summer-early fall. <span class="ital">Xerophyllum</span> flowering heads were consistently cropped in some areas and individual <span class="ital">V. globulare</span> plants were hedged to less than 1 ft (30 cm) in height, Mainly bears and grouse feed on the huckleberry crop.</p>
			<p>Watershed management opportunities are greatest in the VASC and LUHI phases; in general, moderate to high precipitation occurs here, with high rates of evapotranspiration and runoff characteristic of these generally warm exposures.</p>
			
			<h4><a name="set1g"></a><span class="ital">Abies lasiocarpa/Vaccinium scoparium</span> h.t. <br />(ABLA/VASC; subalpine fir/grouse whortleberry)</h4>
			<p><strong>Soils</strong>&#8212;</p>
			<p><strong>Productivity/Management</strong>&#8212;See Steele and others (1981) and Pfister and others (1977) for detailed management considerations. Reconnaissance observations suggest <span class="ital">P. contorta</span> is the only suitable timber species, regenerating easily in unshaded clearings, but having poor height growth.</p>
			
			<h4><a name="set1h"></a><span class="ital">Abies lasiocarpa/Luzula hitchcockii</span> h.t. <br />(ABLA/LUHI; subalpine fir/smooth woodrush)</h4>
			<p><strong>Soils</strong>&#8212;Because all samples with soils information were collected on the eastern portions of the Nez Perce <abbr title="National Forest">NF</abbr> where the Idaho batholith predominates, granitics were the only parent materials represented (<a href="habitat_types_N-ID_app.php">appendix D</a>). Very limited data show soil textures, rock content, and rooting depth to vary widely; no restrictive layers were found. Generally there is little exposed soil, but exposed rock may be considerable. Surface horizons are very acidic (pH 4.2 to 4.8), with values increasing with depth (lower profile pH 5.1 to 5.3).</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber potentials are low. Seral tree regeneration may be difficult to achieve due to heavy snowpack, competition from a sward of <span class="ital">Luzula</span>, and advance regeneration of <span class="ital">Abies lasiocarpa</span> (frequently vegetatively layering).</p>
			<p>These are fragile sites due to their harsh environments. Apparently only the Seven Devils area has been subjected to the degrading forces of intensive sheep trailing cited by Steele and others (1981) as extensive in central Idaho. Key management concerns include watershed protection and maintenance of &#147;high country&#148; esthetics for recreation.</p>
			<p>ABLA/LUHI provides summer and fall cover and forage for elk, deer, mountain goats, bighorn sheep, and bears.</p>
			
			<h4><a name="set1i"></a><span class="ital">Larix lyallii-Abies lasiocarpa</span> communities <br />(LALY-ABLA; alpine larch-subalpine fir)</h4>
			<p>(No soil or productivity/management information on these communities.)</p>
			
			<h4><a name="set1j"></a><span class="ital">Pinus albicaulis-Abies lasiocarpa</span> communities <br />(PIAL-ABLA; whitebark pine-subalpine fir)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber potential is very low because of slow growth rates, low basal areas, and poor bole form. Watershed potential is apparently high, as is esthetic appeal. The fragile nature and slow vegetational recovery time of these sites dictates dispersed, low-impact recreation.</p>
			
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_N-ID_06.php">On to <span class="ital">Abies grandis</span> (ABGR) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_04.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<strong>5</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
