<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management Information on Abies grandis (ABGR) Series</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Northern Idaho - Productivity and Management concerns for Abies grandis (ABGR) series" />
		<meta name="keywords" content="Forest Habitat Types of Northern Idaho Productivity Management concerns Abies grandis series ABGR" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../../../GeoPath/habitat/index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF NORTHERN IDAHO</a> &gt; <span class="ital">ABIES GRANDIS</span> (ABGR) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Northern Idaho</span><br />PRODUCTIVITY/MANAGEMENT EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Neiman, Kenneth E.; Roberts, David W. Rev. 1991. Forest habitat types of northern Idaho: a second approximation. Gen. Tech. Rep. INT-236. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 143 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_05.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<strong>6</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">ABIES GRANDIS</span> (ABGR) SERIES</h3>
			<p><strong>Productivity/Management</strong>&#8212;Site indexes range from moderate to very high, with values from the more moist sites being comparable to those of the THPL series. The diversity of seral trees and their generally high growth rates combine to offer diverse silvicultural opportunities. Site indexes for <span class="ital">A. grandis</span> are highest on relatively warm, moist sites; here its height growth rate occasionally exceeds those of the seral species. <span class="ital">Pinus ponderosa</span> is generally the fastest growing tree but is currently important on only the warmest sites, partly because of fire suppression and advancing succession. <span class="ital">Pseudotsuga</span> is moderately to highly productive in this series and occurs on all but sites having saturated soils. <span class="ital">Picea engelmannii</span> and <span class="ital">P. contorta</span> are adapted to wet and cold sites.</p>
			<p>Ferguson and Adams (1980) have proposed some silvicultural strategies that follow from their model of <span class="ital">A. grandis</span> response (height growth) after overstory removal. Their model indicates that, in addition to physical site variables, habitat type is an important response predictor. Generally, <span class="ital">A. grandis</span> on ABGR series sites is not suitable for release unless certain mitigating conditions are met. A regeneration model applicable to the ABGR series that is based on silvical characteristics of Northern Rocky Mountain tree species, site data, and stratified by habitat type and treatment, has been developed as a submodel of the Prognosis Model (Ferguson and others 1986; Stage 1973).</p>
			<p>Reforestation of h.t.&#8217;s on which succession favors shrubfields, <span class="ital">Rudbeckia occidentalis</span> or <span class="ital">Pteridium</span> glades, or <span class="ital">Calamagrostis rubescens</span> swards may require thorough site preparation and planting. Early successional stages of some types can produce high-quality browse for elk and deer, with lower elevations and south slopes often being used as winter range. Much of this series in the Palouse and Joseph Plains area, where soils are deep, has been converted to farms and pastures.</p>
			<p>Trunk rots, primarily <span class="ital">Echinodontium tinctorium</span> (Indian paint fungus), may be rampant in <span class="ital">Abies</span> on moist sites (areas of heavy mortality noted as "heartrot" centers), but are of decreasing incidence on drier sites (Frederick and Partridge 1977). The intrinsically high rates of <span class="ital">E. tinctorium</span> infestation and increase due to the reactivation of dormant infections by mechanical injury (logging) are major factors arguing against uneven-aged management of <span class="ital">A. grandis</span> on moist sites (Antos and Shearer 1980). <span class="ital">Poria weirii</span> and <span class="ital">Armillaria mellea</span> are the primary root-rot pathogens in the series. Preliminary indications (McDonald 1983) are that the rate and severity of <span class="ital">Armillaria</span> infestations are associated with groups of like h.t.&#8217;s; the more moist, moderate temperature groups are most severely affected.</p>

			<h4><a name="set1a"></a><span class="ital">Abies grandis/Senecio triangularis</span> h.t. <br />(ABGR/SETR; grand fir/arrowleaf groundsel)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Based on limited data, site indexes for <span class="ital">A. grandis</span> and <span class="ital">Picea</span> appear high. As with all high-water-table sites, extreme caution should be exercised in site manipulation. These sites are easily degraded through any disturbance; susceptibility to windthrow may be unusually high. Cutover stands are colonized by <span class="ital">Alnus sinuata</span>, <span class="ital">Pteridium aquilinum</span>, and/or <span class="ital">Rudbeckia occidentalis</span>, making regeneration difficult.</p>

			<h4><a name="set1b"></a><span class="ital">Abies grandis/Asarum caudatum</span> h.t. <br />(ABGR/ASCA; grand fir/wild ginger)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials vary, but granitics and metasediments are best represented. Upper horizons of virtually all profiles are influenced by volcanic ash (<a href="habitat_types_N-ID_app.php">appendix D</a>). Only traces of exposed soil or rock are found, and gravel content generally did not exceed 30 percent (average 15 percent in upper horizons). Soil textures are primarily silt loams and silty clay loams. About half of the ASCA phase profiles possess a restrictive layer, caused by increases in clay content or a compacted horizon; sites not having this layer are well drained. The effective rooting depth ranges widely, from 9 to 31 inches (22 to 80 cm) averaging 20 inches (50 cm). Throughout the profile soil pH ranges from slightly acid (6.0) to neutral (7.1), averaging 6.3.</p>
			<p><strong>Productivity/Management</strong>&#8212;Site indexes for all species across all phases are high to very high. <span class="ital">Pseudotsuga</span> and <span class="ital">P. ponderosa</span> are most successful and fastest growing on lower elevations and warmer exposures within the type (usually the ASCA phase), whereas <span class="ital">Picea</span> establishes and grows most rapidly on colder sites (MEFE phase). Though most stands appear to be highly productive, early site domination by shade-tolerant, tall shrubs (<span class="ital">Menziesia</span> and <span class="ital">Taxus</span>) apparently reduces stocking levels (and productivity) throughout the life of the stand. Removal or reduction of the tall shrub layer may be necessary to establish seral conifers. Partial cutting practices can result in the dominance of <span class="ital">A. grandis</span>; in fact, conditions within the type are so favorable to <span class="ital">A. grandis</span> that it often regenerates on clearcuts in greater numbers than seral associates and its rate of initial height growth can equal that of seral species.</p>
			<p>The TABR and portions of the MEFE phase constitute important winter range for moose (Pierce 1983); they both may also receive appreciable summer and fall use. Silvicultural strategies seeking to maintain <span class="ital">Tarus</span> stands should consider that it is: (1) extremely shade tolerant but can adjust to the high light intensities following canopy removal; (2) capable of regeneration by sprouting and layering following overstory removal, though its primary dispersal mechanism is animals; and (3) extremely sensitive to fire and sun scalding and, to a much lesser degree, to mechanical damage (Crawford 1983). Overstory removal, especially in the ASCA phase, promotes a dense layer of forbs and shrubs that provides considerable large herbivore forage. ASCA phase sites also constitute that portion of the h.t. with the greatest winter range potential for herbivores other than moose.</p>
			<p>Much of this h.t. covers those portions of the Clearwater and Nez Perce <abbr title="National Forest">NF</abbr>&#8217;s where succession on cutover areas leads to dominance by <span class="ital">Alnus sinuata</span>, <span class="ital">Pteridium aquilinum</span>, and/or <span class="ital">Rudbeckia occidentalis</span>; these communities are both long-persisting and intractable to tree regeneration. Pocket gophers (<span class="ital">Thomomys</span> spp.) are a major influence in this complex of community types (Neiman and others 1985).</p>
			
			<h4><a name="set1c"></a><span class="ital">Abies grandis/Clintonia uniflora</span> h.t. <br />(ABGR/CLUN; grand fir/queencup beadlily)</h4>
			<p><strong>Soils</strong>&#8212;The following description considers the modal CLUN-CLUN phase with exceptions noted by phase. Parent materials vary widely and include limestone, a relatively rare substrate in northern Idaho (<a href="habitat_types_N-ID_app.php">appendix D</a>). Ash-influenced soils are relatively rare in the CLUN phase, but ash is prevalent in about one-third of the plots in other phases (lack of ash in our CLUN-phase sites may result from a biased sample, primarily Nez Perce <abbr title="National Forest">NF</abbr> plots). Soil textures are predominantly loams, silt-loams, and clays, but range to loamy sands. Gravel content of surface horizons ranges from zero to 60 percent, averaging between 15 and 20 percent for all phases but MEFE, which has a value of less than 5 percent. MEFE phase gravel content increases sharply with increasing depth. Clay pans developing at depths greater than 20 inches (50 cm) constitute restrictive layers on about one-third of the XETE phase. Effective rooting depth varies widely, from 7 to 31 inches (18 to 80 cm), averaging 16 inches (40 cm), the relatively deep average rooting depth (24 inches [60 cm]) of the MEFE phase may be related to low gravel content. Surface and subsurface soil pH ranges, respectively, from 5.6 to 6.5 (average 6.0) and 5.5 to 6.2 (average 5.9); soils of the TABR phase appear to be more basic (pH values to 7.2).</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity and species suitability for management are related to phase; however, the type in general is highly productive and affords a wide latitude in silvicultural prescriptions. On a portion of this h.t. Daubenmire (1961) found <span class="ital">P. ponderosa</span> height growth was rapid for 50 to 60 years. After approximately age 60, though, growth tapered off, resulting in higher site index values for <span class="ital">P. ponderosa</span> growing on PSME/PHMA and PIPO/PHMA h.t.&#8217;s (at index age of 100 years).</p>
			<p>Site indexes for the ABGR/CLUN phases floristically comparable to ABGR/ASCA phases show a trend of reduced values for all species jointly represented. The warmer ABGR/CLUN phases, PHMA, CLUN, and even XETE, on the basis of limited data, appear to be prime sites for <span class="ital">P. ponderosa</span>. <span class="ital">Abies grandis</span>, <span class="ital">Pseudotsuga</span>, and <span class="ital">P. contorta</span> are easily regenerated on clearcuts, with their response varying according to phase. The moderate nature of these sites should be favorable for <span class="ital">Larix</span>, but insufficient data exist to evaluate its potential. Many of the sites sampled for site index were beyond the geographic concentration of <span class="ital">P. monticola</span>, accounting for its being underrepresented in appendix F. Most ABGR/CLUN sites, except those of the PHMA phase, appear, on the basis of vegetative composition and site parameters, capable of supporting good <span class="ital">P. monticola</span> growth.</p>
			<p>The TABR phase, for which meager data exist, is floristically and environmentally most similar to ABGR/ASCA-TABR and may respond similarly to management. Overstory removal in both h.t.&#8217;s results in a marked seral shrub and forb increase and burning may result in a sward of <span class="ital">Pteridium aquilinum</span>. Reduction of the <span class="ital">Taxus</span> layer will be necessary to achieve stocking with seral conifers. Regarding <span class="ital">Taxus</span> Crawford (1983) indicated that: (1) mortality following overstory removal is due, not to solarization, but to mechanical injury from logging, (2) tractor piling of slash could cause severe losses, and (3) it is extremely intolerant of fire and any attempt at slash disposal and site preparation through broadcast burning would cause its virtual elimination. <span class="ital">Taxus</span> response to manipulation is an important consideration because it is a very significant component of moose winter forage (Pierce 1983). Its high coverages in the west-central Nez Perce <abbr title="National Forest">NF</abbr> are considered responsible for concomitantly high moose populations. Uneven-aged management may be the most feasible approach to preserving <span class="ital">Taxus</span> and harvesting timber, but will probably result in the dominance of <span class="ital">A. grandis</span>, the value of which is severely reduced by a high incidence of Indian paint fungus (<span class="ital">Echinodontium tinctorium</span>) and root rot.</p>
			<p>Little is known concerning the MEFE phase, but it seems to produce <span class="ital">Picea</span> and <span class="ital">P. contorta</span> of high site index, Partial cutting, especially in the MEFE and PHMA phases, may result in a lack of tree regeneration under an increased shrub cover. Clearcutting and stand-replacing wildfire in these two phases can result in dramatic increases in shrub coverages; therefore immediate planting would seem advisable where reforestation is a prime management objective.</p>
			<p>All phases produce abundant elk and deer forage, especially in earlier successional stages. Low-elevation phases with southerly aspects, principally CLUN and PHMA, are utilized as elk and deer winter range. Browse production can be enhanced by broadcast burning of slash following clearcutting or seedtree cuts. The warmer phases of this h.t. potentially support <span class="ital">Pteridium</span> glades, which constitute a loss in browse production and a long-persisting impediment to tree regeneration. Under these conditions, site preparation may be limited to mechanical scarification; if steep slopes dictate burning then planting should immediately follow site disturbance. Consult the management section of ABGR/ASCA concerning the impact of regeneration and site preparation techniques on <span class="ital">Taxus</span>. Livestock find little forage on stocked sites, whereas early successional stages may constitute productive transitional range. Kingery (1983) indicates that livestock use of these sites during early regeneration stages may be detrimental to planted stock.</p>
			<p>Zamora (1982) and Pyke and Zamora (1982) discuss some important management implications regarding succession within the Daubenmires&#8217; (1968) ABGR/<span class="ital">Pachistima myrsinites</span> h.t. (Zamora's plots correspond mainly to our CLUN-CLUN and CLUN-XETE phases). They show an inverse, nearly linear relationship between tree canopy and undergrowth coverages. But the most intense effects of tree-undergrowth interaction do not occur until at least 25 years following cutting. This interval may be considerably extended because it is a function of the rate of post-disturbance tree establishment. Until trees seed in, become established, and overgrow the shrub layer, there is little effect of trees on shrubs. Broadcast-burned clearcuts attain maximum shrub and forb productivities (2,320 to 2,680 lb/acre [2,600 to 3,000 kg/ha]), within 13 to 17 years following disturbance (Zamora 1982).</p>
			
			<h4><a name="set1d"></a><span class="ital">Abies grandis/Linnaea borealis</span> h.t. <br />(ABGR/LIBO; grand fir/twinflower)</h4>
			<p><strong>Soils</strong>&#8212;Very limited data indicate slightly acidic, gravelly depositional soils with shallow ash horizons (<a href="habitat_types_N-ID_app.php">appendix D</a>). Only trace amounts of exposed soil and rock are found. Effective rooting depth varies between 8 and 18 inches (21 and 45 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Site index data are extremely limited, even from adjacent areas; hypothetically, productivity should be moderate to high (Steele and others 1981), somewhat less than on ABGR/CLUN or ABGR/ASCA h.t.&#8217;s. Site indexes on the more moderate LIBO phase are assumed to be higher than on the XETE phase. Opportunity for mixed stand establishment following fire or clearcutting appears good.</p>
			<p>Although the usually gentle terrain may attract livestock, it is primarily the early seral stages that provide forage. Browse potential is greater, too, for big game early in the sere (Steele and others 1981).</p>
			
			<h4><a name="set1e"></a><span class="ital">Abies grandis/Xerophyllum tenax</span> h.t. <br />(ABGR/XETE; grand fir/beargrass)</h4>
			<p><strong>Soils</strong>&#8212;Because all plots with soil pits occurred on the Nez Perce and southern Clearwater <abbr title="National Forest">NF</abbr>'s, the parent materials are nearly exclusively granitics and gneiss; quartzite and shale are also represented (<a href="habitat_types_N-ID_app.php">appendix D</a>). Surface soils are mainly fine textured (loams and silt loams averaging 15 percent gravel) over coarser subsurface soils (sandy loams and sands averaging 20 percent gravel). No restrictive layers were found, and ash deposits were found only in the moist COOC phase. Surface and subsurface pH values are moderately to slightly acidic, averaging 6.2.</p>
			<p><strong>Productivity/Management</strong>&#8212;Site index values range from moderate to high for <span class="ital">Pseudotsuga</span>; other seral trees have a comparable range. Given adequate seed sources, mixed species stands should naturally regenerate following clearcutting with site preparation. Planting <span class="ital">L. occidentalis</span> where historic factors (for example, catastrophic fires) may have eliminated it, or in areas beyond its apparent geographic limits (portions of the Nez Perce <abbr title="National Forest">NF</abbr>) seems warranted on a test basis.</p>
			<p>In Montana, on the ecologically comparable but colder, less mesophytic ABLA/XETE-VAGL h.t., Arno and others (1985) have modeled tree and undergrowth succession for treatments of varying intensities. Their results generally explain the disturbance response of northern Idaho&#8217;s ABGR/XETE and ABLA/XETE h.t.&#8217;s. Salient points of their study are: (1) If slash or site receive no treatment or are broadcast burned full stocking requires &gt;15 years; following wildfire or site scarification regeneration time is half that of untreated stands. (2) Extreme scarification is the treatment most likely to produce "doghair" <span class="ital">P. contorta</span> stands. (3) <span class="ital">P. contorta</span> dominates following all treatments. (4) <span class="ital">Pseudotsuga</span> usually becomes a mature forest stage codominant 100 to 125 years after disturbance (the ubiquity of <span class="ital">P. contorta</span> is reduced in the ABGR/XETE type) and the overstory dominant following <span class="ital">P. contorta</span>&#8217;s demise. (5) Planting is generally either superfluous or unsuccessful.</p>
			<p>These sites are used spring through fall by elk and deer; in some stands <span class="ital">Xerophyllum</span> flowering heads are totally consumed and <span class="ital">V. globulare</span> is heavily hedged. <span class="ital">Vaccinium globulare</span> in adjacent stands may be virtually untouched, possibly an indication of palatability differences or simply a result of proximity to established game trails. Livestock use was not observed in mature stands and potential for such is low. Arno and Simmerman (1982) have found heavy use by cattle on scarified clearcuts produces a persistent, weedy flora in place of native species.</p>
						
			<h4><a name="set1f"></a><span class="ital">Abies grandis/Vaccinium globulare</span> h.t. <br />(ABGR/VAGL; grand fir/blue huckleberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Site indexes are generally high (Steele and others 1981) with <span class="ital">Picea</span> and <span class="ital">Pseudotsuga</span> having the highest values, Seral stands provide important cover and forage for elk and white-tailed deer.</p>
						
			<h4><a name="set1g"></a><span class="ital">Abies grandis/Physocarpus malvaceus</span> h.t. <br />(ABGR/PHMA; grand fir/ninebark)</h4>
			<p><strong>Soils</strong>&#8212;Granite and mica schist dominate the parent materials that included rhyolite, quartzite, argillites, and basalts (<a href="habitat_types_N-ID_app.php">appendix D</a>). Ash layers are uncommon though some profiles were loess influenced. Most soils are fine textured, with loams and silt loams predominating. Gravel content is highly variable but most values ranged from 25 to 55 percent: surface rock and bare soil occur in trace amounts. Somewhat less than half of the PHMA phase plots exhibit a restrictive layer usually associated with the rockiness of glacial till or clay pan development in basalts. Effective rooting depth averages 19 inches (48 cm), ranging from 10 to 28 inches (25 to 70 cm). Surface soil pH values spanned a relatively narrow range (6.1 to 7.1, average 6.4) while subsurface pH ranged widely (4.8 to 7.2).</p>
			<p><strong>Productivity/Management</strong>&#8212;Site indexes range from moderate to very high for all seral and climax species, but stand compositions indicate that <span class="ital">Pseudotsuga</span>, and especially <span class="ital">P. ponderosa</span>, should be favored for reforestation. Overstory removal will permit shrubs to develop a dense, long-persisting layer that competes with establishing tree seedlings. Burning the site will often result in site occupancy by <span class="ital">Ceanothus</span> spp. or <span class="ital">Pteridium aquilinum</span>. For elk and deer, ABGR/PHMA constitutes important winter range and thermal and yearlong hiding cover, especially in earlier seral stages. Livestock use of these sites is usually nil, except in early seral stages; use at this time can produce heavy <span class="ital">Poa pratensis</span> coverages as described by Daubenmire and Daubenmire (1968) for PSME/PHMA.</p>
						
			<h4><a name="set1h"></a><span class="ital">Abies grandis/Spiraea betulifolia</span> h.t. <br />(ABGR/SPBE; grand fir/white spiraea)</h4>
			<p><strong>Soils</strong>&#8212;Very limited data indicate moderately deep (18 to 26 inches [45 to 65 cm]), effective rooting on these well-drained, moderately gravelly (20 percent average), and slightly acid soils (<a href="habitat_types_N-ID_app.php">appendix D</a>). Ash cap depths are highly variable, from a trace to 24 inches (60 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Extrapolating from the central Idaho classification (Steele and others 1981) and limited data from this study, timber productivity should range from moderate to high. Site indexes tentatively appear higher for <span class="ital">P. ponderosa</span> than associated species; however, Steele and others (1981) observed <span class="ital">A. grandis</span> to have exceptionally good growth on these sites under optimum stocking. Site preparation to attain adequate stocking is indicated where Calamagrostis sod is present.</p>
			<p>Generally, steep terrain and low forage productivity should discourage livestock use; however, these sites may have substantially greater potential for wild ungulate use.</p>
						
						
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_N-ID_07.php">On to <span class="ital">Pseudotsuga menziesii</span> (PSME) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_05.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<strong>6</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
