<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management Information on Pseudotsuga menziesii (PSME) Series</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Northern Idaho - Productivity and Management concerns for Pseudotsuga menziesii (PSME) Series" />
		<meta name="keywords" content="Forest Habitat Types of Northern Idaho Productivity Management concerns Pseudotsuga menziesii series PSME" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../../../GeoPath/habitat/index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF NORTHERN IDAHO</a> &gt; <span class="ital">PSEUDOTSUGA MENZIESII</span> (PSME) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Northern Idaho</span><br />PRODUCTIVITY/MANAGEMENT EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Neiman, Kenneth E.; Roberts, David W. Rev. 1991. Forest habitat types of northern Idaho: a second approximation. Gen. Tech. Rep. INT-236. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 143 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_06.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<strong>7</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">PSEUDOTSUGA MENZIESII</span> (PSME) SERIES</h3>
			<p><strong>Productivity/Management</strong>&#8212;Productivity for this series varies from low to moderate and is reflected in the undergrowth composition, which ranges from bunchgrass to shrub dominance. As in the <span class="ital">P. ponderosa</span> series, bunchgrass-dominated <span class="ital">Pseudotsuga</span> associations are susceptible to severe infestation by dwarf mistletoe (<span class="ital">Arceuthobium</span> spp.). Silvicultural treatments must take this into consideration, along with the damage that can result from western budworm (<span class="ital">Choristoneura occidentalis</span>) and Douglas-fir beetle (<span class="ital">Dendroctonus pseudotsugae</span>) infestations. In stands relatively free of insect and disease infestations, and where <span class="ital">Pseudotsuga</span> is the desired regeneration species, a selection or shelterwood treatment is recommended; partial shade for seedlings is often necessary on these relatively harsh sites. For sanitation of a stand or to favor <span class="ital">P. ponderosa</span> or <span class="ital">L. occidentalis</span> regeneration, a clearcut with thorough site preparation and planting of desired species should be used.</p>
			<p>The PSME series is the driest environment in which <span class="ital">Armillaria mellea</span> (laminated root rots) damage conifers and may prove to be the driest sites on which <span class="ital">Armillaria</span> can occur (McDonald 1983). Initial results indicate <span class="ital">Armillaria</span> to be restricted to the moistest environments within this series, with major occurrence and damage in the ABGR, THPL, and TSHE series.</p>
			<p>As in the <span class="ital">P. ponderosa</span> series, light year-round use of shrubs by deer should be beneficial for tree growth (Kosco and Bartolome 1983). Three to 5 years following plantation establishment, light controlled grazing by domestic livestock has been shown to aid timber productivity by reducing herbaceous and woody species competition (Currie and others 1978; Wheeler and others 1980). Initial results from a study currently being conducted in PSME/PHMA and wetter h.t.&#146;s indicate no damage to plantation seedlings in PSME/PHMA from light to moderate livestock grazing the same year as planting (Kingery 1983). Some damage to seedlings does appear to become a problem when similar livestock use is allowed in the <span class="ital">Abies grandis</span> or <span class="ital">Thuja plicata</span> series.</p>
			
			<h4><a name="set1a"></a><span class="ital">Pseudotsuga menziesii/Physocarpus malvaceus</span> h.t. <br />(PSME/PHMA; Douglas-fir/ninebark)</h4>
			<p><strong>Soils</strong>&#8212;Soil parent materials are mainly basalt and quartzite for the SMST phase, with granitics, loess, and volcanic ash also occurring on PHMA phase sites (<a href="habitat_types_N-ID_app.php">appendix D</a>). Textures are generally silt-loam to silty clay-loam in the SMST phase, with a broader textural range, gravelly sandy loam to clay-loam, in the PHMA phase. Total depths vary from 8 to 39 inches (20 to 100 m), with SMST sites tending to have deeper soils. For all phases, pH ranges between 5.5 and 6.6, Bare soil seldom occurs and rock occasionally has up to 25 percent exposure. Litter depth averages 2 inches (5 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Productivity for this h.t. is moderate, with the SMST phase having higher site indexes and total basal area than the PHMA phase. The two highly competitive graminoids, <span class="ital">C. geyeri</span> and <span class="ital">C. rubescens</span>, may cause reduced tree growth in either phase. Sites having a thick moss cushion over basalt talus are essentially unsuitable for intensive management due to unworkable soils.</p>
			<p>Reforestation problems can be significant on this h.t.; for central Idaho, Steele and Geier-Hayes (1983) found contour trenching followed by planting to be the only consistently successful technique. With site preparation that effectively controls early site dominance by shrubs and the highly competitive graminoids, all even-aged silvicultural techniques show promise for regenerating highly productive stands of <span class="ital">P. ponderosa</span>. Uneven-aged techniques should give satisfactory results if <span class="ital">P. menziesii</span> is the preferred species. On the SMST phase, <span class="ital">L. occidentalis</span> should be considered a potential component for increasing the species mix.</p>
			<p>The drier, less-productive PHMA-phase sites within PSME/PHMA may have significant dwarf mistletoe (<span class="ital">Arceuthobium</span>) infestations. PSME/PHMA-SMST appears to be the driest environment (across all series) on which <span class="ital">Armillaria mellea</span> root rots damage conifer species (McDonald 1983). Potential for regeneration failure following site disturbance exists due to <span class="ital">Armillaria inoculum</span> sources remaining onsite.</p>
			<p>This h.t. can receive light to moderate seasonal use by cattle without significant damage to advance reproduction or planted stock (Currie and others 1978; Wheeler and others 1980). Significant damage can occur from excessive use as shaded resting areas adjacent to sites having greater forage production. In mature stands wildlife use this h.t. primarily for cover; forage production for elk is low as is palatability of browse species for deer. Seral stages of this h.t. can be very productive for both foal and cover requirements of big game.</p>
			
			<h4><a name="set1b"></a><span class="ital">Pseudotsuga menziesii/Vaccinium caespitosum</span> h.t. <br />(PSME/VACA; Douglas-fir/dwarf huckleberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity should be moderate for <span class="ital">P. ponderosa</span>, <span class="ital">P. contorta</span>, and <span class="ital">P. menziesii</span>. Expect regeneration on mineral soil to be successful, except in frost pocket locations in the Purcell Trench, where a cover crop of <span class="ital">P. contorta</span> may be required to moderate the microenvironment for seedlings of the other two species. PSME/VACA sites have low forage potential for livestock, and moderate to high potential as winter habitat for deer, elk, and occasionally moose.</p>
						
			<h4><a name="set1c"></a><span class="ital">Pseudotsuga menziesii/Vaccinium globulare</span> h.t. <br />(PSME/VAGL; Douglas-fir/blue huckleberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Extrapolating from Montana data, timber productivity of these sites is expected to be low to moderate. <span class="ital">Pinus ponderosa</span> and <span class="ital">P. contorta</span> are the common seral tree species and should regenerate on mineral soils. This h.t. can produce significant forage and cover for big game, and berry crops for bears, grouse, and humans.</p>
						
			<h4><a name="set1d"></a><span class="ital">Pseudotsuga menziesii/Symphoricarpos albus</span> h.t. <br />(PSME/SYAL; Douglas-fir/common snowberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity, extrapolating from western Montana data, is expected to be low to moderate; however, based on limited data for northern Idaho, this h.t. appears to be considerably more productive. <span class="ital">Pinus ponderosa</span> should regenerate and grow well, whereas <span class="ital">P. menziesii</span> may prove difficult to regenerate on all but the most moist sites. <span class="ital">Calamagrostis rubescens</span> sod may develop following disturbance, causing further regeneration difficulty. Forage and browse production on this h.t. is relatively low.</p>
			
			<h4><a name="set1e"></a><span class="ital">Pseudotsuga menziesii/Spiraea betulifolia</span> h.t. <br />(PSME/SPBE; Douglas-fir/white spiraea)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity of these sites is expected to be low to moderate. <span class="ital">Pinus ponderosa</span> should be the preferred species due to ease of regeneration and higher yields, compared to <span class="ital">P. menziesii</span>. Use of this h.t. by livestock and wildlife can be high. </p>
									
			<h4><a name="set1f"></a><span class="ital">Pseudotsuga menziesii/Calamagrostis rubescens</span> h.t. <br />(PSME/CARU; Douglas-fir/blue huckleberry)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Site index values are generally moderate due primarily to the cold environment and excessively drained soils. <span class="ital">Pinus ponderosa</span> on the ARUV phase shows the best growth potential within the h.t. With the exception of sites supporting high densities of the very palatable bunchgrass <span class="ital">Festuca scabrella</span>, mature stands produce little forage for wild and domestic ungulates. Early and midseral conditions, however, should produce a tall shrub component useful as browse and cover.</p>
									
			<h4><a name="set1g"></a><span class="ital">Pseudotsuga menziesii/Carex geyeri</span> h.t. <br />(PSME/CAGE; Douglas-fir/ninebark)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Productivity should be low to moderate, with <span class="ital">P. ponderosa</span> the most productive and easily regenerated species. Forage production for livestock and elk is site-dependent and variable.</p>
									
			<h4><a name="set1h"></a><span class="ital">Pseudotsuga menziesii/Festuca idahoensis</span> h.t. <br />(PSME/FEID; Douglas-fir/white spiraea)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity of PSME/FEID is expected to be low to very low due to both poor height growth and low stockability. Low regeneration success is a further silvicultural consideration. In good range condition this h.t. is relatively productive (800 lb/acre [896 kg/ha][McLean and others 1971]) for livestock forage in early summer and wildlife habitat during winter months.</p>						
						
			<h4><a name="set1h"></a><span class="ital">Pseudotsuga menziesii/Agropyron spicatum</span> h.t. <br />(PSME/AGSP; Douglas-fir/bluebunch wheatgrass)</h4>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity of PSME/AGSP is expected to be low due to both height growth far below the PSME series average and low stockability; poor regeneration success is a further silvicultural problem. Forage production is generally low (5-year average of 400 lb/acre [448 kg/ha]) (McLean and others 1971); the less steep sites are used for livestock grazing only in the spring. In some areas PSME/AGSP does serve as winter and spring habitat for big game and occasionally wild turkey.</p>						
						
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_N-ID_08.php">On to <span class="ital">Pinus contorta</span> (PICO) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_06.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<strong>7</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
