<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Thuja plicata series</title>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/stylesheet.php");
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Northern Idaho - Soil; Productivity and Management concerns for Thuja plicata (THPL) series" />
		<meta name="keywords" content="Forest Habitat Types of Northern Idaho Productivity Management concerns Thuja plicata series THPL soil soils" />
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../../../GeoPath/habitat/index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF NORTHERN IDAHO</a> &gt; <span class="ital">THUJA PLICATA</span> (THPL) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Northern Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Neiman, Kenneth E.; Roberts, David W. Rev. 1991. Forest habitat types of northern Idaho: a second approximation. Gen. Tech. Rep. INT-236. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 143 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_02.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<strong>3</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">THUJA PLICATA</span> (THPL) SERIES</h3>
			<p><strong>Productivity/Management</strong>&#8212;Although all tree species of northern Idaho except <span class="ital">Larix lyallii</span> can be found in at least minor amounts within the <span class="ital">T. plicata</span> zone, only <span class="ital">A. grandis, L. occidentalis, P. engelmannii, P. monticola, P. contorta, P. menziesii,</span> and <span class="ital">T. plicata</span> are capable of maintaining viable populations and high productivity on these sites. Within the mature stands sampled in northern Idaho, <span class="ital">P. engelmannii, P. monticola, Pseudotsuga,</span> and <span class="ital">Thuja</span> have their highest site indexes in this zone and are the major species on naturally regenerated sites. Competition for soil moisture and heavy browsing by snowshoe hares are found to be significant mortality factors in <span class="ital">Thuja</span> plantations (Mahoney 1981). Attempts at <span class="ital">P. ponderosa</span> plantations using offsite seed sources on sites apparently representing the cooler, more moist habitats of this series have been failures (Daubenmire 1961). Rehfeldt (1980) found for southern Idaho, and is finding in a current study for northern Idaho, considerable genetic diversity among and within <span class="ital">P. ponderosa</span> populations. The presence of relict <span class="ital">P. ponderosa</span> in the drier h.t.&#8217;s of the <span class="ital">Thuja</span> series indicates that plantings with local seed source progeny could be successful. A regeneration model (Ferguson and others 1986), based on silvical characteristics of Northern Rocky Mountain coniferous species and site data stratified by habitat type and treatment, has been developed as a submodel of the Stand Prognosis Model (Stage 1973).</p>

			<h4><a name="set1a"></a><span class="ital">Thuja plicata/Oplopanax horridum</span> h.t. <br />(THPL/OPHO; western redcedar/devil&#8217;s club)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are quartzite and alluvial mixtures of metasediments, siltite, ash, and mica schist. Textures are fairly coarse, ranging from gravelly loamy sands to sandy loams, with gravel content of 40 to 50 percent in most horizons. The pH ranges from 4.5 to 6.0. Bare soil and rock usually do not occur on these sites. Average litter depth is 2 inches (5 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;The THPL/OPHO h.t. is a highly productive site for <span class="ital">Thuja, Tsuga heterophylla,</span> and <span class="ital">Picea</span>. Site index is difficult to measure accurately due to the high percentage of suppressed and overmature trees present in natural stands. <span class="ital">Picea</span> and <span class="ital">Thuja</span> are the species best suited for toeslopes and bottomlands. These two species, along with <span class="ital">Pinus monticola</span> on drier microsites, can be used to regenerate hillside mosaics. In all cases, though, great care must be exercised in logging these sites because water tables are near the surface. Bottomland or riparian sites should not be disturbed other than to salvage high-value trees or to remove high-risk trees. Salvage logging should not remove all dead and down logs because downed woody material serves as a seedbed for <span class="ital">Thuja</span> and <span class="ital">Tsuga</span> regeneration (Parker 1979). Hillside sites should also receive silvicultural treatments conducive to minimal soil disturbance. Natural regeneration by <span class="ital">Thuja</span> and <span class="ital">Tsuga</span> should be sufficient to revegetate sites; interplanting of <span class="ital">Picea</span> throughout the stand and <span class="ital">P. monticola</span> on drier microsites should be successful for establishing mixed-species stands. Major disturbance of this h.t. can result in total site occupancy by tall shrubs (<span class="ital">Acer glabrum, Alnus,</span> and <span class="ital">0. horridum</span>).</p>
			<p>This h.t. has high value as wildlife habitat, offering high quantities of food, cover, and water. An unidentified wild ungulate, presumably elk, utilizes <span class="ital">Oplopanax</span> leaves and flower heads in late summer and fall, leaving some stands with only old, woody <span class="ital">Oplopanax</span> stems. Domestic livestock do not appear to use this h.t. to any extent.</p>

			<h4><a name="set1b"></a><span class="ital">Thuja plicata/Athyrium filix-femina</span> h.t. <br />(THPL/ATFI; western redcedar/lady fern)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are mainly quartzite, sandstone, and granitic, with some sites having metasediments, biotite, shale, and riverine or glacial alluvium. Textures are loamy sands to silt-loams, normally high in gravel content and very permeable. Soil pH ranges from 5.0 to 6.0; total soil depths range from 16 to 32 inches (40 to 80 cm). Bare soil and rock are usually not found on these sites; average litter depth is 2 inches (5 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;The THPL/ATFI h.t. is highly productive, the ADPE phase being slightly more productive than the ATFI phase. Because this habitat type occurs on riparian terraces and adjacent toeslope sites and on wet, highly compactible soils, disruptive logging practices are not recommended. Salvage logging should be limited to preserve downed woody material as a seedbed for <span class="ital">Thuja</span> and <span class="ital">Tsuga</span> regeneration (Parker 1979). These sites, particularly those with <span class="ital">T. brevifolia</span>, have extremely high value as big-game habitat throughout the year. Isolated old-growth stands have added value as recreational and botanical-interest areas.</p>
			
			<h4><a name="set1c"></a><span class="ital">Thuja plicata/Adiantum pedatum</span> h.t. <br />(THPL/ADPE; western redcedar/maidenhair fern)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are mainly metasediments, granitics, or mica schist, with occasional ash deposits, sandstone, and basalt. Textures range from loams to clay-loams, with small amounts of gravel. The pH values normally range from 5.1 to 6.3. Bare soil and rock do not usually occur; litter cover averages 1.5 inches (4 cm) in depth.</p>
			<p><strong>Productivity/Management</strong>&#8212;Site indexes are generally very high in this h.t. Both the small acreages and their close proximity to streams and riparian zones reduce the silvicultural options for this h.t. Salvage on these sites should be limited because downed woody material serves as a seedbed for <span class="ital">Thuja</span> and <span class="ital">Tsuga</span> regeneration. Disturbance to seasonally wet soils may lead to soil compaction or mass wasting. Big game may heavily use these sites, particularly during winter and spring.</p>
			
			<h4><a name="set1d"></a><span class="ital">Thuja plicata/Gymnocarpium dryopteris</span> h.t. <br />(THPL/GYDR; western redcedar/oak fern)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are mainly quartzite, sandstone, and schist, often mixed or overlain with volcanic ash. Textures range from gravelly loam to silty clay loam and pH values range from 5.4 to 6.4. Bare soil and rock are usually absent; litter depth averages 3 inches (8 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;The THPL/GYDR h.t. is highly productive for <span class="ital">A. grandis</span> and <span class="ital">P. engelmannii</span> and moderately productive for <span class="ital">P. monticola, P. menziesii,</span> and <span class="ital">T. plicata</span>. Any of the above species with the proper silvicultural treatment should do well on these sites. Because of the richness and high growth rates of shrub species in this h.t., tree regeneration should be scheduled immediately following logging. Shrub and forb invasion can significantly impact reforestation through direct competition and/or attraction of large and small herbivores. Other major management considerations should be the proximity of these sites to riparian zones and potential compaction of seasonally saturated soils. Stands in this h.t. that have a high coverage of <span class="ital">T. brevifolia</span> may have high local value as moose winter habitat.</p>
			
			<h4><a name="set1e"></a><span class="ital">Thuja plicata/Asarum caudatum</span> h.t. <br />(THPL/ASCA; western redcedar/wild ginger)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are mainly granitic, quartzite, siltite, and sandstone, with some mixed loess and generally an ash cap or a loess-volcanic ash mix in the upper horizons. Textures are predominantly loams to silt-loams, with gravel contents of 5 to 30 percent. The TABR phase tends to have finer textured, more moist upper horizons than the other phases of this h.t. Soil pH ranges from 5.6 to 6.5; total depth ranges from 8 to 43 inches (20 to 110 cm), and average litter depth is 2 inches (5 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;THPL/ASCA is highly productive for timber. <span class="ital">Pseudotsuga menziesii</span> and <span class="ital">A. grandis</span> attain some of their highest site indexes on the ASCA and TABR phases, with significant reductions occuring for all species on the colder MEFE phase. Selection and shelterwood cuts will favor <span class="ital">T. plicata</span> and <span class="ital">A. grandis</span> regeneration. <span class="ital">Pseudotsuga, L. occidentalis, Pinus monticola,</span> and <span class="ital">Pinus ponderosa</span> (ASCA phase only) should regenerate successfully from seedtree or artificial plantation treatments following overstory removal. Due to high productivity, these sites are susceptible to heavy shrub competition and damage from large herbivores and rodents during early stages of stand regeneration. A second precaution pertains to the potential for site degradation following stand entry on seasonally wet soils. Old-growth stands of the TABR phase have high potential as late fall and winter moose habitat (Pierce 1983), particularly where this community replaces ABGR/ASCA-TABR in the areas north of the west-central Nez Perce <abbr title="National Forest">NF</abbr>.</p>
			
			<h4><a name="set1f"></a><span class="ital">Thuja plicata/Clintonia uniflora</span> h.t. <br />(THPL/CLUN; western redcedar/queencup beadlily)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are mostly granitic, quartzite, siltite, and sandstone, with some loess and ash caps. Textures are predominantly loams to silt-loams, with a gravel content of 5 to 35 percent. In the XETE phase the upper soil horizons are well to excessively drained. Soil pH ranges mostly between 5.6 and 6.6. Total soil depths are quite variable, ranging from 8 to 32 inches (20 to 80 cm). Bare soil and rock do not occur on these sites. Average litter depth is 2 inches (5 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;The THPL/CLUN h.t. is generally highly productive for timber. <span class="ital">Abies grandis</span> site indexes are nearly as high as in THPL/ASCA h.t., while <span class="ital">P. menziesii</span> and <span class="ital">L. occidentalis</span> have only slightly lower indexes than those measured on TSHE h.t.&#8217;s. A significant reduction in site index occurs on the MEFE and XETE phases. The site index for <span class="ital">P. monticola</span> does not appear to be greatly affected by differing phases of THPL/CLUN, but its height growth appears to be significantly reduced from that measured on TSHE h.t.&#8217;s.</p>
			<p>Selection and shelterwood cuts will favor <span class="ital">T. plicata</span> and <span class="ital">A. grandis</span> regeneration. <span class="ital">Pinus monticola, P. ponderosa</span> (CLUN phase only), <span class="ital">L. occidentalis,</span> and <span class="ital">P. menziesii</span> should regenerate successfully from seedtree treatments or artificial plantations following overstory removal. Old-growth stands of the TABR and MEFE phases, respectively, have high value as late-fall/winter and summer big game habitat, especially for moose (Pierce 1983).</p>
			
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_N-ID_04.php">On to <span class="ital">Tsuga mertensiana</span> (TSME) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_02.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<strong>3</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="../habitat_types_refs.php">References</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
include($_SERVER["DOCUMENT_ROOT"]."/smp/solo/shared/footer.php");
?>
