<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Successional Status of North Idaho Forests: Fire history, Logging history</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Northern Idaho - Successional Status: Fire history and Logging history" />
		<meta name="keywords" content="Forest Habitat Types of Northern Idaho Productivity Management fire history logging history" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF NORTHERN IDAHO</a> &gt; SUCCESSIONAL STATUS: FIRE HISTORY AND LOGGING HISTORY</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Northern Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Neiman, Kenneth E.; Roberts, David W. Rev. 1991. Forest habitat types of northern Idaho: a second approximation. Gen. Tech. Rep. INT-236. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 143 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="index.php">Index</a>&nbsp;&nbsp;<strong>1</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set2"></a>SUCCESSIONAL STATUS</h3>
			<h4>Fire History</h4>
			<p>Recognition and documentation of the importance of natural (lightning-caused) fires for the perpetuation of natural forest ecosystems and landscape diversity in the Northern Rocky Mountains is steadily accumulating (Arno 1980; Habeck and Mutch 1973; Romme 1982; Wellner 1970a). Incidence of fire in these ecosystems is practically a certainty within 400 to 500 years from stand initiation (Daubenmire and Daubenmire 1968), but natural fire-free intervals are considerably shorter. The studies of Barrett and Arno (1982) emphasize the extensive impact that burning (planned or otherwise) by Native Americans has had on maintaining stand structure and composition. Other human-caused fires were set by prospectors to expose mineral outcrops (Space 1964) and by settlers for range improvement.</p>
			<p>Virtually every stand we sampled had some indication of past fire: even-aged size-class structure of seral species, charred material on the ground, burned-out stumps and snags, charcoal in the soil profile, and fire-marred boles (usually the exception-evidence indicated a high proportion of stand-replacing fires). Where fire evidence was not immediately obvious, soil probing could almost invariably produce charcoal traces. Only unproductive, high-elevation sites or wet sites occasionally lacked fire evidence.</p>
			<p>Thus it is not surprising that the most abundant tree species in northern Idaho are seral ones adapted to a landscape periodically disturbed by fire. Mature <span class="ital">Larix occidentalis</span>, <span class="ital">Pinus ponderosa</span>, and <span class="ital">Pseudotsuga menziesii</span> have thick, corky, fire-resistant bark. The previously cited species and <span class="ital">Pinus monticola</span> have light and/or winged seed, or as is the case with <span class="ital">Pinus contorta</span>, serotinous cones, adaptations for early arrival on burned sites. Their growth patterns are characterized by rapid initial height growth favoring them over their shade-tolerant competitors. Even-aged stand structure that results following extensive stand-replacing fires (for example, 1910 burns) is circumstantial evidence that a considerable amount of viable seed survives these catastrophic fires. The distances from the nearest seed wall to the center of burned areas virtually preclude effective seed dispersal.</p>
			<p>Arno's (1980) recent synopsis of fire history in the Northern Rockies and other publications (Arno 1976; Davis and others 1980; Wellner 1970a) indicate that the fire-free interval (&#8220;fire-return interval&#8221; in other studies) can be related to climax tree series and habitat type. On a local scale, incidence of fire (predominantly surface fire) decreases with decreasing moisture stress, from mean fire-free intervals of 6 years on <span class="ital">Pinus ponderosa-Pseudotsuga menziesii</span>/bunchgrass types to 40+ years on subalpine h.t.'s (Arno and Petersen 1983).</p>
			<p>Surface fires also occur in the <span class="ital">Thuja-Tsuga</span> forests of northern Idaho, but with much-reduced frequency compared to northwestern Montana or the Nez Perce <abbr title="National Forest">NF</abbr>, where reconnaissance data show 40 to 80 percent of the stands in <span class="ital">Thuja</span> h.t.'s experience ground fire. Studies on small subunits (150 to 300 acres [60 to 120 ha]) of the Priest Lake Ranger District, Kaniksu <abbr title="National Forest">NF</abbr> (Arno and Davis 1980) indicate only one or two significant fires per century can be expected on upland <span class="ital">Thuja-Tsuga</span> h.t.'s. Wet-site <span class="ital">Thuja-Tsuga</span> subunits experience only very limited lightning-strike spot fires; average stand-replacing fire intervals may exceed 500 years. The <span class="ital">Abies lasiocarpa</span> h.t.'s associated with the <span class="ital">Tsuga-Thuja</span> zone have much longer fire-free intervals (to 250+ years) and reduced burn sizes (&lt;10 acres [4 ha] [Arno and Davis 1980] compared to ABLA series h.t.'s on the Lolo and Bitterroot <abbr title="National Forest">NF</abbr>'s [beyond the <span class="ital">Tsuga-Thuja</span> zone] [Arno and Petersen 1983; Davis and others 1980]). Arno and Davis (1980) have speculated on management implications associated with the types and frequencies of fire as they interact with h.t.'s, seral species, and site properties on <span class="ital">Thuja-Tsuga</span> zone forests.</p>
			<p>The high productivities of <span class="ital">Thuja-Tsuga</span> forests reflect their mesic environments; however, every few years an extreme summer drought occurs. Drought, combined with drying winds, vastly increases the probability of large, stand-replacing fires. The destructive 56,000-acre (22,700-ha) Sundance Fire (Kaniksu <abbr title="National Forest">NF</abbr>) of 1967 (Anderson 1968) was the most recent example of the massive crown fires that collectively have burned millions of acres. Other extensive fires occurred in 1934, 1926, 1919, 1889, and most notably 1910 (990,000 acres [400,000 ha] burned on the Clearwater and Nez Perce <abbr title="National Forest">NF</abbr>'s alone [Barrows 1952]). The U.S. Forest Service Northern Region (R-1) experiences about three times as many lightning fires as the Intermountain Region (R-4), and the western zone (R-1, west of Continental Divide) records six times as many lightning fires as the eastern zone (Barrows 1952). The Clearwater and Nez Perce <abbr title="National Forest">NF</abbr>'s are clearly the regional focus of lightning fires, both in terms of the average number of fires per million acres (114 and 67, respectively, computed on the period 1931&#8211;46) and average annual acreage burned per million acres (5,670 and 7,580, respectively). The average acreage burned per million acres for these forests is two to 10 times greater than on contiguous forest lands.</p>
			<p>Wellner (1970a) describes how the accumulation of dead, fallen fuels from previous fires may set the stage for massive and successive fires, the eventual outcome being retarded establishment of forest because of seed source elimination and long-persisting shrub and forb fields (dominated by <span class="ital">Salix scouleriana</span>, <span class="ital">Amelanchier alnifolia</span>, <span class="ital">Ceanothus</span> spp., <span class="ital">Acer glabrum</span>, <span class="ital">Prunus</span> spp., <span class="ital">Physocarpus malvaceus</span>, <span class="ital">Holodiscus discolor</span>, <span class="ital">Pteridium aquilinum</span>, and <span class="ital">Rudbeckia occidentalis</span>). On the Clearwater <abbr title="National Forest">NF</abbr> (centered on Cook Mountain area) we find the most extensive reburns and shrubfields in the Northern Rockies. Barrett (1982) has speculated on the combination of factors responsible for these conflagrations: (1) less summer rainfall than northward in the panhandle, yet still enough moisture for rapid fuel buildup; (2) local topography favoring the drying influence of prevailing westerlies on mid and upper slope forests; (3) high lightning frequency.</p>
			<p>Succession modeling (Arno and others 1985) in four extensive habitat types of western Montana (important h.t.'s also in northern Idaho) has documented that the intensity of burn, along with preburn vegetational composition and h.t., are important variables in predicting response to wildfire. The results of Arno and others (1985) have important implications about managing for particular species through specific treatments. In many cases, successional responses to combinations of logging and site preparation will mimic the vegetational responses to wildfire. Fire history studies in combination with succession modeling of vegetation, fuels, and flammability have great potential for ecological understanding of the natural role of wildfire, how fire may be best managed, and the use of prescribed fire as a tool (prescription) to achieve land management objectives. (See Logging History section for additional citations regarding succession models.)</p>
			<h4>Logging History</h4>
			<p>Centers of mining activity were the first areas to be heavily logged. Timber was used for construction, mine supports, and fuel for stamp mills and smelters. Cutting for ties was extensive along railroad lines. Early in the century the most fertile and accessible valleys and adjacent gentle slopes were cleared for agriculture, and upslope stands were used for fuel and building materials. Loggers soon gained access to more remote stands of valuable timber and floated huge log-booms to downstream mills on the major watercourses of the area. Records of these early activities are preserved in springboard cuts on large rot-resistant Thuja plicata stumps. Some areas with these relicts have produced a second cutting and are well on their way to a third.</p>
			<p>The biggest spur to increased harvesting was the booming wartime (World War II) and postwar economy. For instance, on the Clearwater <abbr title="National Forest">NF</abbr> the largest cut prior to 1946 was 18.0 million board ft (MM bd ft), but the annual cut jumped to 116.3 MM bd ft by 1959, and since has dropped below 100 MM bd ft only once; similar increases in harvested volume occurred on other forests in the region. With continued pressure to harvest old-growth stands and the introduction of aerial logging techniques making stands accessible where harvesting was once deemed impractical, it appeared that only the most remote (or unproductive) stands would remain undisturbed. But the Research Natural Areas (RNA) program is preserving primarily old-growth areas representative of formerly extensive types. Also, National Forests are setting aside a certain percentage of their remaining old-growth stands, recognizing that certain wildlife species are dependent upon this structural state.</p>
			<p>Succession models have also been constructed with various cutting practices and site treatments constituting the disturbance types (a major prediction variable). Some models are data intensive, geographically restricted, and treat all lifeforms (for example Arno and others 1985 in western Montana). Others are deterministic, of broad geographic application, but emphasize the response of tree and shrub parameters (Laurson 1984; Moeur 1985; Scharosch 1984). Moeur's (1985) model, COVER, an extension of version 5.0 of the Stand Prognosis Model (Wykoff and others 1982) incorporates the databases of Laurson (1984), Scharosch (1984), and Ferguson and others (1986) making the model applicable to the Inland Northwest and Northern Rocky Mountains.</p>
												
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="index.php">&lt;&lt; Back to Index</a></p>
			<div class="navlist">
				<p>[Pages: <a href="index.php">Index</a>&nbsp;&nbsp;<strong>1</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
