<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Tsuga mertensiana (TSME) series</title>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Northern Idaho - Soil and Productivity and Management concerns for Tsuga mertensiana (TSME) series" />
		<meta name="keywords" content="Forest Habitat Types of Northern Idaho Productivity Management concerns Tsuga mertensiana series TSME soil soils" />
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF NORTHERN IDAHO</a> &gt; <span class="ital">TSUGA MERTENSIANA</span> (TSME) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Northern Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Neiman, Kenneth E.; Roberts, David W. Rev. 1991. Forest habitat types of northern Idaho: a second approximation. Gen. Tech. Rep. INT-236. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 143 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_03.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<strong>4</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">TSUGA MERTENSIANA</span> (TSME) SERIES</h3>
			<p><strong>Productivity/Management</strong>&#8212;Lower elevation sites within the series have the highest timber potentials. In comparison with similar h.t.&#146;s of adjacent areas and in absolute terms, the northern Idaho types show greater seral importance for <span class="ital">Picea</span> and <span class="ital">P. monticola</span> and reduced importance for <span class="ital">Pseudotsuga</span> and <span class="ital">P. contorta</span>. The reduced <span class="ital">P. contorta</span> and <span class="ital">L. occidentalis</span> importance may be spurious; where found, their growth potential was high. Site indexes for all species are remarkably similar to those of the ABLA series.</p>
			<p>Loss to heartrot, particularly <span class="ital">Echinodontium tinctorium</span>, is high in older stands (&gt;100 years). Much of the old-growth <span class="ital">T. mertensiana</span> was cull, especially on moist or upper elevation sites.</p>
			<p>Upper subalpine sites within the series have generally low timber potential and limited silvicultural opportunities; they are best suited to recreation, wildlife, and snowpack management.</p>

			<h4><a name="set1a"></a><span class="ital">Tsuga mertensiana/Streptopus amplexifolius</span> h.t. <br />(TSME/STAM; mountain hemlock/twisted stalk)</h4>
			<p><strong>Soils</strong>&#8212;Small sample size does not permit extensive characterization; preliminary results show rooting depths (to 27.5 inches [70 cm]) are relatively deep for the series and gravel content is high (average 30 percent), even in the upper profile (<a href="habitat_types_N-ID_app.php">appendix D</a>). The dominant factor, however, is a water table that influences the upper profile for at least a portion of the growing season.</p>
			<p><strong>Productivity/Management</strong>&#8212;Based on very limited data, site index values appear to be moderate to high (MEFE phase only), comparable to those of ABLA/STAM. In terms of site index, <span class="ital">Picea</span> is the most productive species. Water tables, which rise following overstory removal, restrict timber management options. Where <span class="ital">Picea</span> has been selectively cut, the result has been pure <span class="ital">Abies-Tsuga</span> stands, with canopy gaps usually filled by dense undergrowth or climax tree reproduction.</p>

			<h4><a name="set1b"></a><span class="ital">Tsuga mertensiana/Clintonia uniflora</span> h.t. <br />(TSME/CLUN; mountain hemlock/queencup beadlily)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are predominantly granitics and quartzite but include other noncalcareous sedimentary rocks (<a href="habitat_types_N-ID_app.php">appendix D</a>); the upper horizons are all strongly ash influenced to a depth of at least 14 inches (35 cm) (average 17 inches [44 cm]). Restrictive layers have not been noted, and exposed soil and rock are negligible. Surface soils are, without exception, fine textured, ranging from loams to silty clay loams; subsurface soils are also dominated by loams and gravel content increases markedly only in the lower B and C horizons (to an average of 20 percent). Effective rooting depths average 19 inches (49 cm), the deepest within the series. Both surface and subsurface horizons are mostly moderately acidic (surface pH averages 5.8, 4.9 to 6.3; subsurface 5.7, 5.2 to 6.0). Insufficient data exist to distinguish phase differences (between MEFE and XETE), though the XETE phase does trend to shallower rooting depths.</p>
			<p><strong>Productivity/Management</strong>&#8212;Based on limited site index data TSME/CLUN appears to be the most productive of the TSME series h.t.&#146;s, similar on a species-by-species comparison with ABLA/CLUN for northern Idaho or western Montana (Pfister and others 1977). Given that seral tree species are often minor components of mature stands as well as on clearcuts, silvicultural prescriptions should address strategies for the establishment of more rapidly growing intolerant species. Other implications and prescriptions follow those for the corresponding phases of ABLA/CLUN.</p>
			
			<h4><a name="set1c"></a><span class="ital">Tsuga mertensiana/Menziesia ferruginea</span> h.t. <br />(TSME/MEFE; mountain hemlock/menziesia)</h4>
			<p><strong>Soils</strong>&#8212;Soils were developed primarily from quartzite, granitics, and gneiss, with all profiles having a moderate ash influence to about 10 inches (25 cm) (<a href="habitat_types_N-ID_app.php">appendix D</a>). Rooting depth in the LUHI phase averaged only 13 inches (33 cm) and is expected to be deeper in the XETE phase. In both phases, surface horizons are dominantly nongravelly whereas subsoils usually contain a high percentage of gravel. The nongravel fractions are loams to silty clay loams. No restrictive layers were found, but rooting depths usually dramatically decrease where rock content increases. Surface soils in the LUHI phase are extremely acidic (average 4.2, range of 4.0 to 5.2), whereas subsoil horizons are mostly strongly acidic (5.5, 5.0 to 5.9); the XETE phase averages more than one pH unit higher than LUHI for surface soils and one-half unit higher for the subsurface.</p>
			<p><strong>Productivity/Management</strong>&#8212;Analysis of limited site index data suggests that productivity decreases along the gradient of increasing site severity, from moderate to high in the XETE phase to low to moderate in the LUHI phase. Management considerations should correspond to those of the comparable ABLA series h.t.&#146;s. Especially noteworthy is the relative lack of seral tree species in both mature stands and following clearcutting (with various postharvest treatments).</p>
			
			<h4><a name="set1d"></a><span class="ital">Tsuga mertensiana/Xerophyllum tenax</span> h.t. <br />(TSME/XETE; mountain hemlock/beargrass)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials consisted of metamorphosed granitic and sedimentary rocks (<a href="habitat_types_N-ID_app.php">appendix D</a>). Ash and loess influenced all profiles to a variable degree. Restrictive layers were not encountered; exposed soil and rock, generally not exceeding 5 percent coverage, occurred in over 75 percent of the stands. Soil textures are predominantly loams and silt loams; however, coarser soils are found more frequently in this than other TSME h.t.'s. Rooting depth varies by phase, VASC and LUHI averaging 14 inches (36 cm) and VAGL 18 inches (46 cm). Gravel content averages 17 percent in the upper profile and increases greatly with increasing depth, usually with a 20 to 50 percent increase from the B horizons to the B/C or C horizons, at a depth that corresponds approximately to the depth of rooting. In all phases soil reactions of the upper profile are strongly to very strongly acidic, decreasing to mostly moderately to slightly acidic with increasing depth.</p>
			<p><strong>Productivity/Management</strong>&#8212;Based on limited data, TSME/XETE site indexes differ according to phase; XETE-VAGL timber productivity appears comparable to that of ABLA/XETE-VAGL. The more limiting environments of VASC and LUHI phases register lower site index values, comparable to those of ABLA/XETE-VASC or ABLA/XETE-LUHI. The reduced importance of typical seral species (<span class="ital">P. contorta</span> and <span class="ital">L. occidentalis</span>) is notable and could have significant silvicultural implications. This observation must be further evaluated over a greater area and for younger stands. The results of Fiedler&#146;s (1980) study may be cautiously extrapolated to this type (see ABLA/XETE); among the salient points is the need for scarification to achieve rapid reforestation by seral species. High coverages of <span class="ital">C. rubescens</span> and <span class="ital">C. geyeri</span>, which may result following overstory removal, retard seedling establishment.</p>
			
			<h4><a name="set1e"></a><span class="ital">Tsuga mertensiana/Luzula hitchcockii</span> h.t. <br />(TSME/LUHI; mountain hemlock/smooth woodrush)</h4>
			<p><strong>Productivity/Management</strong>&#8212;No data exist here, but the similarity to ABLA/LUHI in site factors and vegetation argues that these sites hold marginal timber-producing potential. Because these sites often border mountain grasslands and herb-dominated meadows, they are of value as wildlife cover. Generally low productivity, inaccessibility, and fragility of these sites suggest minimal disturbance.</p>
			
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_N-ID_05.php">On to <span class="ital">Abies lasiocarpa</span> (ABLA) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_03.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_02.php">2</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<strong>4</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("https://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
