<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header1.php");
?>
    <title>Productivity/Management and Soil Information on Tsuga heterophylla series</title>
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/stylesheet.php");
//invoke_stylesheet();
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header2.php");
?>
		<meta name="description" content="Forest Habitat Types of Northern Idaho - Soils and Productivity and Management concerns for Tsuga heterophylla (TSHE) series" />
		<meta name="keywords" content="Forest Habitat Types of Northern Idaho Productivity Management concerns Tsuga heterophylla series TSHE soil soils" />
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/header3.php");
?>
			<h5 class="subnav"><a href="../../../../index.php">SOLO HOME</a> &gt; <a href="../../index.php">HABITAT TYPES</a> &gt; <a href="index.php">FOREST HABITAT TYPES OF NORTHERN IDAHO</a> &gt; <span class="ital">TSUGA HETEROPHYLLA</span> (TSHE) SERIES</h5>
			<h2 class="topheading"><span class="nfsubhead">Forest Habitat Types of Northern Idaho</span><br />PRODUCTIVITY/MANAGEMENT AND SOIL EXCERPTS</h2>
			<p class="note">[Excerpted from: Cooper, Stephen V.; Neiman, Kenneth E.; Roberts, David W. Rev. 1991. Forest habitat types of northern Idaho: a second approximation. Gen. Tech. Rep. INT-236. Ogden, UT: U.S. Department of Agriculture, Forest Service, Intermountain Research Station. 143 p.]</p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_01.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<strong>2</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">Next &gt;&gt;</a> ]</p>
			</div>

			<h3 class="section"><a name="set1"></a><span class="ital">TSUGA HETEROPHYLLA</span> (TSHE) SERIES</h3>
			<p><strong>Productivity/Management</strong>&#8212;The <span class="ital">Tsuga heterophylla</span> and <span class="ital">Thuja plicata</span> series occupy the most productive habitats in northern Idaho. Comparing the two, we find the following tree species to have slightly higher site indexes when growing in the <span class="ital">Tsuga</span> zone: <span class="ital">Abies grandis, A. lasiocarpa, Larix occidentalis, P. contorta, P. monticola, T. heterophylla</span>. Within this series natural regeneration 20 years following various silvicultural treatments is usually significant in quantity (Boyd 1969). Any disturbance in existing stands can result in tremendous <span class="ital">Tsuga</span> regeneration (Graham 1982). <span class="ital">Abies grandis, P. monticola,</span> and <span class="ital">T. heterophylla</span> are the major components of these naturally regenerated sites. Some attempts at <span class="ital">Pinus ponderosa</span> plantations in this series have been failures (Daubenmire 1961). Use of <span class="ital">P. ponderosa</span> in a planting mixture should be successful on the warmest, driest sites of this series; there are tentative indications though that the seed source should come from the <span class="ital">Tsuga</span> series (Rehfeldt 1983).</p>
			<p>Natural regeneration should be successful if adequate seed is available. Ferguson and others (1986) have developed a regeneration model as a submodel to Stage's (1973) Prognosis Model; their model uses the silvical characteristics of Northern Rocky Mountain conifer species and site data stratified by habitat type and treatment to predict regeneration success.</p>

			<h4><a name="set1a"></a><span class="ital">Tsuga heterophylla/Gymnocarpium dryopteris</span> h.t. <br />(TSHE/GYDR; western hemlock/oak fern)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are mostly ash over quartzite, but also include siltite, metasediments, and glacial till. Textures are predominantly loams or sandy loams, with 30 to 50 percent gravel. Total soil depth ranges between 15 and 28 inches (40 and 70 cm), and pH ranges between 4.9 and 6.0. Bare soil and rock usually do not occur on these sites. Average litter depth is 2 inches (5 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;High site indexes and basal areas indicate high timber productivity. <span class="ital">Abies grandis, L. occidentalis, T. plicata,</span> and <span class="ital">P. engelmannii</span> achieve some of their highest site indexes in this h.t. (appendix F). <span class="ital">Pinus monticola</span> does well here, but better growth is achieved on slightly drier sites. Short-rotation, even-aged management of <span class="ital">L. occidentalis, P. engelmannii,</span> and/or <span class="ital">P. monticola</span> is currently the preferred management regime. The soils remain moist throughout the year; logging operations should be scheduled such that desirable soil characteristics are not unduly modified. Mature stands within this type have a high percentage of the trees with extensive heartrot (for example, <span class="ital">Echinodontium tinctorum, Fomes pini,</span> and <span class="ital">Polyporus tomentosus</span>). Windthrow and root rot pockets give the mature stand a rather open character. Forage production for big game is good during early seral stages, poor during the closed canopy mid- to late-seral stages, and fair in mature stands.</p>

			<h4><a name="set1b"></a><span class="ital">Tsuga heterophylla/Asarum caudatum</span> h.t. <br />(TSHE/ASCA; western hemlock/wild ginger)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are quartzite, sandstone, siltite, and metasediments, with an ash cap or mantle of mixed loess and volcanic material. The predominant textural classes are loam to silty-loam and occasionally clay-loam. Gravel content ranges from 30 to 60 percent in the ARNU and MEFE phases, only 10 percent being normal for the ASCA phase. Total soil depth ranges between 12 and 26 inches (30 and 65 cm), and average pH varies widely, from 4.5 to 6.7. Bare soil and rock usually do not occur; litter depth averages 1.5 inches (4 cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Of the extensively occurring h.t.&#8217;s in northern Idaho, TSHE/ASCA is the most productive. Excellent height growth is achieved by <span class="ital">P. menziesii, L. occidentalis, P. monticola,</span> and <span class="ital">A. grandis</span> on this h.t. Any natural or artificial regeneration treatment should be successful; the main problem is the potential for overstocked stands. Shelterwood or selection treatments will favor regeneration of <span class="ital">A. grandis, T. plicata, T. heterophylla, P. engelmannii,</span> and/or <span class="ital">A. lasiocarpa</span>. Inherent high productivity of these sites can lead to heavy shrub competition, particularly if shrub establishment is allowed to precede tree regeneration by a year or two. Seasonally wet soils in the ARNU phase are subject to compaction during most of the year. Large herbivores and rodents may do extensive damage during early stages of regeneration. Stands with high coverages of shrubs, particularly <span class="ital">Taxus brevifolia</span> and <span class="ital">Vaccinium globulare</span>, may provide significant moose, elk, and grizzly bear habitat.</p>
			
			<h4><a name="set1c"></a><span class="ital">Tsuga heterophylla/Clintonia uniflora</span> h.t. <br />(TSHE/CLUN; western hemlock/queencup beadlily)</h4>
			<p><strong>Soils</strong>&#8212;Parent materials are mainly quartzite, siltite, sandstone, and metasediments with an ash cap, but gneiss, schist, gabbro, and loess are also found. Textures are slightly heavier than TSHE/GYDR and TSHE/ASCA soils, the predominant textural classes being silty-loam to silty clay-loam. The ARNU, MEFE, and XETE phases have 30 to 60 percent gravel, while the CLUN phase tends to have less than 10 percent gravel in its horizons. Average pH varies from 4.8 to 6.8. Total soil depths average between 12 and 26 inches (30 and 65 cm). Bare soil and rock usually do not occur on these sites. Average litter depth is 1.5 inches (4cm).</p>
			<p><strong>Productivity/Management</strong>&#8212;Timber productivity is high to very high in the TSHE/CLUN h.t. Excellent height growth can be realized from <span class="ital">P. menziesii, L. occidentalis, A. grandis,</span> or <span class="ital">P. monticola</span>. The highest site indexes for <span class="ital">Pseudotsuga</span> are found on the CLUN phase: the best height growth for <span class="ital">Larix</span> is on the ARNU phase, and all species have appreciably reduced height growth on the XETE phase.</p> 			
			<p>Seedtree or very open shelterwood treatments on south east to west slopes should result in good natural regeneration of <span class="ital">P. menziesii, L. occidentalis, A. grandis,</span> and <span class="ital">P. monticola</span>. On all other aspects, if an adequate seed source is present, clearcutting following seedfall should lead to abundant natural regeneration of these same species and even <span class="ital">T. heterophylla</span> (Boyd 1969). If the seed source is inadequate, planting in either of these aspect-dependent situations should prove successful. Shelterwood and selection treatments may be utilized if the desired regeneration species are <span class="ital">A. grandis, T. heterophylla, T. plicata, P. engelmannii,</span> or <span class="ital">A. lasiocarpa</span>. Stands with tall shrub components, particularly <span class="ital">Taxus brevifolia</span> and <span class="ital">V. globulare</span>, are important as moose, elk, and grizzly bear habitat.</p>
			
			<h4><a name="set1d"></a><span class="ital">Tsuga heterophylla/Menziesia ferruginea</span> h.t. <br />(TSHE/MEFE; western hemlock/menziesia)</h4>
			<p><strong>Productivity/Management</strong>&#8212;We assume, lacking productivity data, that this h.t. approximates the timber productivity of ABLA/MEFE-XETE or TSME/MEFE-XETE. Management considerations should correspond to those of the two foregoing h.t.&#8217;s. The low species diversity in both overstory and undergrowth may indicate a nonproductive site having serious regeneration problems.</p>
			
			<p class="backlink"><a href="#set0">&lt;&lt; Back to top</a></p>
			<p class="backlink"><a href="habitat_types_N-ID_03.php">On to <span class="ital">Thuja plicata</span> (THPL) Series &gt;&gt;</a></p>
			<div class="navlist">
				<p>[Pages: <a href="habitat_types_N-ID_01.php">&lt;&lt; Back</a>&nbsp;&nbsp;<a href="index.php">Index</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_01.php">1</a>&nbsp;&nbsp;<strong>2</strong>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">3</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_04.php">4</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_05.php">5</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_06.php">6</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_07.php">7</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_08.php">8</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_09.php">9</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_10.php">10</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_11.php">11</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_app.php">Appendixes</a>&nbsp;&nbsp;<a href="habitat_types_N-ID_03.php">Next &gt;&gt;</a> ]</p>
			</div>
<?php
require("http://forest.moscowfsl.wsu.edu/smp/solo/shared/footer.php");
?>
